//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_IROUTES_H
#define GUARD_LIBCSC_CUSTOMER_IROUTES_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class IRoutes
{
public:
    virtual ~IRoutes() {}

    virtual basar::Int16 getWeekday() const = 0;
    virtual basar::VarString getTourId() const = 0;
    virtual basar::Int32 getDuration() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_IROUTES_H
