//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/routes/routessqlmapper.h>

namespace libcsc {
namespace customer {

RoutesSqlMapper::RoutesSqlMapper(RoutesPtr routes, const basar::db::sql::ResultsetRef resultSet)
: RoutesMapperBase(routes), m_ResultSet(resultSet)
{
}

RoutesSqlMapper::~RoutesSqlMapper()
{
}

void RoutesSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setWeekday(m_ResultSet.getInt16("weekday"));
    setTourId(m_ResultSet.getString("tourid"));
    setDuration(m_ResultSet.getInt32("duration"));
}

} // end namespace customer
} // end namespace libcsc
