//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ROUTESMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_ROUTESMAPPERBASE_H

#include <customer/routes/routesptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class RoutesMapperBase
{
public:
    RoutesMapperBase(RoutesPtr routes);

    void map();

protected:
    virtual ~RoutesMapperBase();

    virtual void doMap() = 0;

    void setWeekday(const basar::Int16& weekday);
    void setTourId(const basar::VarString& tourId);
    void setDuration(const basar::Int32& duration);

private:
    RoutesPtr m_Routes;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ROUTESMAPPERBASE_H
