//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/routes/routes.h>

namespace libcsc {
namespace customer {

Routes::Routes()
{
}

Routes::~Routes()
{
}

basar::Int16 Routes::getWeekday() const
{
    return m_Weekday;
}

basar::VarString Routes::getTourId() const
{
    return m_TourId;
}

basar::Int32 Routes::getDuration() const
{
    return m_Duration;
}

} // end namespace customer
} // end namespace libcsc
