//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/routes/routesmapperbase.h>
#include <customer/routes/routes.h>

namespace libcsc {
namespace customer {

RoutesMapperBase::RoutesMapperBase(RoutesPtr routes)
: m_Routes(routes)
{
}

RoutesMapperBase::~RoutesMapperBase()
{
}

void RoutesMapperBase::map()
{
    doMap();
}

void RoutesMapperBase::setWeekday(const basar::Int16& weekday)
{
    m_Routes->m_Weekday = weekday;
    m_Routes->m_Weekday.setClean();
}

void RoutesMapperBase::setTourId(const basar::VarString& tourId)
{
    m_Routes->m_TourId = tourId;
    m_Routes->m_TourId.setClean();
}

void RoutesMapperBase::setDuration(const basar::Int32& duration)
{
    m_Routes->m_Duration = duration;
    m_Routes->m_Duration.setClean();
}

} // end namespace customer
} // end namespace libcsc
