//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ROUTESSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_ROUTESSQLMAPPER_H

#include <customer/routes/routesmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class RoutesSqlMapper : public RoutesMapperBase
{
public:
    RoutesSqlMapper(RoutesPtr routes, const basar::db::sql::ResultsetRef resultSet);
    virtual ~RoutesSqlMapper();

protected:
    virtual void doMap();

private:
    RoutesSqlMapper(const RoutesSqlMapper&);
    RoutesSqlMapper& operator=(const RoutesSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ROUTESSQLMAPPER_H
