//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ROUTES_H
#define GUARD_LIBCSC_CUSTOMER_ROUTES_H

#include <customer/routes/iroutes.h>
#include <datatypes/int16.h>
#include <datatypes/varstring.h>
#include <datatypes/int32.h>

namespace libcsc {
namespace customer {

class Routes : public IRoutes
{
    // because of OR mapping
    friend class RoutesMapperBase;

public:
    Routes();
    virtual ~Routes();

    virtual basar::Int16 getWeekday() const;
    virtual basar::VarString getTourId() const;
    virtual basar::Int32 getDuration() const;

private:
    libcsc::Int16 m_Weekday;
    libcsc::VarString m_TourId;
    libcsc::Int32 m_Duration;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ROUTES_H
