    

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ROUTESCOLLECTION_H
#define GUARD_LIBCSC_CUSTOMER_ROUTESCOLLECTION_H

#include <vector>
#include <customer/routes/routesptr.h>

namespace libcsc {
namespace customer {

typedef std::vector<RoutesPtr> RoutesCollection;

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ROUTESCOLLECTION_H
