#ifndef PXPARAMETERDEF_INC
#define PXPARAMETERDEF_INC

#define cPAR_KSC_GROUP            "KSC"
#define cPAR_KSC_DEL_PURPOSE      "ALLENOTAS"
#define cPAR_KSC_FOR_PARAMNAME    "IDFNR"

#define cPAR_GROUP_ORDERENTRY     "ORDERENTRY"
#define cPAR_PURPOSE_TAXSPANNE    "TAXSPANNE"
#define cPAR_PARAM_FIXZUSCHLAG    "FIXZUSCHLAG"

#define cPAR_HMK_GROUP            "Hmkdrvr"
#define cPAR_HMK_PURPOSE          "SuppressMessage"
#define cPAR_HMK_PARAMNAME        "MessageNumber"

#define cPAR_KSCSERVER_GROUP      "KSCSERVER"
#define cPAR_KSCSERVER_PURPOSE    "LOCKLEVEL"
#define cPAR_KSCSERVER_PARAMNAME  ""
#define cPAR_KSCSERVER_PARAMNAME_ENABLE "ENABLE"
#define cPAR_KSCSERVER_PARAMNAME_OMGDURATION  "OMG_DURATION"

#define cPAR_KSCSERVER_PURPOSE_CUSTOMERSPECIALS "CUSTOMERSPECIALS"
#define cPAR_KSCSERVER_PURPOSE_WRITEKDVERBUND	"WRITEKDVERBUND"
#define cPAR_KSCSERVER_PURPOSE_SPECIAL_PRISMA_PRISING	"SPECIALPRISMAPRICING"
#define cPAR_KSCSERVER_PURPOSE_TENDER			"TENDER"
#define cPAR_KSCSERVER_PURPOSE_CHECKPRICELIMITATION	"CHECKPRICELIMITATION"
#define cPAR_KSCSERVER_PURPOSE_MSV3_REIMPORTPROPOSAL "MSV3REIMPORTPROPOSAL"

#define cPAR_PHATRA_PROGRAMMNAME	"CSC_PHATRA"
#define cPAR_PHATRA_PARTNOTA		"PARTNOTA"
#define cPAR_PHATRA_PARAMNAME		""

#define cPAR_KSC_PURPOSE_MSV3RETURNS			"MSV3RETURNS"
#define cPAR_KSC_PARAMNAME_HIGHPRICELIMIT		"HighPriceLimit"

#endif
