//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_IPAYMENTS_H
#define GUARD_LIBCSC_CUSTOMER_IPAYMENTS_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class IPayments
{
public:
    virtual ~IPayments() {}

    virtual basar::VarString getInvoiceNo() const = 0;
    virtual basar::Int32 getInvoiceDate() const = 0;
    virtual basar::VarString getDocType() const = 0;
    virtual basar::Int16 getKindOfInvoice() const = 0;
    virtual basar::VarString getKindOfOrder() const = 0;
    virtual basar::Int16 getDueDays() const = 0;
    virtual basar::Int32 getDueDate() const = 0;
    virtual basar::Decimal getInvoiceValue() const = 0;
    virtual basar::Decimal getPaidValue() const = 0;
    virtual basar::VarString getPaymentSpec() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_IPAYMENTS_H
