//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PAYMENTSCOLLECTIONPTR_H
#define GUARD_LIBCSC_CUSTOMER_PAYMENTSCOLLECTIONPTR_H

#include <boost/shared_ptr.hpp>
#include <customer/payments/paymentscollection.h>

namespace libcsc {
namespace customer {

typedef boost::shared_ptr<PaymentsCollection> PaymentsCollectionPtr;

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PAYMENTSCOLLECTIONPTR_H
