//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PAYMENTSSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_PAYMENTSSQLMAPPER_H

#include <customer/payments/paymentsmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class PaymentsSqlMapper : public PaymentsMapperBase
{
public:
    PaymentsSqlMapper(PaymentsPtr payments, const basar::db::sql::ResultsetRef resultSet);
    virtual ~PaymentsSqlMapper();

protected:
    virtual void doMap();

private:
    PaymentsSqlMapper(const PaymentsSqlMapper&);
    PaymentsSqlMapper& operator=(const PaymentsSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PAYMENTSSQLMAPPER_H
