//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/payments/payments.h>

namespace libcsc {
namespace customer {

Payments::Payments()
{
}

Payments::~Payments()
{
}

basar::VarString Payments::getInvoiceNo() const
{
    return m_InvoiceNo;
}

basar::Int32 Payments::getInvoiceDate() const
{
    return m_InvoiceDate;
}

basar::VarString Payments::getDocType() const
{
    return m_DocType;
}

basar::Int16 Payments::getKindOfInvoice() const
{
    return m_KindOfInvoice;
}

basar::VarString Payments::getKindOfOrder() const
{
    return m_KindOfOrder;
}

basar::Int16 Payments::getDueDays() const
{
    return m_DueDays;
}

basar::Int32 Payments::getDueDate() const
{
    return m_DueDate;
}

basar::Decimal Payments::getInvoiceValue() const
{
    return m_InvoiceValue;
}

basar::Decimal Payments::getPaidValue() const
{
    return m_PaidValue;
}

basar::VarString Payments::getPaymentSpec() const
{
    return m_PaymentSpec;
}

} // end namespace customer
} // end namespace libcsc
