//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/payments/paymentssqlmapper.h>

namespace libcsc {
namespace customer {

PaymentsSqlMapper::PaymentsSqlMapper(PaymentsPtr payments, const basar::db::sql::ResultsetRef resultSet)
: PaymentsMapperBase(payments), m_ResultSet(resultSet)
{
}

PaymentsSqlMapper::~PaymentsSqlMapper()
{
}

void PaymentsSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setInvoiceNo(m_ResultSet.getString("invoiceno"));
    setInvoiceDate(m_ResultSet.getInt32("invoicedate"));
    setDocType(m_ResultSet.getString("doctype"));
    setKindOfInvoice(m_ResultSet.getInt16("kindofinvoice"));
    setKindOfOrder(m_ResultSet.getString("kindoforder"));
    setDueDays(m_ResultSet.getInt16("duedays"));
    setDueDate(m_ResultSet.getInt32("duedate"));
    setInvoiceValue(m_ResultSet.getDecimal("invoicevalue"));
    setPaidValue(m_ResultSet.getDecimal("paidvalue"));
    setPaymentSpec(m_ResultSet.getString("paymentspec"));
}

} // end namespace customer
} // end namespace libcsc
