//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/payments/paymentsmapperbase.h>
#include <customer/payments/payments.h>

namespace libcsc {
namespace customer {

PaymentsMapperBase::PaymentsMapperBase(PaymentsPtr payments)
: m_Payments(payments)
{
}

PaymentsMapperBase::~PaymentsMapperBase()
{
}

void PaymentsMapperBase::map()
{
    doMap();
}

void PaymentsMapperBase::setInvoiceNo(const basar::VarString& invoiceNo)
{
    m_Payments->m_InvoiceNo = invoiceNo;
    m_Payments->m_InvoiceNo.setClean();
}

void PaymentsMapperBase::setInvoiceDate(const basar::Int32& invoiceDate)
{
    m_Payments->m_InvoiceDate = invoiceDate;
    m_Payments->m_InvoiceDate.setClean();
}

void PaymentsMapperBase::setDocType(const basar::VarString& docType)
{
    m_Payments->m_DocType = docType;
    m_Payments->m_DocType.setClean();
}

void PaymentsMapperBase::setKindOfInvoice(const basar::Int16& kindOfInvoice)
{
    m_Payments->m_KindOfInvoice = kindOfInvoice;
    m_Payments->m_KindOfInvoice.setClean();
}

void PaymentsMapperBase::setKindOfOrder(const basar::VarString& kindOfOrder)
{
    m_Payments->m_KindOfOrder = kindOfOrder;
    m_Payments->m_KindOfOrder.setClean();
}

void PaymentsMapperBase::setDueDays(const basar::Int16& dueDays)
{
    m_Payments->m_DueDays = dueDays;
    m_Payments->m_DueDays.setClean();
}

void PaymentsMapperBase::setDueDate(const basar::Int32& dueDate)
{
    m_Payments->m_DueDate = dueDate;
    m_Payments->m_DueDate.setClean();
}

void PaymentsMapperBase::setInvoiceValue(const basar::Decimal& invoiceValue)
{
    m_Payments->m_InvoiceValue = invoiceValue;
    m_Payments->m_InvoiceValue.setClean();
}

void PaymentsMapperBase::setPaidValue(const basar::Decimal& paidValue)
{
    m_Payments->m_PaidValue = paidValue;
    m_Payments->m_PaidValue.setClean();
}

void PaymentsMapperBase::setPaymentSpec(const basar::VarString& paymentSpec)
{
    m_Payments->m_PaymentSpec = paymentSpec;
    m_Payments->m_PaymentSpec.setClean();
}

} // end namespace customer
} // end namespace libcsc
