//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PAYMENTS_H
#define GUARD_LIBCSC_CUSTOMER_PAYMENTS_H

#include <customer/payments/ipayments.h>
#include <datatypes/varstring.h>
#include <datatypes/int32.h>
#include <datatypes/int16.h>
#include <datatypes/decimal.h>

namespace libcsc {
namespace customer {

class Payments : public IPayments
{
    // because of OR mapping
    friend class PaymentsMapperBase;

public:
    Payments();
    virtual ~Payments();

    virtual basar::VarString getInvoiceNo() const;
    virtual basar::Int32 getInvoiceDate() const;
    virtual basar::VarString getDocType() const;
    virtual basar::Int16 getKindOfInvoice() const;
    virtual basar::VarString getKindOfOrder() const;
    virtual basar::Int16 getDueDays() const;
    virtual basar::Int32 getDueDate() const;
    virtual basar::Decimal getInvoiceValue() const;
    virtual basar::Decimal getPaidValue() const;
    virtual basar::VarString getPaymentSpec() const;

private:
    libcsc::VarString m_InvoiceNo;
    libcsc::Int32 m_InvoiceDate;
    libcsc::VarString m_DocType;
    libcsc::Int16 m_KindOfInvoice;
    libcsc::VarString m_KindOfOrder;
    libcsc::Int16 m_DueDays;
    libcsc::Int32 m_DueDate;
    libcsc::Decimal m_InvoiceValue;
    libcsc::Decimal m_PaidValue;
    libcsc::VarString m_PaymentSpec;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PAYMENTS_H
