//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PAYMENTSMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_PAYMENTSMAPPERBASE_H

#include <customer/payments/paymentsptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class PaymentsMapperBase
{
public:
    PaymentsMapperBase(PaymentsPtr payments);

    void map();

protected:
    virtual ~PaymentsMapperBase();

    virtual void doMap() = 0;

    void setInvoiceNo(const basar::VarString& invoiceNo);
    void setInvoiceDate(const basar::Int32& invoiceDate);
    void setDocType(const basar::VarString& docType);
    void setKindOfInvoice(const basar::Int16& kindOfInvoice);
    void setKindOfOrder(const basar::VarString& kindOfOrder);
    void setDueDays(const basar::Int16& dueDays);
    void setDueDate(const basar::Int32& dueDate);
    void setInvoiceValue(const basar::Decimal& invoiceValue);
    void setPaidValue(const basar::Decimal& paidValue);
    void setPaymentSpec(const basar::VarString& paymentSpec);

private:
    PaymentsPtr m_Payments;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PAYMENTSMAPPERBASE_H
