//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/guidata/guidatasqlmapper.h>

namespace libcsc {
namespace crema {

GuiDataSqlMapper::GuiDataSqlMapper(GuiDataPtr guiData, const basar::db::sql::ResultsetRef resultSet)
: GuiDataMapperBase(guiData), m_ResultSet(resultSet)
{
}

GuiDataSqlMapper::~GuiDataSqlMapper()
{
}

void GuiDataSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setBranchNo(m_ResultSet.getInt16("vertriebszentrumnr"));
    setIdf(m_ResultSet.getInt32("idfnr"));
    setCreditLimit(m_ResultSet.getDecimal("limit"));
    setCustomer(m_ResultSet.getString("nameapo"));
    setOrderID(m_ResultSet.getInt32("kdauftragnr"));
    setPlace(m_ResultSet.getString("ort"));
    setPostalCode(m_ResultSet.getString("postleitzahl"));
    setApothecary(m_ResultSet.getString("nameinhaber"));
    setOrderAmount(m_ResultSet.getDecimal("wertlieferung"));
    setSumDebitside(m_ResultSet.getDecimal("sum_debitside"));
    setSumCreditside(m_ResultSet.getDecimal("sum_creditside"));
    setSumMonTurnover(m_ResultSet.getDecimal("sum_monturnover"));
    setSumDayTurnover(m_ResultSet.getDecimal("sum_dayturnover"));
    setSumReturns(m_ResultSet.getDecimal("sum_returns"));
    setSumGoodsReceipt(m_ResultSet.getDecimal("sum_goodsreceipt"));
    setChainNo(m_ResultSet.getInt32("maincstno"));
}

} // end namespace crema
} // end namespace libcsc
