//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_GUIDATAMAPPERBASE_H
#define GUARD_LIBCSC_CREMA_GUIDATAMAPPERBASE_H

#include <crema/guidata/guidataptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class GuiDataMapperBase
{
public:
    GuiDataMapperBase(GuiDataPtr guiData);

    void map();

protected:
    virtual ~GuiDataMapperBase();

    virtual void doMap() = 0;

    void setBranchNo(const basar::Int16& branchNo);
    void setIdf(const basar::Int32& idf);
    void setCreditLimit(const basar::Decimal& creditLimit);
    void setCustomer(const basar::VarString& customer);
    void setOrderID(const basar::Int32& orderID);
    void setPlace(const basar::VarString& place);
    void setPostalCode(const basar::VarString& postalCode);
    void setApothecary(const basar::VarString& apothecary);
    void setOrderAmount(const basar::Decimal& orderAmount);
    void setSumDebitside(const basar::Decimal& sumDebitside);
    void setSumCreditside(const basar::Decimal& sumCreditside);
    void setSumMonTurnover(const basar::Decimal& sumMonTurnover);
    void setSumDayTurnover(const basar::Decimal& sumDayTurnover);
    void setSumReturns(const basar::Decimal& sumReturns);
    void setSumGoodsReceipt(const basar::Decimal& sumGoodsReceipt);
    void setChainNo(const basar::Int32& chainNo);
private:
    GuiDataPtr m_GuiData;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_GUIDATAMAPPERBASE_H
