//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/guidata/guidata.h>

namespace libcsc {
namespace crema {

GuiData::GuiData()
{
}

GuiData::~GuiData()
{
}

basar::Int16 GuiData::getBranchNo() const
{
    return m_BranchNo;
}

basar::Int32 GuiData::getIdf() const
{
    return m_Idf;
}

basar::Decimal GuiData::getCreditLimit() const
{
    return m_CreditLimit;
}

basar::VarString GuiData::getCustomer() const
{
    return m_Customer;
}

basar::Int32 GuiData::getOrderID() const
{
    return m_OrderID;
}

basar::VarString GuiData::getPlace() const
{
    return m_Place;
}

basar::VarString GuiData::getPostalCode() const
{
    return m_PostalCode;
}

basar::VarString GuiData::getApothecary() const
{
    return m_Apothecary;
}

basar::Decimal GuiData::getOrderAmount() const
{
    return m_OrderAmount;
}

basar::Decimal GuiData::getSumDebitside() const
{
    return m_SumDebitside;
}

basar::Decimal GuiData::getSumCreditside() const
{
    return m_SumCreditside;
}

basar::Decimal GuiData::getSumMonTurnover() const
{
    return m_SumMonTurnover;
}

basar::Decimal GuiData::getSumDayTurnover() const
{
    return m_SumDayTurnover;
}

basar::Decimal GuiData::getSumReturns() const
{
    return m_SumReturns;
}

basar::Decimal GuiData::getSumGoodsReceipt() const
{
    return m_SumGoodsReceipt;
}

basar::Int32 GuiData::getChainNo() const
{
    return m_ChainNo;
}

} // end namespace crema
} // end namespace libcsc
