//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_GUIDATA_H
#define GUARD_LIBCSC_CREMA_GUIDATA_H

#include <crema/guidata/iguidata.h>
#include <datatypes/int16.h>
#include <datatypes/int32.h>
#include <datatypes/decimal.h>
#include <datatypes/varstring.h>

namespace libcsc {
namespace crema {

class GuiData : public IGuiData
{
    // because of OR mapping
    friend class GuiDataMapperBase;

public:
    GuiData();
    virtual ~GuiData();

    virtual basar::Int16 getBranchNo() const;
    virtual basar::Int32 getIdf() const;
    virtual basar::Decimal getCreditLimit() const;
    virtual basar::VarString getCustomer() const;
    virtual basar::Int32 getOrderID() const;
    virtual basar::VarString getPlace() const;
    virtual basar::VarString getPostalCode() const;
    virtual basar::VarString getApothecary() const;
    virtual basar::Decimal getOrderAmount() const;
    virtual basar::Decimal getSumDebitside() const;
    virtual basar::Decimal getSumCreditside() const;
    virtual basar::Decimal getSumMonTurnover() const;
    virtual basar::Decimal getSumDayTurnover() const;
    virtual basar::Decimal getSumReturns() const;
    virtual basar::Decimal getSumGoodsReceipt() const;
    virtual basar::Int32 getChainNo() const;

private:
    libcsc::Int16 m_BranchNo;
    libcsc::Int32 m_Idf;
    libcsc::Decimal m_CreditLimit;
    libcsc::VarString m_Customer;
    libcsc::Int32 m_OrderID;
    libcsc::VarString m_Place;
    libcsc::VarString m_PostalCode;
    libcsc::VarString m_Apothecary;
    libcsc::Decimal m_OrderAmount;
    libcsc::Decimal m_SumDebitside;
    libcsc::Decimal m_SumCreditside;
    libcsc::Decimal m_SumMonTurnover;
    libcsc::Decimal m_SumDayTurnover;
    libcsc::Decimal m_SumReturns;
    libcsc::Decimal m_SumGoodsReceipt;
    libcsc::Int32 m_ChainNo;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_GUIDATA_H
