//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_GUIDATASQLMAPPER_H
#define GUARD_LIBCSC_CREMA_GUIDATASQLMAPPER_H

#include <crema/guidata/guidatamapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class GuiDataSqlMapper : public GuiDataMapperBase
{
public:
    GuiDataSqlMapper(GuiDataPtr guiData, const basar::db::sql::ResultsetRef resultSet);
    virtual ~GuiDataSqlMapper();

protected:
    virtual void doMap();

private:
    GuiDataSqlMapper(const GuiDataSqlMapper&);
    GuiDataSqlMapper& operator=(const GuiDataSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_GUIDATASQLMAPPER_H
