//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/guidata/guidatamapperbase.h>
#include <crema/guidata/guidata.h>

namespace libcsc {
namespace crema {

GuiDataMapperBase::GuiDataMapperBase(GuiDataPtr guiData)
: m_GuiData(guiData)
{
}

GuiDataMapperBase::~GuiDataMapperBase()
{
}

void GuiDataMapperBase::map()
{
    doMap();
}

void GuiDataMapperBase::setBranchNo(const basar::Int16& branchNo)
{
    m_GuiData->m_BranchNo = branchNo;
    m_GuiData->m_BranchNo.setClean();
}

void GuiDataMapperBase::setIdf(const basar::Int32& idf)
{
    m_GuiData->m_Idf = idf;
    m_GuiData->m_Idf.setClean();
}

void GuiDataMapperBase::setCreditLimit(const basar::Decimal& creditLimit)
{
    m_GuiData->m_CreditLimit = creditLimit;
    m_GuiData->m_CreditLimit.setClean();
}

void GuiDataMapperBase::setCustomer(const basar::VarString& customer)
{
    m_GuiData->m_Customer = customer;
    m_GuiData->m_Customer.setClean();
}

void GuiDataMapperBase::setOrderID(const basar::Int32& orderID)
{
    m_GuiData->m_OrderID = orderID;
    m_GuiData->m_OrderID.setClean();
}

void GuiDataMapperBase::setPlace(const basar::VarString& place)
{
    m_GuiData->m_Place = place;
    m_GuiData->m_Place.setClean();
}

void GuiDataMapperBase::setPostalCode(const basar::VarString& postalCode)
{
    m_GuiData->m_PostalCode = postalCode;
    m_GuiData->m_PostalCode.setClean();
}

void GuiDataMapperBase::setApothecary(const basar::VarString& apothecary)
{
    m_GuiData->m_Apothecary = apothecary;
    m_GuiData->m_Apothecary.setClean();
}

void GuiDataMapperBase::setOrderAmount(const basar::Decimal& orderAmount)
{
    m_GuiData->m_OrderAmount = orderAmount;
    m_GuiData->m_OrderAmount.setClean();
}

void GuiDataMapperBase::setSumDebitside(const basar::Decimal& sumDebitside)
{
    m_GuiData->m_SumDebitside = sumDebitside;
    m_GuiData->m_SumDebitside.setClean();
}

void GuiDataMapperBase::setSumCreditside(const basar::Decimal& sumCreditside)
{
    m_GuiData->m_SumCreditside = sumCreditside;
    m_GuiData->m_SumCreditside.setClean();
}

void GuiDataMapperBase::setSumMonTurnover(const basar::Decimal& sumMonTurnover)
{
    m_GuiData->m_SumMonTurnover = sumMonTurnover;
    m_GuiData->m_SumMonTurnover.setClean();
}

void GuiDataMapperBase::setSumDayTurnover(const basar::Decimal& sumDayTurnover)
{
    m_GuiData->m_SumDayTurnover = sumDayTurnover;
    m_GuiData->m_SumDayTurnover.setClean();
}

void GuiDataMapperBase::setSumReturns(const basar::Decimal& sumReturns)
{
    m_GuiData->m_SumReturns = sumReturns;
    m_GuiData->m_SumReturns.setClean();
}

void GuiDataMapperBase::setSumGoodsReceipt(const basar::Decimal& sumGoodsReceipt)
{
    m_GuiData->m_SumGoodsReceipt = sumGoodsReceipt;
    m_GuiData->m_SumGoodsReceipt.setClean();
}

void GuiDataMapperBase::setChainNo(const basar::Int32& chainNo)
{
    m_GuiData->m_ChainNo = chainNo;
    m_GuiData->m_ChainNo.setClean();
}

} // end namespace crema
} // end namespace libcsc
