//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_IGUIDATA_H
#define GUARD_LIBCSC_CREMA_IGUIDATA_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class IGuiData
{
public:
    virtual ~IGuiData() {}

    virtual basar::Int16 getBranchNo() const = 0;
    virtual basar::Int32 getIdf() const = 0;
    virtual basar::Decimal getCreditLimit() const = 0;
    virtual basar::VarString getCustomer() const = 0;
    virtual basar::Int32 getOrderID() const = 0;
    virtual basar::VarString getPlace() const = 0;
    virtual basar::VarString getPostalCode() const = 0;
    virtual basar::VarString getApothecary() const = 0;
    virtual basar::Decimal getOrderAmount() const = 0;
    virtual basar::Decimal getSumDebitside() const = 0;
    virtual basar::Decimal getSumCreditside() const = 0;
    virtual basar::Decimal getSumMonTurnover() const = 0;
    virtual basar::Decimal getSumDayTurnover() const = 0;
    virtual basar::Decimal getSumReturns() const = 0;
    virtual basar::Decimal getSumGoodsReceipt() const = 0;
    virtual basar::Int32 getChainNo() const = 0;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_IGUIDATA_H
