//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_IMAILDATA_H
#define GUARD_LIBCSC_CREMA_IMAILDATA_H

#include <libbasar_definitions.h>
#include <crema/maildata/recipientcollectionptr.h>

namespace libcsc {
namespace crema {

class IMailData
{
public:
    virtual ~IMailData() {}

    virtual basar::VarString getSender() const = 0;

    virtual RecipientCollectionPtr getRecipients() const = 0;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_IMAILDATA_H
