//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_MAILDATA_H
#define GUARD_LIBCSC_CREMA_MAILDATA_H

#include <crema/maildata/imaildata.h>
#include <datatypes/varstring.h>

namespace libcsc {
namespace crema {

class MailData : public IMailData
{
    // because of OR mapping
    friend class MailDataMapperBase;

public:
    MailData();
    virtual ~MailData();

    virtual basar::VarString getSender() const;

    virtual RecipientCollectionPtr getRecipients() const;

private:
    libcsc::VarString m_Sender;
    RecipientCollectionPtr m_Recipients;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_MAILDATA_H
