//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_MAILDATAMAPPERBASE_H
#define GUARD_LIBCSC_CREMA_MAILDATAMAPPERBASE_H

#include <crema/maildata/maildataptr.h>
#include <crema/maildata/recipientptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class MailDataMapperBase
{
public:
    MailDataMapperBase(MailDataPtr mailData);

    void map();

protected:
    virtual ~MailDataMapperBase();

    virtual void doMap() = 0;

    void setSender(const basar::VarString& sender);

    void setRecipient(const basar::Int16& emailType, const basar::VarString& recipient);

private:
    MailDataPtr m_MailData;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_MAILDATAMAPPERBASE_H
