//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/maildata/maildatasqlmapper.h>

namespace libcsc {
namespace crema {

MailDataSqlMapper::MailDataSqlMapper(MailDataPtr mailData, const basar::db::sql::ResultsetRef resultSet)
: MailDataMapperBase(mailData), m_ResultSet(resultSet)
{
}

MailDataSqlMapper::~MailDataSqlMapper()
{
}

void MailDataSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setSender(m_ResultSet.getString("sentfromaddress"));
    setRecipient(m_ResultSet.getInt16("emailtype"), m_ResultSet.getString("senttoaddress"));
}

} // end namespace crema
} // end namespace libcsc
