//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/maildata/maildatamapperbase.h>
#include <crema/maildata/maildata.h>
#include <crema/maildata/recipient.h>
#include <crema/maildata/recipientcollection.h>
#include <boost/make_shared.hpp>

namespace libcsc {
namespace crema {

MailDataMapperBase::MailDataMapperBase(MailDataPtr mailData)
: m_MailData(mailData)
{
}

MailDataMapperBase::~MailDataMapperBase()
{
}

void MailDataMapperBase::map()
{
    doMap();
}

void MailDataMapperBase::setSender(const basar::VarString& sender)
{
    if (m_MailData->m_Sender.isUnset())
    {
        m_MailData->m_Sender = sender;
        m_MailData->m_Sender.setClean();
    }
}

void MailDataMapperBase::setRecipient(const basar::Int16& emailType, const basar::VarString& address)
{
    RecipientPtr pRecipient = boost::make_shared<Recipient>();
    pRecipient->m_EmailType = emailType;
    pRecipient->m_EmailType.setClean();
    pRecipient->m_Address = address;
    pRecipient->m_Address.setClean();

    m_MailData->m_Recipients->push_back(pRecipient);
}

} // end namespace crema
} // end namespace libcsc
