//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/maildata/maildata.h>
#include <boost/make_shared.hpp>

namespace libcsc {
namespace crema {

MailData::MailData()
{
    m_Recipients = boost::make_shared<RecipientCollection>();
}

MailData::~MailData()
{
}

basar::VarString MailData::getSender() const
{
    return m_Sender;
}

RecipientCollectionPtr MailData::getRecipients() const
{
    return m_Recipients;
}

} // end namespace crema
} // end namespace libcsc
