//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_RECIPIENT_H
#define GUARD_LIBCSC_CREMA_RECIPIENT_H

#include <crema/maildata/irecipient.h>
#include <datatypes/int16.h>
#include <datatypes/varstring.h>

namespace libcsc {
namespace crema {

class Recipient : public IRecipient
{
    // because of OR mapping
    friend class MailDataMapperBase;

public:
    Recipient();
    virtual ~Recipient();

    virtual basar::VarString getAddress() const;

    virtual basar::Int16 getEmailType() const;

private:
    libcsc::VarString m_Address;
    libcsc::Int16 m_EmailType;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_RECIPIENT_H
