//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/maildata/recipient.h>

namespace libcsc {
namespace crema {

Recipient::Recipient()
{
}

Recipient::~Recipient()
{
}

basar::VarString Recipient::getAddress() const
{
    return m_Address;
}

basar::Int16 Recipient::getEmailType() const
{
    return m_EmailType;
}

} // end namespace crema
} // end namespace libcsc
