//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_IORDERDATA_H
#define GUARD_LIBCSC_CREMA_IORDERDATA_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class IOrderData
{
public:
    virtual ~IOrderData() {}

    virtual basar::Int16 getBranchNo() const = 0;
    virtual basar::Int32 getOrderID() const = 0;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_IORDERDATA_H
