//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/orderdata/orderdatasqlmapper.h>

namespace libcsc {
namespace crema {

OrderDataSqlMapper::OrderDataSqlMapper(OrderDataPtr orderData, const basar::db::sql::ResultsetRef resultSet)
: OrderDataMapperBase(orderData), m_ResultSet(resultSet)
{
}

OrderDataSqlMapper::~OrderDataSqlMapper()
{
}

void OrderDataSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setBranchNo(m_ResultSet.getInt16("branchno"));
    setOrderID(m_ResultSet.getInt32("kdauftragNr"));
}

} // end namespace crema
} // end namespace libcsc
