//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/orderdata/orderdata.h>

namespace libcsc {
namespace crema {

OrderData::OrderData()
{
}

OrderData::~OrderData()
{
}

basar::Int16 OrderData::getBranchNo() const
{
    return m_BranchNo;
}

basar::Int32 OrderData::getOrderID() const
{
    return m_OrderID;
}

} // end namespace crema
} // end namespace libcsc
