//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_ORDERDATAMAPPERBASE_H
#define GUARD_LIBCSC_CREMA_ORDERDATAMAPPERBASE_H

#include <crema/orderdata/orderdataptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class OrderDataMapperBase
{
public:
    OrderDataMapperBase(OrderDataPtr orderData);

    void map();

protected:
    virtual ~OrderDataMapperBase();

    virtual void doMap() = 0;

    void setBranchNo(const basar::Int16& branchNo);
    void setOrderID(const basar::Int32& orderID);

private:
    OrderDataPtr m_OrderData;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_ORDERDATAMAPPERBASE_H
