//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/orderdata/orderdatamapperbase.h>
#include <crema/orderdata/orderdata.h>

namespace libcsc {
namespace crema {

OrderDataMapperBase::OrderDataMapperBase(OrderDataPtr orderData)
: m_OrderData(orderData)
{
}

OrderDataMapperBase::~OrderDataMapperBase()
{
}

void OrderDataMapperBase::map()
{
    doMap();
}

void OrderDataMapperBase::setBranchNo(const basar::Int16& branchNo)
{
    m_OrderData->m_BranchNo = branchNo;
    m_OrderData->m_BranchNo.setClean();
}

void OrderDataMapperBase::setOrderID(const basar::Int32& orderID)
{
    m_OrderData->m_OrderID = orderID;
    m_OrderData->m_OrderID.setClean();
}

} // end namespace crema
} // end namespace libcsc
