//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_ORDERDATASQLMAPPER_H
#define GUARD_LIBCSC_CREMA_ORDERDATASQLMAPPER_H

#include <crema/orderdata/orderdatamapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class OrderDataSqlMapper : public OrderDataMapperBase
{
public:
    OrderDataSqlMapper(OrderDataPtr orderData, const basar::db::sql::ResultsetRef resultSet);
    virtual ~OrderDataSqlMapper();

protected:
    virtual void doMap();

private:
    OrderDataSqlMapper(const OrderDataSqlMapper&);
    OrderDataSqlMapper& operator=(const OrderDataSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_ORDERDATASQLMAPPER_H
