//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_ORDERDATA_H
#define GUARD_LIBCSC_CREMA_ORDERDATA_H

#include <crema/orderdata/iorderdata.h>
#include <datatypes/int16.h>
#include <datatypes/int32.h>

namespace libcsc {
namespace crema {

class OrderData : public IOrderData
{
    // because of OR mapping
    friend class OrderDataMapperBase;

public:
    OrderData();
    virtual ~OrderData();

    virtual basar::Int16 getBranchNo() const;
    virtual basar::Int32 getOrderID() const;

private:
    libcsc::Int16 m_BranchNo;
    libcsc::Int32 m_OrderID;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_ORDERDATA_H
