#ifndef PRZ_AE_TEXTE_H
#define PRZ_AE_TEXTE_H

#define AET_KENNBUCHSTABE       "K"
#define AET_EINHEIT             "Einheit"
#define AET_ARTIKELNAME         "Artikelname"
#define AET_DAF                 "DAF"  /* Darreichungsform */
#define AET_PZN                 "PZN"

#define AET_REZEPTPFLICHTIG     "rezeptpflichtig"
#define AET_APOTHEKENPFLICHTIG  "apothekenpflichtig"
#define AET_VERFALLDATUM        "Verfalldatum"
#define AET_HERSTELLERDEFEKT    "Herstellerdefekt"
#define AET_AUSSERHANDEL        "ausser Handel"
#define AET_NRAKTION            "NR-Aktion"
#define AET_NETTOAKTION         "Netto-Aktion"
#define AET_NICHT_UEBER_GH      "nicht über Großhandel"
#define AET_RUECKRUF            "Rückruf"
#define AET_RETOUREN_SPERRE     "Retourensperre"
#define AET_ERMAESSIGTE_MWST    "ermäßigte Mehrwertsteuer"
#define AET_KLINIKPACKUNG       "Klinikpackung"
#define AET_UEBERVORRAT         "Übervorrat"

#define AET_MENGE               "Menge"
#define AET_MENGE_ALT           "Menge alt"
#define AET_PREIS               "Preis"
#define AET_RG                  "RG"
#define AET_STUECK              " Stück"

#define AET_LAGERORT            "Lagerort"
#define AET_BER                 "Ber."      /* Bereich */
#define AET_ST                  "St."
#define AET_BEST                "Best."
#define AET_VERFALL             "Verfall"

#define AET_AMGE                "AM"
#define AET_BMGE                "BM"
#define AET_NRME                "NR"
#define AET_FU                  "FU"
#define AET_PA                  "PA"
#define AET_PNR                 "PNR"
#define AET_BEMERKUNG           "Bemerkung"

#define AET_IDF_NR              "IDF-Nr."
#define AET_APOTHEKENNAME       "Apothekenname"
#define AET_ORT                 "Ort"
#define AET_AUF_NR              "Auf.-Nr."
#define AET_TOUR                "Tour"
#define AET_A_ART               "AArt"
#define AET_GRST                "ST"
#define AET_POS                 "Pos."
#define AET_TRM                 "TRM"

#define AET_DATUM               "Datum"
#define AET_ZEIT                "Zeit"
#define AET_EREIGNIS            "Ereignis"
#define AET_TERMINAL            "Terminal"
#define AET_ANWENDER            "Anwender"

#define AET_ABC                 "ABC"
#define AET_STRASSE             "Straße"
#define AET_INHABER             "Inhaber"

#define AET_DFU                 "DFU"
#define AET_PH                  "PH"
#define AET_APOTHEKE            "Apotheke"
#define AET_ENDE                "Ende"
#define AET_KZ_PATA             "P"
#define AET_KURZ_AUFTR_NR       "A-Nr"

#define AET_BEZEICHNUNG         "Bezeichnung"
#define AET_ALTERNATIVNAME      "Alternativname"
#define AET_DISPO_HINWEIS       "Dispo-Hinweis"
#define AET_KZ_ANZ_ALPHA_TXT    "A"
#define AET_KURZ_BESTAND        "Bst"
#define AET_AEP                 "AEP"   /* Apothekeneinkaufspreis */
#define AET_KURZ_VERFALL        "Verf."
#define AET_KZ_KENNZEICHEN      "KZ"

#define AET_KZ_AUFTRAGSART      "AA"
#define AET_KURZ_VALUTA         "Val"
#define AET_KZ_NATRA            "N"
#define AET_KZ_NETTO            "A"
#define AET_KZ_BASIS_NATRA      "B"
#define AET_KZ_MONRAB           "M" /* Monatsrabatt */
#define AET_KZ_VERBUNDSPERRE    "V"
#define AET_KZ_VALUTASPERRE     "S"

#define AET_KURZ_TOUR_ID        "ID"
#define AET_KURZ_FOLGE          "Flg"
#define AET_ART                 "Art"

#define AET_AUFTRAGSERF_SYSTEM  "Auftragserfassungssystem"
#define AET_PHOENIX_OPER_SYST   "PHOENIX operatives System in SINIX"

#define AET_IN_UEBERTRAGUNG     "In Übertragung"
#define AET_UEBERTRAGEN         "Übertragen"
#define AET_IN_ERFASSUNG        "In Erfassung"
#define AET_IN_AENDERUNG        "In Änderung"
#define AET_ZURUECKGESTELLT     "Zurückgestellt"
#define AET_ENDE_ERFASSUNG      "Ende Erfassung"
#define AET_IN_KOMMI            "In Kommi"
#define AET_ENDE_KOMMI          "Ende Kommi"
#define AET_FAKTURIERBEREIT     "Fakturierbereit"
#define AET_FAKTURIERT          "Fakturiert"
#define AET_STORNIERT           "Storniert"

#define AET_TYP                 "Typ"
#define AET_GLOB                "Glob"

#define AET_KZ_BUCHART          "BA"
#define AET_KZ_BUCHMETHODE      "BM"
#define AET_KZ_KOMMIART         "KA"
#define AET_KZ_KOMMIMETHODE     "KM"
#define AET_KZ_KUNDENGRUPPE     "KG"
#define AET_KZ_STANDARD         "STD"

#define AET_KZ_FILIALE          "Fi"
#define AET_LAENGE              "Länge"
#define AET_HOEHE               "Höhe"
#define AET_BREITE              "Breite"
#define AET_VOLUMEN             "Volumen"

#define AET_KZ_FORMULARKENNUNG  "FK"
#define AET_KZ_LAGEREBENE       "LB"
#define AET_NACHRICHT           "Nachricht"

#define AET_UHR_BHF             " Uhr Bhf.: "
#define AET_UHR                 "Uhr"

#define AET_ARTIKELINFORMATION  "Artikelinformationen"
#define AET_KEINE               "keine"
#define AET_KEINER              "keiner"
#define AET_MONATE              " Monate"
#define AET_KUNDENINFORMATION   "Kundeninformationen"
#define AET_DM                  "€"

#define AET_HOME_CARE           "Home-Care"
#define AET_POOL_KUNDE          "MVDA-Kunde"
#define AET_ARB_KREIS_AKTUELL   "Arb.kreis akt"
#define AET_DIABETES            "Diabetes"
#define AET_TEAM_KUNDE          "Team-Kunde"
#define AET_KRITISCH            "kritisch"
#define AET_VIP_KUNDE           "Vip-Kunde"
#define AET_ALLGEMEIN           "allgemein"
#define AET_VICHY                "Vichy"
#define AET_BOUHON              "Bouhon"
#define AET_POOL                "MVDA"
#define AET_BUECHER             "Bücher"

#define AET_KZ_JA               "J"
#define AET_KZ_NEIN             "N"
#define AET_PARA                "PARA"
#define AET_SERA                "SERA"
#define AET_PHON                "PHON"
#define AET_AUTO                "AUTO"

#define AET_SP_ANKUNFT          "  Ank.: "
#define AET_PHOSIX_AUFTRAGSANN  "PHOENIX-Auftragsannahmesystem"
#define AET_VON                 "von"
#define AET_BIS                 "bis"
#define AET_ZEILEN              "Zeilen"
#define AET_AUFTRZ              "Auftr."
#define AET_WERT                "Wert"
#define AET_ZEILEN_DAFUE        "DAFUE"
#define AET_ZEILEN_PHON         "Phon."
#define AET_ZEILEN_ALPHA        "ALPHA"
#define AET_AUFTRAGSTATISTIK    "Auftragsstatistik"
#define AET_DRUCKER_FEHLER      "Drucken nicht möglich -> Fehler"
#define AET_LISTE_FEHLER        "Drucken nicht möglich -> zu viele Kopf- und Fusszeilen"
#define AET_SEITE               "Seite: "
#define AET_GESAMT              "Gesamt:"
#define AET_KUNDEN_NR           "Kundennummer:"
#define AET_TELEFON             "Telefon:"
#define AET_KURZWAHL            "Kurzwahl:"
#define AET_AUF_WERT            "Auf.-Wert:"
#define AET_KOM_ART             "KomArt:"
#define AET_BUCH_ART            "BuchArt:"
#define AET_LIF_WERT            "Liefer-Wert:"
#define AET_PLZ_ORT             "PLZ/Ort:"
#define AET_D_ZEILEN_WERT       "d. Zeilenwert:"
#define AET_PHONIE_INFO         "Phonieinfo:"

#define AET_KURZ_KILOMETER      "KM"
#define AET_AUF_ERF             "A-Erf"
#define AET_AUF_FAKT            "A-Fak"
#define AET_KZ_WANNEN           "Wan"
#define AET_KND_SOLL            "Soll"
#define AET_KND_IST             "Ist"
#define AET_STATUS              "Stat"

#define AET_KZ_URSPR_BAHNHOF    "AB"
#define AET_KZ_ANZ_WANNEN       "AW"
#define AET_ANZ_ZUR_WANNEN      "AWR"
#define AET_ANZ_ZUS_WANNEN      "WZ"
#define AET_ANZ_BEIPACKS        "BP"
#define AET_ANZ_SONDERWANNEN    "SW"

#define AET_ORDSTAT_STORNO      "ST"
#define AET_ORDSTAT_FAKTURENDE  "FA"
#define AET_ORDSTAT_BERFAKTUR   "BF"
#define AET_ORDSTAT_KOMMIENDE   "KO"
#define AET_ORDSTAT_INKOMMI     "NK"
#define AET_ORDSTAT_ERFASST     "ER"
#define AET_ORDSTAT_INAENDERUNG "AE"
#define AET_ORDSTAT_INERFASSUNG "IE"
#define AET_ORDSTAT_DFZURUECKG  "DF"
#define AET_ORDSTAT_ZURUECKG    "ZU"
#define AET_ORDSTAT_KEIN        "XX"

#define AET_FILIALE             "Filiale"
#define AET_FOLGE               "Folge"
#define AET_ZEITKEY             "Zeitschlüssel"
#define AET_ZEITART             "Zeitart"
#define AET_TAG                 "Tag"
#define AET_BEGIN               "Anfang"
#define AET_GERAET              "Gerät"

#define AET_CONT                "C" /* Container oder Lagerebene */

#define AET_DAT_WE              "Dat.WE"    /* WE-Datum */
#define AET_BEST_NR             "Best.Nr"   /* Bestellnummer */
#define AET_DAT_BEST            "Dat.Bst"   /* Datum Bestellung */

#define AET_NO_NEW_ORDERS       "Es stehen keine Aufträge zur Bearbeitung bereit."
#define AET_NEW_ORDERS          "Es stehen Aufträge zur Bearbeitung bereit."

#define AET_VERBME              "VM"
#define AET_VERBFIL             "VV"
#define AET_LAGBER              "LB"    /* Lagerbereich */
#define AET_KUF_ANZ             "Kopf- und Fußtexte anzeigen"

#define AET_KZ_DISPO            "DI"
#define AET_KZ_NACHL            "NL"
#define AET_NUMMER              "Nr."

#define AET_LOEDAFUE            "LOEDAFUE"
#define AET_AENKUNDE            "AENKUNDE"
#define AET_BUCHEN              "Buchen"
#define AET_ANZ_POS             "Positionen"
#define AET_KURZ_VALUTAAUTO     "VA"

#define AET_DATUM_ALT           "Dat.alt"
#define AET_AUFTRNR_ALT         "ANr.alt"
#define AET_AENDERUNGSART       "Änd.-Art"
#define AET_DATUM_NEU           "Dat.neu"
#define AET_AUFTRNR_NEU         "ANr.neu"
#define AET_MENGE_ALT_KZ        "Mng.alt"
#define AET_MENGE_NEU           "Mng.neu"
#define AET_MENGE_GEL           "Mng.gel"
#define AET_MENGE_OFFEN         "Mng.off"
#define AET_NACHLIEF            "Nachl."
#define AET_AENDER              "Änder."
#define AET_LOESC               "Lösch."

#define AET_HERKUNFT            "Herk.Filiale"
#define AET_MODUS               "Modus"
#define AET_VERBUND             "Verbund"
#define AET_CLEARING            "Clearing"
#define AET_EINRICHT            "Einricht"
#define AET_VORRAT              "Vorrat"
#define AET_UEBERVORRAT         "Übervorrat"
#define AET_RETOURE             "Retoure"
#define AET_STAMMHAUS           "Stammhaus"
#define AET_FEHLERAUFTRAG       "Fehlerauftrag"
#define AET_DOZ                 "Dir.o.Zeit"
#define AET_EMZ                 "Einm.m.Zeit"
#define AET_PMZ                 "Perm.m.Zeit"
#define AET_INTERN              "Intern"
#define AET_STAND_UM            "Stand um"
#define AET_NACHLIEFERUNG       "AUSLIEFERUNG AUFGRUND NACHLIEFERWUNSCH"
#define AET_RECHNR              "Rechn.-Nr."

#define AET_PORTO_VERPACKUNG    "PORTO UND VERPACKUNG"
#define AET_NEW_ORDER_NOT_POSS  "Die Erfassung neuer Aufträge wurde gesperrt!"

#define AET_ZEILEN_DAFUE_KZ     "ZD"

#define AET_DISPO               "DISPO"
#define AET_NACHL               "NACHL"
#define AET_INFO                "INFOTEXT"
#define AET_ART_UMGESCHL        "Umgeschl."

#define AET_UMS_AEP             "Umsätze zum AE-Preis"
#define AET_UMS_GP              "Umsätze zum Grosso-Preis"
#define AET_UMS_NN              "Umsätze Netto-Netto zum Netto-Netto AE-Preis"
#define AET_ANZ_AUFTR           "Anzahl Aufträge"
#define AET_ANZ_ZEILEN          "Anzahl Zeilen"
#define AET_WANNEN_NR           "Wannennr.:"
#define AET_ART_GESPERRT        "für AE gesperrt"
#define AET_VB_GESPERRT         "für Verbund gesperrt"
#define AET_NICHTGEF            "Führen wir nicht"

#define AET_RABATT_00           "rabattfähig"
#define AET_RABATT_01           "nicht rabattfähig"
#define AET_RABATT_02           "nicht rabattfähige\nInsuline"
#define AET_RABATT_03           "nicht rabattfähige\nImpfstoffe"
#define AET_RABATT_04           "nicht rabattfähig\nmindergängig"
#define AET_RABATT_1X           "bei Überweisungsauft.\nrabattfähig"
#define AET_RRPARTNER           "Rückrufpartner"
#define AET_RRZEIT              "Rückrufzeit"
#define AET_ZUSATZ              "Zusatz"
#define AET_FIL_NAME            "Filialname"
#define AET_BGA_NR              "BGA_Nr."
#define AET_CLOSE_TIME          "Schließzeiten"
#define AET_RECHNER_NAME        "Rechner"
#define AET_RR_OFFEN            "offen"
#define AET_RR_ERLEDIGT         "erledigt"
#define AET_KZ_ANZ_SHIFT        "AV"
#define AET_AUFTRAG_AUF         "Auftrag eröffnet, Auftragnr:"
#define AET_ZENTRAL_ART         "Privatsortiment"
#define AET_DEFEKT              "aus Defekt"
#define AET_HISTORY             "aus Historie"
#define AET_DEC                 "DEC"
#define AET_TEXT                "Text"
#define AET_GRUPPE              "Gruppe"
#define AET_ENTFERNUNG          "Entfernung"
#define AET_KDKLASSE            "KdKlasse"
#define AET_PLAN                "Plan"
#define AET_VERSCH              "versch."
#define AET_EINMAL              "1X"
#define AET_ZWEIMAL             "2X"
#define AET_DREIMAL             "3X"
#define AET_MEHR                ">3X"
#define AET_RUFE                "Rufe"
#define AET_VZ                  "VZ"
#define AET_BGA_NR_TAG          "BGA_Nr.Tagtour"
#define AET_VB_TOUR_ZEIT        "VB-Tourzeit"
#define AET_VB_TOUR_ZEIT_TAG    "VB-Tagtourzeit"
#define AET_OHNE_ZERTIFIKAT     "Ohne Zertifikat"
#define AET_VON_JAHR            "von Jahr"
#define AET_BIS_JAHR            "bis Jahr"
#define AET_ZEIT_AB             "Zeit ab"
#define AET_BUNDESLAND          "Land"
#define AET_VB                  "VB"
#define AET_ND                  "ND"
#define AET_POOL_NR             "Pool-Nr."
#define AET_POOL_TYP            "Pool-Typ"
#define AET_AKTIV               "aktiv"
#define AET_AUF_NR_FIL          "Auf.Nr.Fili."
#define AET_BEST_KSC            "Best. KSC"
#define AET_BEST_VSE            "Best. VSE"
#define AET_BELEG_NR            "Belegnr"
#define AET_UID                 "UID"
#define AET_KEY                 "Key"
#define AET_FAX                 "Fax:"
#define AET_AUF_NR_VSE          "Pharmos"
#define AET_BTM                 "BTM"
#define AET_STAMMLAGER          "Stammlager"
#define AET_MIDAS               "Midas"
#define AET_FAHRZEIT            "Fahrzeit"
#define AET_EKS                 "Zentrale Einkaufsperre"

#endif
