#pragma once
// DParAufBearb.h : header file
//


/////////////////////////////////////////////////////////////////////////////
// CDParAufBearb dialog

class CDParAufBearb : public CDialogMultiLang
{
// Construction
public:
    CDParAufBearb(CWnd* pParent = NULL);   // standard constructor

    enum { IDD = IDD_AE_PAR_AUFBEARB };
    CButton m_CBJa17;
    CButton m_CBNein17;
    CEdit   m_EditPZNZyto;
    CEdit   m_EditVbPos;
    CEdit   m_EditZeitNoBTM;
    CButton m_CBNein16;
    CButton m_CBJa16;
    CButton m_CBJa15;
    CButton m_CBNein15;
    CButton m_CBNein14;
    CButton m_CBJa14;
    CButton m_CBNein13;
    CButton m_CBNein12;
    CButton m_CBJa13;
    CButton m_CBJa12;
    CButton m_CBNein11;
    CButton m_CBJa11;
    CEdit   m_EditDefwertkeinabschluss;
    CButton m_CBNein10;
    CButton m_CBJa10;
    CButton m_CBNein9;
    CButton m_CBJa9;
    CButton m_CBNein8;
    CButton m_CBJa8;
    CEdit   m_EditTourKippZeit;
    CEdit   m_EditFiliale;
    CButton m_CBNein3;
    CButton m_CBNein7;
    CButton m_CBNein6;
    CButton m_CBNein5;
    CButton m_CBNein4;
    CButton m_CBNein2;
    CButton m_CBNein1;
    CButton m_CBJa7;
    CButton m_CBJa6;
    CButton m_CBJa5;
    CButton m_CBJa4;
    CButton m_CBJa3;
    CButton m_CBJa2;
    CButton m_CBJa1;
    CEdit   m_EditZMM;
    CEdit   m_EditZHH;
    CEdit   m_EditWTyp;
    CEdit   m_EditWTag;
    CEdit   m_EditSpaeter;
    CEdit   m_EditSepZeit;
    CEdit   m_EditPZNWf2;
    CEdit   m_EditPZNWf1;
    CEdit   m_EditPZNKl;
    CEdit   m_EditPZNGr;
    CEdit   m_EditPZNBTM;
    CEdit   m_EditNZeit;
    CEdit   m_EditMaxPos;
    CEdit   m_EditKZeit;
    CEdit   m_EditKa;
    CEdit   m_EditEilZeit;
    CEdit   m_EditDopKo;
    CEdit   m_EditBa;
    CEdit   m_EditAnzPos;
    CEdit   m_EditAa;
    CString m_CAa;
    long    m_lAnzPos;
    CString m_CBa;
    CString m_CDopKo;
    long    m_lEilZeit;
    CString m_CKa;
    long    m_lMaxPos;
    long    m_lNZeit;
    long    m_lPZNBTM;
    long    m_lPZNGr;
    long    m_lPZNKl;
    long    m_lPZNWf1;
    long    m_lPZNWf2;
    long    m_lSpaeter;
    CString m_CWTag;
    long    m_lZHH;
    long    m_lZMM;
    BOOL    m_bJa1;
    BOOL    m_bJa2;
    BOOL    m_bJa3;
    BOOL    m_bJa4;
    BOOL    m_bJa5;
    BOOL    m_bJa6;
    BOOL    m_bJa7;
    BOOL    m_bNein1;
    BOOL    m_bNein7;
    BOOL    m_bNein6;
    BOOL    m_bNein5;
    BOOL    m_bNein4;
    BOOL    m_bNein3;
    BOOL    m_bNein2;
    long    m_lKZeit;
    int     m_iFiliale;
    long    m_lSepZeit;
    int     m_iWTyp;
    BOOL    m_bJa8;
    BOOL    m_bNein8;
    long    m_lTourKippZeit;
    BOOL    m_bJa9;
    BOOL    m_bNein9;
    BOOL    m_bJa10;
    BOOL    m_bNein10;
    long    m_LDefwertkeinabschluss;
    BOOL    m_bJa11;
    BOOL    m_bNein11;
    BOOL    m_bJa12;
    BOOL    m_bJa13;
    BOOL    m_bNein12;
    BOOL    m_bNein13;
    BOOL    m_bJa14;
    BOOL    m_bJa15;
    BOOL    m_bNein14;
    BOOL    m_bNein15;
    BOOL    m_bJa16;
    BOOL    m_bNein16;
    long    m_lZeitNoBTM;
    long    m_lVbPos;
    long    m_lPZNZyto;
    BOOL    m_bNein17;
    BOOL    m_bJa17;
    short   m_FilialNr;
    BOOL    m_sklclose;
    CEdit   m_EditWake1;
    CEdit   m_EditWake2;
    short   m_sWake1;
    short   m_sWake2;
    CEdit   m_EditMaxSurcharge;
    double  m_dMaxSurcharge;
    COLORREF tour;

    BOOL m_bJa18;
    CButton m_CBJa18;
    CButton m_CBNein18;
    BOOL m_bNein18;
    CButton m_CBJa19;
    BOOL m_bJa19;
    CButton m_CBNein19;
    BOOL m_bNein19;
    CButton m_CBJa20;
    BOOL m_bJa20;
    CButton m_CBNein20;
    BOOL m_bNein20;
    CEdit m_edit_MaxPosAuf;
    short m_lMaxPosAuf;
    CEdit m_edit_PosZu;
    long m_lPosZu;
    CEdit m_edit_MaxEil;
    long m_lMaxEil;
    CEdit m_EditNorouting;
    CString m_CNorouting;
    CButton m_CBJa21;
    BOOL m_bJa21;
    CButton m_CBJa22;
    BOOL m_bJa22;
    CButton m_CBNein21;
    BOOL m_bNein21;
    CButton m_CBNein22;
    BOOL m_bNein22;
    CButton m_CB_Ja23;
    BOOL m_bJa23;
    CButton m_CB_Nein23;
    BOOL m_bNein23;
    CEdit m_EditPlusBTM;
    short m_sPlusBTM;
    CEdit m_EditNoNatra;
    long m_lNoNatra;
    CEdit m_EditMinBestell;
    CString m_CMinBestell;
    CEdit m_EditPZNGeb;
    CString m_CPZNGeb;
    CEdit m_EditMaxDauer;
    CString m_CMaxDauer;
    CEdit m_EditMaxQty;
    CString m_CMaxQty;
    CEdit m_EditPriceRange;
    CString m_CPriceRange;
    CButton m_CBJa24;
    BOOL m_bJa24;
    CButton m_CBNein24;
    BOOL m_bNein24;
    CButton m_CBJa25;
    BOOL m_bJa25;
    CButton m_CBNein25;
    BOOL m_bNein25;
    CButton m_CBJa26;
    BOOL m_bJa26;
    CButton m_CBNein26;
    BOOL m_bNein26;
    CEdit m_EditTourCheck;
    CString m_CTourCheck;
    CEdit m_EditPZNFranko;
    CString m_CPZNFranko;
    CEdit m_EditPZNFracht;
    CString m_CPZNFracht;
    CEdit m_EditAufClose;
    CString m_CAufClose;
    CEdit m_EditPosClose;
    CString m_CPosClose;
    CButton m_CBJa27;
    BOOL m_bJa27;
    CButton m_CBNein27;
    BOOL m_bNein27;
    CButton m_CBJa28;
    BOOL m_bJa28;
    CButton m_CBNein28;
    BOOL m_bNein28;
    CButton m_CBJa29;
    BOOL m_bJa29;
    CButton m_CBNein29;
    BOOL m_bNein29;
    CEdit m_editBeifueger;
    long m_lBeifueger;
    CButton m_CBJa30;
    BOOL m_bJa30;
    CButton m_CBNein30;
    BOOL m_bNein30;
    CButton m_CBJa31;
    BOOL m_bJa31;
    CButton m_CBNein31;
    BOOL m_bNein31;
    BOOL m_bJa32;
    BOOL m_bNein32;
    CButton m_CBJa32;
    CButton m_CBNein32;
    CEdit m_editTimeToClose;
    short m_sTimeToClose;
    CEdit m_editRequest;
    short m_sRequest;
    CEdit m_editDPODays;
    short m_sDPODays;
    CEdit m_editDelayedDays;
    short m_sDelayedDays;
    CButton m_CB_Ja33;
    BOOL m_bJa33;
    CButton m_CBNein33;
    BOOL m_bNein33;
    CButton m_CB_Ja34;
    BOOL m_bJa34;
    CButton m_CBNein34;
    BOOL m_bNein34;
    CButton m_CB_Ja35;
    BOOL m_bJa35;
    CButton m_CBNein35;
    BOOL m_bNein35;
    CButton m_CB_Ja36;
    BOOL m_bJa36;
    CButton m_CBNein36;
    BOOL m_bNein36;
    CButton m_CB_Ja37;
    BOOL m_bJa37;
    CButton m_CBNein37;
    BOOL m_bNein37;
    CButton m_CB_Ja38;
    BOOL m_bJa38;
    CButton m_CBNein38;
    BOOL m_bNein38;
    CButton m_CB_Ja39;
    BOOL m_bJa39;
    CButton m_CBNein39;
    BOOL m_bNein39;
    CButton m_CB_Ja40;
    BOOL m_bJa40;
    CButton m_CBNein40;
    BOOL m_bNein40;
    CButton m_CB_Ja41;
    BOOL m_bJa41;
    CButton m_CBNein41;
    BOOL m_bNein41;
    CButton m_CB_Ja42;
    BOOL m_bJa42;
    CButton m_CBNein42;
    BOOL m_bNein42;
    CEdit m_editReverse;
    short m_sReverse;
    CEdit m_editCremacancel;
    short m_sCremacancel;

protected:
    virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

    CPARAUFBEARB m_paraufbearb;

    // Generated message map functions
    afx_msg HBRUSH OnCtlColor(CDC* pDC, CWnd* pWnd, UINT nCtlColor);
    virtual BOOL OnInitDialog();
    afx_msg void OnCheckJa1();
    afx_msg void OnCheckJa2();
    afx_msg void OnCheckJa3();
    afx_msg void OnCheckJa4();
    afx_msg void OnCheckJa5();
    afx_msg void OnCheckJa6();
    afx_msg void OnCheckJa7();
    afx_msg void OnCheckNein1();
    afx_msg void OnCheckNein2();
    afx_msg void OnCheckNein3();
    afx_msg void OnCheckNein4();
    afx_msg void OnCheckNein5();
    afx_msg void OnCheckNein6();
    afx_msg void OnCheckNein7();
    afx_msg void OnChangeEditAa();
    afx_msg void OnChangeEditAnzpos();
    afx_msg void OnChangeEditBa();
    afx_msg void OnChangeEditDopko();
    afx_msg void OnChangeEditEilzeit();
    afx_msg void OnChangeEditKa();
    afx_msg void OnChangeEditKzeit();
    afx_msg void OnChangeEditMaxpos();
    afx_msg void OnChangeEditNzeit();
    afx_msg void OnChangeEditPznbtm();
    afx_msg void OnChangeEditPzngr();
    afx_msg void OnChangeEditPznkl();
    afx_msg void OnChangeEditPznwf1();
    afx_msg void OnChangeEditPznwf2();
    afx_msg void OnChangeEditSpaeter();
    afx_msg void OnChangeEditWtag();
    afx_msg void OnChangeEditZhh();
    afx_msg void OnChangeEditZmm();
    afx_msg void OnChangeEditWtyp();
    afx_msg void OnChangeEditSepzeit();
    virtual void OnOK();
    afx_msg void OnCheckNein8();
    afx_msg void OnCheckJa8();
    afx_msg void OnChangeEditTourkippzeit();
    afx_msg void OnCheckJa10();
    afx_msg void OnCheckJa9();
    afx_msg void OnCheckNein10();
    afx_msg void OnCheckNein9();
    afx_msg void OnChangeEditDefwertkeinabschluss();
    afx_msg void OnCheckJa11();
    afx_msg void OnCheckNein11();
    afx_msg void OnCheckJa12();
    afx_msg void OnCheckJa13();
    afx_msg void OnCheckNein12();
    afx_msg void OnCheckNein13();
    afx_msg void OnCheckJa14();
    afx_msg void OnCheckJa15();
    afx_msg void OnCheckNein14();
    afx_msg void OnCheckNein15();
    afx_msg void OnCheckJa16();
    afx_msg void OnCheckNein16();
    afx_msg void OnChangeEditZeitnobtm();
    afx_msg void OnChangeEditVbpos();
    afx_msg void OnChangeEditPznzyto();
    afx_msg void OnCheckJa17();
    afx_msg void OnCheckNein17();
    afx_msg void OnBnClickedCheckJa18();
    afx_msg void OnBnClickedCheckNein18();
    afx_msg void OnBnClickedCheckJa19();
    afx_msg void OnBnClickedCheckNein19();
    afx_msg void OnBnClickedCheckJa20();
    afx_msg void OnBnClickedCheckNein20();
    afx_msg void OnEnChangeEditMaxposauf();
    afx_msg void OnEnChangeEditPosZu();
    afx_msg void OnEnChangeEditMaxEil();
    afx_msg void OnEnChangeEditNorouting();
    afx_msg void OnBnClickedCheckJa21();
    afx_msg void OnBnClickedCheckNein21();
    afx_msg void OnBnClickedCheckJa22();
    afx_msg void OnBnClickedCheckNein22();
    afx_msg void OnBnClickedCheckJa23();
    afx_msg void OnBnClickedCheckNein23();
    afx_msg void OnEnChangeEditPlusBtm();
    afx_msg void OnEnChangeEditMinBestell();
    afx_msg void OnEnChangeEditPznGeb();
    afx_msg void OnEnChangeEditMaxDauer();
    afx_msg void OnEnChangeEditMaxQty();
    afx_msg void OnEnChangeEditPriceRange();
    afx_msg void OnBnClickedCheckJa24();
    afx_msg void OnBnClickedCheckNein24();
    afx_msg void OnBnClickedCheckJa25();
    afx_msg void OnBnClickedCheckNein25();
    afx_msg void OnBnClickedCheckJa26();
    afx_msg void OnBnClickedCheckNein26();
    afx_msg void OnEnChangeEditTourCheck();
    afx_msg void OnEnChangeEditPznFranko();
    afx_msg void OnEnChangeEditPznFracht();
    afx_msg void OnEnChangeEditAufClose();
    afx_msg void OnEnChangeEditPosClose();
    afx_msg void OnBnClickedCheckJa27();
    afx_msg void OnBnClickedCheckNein27();
    afx_msg void OnBnClickedCheckJa28();
    afx_msg void OnBnClickedCheckNein28();
    afx_msg void OnBnClickedCheckJa29();
    afx_msg void OnBnClickedCheckNein29();
    afx_msg void OnEnChangeEditWake1();
    afx_msg void OnEnChangeEditWake2();
    afx_msg void OnBnClickedCheckJa30();
    afx_msg void OnBnClickedCheckNein30();
    afx_msg void OnEnChangeEditBeifueger();
    afx_msg void OnBnClickedCheckJa31();
    afx_msg void OnBnClickedCheckNein31();
    afx_msg void OnBnClickedCheckJa32();
    afx_msg void OnBnClickedCheckNein32();
    afx_msg void OnEnChangeEditTimetoclose();
    afx_msg void OnEnChangeEditRequest();
    afx_msg void OnEnChangeEditDpodays();
    afx_msg void OnEnChangeEditDelayeddays();
    afx_msg void OnBnClickedCheckJa33();
    afx_msg void OnBnClickedCheckNein33();
    afx_msg void OnBnClickedCheckJa34();
    afx_msg void OnBnClickedCheckNein34();
    afx_msg void OnBnClickedCheckJa35();
    afx_msg void OnBnClickedCheckNein35();
    afx_msg void OnBnClickedCheckJa36();
    afx_msg void OnBnClickedCheckNein36();
    afx_msg void OnBnClickedCheckJa37();
    afx_msg void OnBnClickedCheckNein37();
    afx_msg void OnBnClickedCheckJa38();
    afx_msg void OnBnClickedCheckNein38();
    afx_msg void OnBnClickedCheckJa39();
    afx_msg void OnBnClickedCheckNein39();
    afx_msg void OnBnClickedCheckJa40();
    afx_msg void OnBnClickedCheckNein40();
    afx_msg void OnBnClickedCheckJa41();
    afx_msg void OnBnClickedCheckNein41();
    afx_msg void OnBnClickedCheckJa42();
    afx_msg void OnBnClickedCheckNein42();
    afx_msg void OnEnChangeEditReverse();
    afx_msg void OnEnChangeEditCremacancel();
    DECLARE_MESSAGE_MAP()

    long m_lPZNKl_old;
    long m_lPZNGr_old;
    long m_lPZNBTM_old;
    long m_lPZNWf1_old;
    long m_lPZNWf2_old;
    long m_lPZNZyto_old;
    long m_lPZNGeb_old;
    long m_lPZNFranko_old;
    long m_lPZNFracht_old;
};
