// DRechteAa.h : header file
//

/////////////////////////////////////////////////////////////////////////////
// CDRechteAa dialog
#pragma once

class CDRechteAa : public CDialogMultiLang
{
// Construction
public:
    CDRechteAa(CWnd* pParent = NULL);   // standard constructor
    CAeUser m_User;                     // User der geändert werden soll

    enum { IDD = IDD_AE_RECHTE_AA };
    CButton m_CBInfoPflege;
    CEdit   m_edit_AgentId;
    CButton m_CBHiPath;
    CButton m_CBDispodoku;
    CButton m_CBDisporechte;
    CButton m_CBDispobearb;
    CButton m_CBKeinPlan;
    CButton m_CBBewegungen;
    CButton m_CBFeiertage;
    CButton m_CBUpdRegion;
    CButton m_CBAnrufplan;
    CButton m_CBMehrVz;
    CButton m_CBUpdModem;
    CButton m_CBMessage;
    CButton m_CBMailUser;
    CButton m_CBNurInfo;
    CButton m_CBSperreAe;
    CButton m_CBAufAnz;
    CButton m_mCBSeraPlan;
    CButton m_CBStatusErl;
    CButton m_CBChangeFiliale;
    CButton m_CBCallback;
    CButton m_CBPlanteil;
    CButton m_CBKndFiliUms;
    CButton m_CBKndAart;
    CButton m_CBRufpAbw;
    CButton m_CBUpdEntsperr;
    CButton m_CBUpdAltfil;
    CButton m_CBUpdZeitart;
    CButton m_CBUpdInfo;
    CButton m_CBUpdtour;
    CButton m_CBAndFil;
    CButton m_CDKndInf;
    CButton m_CDParAufArt;
    CButton m_CDParAufBearb;
    CButton m_CDParAufErg;
    CButton m_CDParBuchArt;
    CButton m_CDParKaBaKomb;
    CButton m_CDParKommi;
    CButton m_CDParKoBehTyp;
    CButton m_CDParKommiArt;
    CButton m_CDParKondGr;
    CButton m_CBParNachArt;
    CButton m_CBUPdUser;
    CButton m_CBUser;
    CButton m_CBAdmin;
    CButton m_CBVoraus;
    BOOL    m_bAdmin;
    BOOL    m_bAndFil;
    BOOL    m_bKndInf;
    BOOL    m_bParAufArt;
    BOOL    m_bParAufBearb;
    BOOL    m_bParAufErg;
    BOOL    m_bParBuchArt;
    BOOL    m_bParKaBaKomb;
    BOOL    m_bParKoBehTyp;
    BOOL    m_bParKommi;
    BOOL    m_bParKommiArt;
    BOOL    m_bParKondGr;
    BOOL    m_bParNachArt;
    BOOL    m_bUpdUser;
    BOOL    m_bUser;
    CString m_CUser;
    CString m_CVergUser;
    BOOL    m_bUpdTour;
    BOOL    m_bUpdInfo;
    BOOL    m_bUpdZeitart;
    BOOL    m_bUpdAltfil;
    BOOL    m_bUpdEntsperr;
    BOOL    m_bRufpAbw;
    BOOL    m_bKndAart;
    BOOL    m_bKndFiliUms;
    BOOL    m_bPlanteil;
    BOOL    m_bCallback;
    BOOL    m_bChangeFiliale;
    BOOL    m_bStatusErl;
    BOOL    m_bSeraPlan;
    BOOL    m_bAufAnz;
    BOOL    m_bSperreAe;
    BOOL    m_bNurInfo;
    BOOL    m_bMailUser;
    BOOL    m_bMessage;
    BOOL    m_bUpdModem;
    BOOL    m_bMehrVz;
    BOOL    m_bAnrufplan;
    BOOL    m_bUpdRegion;
    BOOL    m_bFeiertage;
    BOOL    m_bBewegungen;
    BOOL    m_bKeinPlan;
    BOOL    m_bDispobearb;
    BOOL    m_bDisporechte;
    BOOL    m_bDispodoku;
    BOOL    m_bDispoHinttext;
    BOOL    m_bHiPath;
    CString m_csAgentId;
    BOOL    m_bInfoPflege;
    BOOL    m_bVoraus;
    BOOL    m_bUserInfoVz;
    BOOL    m_bUserInfoAll;
    BOOL m_bKreditAbschluss;
    BOOL m_bInternetAbschluss;
    BOOL m_bReserve;
    BOOL m_bBTMAbschluss;
    BOOL m_bCustGrpsAdmin;
    BOOL m_bNotfall;
    BOOL m_bCC;
    BOOL m_bRufweiter;
    BOOL m_bQuota;
    BOOL m_bDD;
    BOOL m_bBranchInfo;
    BOOL m_bForbidden;
    BOOL m_bSeporder;
    BOOL m_bVA;
    BOOL m_bFreePrice;
    BOOL m_bDiscountUp;
    BOOL m_bBeilageUp;
    CComboBox m_CComboBoxPool;
    BOOL m_bReserveZert;
    BOOL m_bReserveBPZ;
    BOOL m_bArzneiEH;
    BOOL m_bCheckKC;
    BOOL m_bDealerInfoAll;
    BOOL m_bEncloser;
    BOOL m_bOnlyInfo;
    BOOL m_bReserveCharge;
    BOOL m_bChangeRebateCalc;
    BOOL m_bDPODays;
    BOOL m_bMSV3bearb;
    CButton m_CBOriginTypeSettings;
    BOOL m_bOriginTypeSettings;
    BOOL m_bCremaMailAdr;
    BOOL m_bCremaStorno;
    BOOL m_bMSV3bearbNo;
    BOOL m_b2ndLevel;
    BOOL m_bCBRemarks;
    BOOL m_bCstTours;
    BOOL m_bExtraTourReasons;
    BOOL m_bBestellFenster;
    BOOL m_bCremaChangeTour;
    BOOL m_bReservationConfig;
    CButton m_CBCSVFormate;
    BOOL m_bCSVFormate;
    CButton m_CBCSVImport;
    BOOL m_bCSVImport;
    CButton m_CBDEGetter;
    BOOL m_bDEGetter;
    CButton m_CBCBRemarks;
    CButton m_CBAnzLief;
    BOOL m_bAnzLief;
    CButton m_CBAnzRech;
    BOOL m_bAnzRech;
    CButton m_CBWerbeFach;
    BOOL m_bWerbeFach;
    CButton m_CBAnzParamChange;
    BOOL m_bAnzParamChange;
    CButton m_CBChangeCMIOrder;
    BOOL m_bChangeCMIOrder;

protected:
    virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

    void RechteVorbelegen();

    virtual BOOL OnInitDialog();
    afx_msg void OnAeAdmin();
    afx_msg void OnAeAndereFiliale();
    afx_msg void OnAeKundeninfo();
    afx_msg void OnAeParAufart();
    afx_msg void OnAeParAufbearb();
    afx_msg void OnAeParAuferg();
    afx_msg void OnAeParBuchart();
    afx_msg void OnAeParKabakomb();
    afx_msg void OnAeParKobehtyp();
    afx_msg void OnAeParKommi();
    afx_msg void OnAeParKommiart();
    afx_msg void OnAeParKondgr();
    afx_msg void OnAeParNachart();
    afx_msg void OnAeUpduser();
    afx_msg void OnAeUser();
    virtual void OnOK();
    afx_msg void OnAeUpdinfo();
    afx_msg void OnAeZeitart();
    afx_msg void OnAeAltfiliale();
    afx_msg void OnAeEntsperr();
    afx_msg void OnAeRufpAbw();
    afx_msg void OnAeKndAart();
    afx_msg void OnAeKndFiliUms();
    afx_msg void OnAePlanteil();
    afx_msg void OnAeCallback();
    afx_msg void OnCheckChangeFiliale();
    afx_msg void OnAeStatusErl();
    afx_msg void OnAeSeraPlan();
    afx_msg void OnAeAufAnz();
    afx_msg void OnAeSperreAe();
    afx_msg void OnAeNurInfo();
    afx_msg void OnCheckMailUser();
    afx_msg void OnCheckMessage();
    afx_msg void OnAeUpdModem();
    afx_msg void OnAeMehrVz();
    afx_msg void OnAeAnrufplan();
    afx_msg void OnAeUpdRegion();
    afx_msg void OnAeFeiertage();
    afx_msg void OnAeBewegungen();
    afx_msg void OnCheckKeinPlan();
    afx_msg void OnAeDispoBearb();
    afx_msg void OnAeDispoRechte();
    afx_msg void OnAeDispoDoku();
    afx_msg void OnAeHipath();
    afx_msg void OnChangeEditAgentid();
    afx_msg void OnCheckInfoPflege();
    afx_msg void OnBnClickedAeVoraus();
    afx_msg void OnBnClickedAeKreditAbschluss();
    afx_msg void OnBnClickedAeInternetAbschluss();
    afx_msg void OnBnClickedAeReserve();
    afx_msg void OnBnClickedAeBtmAbschluss();
    afx_msg void OnBnClickedChkCustgrps4collorder();
    afx_msg void OnBnClickedCheckNotfall();
    afx_msg void OnBnClickedCheckCountry();
    afx_msg void OnBnClickedCheckRufweiter();
    afx_msg void OnBnClickedCheckQuota();
    afx_msg void OnBnClickedCheckDd();
    afx_msg void OnBnClickedCheckBranchinfo();
    afx_msg void OnBnClickedCheckForbidden();
    afx_msg void OnBnClickedCheckSeporder();
    afx_msg void OnBnClickedCheckVa();
    afx_msg void OnBnClickedCheckFreePrice();
    afx_msg void OnBnClickedCheckDiscountUp();
    afx_msg void OnBnClickedCheckBeilageUp();
    afx_msg void OnBnClickedAeReserveZert();
    afx_msg void OnBnClickedAeReserveBPZ();
    afx_msg void OnBnClickedArzneiEH();
    afx_msg void OnBnClickedCheckKC();
    afx_msg void OnBnClickedUserInfoVz();
    afx_msg void OnBnClickedUserInfoAll();
    afx_msg void OnBnClickedCheckDealerInfoAlle();
    afx_msg void OnBnClickedCheckEncloser();
    afx_msg void OnBnClickedCheckNurInfo();
    afx_msg void OnBnClickedCheckReserveCharge();
    afx_msg void OnBnClickedCheckChangeRebateCalc();
    afx_msg void OnBnClickedCheckDpodays();
    afx_msg void OnBnClickedAeMsv3Bearb();
    afx_msg void OnBnClickedCheckOrigintypesettings();
    afx_msg void OnBnClickedCheckCremaMailAdr();
    afx_msg void OnBnClickedCheckCremaStorno();
    afx_msg void OnBnClickedAeMsv3BearbNo();
    afx_msg void OnBnClickedCheck2ndLevel();
    afx_msg void OnBnClickedCBRemarks();
    afx_msg void OnBnClickedCstTours();
    afx_msg void OnBnClickedExtraTourReasons();
    afx_msg void OnBnClickedBestellFenster();
    afx_msg void OnBnClickedCremaChangeTour();
    afx_msg void OnBnClickedCheckReservationConfig();
    afx_msg void OnBnClickedCheckPflegeCsvimport();
    afx_msg void OnBnClickedCheckImportCsvAuftrag();
    afx_msg void OnBnClickedCheckDeGetter();
    afx_msg void OnBnClickedCheckAnzLief();
    afx_msg void OnBnClickedCheckAnzRech();
    afx_msg void OnBnClickedAeParWerbefach();
    afx_msg void OnBnClickedCheckAnzParamChanges();
    afx_msg void OnBnClickedChangeCMIOrder(); //TODO DZ
    DECLARE_MESSAGE_MAP()
};
