//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_DOCUMENT_ITAXRATESPTR_H
#define GUARD_LIBCSC_DOCUMENT_ITAXRATESPTR_H

#include <boost/shared_ptr.hpp>

namespace libcsc {
namespace document {

class ITaxrates;
typedef boost::shared_ptr<ITaxrates> ITaxratesPtr;

} // end namespace document
} // end namespace libcsc

#endif // GUARD_LIBCSC_DOCUMENT_ITAXRATESPTR_H
