//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_DOCUMENT_ITAXRATES_H
#define GUARD_LIBCSC_DOCUMENT_ITAXRATES_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace document {

class ITaxrates
{
public:
    virtual ~ITaxrates() {}

    virtual basar::Int16 getTaxlevel() const = 0;
    virtual basar::Decimal getSalesTaxrate() const = 0;
};

} // end namespace document
} // end namespace libcsc

#endif // GUARD_LIBCSC_DOCUMENT_ITAXRATES_H
