//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_DOCUMENT_TAXRATESSQLMAPPER_H
#define GUARD_LIBCSC_DOCUMENT_TAXRATESSQLMAPPER_H

#include <document/taxrates/taxratesmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace document {

class TaxratesSqlMapper : public TaxratesMapperBase
{
public:
    TaxratesSqlMapper(TaxratesPtr taxrates, const basar::db::sql::ResultsetRef resultSet);
    virtual ~TaxratesSqlMapper();

protected:
    virtual void doMap();

private:
    TaxratesSqlMapper(const TaxratesSqlMapper&);
    TaxratesSqlMapper& operator=(const TaxratesSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace document
} // end namespace libcsc

#endif // GUARD_LIBCSC_DOCUMENT_TAXRATESSQLMAPPER_H
