    

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_DOCUMENT_TAXRATESCOLLECTION_H
#define GUARD_LIBCSC_DOCUMENT_TAXRATESCOLLECTION_H

#include <vector>
#include <document/taxrates/taxratesptr.h>

namespace libcsc {
namespace document {

typedef std::vector<TaxratesPtr> TaxratesCollection;

} // end namespace document
} // end namespace libcsc

#endif // GUARD_LIBCSC_DOCUMENT_TAXRATESCOLLECTION_H
