//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <document/taxrates/taxrates.h>

namespace libcsc {
namespace document {

Taxrates::Taxrates()
{
}

Taxrates::~Taxrates()
{
}

basar::Int16 Taxrates::getTaxlevel() const
{
    return m_Taxlevel;
}

basar::Decimal Taxrates::getSalesTaxrate() const
{
    return m_SalesTaxrate;
}

} // end namespace document
} // end namespace libcsc
