//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <document/taxrates/taxratessqlmapper.h>

namespace libcsc {
namespace document {

TaxratesSqlMapper::TaxratesSqlMapper(TaxratesPtr taxrates, const basar::db::sql::ResultsetRef resultSet)
: TaxratesMapperBase(taxrates), m_ResultSet(resultSet)
{
}

TaxratesSqlMapper::~TaxratesSqlMapper()
{
}

void TaxratesSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setTaxlevel(m_ResultSet.getInt16("taxlevel"));
    setSalesTaxrate(m_ResultSet.getDecimal("salestaxrate"));
}

} // end namespace document
} // end namespace libcsc
