//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_DOCUMENT_TAXRATESMAPPERBASE_H
#define GUARD_LIBCSC_DOCUMENT_TAXRATESMAPPERBASE_H

#include <document/taxrates/taxratesptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace document {

class TaxratesMapperBase
{
public:
    TaxratesMapperBase(TaxratesPtr taxrates);

    void map();

protected:
    virtual ~TaxratesMapperBase();

    virtual void doMap() = 0;

    void setTaxlevel(const basar::Int16& taxlevel);
    void setSalesTaxrate(const basar::Decimal& salesTaxrate);

private:
    TaxratesPtr m_Taxrates;
};

} // end namespace document
} // end namespace libcsc

#endif // GUARD_LIBCSC_DOCUMENT_TAXRATESMAPPERBASE_H
