//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_DOCUMENT_TAXRATES_H
#define GUARD_LIBCSC_DOCUMENT_TAXRATES_H

#include <document/taxrates/itaxrates.h>
#include <datatypes/int16.h>
#include <datatypes/decimal.h>

namespace libcsc {
namespace document {

class Taxrates : public ITaxrates
{
    // because of OR mapping
    friend class TaxratesMapperBase;

public:
    Taxrates();
    virtual ~Taxrates();

    virtual basar::Int16 getTaxlevel() const;
    virtual basar::Decimal getSalesTaxrate() const;

private:
    libcsc::Int16 m_Taxlevel;
    libcsc::Decimal m_SalesTaxrate;
};

} // end namespace document
} // end namespace libcsc

#endif // GUARD_LIBCSC_DOCUMENT_TAXRATES_H
