//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <document/taxrates/taxratesmapperbase.h>
#include <document/taxrates/taxrates.h>

namespace libcsc {
namespace document {

TaxratesMapperBase::TaxratesMapperBase(TaxratesPtr taxrates)
: m_Taxrates(taxrates)
{
}

TaxratesMapperBase::~TaxratesMapperBase()
{
}

void TaxratesMapperBase::map()
{
    doMap();
}

void TaxratesMapperBase::setTaxlevel(const basar::Int16& taxlevel)
{
    m_Taxrates->m_Taxlevel = taxlevel;
    m_Taxrates->m_Taxlevel.setClean();
}

void TaxratesMapperBase::setSalesTaxrate(const basar::Decimal& salesTaxrate)
{
    m_Taxrates->m_SalesTaxrate = salesTaxrate;
    m_Taxrates->m_SalesTaxrate.setClean();
}

} // end namespace document
} // end namespace libcsc
