/*(c)
 ********************* PHARMX Customer Order Entry Server *********************

Class pxOrder:
Implementation of order item entry methods.
In this case an existing orderpositiondiscountentry linked to the parameter item will be deleted
*/
#include "pxrecord.h"
#include "pxdevice.hpp"
#include "pxsess.hpp"
#include "pxcstbas.hpp"
#include "pxcustomergrpflags.hpp"
#include "pxitem.hpp"
#include "pxitemattributes.hpp"
#include "pxorder.hpp"
#include "pxoeparm.hpp"
#include "pxorderposevent.hpp"
#include "pxorderpospromo.hpp"
#include "pxstockbooking.hpp"
#include <logger/loggerpool.h>
#include <libbasarcmnutil_datetime.h>
#include <tender/repository/itenderrepository.h>
#include <discount/orderpositiondiscount/orderpositiondiscountcollection.h>
#include <discount/orderpositiondiscount/orderpositiondiscount.h>
#include <discount/orderpositiondiscount/orderpositiondiscountrepositoryptr.h>
#include <discount/orderpositiondiscount/iorderpositiondiscountrepository.h>
#include <discount/orderpositiondiscount/iorderpositiondiscountrepositoryptr.h>


/*----------------------------------------------------------------------------*/
/*   EraseOrderpositionDiscountEntry                                          */
/*   the orderpositiondiscountentry was generated by mistake within the new   */
/*   rebate calculation feature.                                              */
/*----------------------------------------------------------------------------*/
int
pxOrder::EraseOrderpositionDiscountEntry
(
    pxOrderItem* item
)
{
    BLOG_TRACE_METHOD(libcsc::LoggerPool::getLoggerOrder(), "pxOrder::EraseOrderpositionDiscountEntry()");

    basar::Int32 rebInKindPosNo = 0;
    if (Param()->UseNewDiscountCalc())
    {
        try
        {
            if (0 != item->getDiscountList().get())
            {
                libcsc::discount::IOrderPositionDiscountRepositoryPtr opdRepository = Session()->getOrderPositionDiscountRepository();
                opdRepository->findByID(KdAuftragNr(), item->PosNr());

                libcsc::discount::OrderPositionDiscountListPtr opdDiscountList = item->getDiscountList();
                libcsc::discount::OrderPositionDiscountList::const_iterator it = opdDiscountList->begin();
                while (it != opdDiscountList->end())
                {
                    rebInKindPosNo = (*it)->getRebateInKindPositionNo();
                    if (rebInKindPosNo > 0)
                    {
                        opdRepository->erase(opdRepository->getOrderPositionDiscount((*it)->getPositionNo(), (*it)->getDiscountMode(), (*it)->getRebateInKindPositionNo(), (*it)->getRebateInKindOrderNo()));
                    }
                    ++it;
                }
                item->m_DiscountList.reset();
            }
        }
        catch (const basar::Exception & e)
        {
            std::stringstream ss;
            ss << "pxOrder::EraseOrderpositionDiscountEntry(): " << e.what().c_str();
            BLOG_ERROR(libcsc::LoggerPool::getLoggerOrderPositionDiscount(), ss.str().c_str());
        }
    }
    return ErrorState();
}
