#! /usr/bin/ksh
set -e

cd cxxtools
make -j40
cd ../pxdb
make -j40
cd ../pxverbund
make -j40
cd ../libcsc
make -j40

cd ../aaorderclose
make -j40
cd ../aapserv
make -j40
cd ../clearreservation
make -j40
cd ../kscserver
make -j40
cd ../thrift
make -j40
cd ../vborderimport2
make -j40

cd ../csc_host_interface/libbatch
make -j40
cd ../libcsc_utils
make -j40
cd ../csc_corpha
make -j40
cd ../csc_phabor
make -j40
cd ../csc_phatra
make -j40

cd ../../ibtorderimport
make -j40

cd ../csc_deli/libcsc_deli
make -j40
cd ../csc_deli
make -j40

cd ../..

installhome.sh


