//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ITURNOVER_H
#define GUARD_LIBCSC_CUSTOMER_ITURNOVER_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class ITurnover
{
public:
    virtual ~ITurnover() {}

    virtual basar::Decimal getTotal() const = 0;
    virtual basar::Decimal getXmlValue() const = 0;
    virtual basar::Decimal getValue() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ITURNOVER_H
