//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/turnover/turnover.h>

namespace libcsc {
namespace customer {

Turnover::Turnover()
{
}

Turnover::~Turnover()
{
}

basar::Decimal Turnover::getTotal() const
{
    return m_Total;
}

basar::Decimal Turnover::getXmlValue() const
{
    return m_XmlValue;
}

basar::Decimal Turnover::getValue() const
{
    return m_Value;
}

} // end namespace customer
} // end namespace libcsc
