//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_TURNOVER_H
#define GUARD_LIBCSC_CUSTOMER_TURNOVER_H

#include <customer/turnover/iturnover.h>
#include <datatypes/decimal.h>

namespace libcsc {
namespace customer {

class Turnover : public ITurnover
{
    // because of OR mapping
    friend class TurnoverMapperBase;

public:
    Turnover();
    virtual ~Turnover();

    virtual basar::Decimal getTotal() const;
    virtual basar::Decimal getXmlValue() const;
    virtual basar::Decimal getValue() const;

private:
    libcsc::Decimal m_Total;
    libcsc::Decimal m_XmlValue;
    libcsc::Decimal m_Value;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_TURNOVER_H
