//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_TURNOVERMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_TURNOVERMAPPERBASE_H

#include <customer/turnover/turnoverptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class TurnoverMapperBase
{
public:
    TurnoverMapperBase(TurnoverPtr turnover);

    void map();

protected:
    virtual ~TurnoverMapperBase();

    virtual void doMap() = 0;

    void setTotal(const basar::Decimal& total);
    void setXmlValue(const basar::Decimal& xmlValue);
    void setValue(const basar::Decimal& value);

private:
    TurnoverPtr m_Turnover;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_TURNOVERMAPPERBASE_H
