//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/turnover/turnoversqlmapper.h>

namespace libcsc {
namespace customer {

TurnoverSqlMapper::TurnoverSqlMapper(TurnoverPtr turnover, const basar::db::sql::ResultsetRef resultSet)
: TurnoverMapperBase(turnover), m_ResultSet(resultSet)
{
}

TurnoverSqlMapper::~TurnoverSqlMapper()
{
}

void TurnoverSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setTotal(m_ResultSet.getDecimal("total"));
    setXmlValue(m_ResultSet.getDecimal("xmlvalue"));
    setValue(m_ResultSet.getDecimal("value"));
}

} // end namespace customer
} // end namespace libcsc
