//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/turnover/turnovermapperbase.h>
#include <customer/turnover/turnover.h>

namespace libcsc {
namespace customer {

TurnoverMapperBase::TurnoverMapperBase(TurnoverPtr turnover)
: m_Turnover(turnover)
{
}

TurnoverMapperBase::~TurnoverMapperBase()
{
}

void TurnoverMapperBase::map()
{
    doMap();
}

void TurnoverMapperBase::setTotal(const basar::Decimal& total)
{
    m_Turnover->m_Total = total;
    m_Turnover->m_Total.setClean();
}

void TurnoverMapperBase::setXmlValue(const basar::Decimal& xmlValue)
{
    m_Turnover->m_XmlValue = xmlValue;
    m_Turnover->m_XmlValue.setClean();
}

void TurnoverMapperBase::setValue(const basar::Decimal& value)
{
    m_Turnover->m_Value = value;
    m_Turnover->m_Value.setClean();
}

} // end namespace customer
} // end namespace libcsc
