//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CSCPlatformConsolidationToolConfig {
    
    private CSCPlatformConsolidationToolConfigBranches2BMoved branches2BMovedField;
    
    private CSCPlatformConsolidationToolConfigApplication[] applicationsField;
    
    private string[] serversField;
    
    private CSCPlatformConsolidationToolConfigInterfaces interfacesField;
    
    private CSCPlatformConsolidationToolConfigPaths pathsField;
    
    private CSCPlatformConsolidationToolConfigModus modusField;
    
    private CSCPlatformConsolidationToolConfigEnvironment environmentField;
    
    /// <remarks/>
    public CSCPlatformConsolidationToolConfigBranches2BMoved Branches2BMoved {
        get {
            return this.branches2BMovedField;
        }
        set {
            this.branches2BMovedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Application", IsNullable=false)]
    public CSCPlatformConsolidationToolConfigApplication[] Applications {
        get {
            return this.applicationsField;
        }
        set {
            this.applicationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Server", IsNullable=false)]
    public string[] Servers {
        get {
            return this.serversField;
        }
        set {
            this.serversField = value;
        }
    }
    
    /// <remarks/>
    public CSCPlatformConsolidationToolConfigInterfaces Interfaces {
        get {
            return this.interfacesField;
        }
        set {
            this.interfacesField = value;
        }
    }
    
    /// <remarks/>
    public CSCPlatformConsolidationToolConfigPaths Paths {
        get {
            return this.pathsField;
        }
        set {
            this.pathsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CSCPlatformConsolidationToolConfigModus Modus {
        get {
            return this.modusField;
        }
        set {
            this.modusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CSCPlatformConsolidationToolConfigEnvironment Environment {
        get {
            return this.environmentField;
        }
        set {
            this.environmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CSCPlatformConsolidationToolConfigBranches2BMoved {
    
    private int[] branchField;
    
    private CSCPlatformConsolidationToolConfigBranches2BMovedDirection directionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Branch")]
    public int[] Branch {
        get {
            return this.branchField;
        }
        set {
            this.branchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CSCPlatformConsolidationToolConfigBranches2BMovedDirection Direction {
        get {
            return this.directionField;
        }
        set {
            this.directionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum CSCPlatformConsolidationToolConfigBranches2BMovedDirection {
    
    /// <remarks/>
    North2South,
    
    /// <remarks/>
    South2North,
    
    /// <remarks/>
    DeactivateCompletely,
    
    /// <remarks/>
    ActivateInSouth,
    
    /// <remarks/>
    ActivateInNorth,
    
    /// <remarks/>
    DeactivateSouth,
    
    /// <remarks/>
    DeactivateNorth,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CSCPlatformConsolidationToolConfigApplication {
    
    private string applicationVersionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ApplicationVersion {
        get {
            return this.applicationVersionField;
        }
        set {
            this.applicationVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CSCPlatformConsolidationToolConfigInterfaces {
    
    private string[] mSV3v1InterfacesField;
    
    private string[] mSV3v2InterfacesField;
    
    private string[] swimpInterfacesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("MSV3v1Interface", IsNullable=false)]
    public string[] MSV3v1Interfaces {
        get {
            return this.mSV3v1InterfacesField;
        }
        set {
            this.mSV3v1InterfacesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("MSV3v2Interface", IsNullable=false)]
    public string[] MSV3v2Interfaces {
        get {
            return this.mSV3v2InterfacesField;
        }
        set {
            this.mSV3v2InterfacesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SwimpInterface", IsNullable=false)]
    public string[] SwimpInterfaces {
        get {
            return this.swimpInterfacesField;
        }
        set {
            this.swimpInterfacesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CSCPlatformConsolidationToolConfigPaths {
    
    private string backupDirField;
    
    private string tempDirField;
    
    /// <remarks/>
    public string BackupDir {
        get {
            return this.backupDirField;
        }
        set {
            this.backupDirField = value;
        }
    }
    
    /// <remarks/>
    public string TempDir {
        get {
            return this.tempDirField;
        }
        set {
            this.tempDirField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum CSCPlatformConsolidationToolConfigModus {
    
    /// <remarks/>
    Real,
    
    /// <remarks/>
    Simulation,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum CSCPlatformConsolidationToolConfigEnvironment {
    
    /// <remarks/>
    Test,
    
    /// <remarks/>
    Prod,
}
