//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/changedquantities/changedquantitiesmapperbase.h>
#include <customer/changedquantities/changedquantities.h>

namespace libcsc {
namespace customer {

ChangedQuantitiesMapperBase::ChangedQuantitiesMapperBase(ChangedQuantitiesPtr changedQuantities)
: m_ChangedQuantities(changedQuantities)
{
}

ChangedQuantitiesMapperBase::~ChangedQuantitiesMapperBase()
{
}

void ChangedQuantitiesMapperBase::map()
{
    doMap();
}

void ChangedQuantitiesMapperBase::setBranchNo(const basar::Int16& branchNo)
{
    m_ChangedQuantities->m_BranchNo = branchNo;
    m_ChangedQuantities->m_BranchNo.setClean();
}

void ChangedQuantitiesMapperBase::setCustomerNo(const basar::Int32& customerNo)
{
    m_ChangedQuantities->m_CustomerNo = customerNo;
    m_ChangedQuantities->m_CustomerNo.setClean();
}

void ChangedQuantitiesMapperBase::setOrderDate(const basar::Int32& orderDate)
{
    m_ChangedQuantities->m_OrderDate = orderDate;
    m_ChangedQuantities->m_OrderDate.setClean();
}

void ChangedQuantitiesMapperBase::setOrderNo(const basar::Int32& orderNo)
{
    m_ChangedQuantities->m_OrderNo = orderNo;
    m_ChangedQuantities->m_OrderNo.setClean();
}

void ChangedQuantitiesMapperBase::setInvoiceNo(const basar::VarString& invoiceNo)
{
    m_ChangedQuantities->m_InvoiceNo = invoiceNo;
    m_ChangedQuantities->m_InvoiceNo.setClean();
}

void ChangedQuantitiesMapperBase::setArticleNo(const basar::Int32& articleNo)
{
    m_ChangedQuantities->m_ArticleNo = articleNo;
    m_ChangedQuantities->m_ArticleNo.setClean();
}

void ChangedQuantitiesMapperBase::setArticleName(const basar::VarString& articleName)
{
    m_ChangedQuantities->m_ArticleName = articleName;
    m_ChangedQuantities->m_ArticleName.setClean();
}

void ChangedQuantitiesMapperBase::setQuantityOriginal(const basar::Int32& quantityOriginal)
{
    m_ChangedQuantities->m_QuantityOriginal = quantityOriginal;
    m_ChangedQuantities->m_QuantityOriginal.setClean();
}

void ChangedQuantitiesMapperBase::setQuantityNew(const basar::Int32& quantityNew)
{
    m_ChangedQuantities->m_QuantityNew = quantityNew;
    m_ChangedQuantities->m_QuantityNew.setClean();
}

void ChangedQuantitiesMapperBase::setQuantityOrdered(const basar::Int32& quantityOrdered)
{
    m_ChangedQuantities->m_QuantityOrdered = quantityOrdered;
    m_ChangedQuantities->m_QuantityOrdered.setClean();
}

} // end namespace customer
} // end namespace libcsc
