//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIESSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIESSQLMAPPER_H

#include <customer/changedquantities/changedquantitiesmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class ChangedQuantitiesSqlMapper : public ChangedQuantitiesMapperBase
{
public:
    ChangedQuantitiesSqlMapper(ChangedQuantitiesPtr changedQuantities, const basar::db::sql::ResultsetRef resultSet);
    virtual ~ChangedQuantitiesSqlMapper();

protected:
    virtual void doMap();

private:
    ChangedQuantitiesSqlMapper(const ChangedQuantitiesSqlMapper&);
    ChangedQuantitiesSqlMapper& operator=(const ChangedQuantitiesSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIESSQLMAPPER_H
