//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/changedquantities/changedquantities.h>

namespace libcsc {
namespace customer {

ChangedQuantities::ChangedQuantities()
{
}

ChangedQuantities::~ChangedQuantities()
{
}

basar::Int16 ChangedQuantities::getBranchNo() const
{
    return m_BranchNo;
}

basar::Int32 ChangedQuantities::getCustomerNo() const
{
    return m_CustomerNo;
}

basar::Int32 ChangedQuantities::getOrderDate() const
{
    return m_OrderDate;
}

basar::Int32 ChangedQuantities::getOrderNo() const
{
    return m_OrderNo;
}

basar::VarString ChangedQuantities::getInvoiceNo() const
{
    return m_InvoiceNo;
}

basar::Int32 ChangedQuantities::getArticleNo() const
{
    return m_ArticleNo;
}

basar::VarString ChangedQuantities::getArticleName() const
{
    return m_ArticleName;
}

basar::Int32 ChangedQuantities::getQuantityOriginal() const
{
    return m_QuantityOriginal;
}

basar::Int32 ChangedQuantities::getQuantityNew() const
{
    return m_QuantityNew;
}

basar::Int32 ChangedQuantities::getQuantityOrdered() const
{
    return m_QuantityOrdered;
}

} // end namespace customer
} // end namespace libcsc
