//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIES_H
#define GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIES_H

#include <customer/changedquantities/ichangedquantities.h>
#include <datatypes/int16.h>
#include <datatypes/int32.h>
#include <datatypes/varstring.h>

namespace libcsc {
namespace customer {

class ChangedQuantities : public IChangedQuantities
{
    // because of OR mapping
    friend class ChangedQuantitiesMapperBase;

public:
    ChangedQuantities();
    virtual ~ChangedQuantities();

    virtual basar::Int16 getBranchNo() const;
    virtual basar::Int32 getCustomerNo() const;
    virtual basar::Int32 getOrderDate() const;
    virtual basar::Int32 getOrderNo() const;
    virtual basar::VarString getInvoiceNo() const;
    virtual basar::Int32 getArticleNo() const;
    virtual basar::VarString getArticleName() const;
    virtual basar::Int32 getQuantityOriginal() const;
    virtual basar::Int32 getQuantityNew() const;
    virtual basar::Int32 getQuantityOrdered() const;

private:
    libcsc::Int16 m_BranchNo;
    libcsc::Int32 m_CustomerNo;
    libcsc::Int32 m_OrderDate;
    libcsc::Int32 m_OrderNo;
    libcsc::VarString m_InvoiceNo;
    libcsc::Int32 m_ArticleNo;
    libcsc::VarString m_ArticleName;
    libcsc::Int32 m_QuantityOriginal;
    libcsc::Int32 m_QuantityNew;
    libcsc::Int32 m_QuantityOrdered;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIES_H
