//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/changedquantities/changedquantitiessqlmapper.h>

namespace libcsc {
namespace customer {

ChangedQuantitiesSqlMapper::ChangedQuantitiesSqlMapper(ChangedQuantitiesPtr changedQuantities, const basar::db::sql::ResultsetRef resultSet)
: ChangedQuantitiesMapperBase(changedQuantities), m_ResultSet(resultSet)
{
}

ChangedQuantitiesSqlMapper::~ChangedQuantitiesSqlMapper()
{
}

void ChangedQuantitiesSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setBranchNo(m_ResultSet.getInt16("branchno"));
    setCustomerNo(m_ResultSet.getInt32("customerno"));
    setOrderDate(m_ResultSet.getInt32("orderdate"));
    setOrderNo(m_ResultSet.getInt32("orderno"));
    setInvoiceNo(m_ResultSet.getString("invoiceno"));
    setArticleNo(m_ResultSet.getInt32("articleno"));
    setArticleName(m_ResultSet.getString("articlename"));
    setQuantityOriginal(m_ResultSet.getInt32("quantityoriginal"));
    setQuantityNew(m_ResultSet.getInt32("quantitynew"));
    setQuantityOrdered(m_ResultSet.getInt32("quantityordered"));
}

} // end namespace customer
} // end namespace libcsc
