//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIESMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIESMAPPERBASE_H

#include <customer/changedquantities/changedquantitiesptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class ChangedQuantitiesMapperBase
{
public:
    ChangedQuantitiesMapperBase(ChangedQuantitiesPtr changedQuantities);

    void map();

protected:
    virtual ~ChangedQuantitiesMapperBase();

    virtual void doMap() = 0;

    void setBranchNo(const basar::Int16& branchNo);
    void setCustomerNo(const basar::Int32& customerNo);
    void setOrderDate(const basar::Int32& orderDate);
    void setOrderNo(const basar::Int32& orderNo);
    void setInvoiceNo(const basar::VarString& invoiceNo);
    void setArticleNo(const basar::Int32& articleNo);
    void setArticleName(const basar::VarString& articleName);
    void setQuantityOriginal(const basar::Int32& quantityOriginal);
    void setQuantityNew(const basar::Int32& quantityNew);
    void setQuantityOrdered(const basar::Int32& quantityOrdered);

private:
    ChangedQuantitiesPtr m_ChangedQuantities;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_CHANGEDQUANTITIESMAPPERBASE_H
