//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ICHANGEDQUANTITIES_H
#define GUARD_LIBCSC_CUSTOMER_ICHANGEDQUANTITIES_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class IChangedQuantities
{
public:
    virtual ~IChangedQuantities() {}

    virtual basar::Int16 getBranchNo() const = 0;
    virtual basar::Int32 getCustomerNo() const = 0;
    virtual basar::Int32 getOrderDate() const = 0;
    virtual basar::Int32 getOrderNo() const = 0;
    virtual basar::VarString getInvoiceNo() const = 0;
    virtual basar::Int32 getArticleNo() const = 0;
    virtual basar::VarString getArticleName() const = 0;
    virtual basar::Int32 getQuantityOriginal() const = 0;
    virtual basar::Int32 getQuantityNew() const = 0;
    virtual basar::Int32 getQuantityOrdered() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ICHANGEDQUANTITIES_H
