//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_IPRICESANDDISCOUNTS_H
#define GUARD_LIBCSC_CUSTOMER_IPRICESANDDISCOUNTS_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class IPricesAndDiscounts
{
public:
    virtual ~IPricesAndDiscounts() {}

    virtual basar::Int32 getArticleNo() const = 0;
    virtual basar::Int16 getSellingMode() const = 0;
    virtual basar::Decimal getDiscountPercentage() const = 0;
    virtual basar::Decimal getGrossProfitPercentage() const = 0;
    virtual basar::Decimal getSalesPrice() const = 0;
    virtual basar::Decimal getPharmacySellPrice() const = 0;
    virtual basar::VarString getNZOKCode() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_IPRICESANDDISCOUNTS_H
