//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTSMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTSMAPPERBASE_H

#include <customer/pricesanddiscounts/pricesanddiscountsptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class PricesAndDiscountsMapperBase
{
public:
    PricesAndDiscountsMapperBase(PricesAndDiscountsPtr pricesAndDiscounts);

    void map();

protected:
    virtual ~PricesAndDiscountsMapperBase();

    virtual void doMap() = 0;

    void setArticleNo(const basar::Int32& articleNo);
    void setSellingMode(const basar::Int16& sellingMode);
    void setDiscountPercentage(const basar::Decimal& discountPercentage);
    void setGrossProfitPercentage(const basar::Decimal& grossProfitPercentage);
    void setSalesPrice(const basar::Decimal& salesPrice);
    void setPharmacySellPrice(const basar::Decimal& pharmacySellPrice);
    void setNZOKCode(const basar::VarString& nZOKCode);

private:
    PricesAndDiscountsPtr m_PricesAndDiscounts;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTSMAPPERBASE_H
