//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/pricesanddiscounts/pricesanddiscountssqlmapper.h>

namespace libcsc {
namespace customer {

PricesAndDiscountsSqlMapper::PricesAndDiscountsSqlMapper(PricesAndDiscountsPtr pricesAndDiscounts, const basar::db::sql::ResultsetRef resultSet)
: PricesAndDiscountsMapperBase(pricesAndDiscounts), m_ResultSet(resultSet)
{
}

PricesAndDiscountsSqlMapper::~PricesAndDiscountsSqlMapper()
{
}

void PricesAndDiscountsSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setArticleNo(m_ResultSet.getInt32("articleno"));
    setSellingMode(m_ResultSet.getInt16("sellingmode"));
    setDiscountPercentage(m_ResultSet.getDecimal("discountpercentage"));
    setGrossProfitPercentage(m_ResultSet.getDecimal("grossprofitpercentage"));
    setSalesPrice(m_ResultSet.getDecimal("salesprice"));
    setPharmacySellPrice(m_ResultSet.getDecimal("pharmacysellprice"));
    setNZOKCode(m_ResultSet.getString("nzokcode"));
}

} // end namespace customer
} // end namespace libcsc
