//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/pricesanddiscounts/pricesanddiscounts.h>

namespace libcsc {
namespace customer {

PricesAndDiscounts::PricesAndDiscounts()
{
}

PricesAndDiscounts::~PricesAndDiscounts()
{
}

basar::Int32 PricesAndDiscounts::getArticleNo() const
{
    return m_ArticleNo;
}

basar::Int16 PricesAndDiscounts::getSellingMode() const
{
    return m_SellingMode;
}

basar::Decimal PricesAndDiscounts::getDiscountPercentage() const
{
    return m_DiscountPercentage;
}

basar::Decimal PricesAndDiscounts::getGrossProfitPercentage() const
{
    return m_GrossProfitPercentage;
}

basar::Decimal PricesAndDiscounts::getSalesPrice() const
{
    return m_SalesPrice;
}

basar::Decimal PricesAndDiscounts::getPharmacySellPrice() const
{
    return m_PharmacySellPrice;
}

basar::VarString PricesAndDiscounts::getNZOKCode() const
{
    return m_NZOKCode;
}

} // end namespace customer
} // end namespace libcsc
