//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTSSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTSSQLMAPPER_H

#include <customer/pricesanddiscounts/pricesanddiscountsmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class PricesAndDiscountsSqlMapper : public PricesAndDiscountsMapperBase
{
public:
    PricesAndDiscountsSqlMapper(PricesAndDiscountsPtr pricesAndDiscounts, const basar::db::sql::ResultsetRef resultSet);
    virtual ~PricesAndDiscountsSqlMapper();

protected:
    virtual void doMap();

private:
    PricesAndDiscountsSqlMapper(const PricesAndDiscountsSqlMapper&);
    PricesAndDiscountsSqlMapper& operator=(const PricesAndDiscountsSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTSSQLMAPPER_H
