//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/pricesanddiscounts/pricesanddiscountsmapperbase.h>
#include <customer/pricesanddiscounts/pricesanddiscounts.h>

namespace libcsc {
namespace customer {

PricesAndDiscountsMapperBase::PricesAndDiscountsMapperBase(PricesAndDiscountsPtr pricesAndDiscounts)
: m_PricesAndDiscounts(pricesAndDiscounts)
{
}

PricesAndDiscountsMapperBase::~PricesAndDiscountsMapperBase()
{
}

void PricesAndDiscountsMapperBase::map()
{
    doMap();
}

void PricesAndDiscountsMapperBase::setArticleNo(const basar::Int32& articleNo)
{
    m_PricesAndDiscounts->m_ArticleNo = articleNo;
    m_PricesAndDiscounts->m_ArticleNo.setClean();
}

void PricesAndDiscountsMapperBase::setSellingMode(const basar::Int16& sellingMode)
{
    m_PricesAndDiscounts->m_SellingMode = sellingMode;
    m_PricesAndDiscounts->m_SellingMode.setClean();
}

void PricesAndDiscountsMapperBase::setDiscountPercentage(const basar::Decimal& discountPercentage)
{
    m_PricesAndDiscounts->m_DiscountPercentage = discountPercentage;
    m_PricesAndDiscounts->m_DiscountPercentage.setClean();
}

void PricesAndDiscountsMapperBase::setGrossProfitPercentage(const basar::Decimal& grossProfitPercentage)
{
    m_PricesAndDiscounts->m_GrossProfitPercentage = grossProfitPercentage;
    m_PricesAndDiscounts->m_GrossProfitPercentage.setClean();
}

void PricesAndDiscountsMapperBase::setSalesPrice(const basar::Decimal& salesPrice)
{
    m_PricesAndDiscounts->m_SalesPrice = salesPrice;
    m_PricesAndDiscounts->m_SalesPrice.setClean();
}

void PricesAndDiscountsMapperBase::setPharmacySellPrice(const basar::Decimal& pharmacySellPrice)
{
    m_PricesAndDiscounts->m_PharmacySellPrice = pharmacySellPrice;
    m_PricesAndDiscounts->m_PharmacySellPrice.setClean();
}

void PricesAndDiscountsMapperBase::setNZOKCode(const basar::VarString& nZOKCode)
{
    m_PricesAndDiscounts->m_NZOKCode = nZOKCode;
    m_PricesAndDiscounts->m_NZOKCode.setClean();
}

} // end namespace customer
} // end namespace libcsc
