//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTS_H
#define GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTS_H

#include <customer/pricesanddiscounts/ipricesanddiscounts.h>
#include <datatypes/int32.h>
#include <datatypes/int16.h>
#include <datatypes/decimal.h>
#include <datatypes/varstring.h>

namespace libcsc {
namespace customer {

class PricesAndDiscounts : public IPricesAndDiscounts
{
    // because of OR mapping
    friend class PricesAndDiscountsMapperBase;

public:
    PricesAndDiscounts();
    virtual ~PricesAndDiscounts();

    virtual basar::Int32 getArticleNo() const;
    virtual basar::Int16 getSellingMode() const;
    virtual basar::Decimal getDiscountPercentage() const;
    virtual basar::Decimal getGrossProfitPercentage() const;
    virtual basar::Decimal getSalesPrice() const;
    virtual basar::Decimal getPharmacySellPrice() const;
    virtual basar::VarString getNZOKCode() const;

private:
    libcsc::Int32 m_ArticleNo;
    libcsc::Int16 m_SellingMode;
    libcsc::Decimal m_DiscountPercentage;
    libcsc::Decimal m_GrossProfitPercentage;
    libcsc::Decimal m_SalesPrice;
    libcsc::Decimal m_PharmacySellPrice;
    libcsc::VarString m_NZOKCode;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PRICESANDDISCOUNTS_H
