//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_IPROMOTIONS_H
#define GUARD_LIBCSC_CUSTOMER_IPROMOTIONS_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class IPromotions
{
public:
    virtual ~IPromotions() {}

    virtual basar::Int32 getMaxQuantity1() const = 0;
    virtual basar::Int32 getMaxQuantity() const = 0;
    virtual basar::Int32 getSoldQuantity() const = 0;
    virtual basar::Int32 getMinQuantity() const = 0;
    virtual basar::Int32 getDateFrom() const = 0;
    virtual basar::Int32 getDateTo() const = 0;
    virtual basar::Int32 getArticleNo() const = 0;
    virtual basar::Int32 getBaseQuantity() const = 0;
    virtual basar::Decimal getBaseValue() const = 0;
    virtual basar::Decimal getDiscountValuePercentage() const = 0;
    virtual basar::Int16 getDiscountQuantity() const = 0;
    virtual basar::Int32 getDiscountArticle() const = 0;
    virtual basar::Int16 getDiscountSpecification() const = 0;
    virtual basar::VarString getNotViaSalesWeb() const = 0;
    virtual basar::Int16 getPromotionNo() const = 0;
    virtual basar::VarString getName() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_IPROMOTIONS_H
