//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/promotions/promotions.h>

namespace libcsc {
namespace customer {

Promotions::Promotions()
{
}

Promotions::~Promotions()
{
}

basar::Int32 Promotions::getMaxQuantity1() const
{
    return m_MaxQuantity1;
}

basar::Int32 Promotions::getMaxQuantity() const
{
    return m_MaxQuantity;
}

basar::Int32 Promotions::getSoldQuantity() const
{
    return m_SoldQuantity;
}

basar::Int32 Promotions::getMinQuantity() const
{
    return m_MinQuantity;
}

basar::Int32 Promotions::getDateFrom() const
{
    return m_DateFrom;
}

basar::Int32 Promotions::getDateTo() const
{
    return m_DateTo;
}

basar::Int32 Promotions::getArticleNo() const
{
    return m_ArticleNo;
}

basar::Int32 Promotions::getBaseQuantity() const
{
    return m_BaseQuantity;
}

basar::Decimal Promotions::getBaseValue() const
{
    return m_BaseValue;
}

basar::Decimal Promotions::getDiscountValuePercentage() const
{
    return m_DiscountValuePercentage;
}

basar::Int16 Promotions::getDiscountQuantity() const
{
    return m_DiscountQuantity;
}

basar::Int32 Promotions::getDiscountArticle() const
{
    return m_DiscountArticle;
}

basar::Int16 Promotions::getDiscountSpecification() const
{
    return m_DiscountSpecification;
}

basar::VarString Promotions::getNotViaSalesWeb() const
{
    return m_NotViaSalesWeb;
}

basar::Int16 Promotions::getPromotionNo() const
{
    return m_PromotionNo;
}

basar::VarString Promotions::getName() const
{
    return m_Name;
}

} // end namespace customer
} // end namespace libcsc
