//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PROMOTIONS_H
#define GUARD_LIBCSC_CUSTOMER_PROMOTIONS_H

#include <customer/promotions/ipromotions.h>
#include <datatypes/int32.h>
#include <datatypes/decimal.h>
#include <datatypes/int16.h>
#include <datatypes/varstring.h>

namespace libcsc {
namespace customer {

class Promotions : public IPromotions
{
    // because of OR mapping
    friend class PromotionsMapperBase;

public:
    Promotions();
    virtual ~Promotions();

    virtual basar::Int32 getMaxQuantity1() const;
    virtual basar::Int32 getMaxQuantity() const;
    virtual basar::Int32 getSoldQuantity() const;
    virtual basar::Int32 getMinQuantity() const;
    virtual basar::Int32 getDateFrom() const;
    virtual basar::Int32 getDateTo() const;
    virtual basar::Int32 getArticleNo() const;
    virtual basar::Int32 getBaseQuantity() const;
    virtual basar::Decimal getBaseValue() const;
    virtual basar::Decimal getDiscountValuePercentage() const;
    virtual basar::Int16 getDiscountQuantity() const;
    virtual basar::Int32 getDiscountArticle() const;
    virtual basar::Int16 getDiscountSpecification() const;
    virtual basar::VarString getNotViaSalesWeb() const;
    virtual basar::Int16 getPromotionNo() const;
    virtual basar::VarString getName() const;

private:
    libcsc::Int32 m_MaxQuantity1;
    libcsc::Int32 m_MaxQuantity;
    libcsc::Int32 m_SoldQuantity;
    libcsc::Int32 m_MinQuantity;
    libcsc::Int32 m_DateFrom;
    libcsc::Int32 m_DateTo;
    libcsc::Int32 m_ArticleNo;
    libcsc::Int32 m_BaseQuantity;
    libcsc::Decimal m_BaseValue;
    libcsc::Decimal m_DiscountValuePercentage;
    libcsc::Int16 m_DiscountQuantity;
    libcsc::Int32 m_DiscountArticle;
    libcsc::Int16 m_DiscountSpecification;
    libcsc::VarString m_NotViaSalesWeb;
    libcsc::Int16 m_PromotionNo;
    libcsc::VarString m_Name;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PROMOTIONS_H
