//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PROMOTIONSMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_PROMOTIONSMAPPERBASE_H

#include <customer/promotions/promotionsptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class PromotionsMapperBase
{
public:
    PromotionsMapperBase(PromotionsPtr promotions);

    void map();

protected:
    virtual ~PromotionsMapperBase();

    virtual void doMap() = 0;

    void setMaxQuantity1(const basar::Int32& maxQuantity1);
    void setMaxQuantity(const basar::Int32& maxQuantity);
    void setSoldQuantity(const basar::Int32& soldQuantity);
    void setMinQuantity(const basar::Int32& minQuantity);
    void setDateFrom(const basar::Int32& dateFrom);
    void setDateTo(const basar::Int32& dateTo);
    void setArticleNo(const basar::Int32& articleNo);
    void setBaseQuantity(const basar::Int32& baseQuantity);
    void setBaseValue(const basar::Decimal& baseValue);
    void setDiscountValuePercentage(const basar::Decimal& discountValuePercentage);
    void setDiscountQuantity(const basar::Int16& discountQuantity);
    void setDiscountArticle(const basar::Int32& discountArticle);
    void setDiscountSpecification(const basar::Int16& discountSpecification);
    void setNotViaSalesWeb(const basar::VarString& notViaSalesWeb);
    void setPromotionNo(const basar::Int16& promotionNo);
    void setName(const basar::VarString& name);

private:
    PromotionsPtr m_Promotions;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PROMOTIONSMAPPERBASE_H
