//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PROMOTIONSSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_PROMOTIONSSQLMAPPER_H

#include <customer/promotions/promotionsmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class PromotionsSqlMapper : public PromotionsMapperBase
{
public:
    PromotionsSqlMapper(PromotionsPtr promotions, const basar::db::sql::ResultsetRef resultSet);
    virtual ~PromotionsSqlMapper();

protected:
    virtual void doMap();

private:
    PromotionsSqlMapper(const PromotionsSqlMapper&);
    PromotionsSqlMapper& operator=(const PromotionsSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PROMOTIONSSQLMAPPER_H
