//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/promotions/promotionsmapperbase.h>
#include <customer/promotions/promotions.h>

namespace libcsc {
namespace customer {

PromotionsMapperBase::PromotionsMapperBase(PromotionsPtr promotions)
: m_Promotions(promotions)
{
}

PromotionsMapperBase::~PromotionsMapperBase()
{
}

void PromotionsMapperBase::map()
{
    doMap();
}

void PromotionsMapperBase::setMaxQuantity1(const basar::Int32& maxQuantity1)
{
    m_Promotions->m_MaxQuantity1 = maxQuantity1;
    m_Promotions->m_MaxQuantity1.setClean();
}

void PromotionsMapperBase::setMaxQuantity(const basar::Int32& maxQuantity)
{
    m_Promotions->m_MaxQuantity = maxQuantity;
    m_Promotions->m_MaxQuantity.setClean();
}

void PromotionsMapperBase::setSoldQuantity(const basar::Int32& soldQuantity)
{
    m_Promotions->m_SoldQuantity = soldQuantity;
    m_Promotions->m_SoldQuantity.setClean();
}

void PromotionsMapperBase::setMinQuantity(const basar::Int32& minQuantity)
{
    m_Promotions->m_MinQuantity = minQuantity;
    m_Promotions->m_MinQuantity.setClean();
}

void PromotionsMapperBase::setDateFrom(const basar::Int32& dateFrom)
{
    m_Promotions->m_DateFrom = dateFrom;
    m_Promotions->m_DateFrom.setClean();
}

void PromotionsMapperBase::setDateTo(const basar::Int32& dateTo)
{
    m_Promotions->m_DateTo = dateTo;
    m_Promotions->m_DateTo.setClean();
}

void PromotionsMapperBase::setArticleNo(const basar::Int32& articleNo)
{
    m_Promotions->m_ArticleNo = articleNo;
    m_Promotions->m_ArticleNo.setClean();
}

void PromotionsMapperBase::setBaseQuantity(const basar::Int32& baseQuantity)
{
    m_Promotions->m_BaseQuantity = baseQuantity;
    m_Promotions->m_BaseQuantity.setClean();
}

void PromotionsMapperBase::setBaseValue(const basar::Decimal& baseValue)
{
    m_Promotions->m_BaseValue = baseValue;
    m_Promotions->m_BaseValue.setClean();
}

void PromotionsMapperBase::setDiscountValuePercentage(const basar::Decimal& discountValuePercentage)
{
    m_Promotions->m_DiscountValuePercentage = discountValuePercentage;
    m_Promotions->m_DiscountValuePercentage.setClean();
}

void PromotionsMapperBase::setDiscountQuantity(const basar::Int16& discountQuantity)
{
    m_Promotions->m_DiscountQuantity = discountQuantity;
    m_Promotions->m_DiscountQuantity.setClean();
}

void PromotionsMapperBase::setDiscountArticle(const basar::Int32& discountArticle)
{
    m_Promotions->m_DiscountArticle = discountArticle;
    m_Promotions->m_DiscountArticle.setClean();
}

void PromotionsMapperBase::setDiscountSpecification(const basar::Int16& discountSpecification)
{
    m_Promotions->m_DiscountSpecification = discountSpecification;
    m_Promotions->m_DiscountSpecification.setClean();
}

void PromotionsMapperBase::setNotViaSalesWeb(const basar::VarString& notViaSalesWeb)
{
    m_Promotions->m_NotViaSalesWeb = notViaSalesWeb;
    m_Promotions->m_NotViaSalesWeb.setClean();
}

void PromotionsMapperBase::setPromotionNo(const basar::Int16& promotionNo)
{
    m_Promotions->m_PromotionNo = promotionNo;
    m_Promotions->m_PromotionNo.setClean();
}

void PromotionsMapperBase::setName(const basar::VarString& name)
{
    m_Promotions->m_Name = name;
    m_Promotions->m_Name.setClean();
}

} // end namespace customer
} // end namespace libcsc
