//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/promotions/promotionssqlmapper.h>

namespace libcsc {
namespace customer {

PromotionsSqlMapper::PromotionsSqlMapper(PromotionsPtr promotions, const basar::db::sql::ResultsetRef resultSet)
: PromotionsMapperBase(promotions), m_ResultSet(resultSet)
{
}

PromotionsSqlMapper::~PromotionsSqlMapper()
{
}

void PromotionsSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setMaxQuantity1(m_ResultSet.getInt32("maxquantity1"));
    setMaxQuantity(m_ResultSet.getInt32("maxquantity"));
    setSoldQuantity(m_ResultSet.getInt32("soldquantity"));
    setMinQuantity(m_ResultSet.getInt32("minquantity"));
    setDateFrom(m_ResultSet.getInt32("datefrom"));
    setDateTo(m_ResultSet.getInt32("dateto"));
    setArticleNo(m_ResultSet.getInt32("articleno"));
    setBaseQuantity(m_ResultSet.getInt32("basequantity"));
    setBaseValue(m_ResultSet.getDecimal("basevalue"));
    setDiscountValuePercentage(m_ResultSet.getDecimal("discountvaluepercentage"));
    setDiscountQuantity(m_ResultSet.getInt16("discountquantity"));
    setDiscountArticle(m_ResultSet.getInt32("discountarticle"));
    setDiscountSpecification(m_ResultSet.getInt16("discountspecification"));
    setNotViaSalesWeb(m_ResultSet.getString("notviasalesweb"));
    setPromotionNo(m_ResultSet.getInt16("promotionno"));
    setName(m_ResultSet.getString("name"));
}

} // end namespace customer
} // end namespace libcsc
