//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_IWEEKTOURS_H
#define GUARD_LIBCSC_CUSTOMER_IWEEKTOURS_H

#include <libbasar_definitions.h>

namespace libcsc {
    namespace customer {

        class IWeekTours
        {
        public:
            virtual ~IWeekTours() {}

            virtual basar::VarString getTourId() const = 0;
            virtual basar::Int32 getFahrtZeit() const = 0;
            virtual basar::Int16 getWeekday() const = 0;
            virtual basar::VarString getOrderType() const = 0;
            virtual bool isIbtTour() const = 0;
            virtual bool isBtmTour() const = 0;
            virtual bool isKKTour() const = 0;
            virtual bool isK08Tour() const = 0;
            virtual bool isK20Tour() const = 0;
            virtual bool isReturnsTour() const = 0;
            virtual basar::Int32 getOrderPeriodFromTime() const = 0;
            virtual basar::Int32 getOrderPeriodToTime() const = 0;
            virtual basar::Int32 getOrderPeriodMainTime() const = 0;
        };

    } // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_IWEEKTOURS_H
