//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_WEEKTOURSCOLLECTIONPTR_H
#define GUARD_LIBCSC_CUSTOMER_WEEKTOURSCOLLECTIONPTR_H

#include <boost/shared_ptr.hpp>
#include <customer/tours/weektours/weektourscollection.h>

namespace libcsc {
    namespace customer {

        typedef boost::shared_ptr<WeekToursCollection> WeekToursCollectionPtr;

    } // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_WEEKTOURSCOLLECTIONPTR_H
