//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_WEEKTOURSMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_WEEKTOURSMAPPERBASE_H

#include <customer/tours/weektours/weektoursptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
    namespace customer {

        class WeekToursMapperBase
        {
        public:
            WeekToursMapperBase(WeekToursPtr tours);

            void map();

        protected:
            virtual ~WeekToursMapperBase();

            virtual void doMap() = 0;

            void setTourId(const basar::VarString& tourId);
            void setFahrtZeit(const basar::Int32& fahrtZeit);
            void setWeekday(const basar::Int16& weekday);
            void setOrderType(const basar::VarString& orderType);
            void setIsIbtTour(const bool& isIbtTour);
            void setIsBtmTour(const bool& isBtmTour);
            void setIsKKTour(const bool& isKKTour);
            void setIsK08Tour(const bool& isK08Tour);
            void setIsK20Tour(const bool& isK20Tour);
            void setIsReturnsTour(const bool& isReturnsTour);
            void setOrderPeriodFromTime(const basar::Int32& orderPeriodFromTime);
            void setOrderPeriodToTime(const basar::Int32& orderPeriodToTime);
            void setOrderPeriodMainTime(const basar::Int32& orderPeriodMainTime);

        private:
            WeekToursPtr m_Tours;
        };

    } // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_WEEKTOURSMAPPERBASE_H
