//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_WEEKTOURS_H
#define GUARD_LIBCSC_CUSTOMER_WEEKTOURS_H

#include <customer/tours/weektours/iweektours.h>
#include <datatypes/varstring.h>
#include <datatypes/int32.h>
#include <datatypes/int16.h>

namespace libcsc {
    namespace customer {

        class WeekTours : public IWeekTours
        {
            // because of OR mapping
            friend class WeekToursMapperBase;

        public:
            WeekTours();
            virtual ~WeekTours();

            virtual basar::VarString getTourId() const;
            virtual basar::Int32 getFahrtZeit() const;
            virtual basar::Int16 getWeekday() const;
            virtual basar::VarString getOrderType() const;
            virtual bool isIbtTour() const;
            virtual bool isBtmTour() const;
            virtual bool isKKTour() const;
            virtual bool isK08Tour() const;
            virtual bool isK20Tour() const;
            virtual bool isReturnsTour() const;
            virtual basar::Int32 getOrderPeriodFromTime() const;
            virtual basar::Int32 getOrderPeriodToTime() const;
            virtual basar::Int32 getOrderPeriodMainTime() const;

        private:
            libcsc::VarString m_TourId;
            libcsc::Int32 m_FahrtZeit;
            libcsc::Int16 m_Weekday;
            libcsc::VarString m_OrderType;
            libcsc::Int16 m_IsIbtTour;
            libcsc::Int16 m_IsBtmTour;
            libcsc::Int16 m_IsKKTour;
            libcsc::Int16 m_IsK08Tour;
            libcsc::Int16 m_IsK20Tour;
            libcsc::Int16 m_IsReturnsTour;
            libcsc::Int32 m_OrderPeriodFromTime;
            libcsc::Int32 m_OrderPeriodToTime;
            libcsc::Int32 m_OrderPeriodMainTime;

        };

    } // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_WEEKTOURS_H
