//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/tours/weektours/weektoursmapperbase.h>
#include <customer/tours/weektours/weektours.h>

namespace libcsc {
    namespace customer {

        WeekToursMapperBase::WeekToursMapperBase(WeekToursPtr tours)
            : m_Tours(tours)
        {
        }

        WeekToursMapperBase::~WeekToursMapperBase()
        {
        }

        void WeekToursMapperBase::map()
        {
            doMap();
        }

        void WeekToursMapperBase::setTourId(const basar::VarString& tourId)
        {
            m_Tours->m_TourId = tourId;
            m_Tours->m_TourId.setClean();
        }

        void WeekToursMapperBase::setFahrtZeit(const basar::Int32& fahrtZeit)
        {
            m_Tours->m_FahrtZeit = fahrtZeit;
            m_Tours->m_FahrtZeit.setClean();
        }

        void WeekToursMapperBase::setWeekday(const basar::Int16& weekday)
        {
            m_Tours->m_Weekday = weekday;
            m_Tours->m_Weekday.setClean();
        }

        void WeekToursMapperBase::setOrderType(const basar::VarString& orderType)
        {
            m_Tours->m_OrderType = orderType;
            m_Tours->m_OrderType.setClean();
        }

        void WeekToursMapperBase::setIsIbtTour(const bool& isIbtTour)
        {
            m_Tours->m_IsIbtTour = isIbtTour;
            m_Tours->m_IsIbtTour.setClean();
        }

        void WeekToursMapperBase::setIsBtmTour(const bool& isBtmTour)
        {
            m_Tours->m_IsBtmTour = isBtmTour;
            m_Tours->m_IsBtmTour.setClean();
        }

        void WeekToursMapperBase::setIsKKTour(const bool& isKKTour)
        {
            m_Tours->m_IsKKTour = isKKTour;
            m_Tours->m_IsKKTour.setClean();
        }

        void WeekToursMapperBase::setIsK08Tour(const bool& isK08Tour)
        {
            m_Tours->m_IsK08Tour = isK08Tour;
            m_Tours->m_IsK08Tour.setClean();
        }

        void WeekToursMapperBase::setIsK20Tour(const bool& isK20Tour)
        {
            m_Tours->m_IsK20Tour = isK20Tour;
            m_Tours->m_IsK20Tour.setClean();
        }

        void WeekToursMapperBase::setIsReturnsTour(const bool& isReturnsTour)
        {
            m_Tours->m_IsReturnsTour = isReturnsTour;
            m_Tours->m_IsReturnsTour.setClean();
        }

        void WeekToursMapperBase::setOrderPeriodFromTime(const basar::Int32& orderPeriodFromTime)
        {
            m_Tours->m_OrderPeriodFromTime = orderPeriodFromTime;
            m_Tours->m_OrderPeriodFromTime.setClean();
        }

        void WeekToursMapperBase::setOrderPeriodToTime(const basar::Int32& orderPeriodToTime)
        {
            m_Tours->m_OrderPeriodToTime = orderPeriodToTime;
            m_Tours->m_OrderPeriodToTime.setClean();
        }

        void WeekToursMapperBase::setOrderPeriodMainTime(const basar::Int32& orderPeriodMainTime)
        {
            m_Tours->m_OrderPeriodMainTime = orderPeriodMainTime;
            m_Tours->m_OrderPeriodMainTime.setClean();
        }

    } // end namespace customer
} // end namespace libcsc
