//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_WEEKTOURSSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_WEEKTOURSSQLMAPPER_H

#include <customer/tours/weektours/weektoursmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
    namespace customer {

        class WeekToursSqlMapper : public WeekToursMapperBase
        {
        public:
            WeekToursSqlMapper(WeekToursPtr tours, const basar::db::sql::ResultsetRef resultSet);
            virtual ~WeekToursSqlMapper();

        protected:
            virtual void doMap();

        private:
            WeekToursSqlMapper(const WeekToursSqlMapper&);
            WeekToursSqlMapper& operator=(const WeekToursSqlMapper&);

            const basar::db::sql::ResultsetRef m_ResultSet;
        };

    } // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_WEEKTOURSSQLMAPPER_H
