//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/tours/weektours/weektourssqlmapper.h>

namespace libcsc {
    namespace customer {

        WeekToursSqlMapper::WeekToursSqlMapper(WeekToursPtr tours, const basar::db::sql::ResultsetRef resultSet)
            : WeekToursMapperBase(tours), m_ResultSet(resultSet)
        {
        }

        WeekToursSqlMapper::~WeekToursSqlMapper()
        {
        }

        void WeekToursSqlMapper::doMap()
        {
            if (m_ResultSet.isNull())
            {
                throw;
            }

            static basar::VarString ValueSet = "1";

            setTourId(m_ResultSet.getString("tourid"));
            setWeekday(m_ResultSet.getInt16("weekday"));
            setFahrtZeit(m_ResultSet.getInt32("fahrtzeit"));
            setOrderType(m_ResultSet.getString("ordertype"));
            setIsIbtTour(m_ResultSet.getString("isibttour") == ValueSet);
            setIsBtmTour(m_ResultSet.getInt16("isbtmtour"));
            setIsKKTour(m_ResultSet.getInt16("iskktour"));
            setIsK08Tour(m_ResultSet.getInt16("isk08tour"));
            setIsK20Tour(m_ResultSet.getInt16("isk20tour"));
            setIsReturnsTour(m_ResultSet.getInt16("isreturnstour"));
            setOrderPeriodFromTime(m_ResultSet.getInt32("orderperiodfromtime"));
            setOrderPeriodToTime(m_ResultSet.getInt32("orderperiodtotime"));
            setOrderPeriodMainTime(m_ResultSet.getInt32("orderperiodmaintime"));
        }

    } // end namespace customer
} // end namespace libcsc
