//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/tours/weektours/weektours.h>

namespace libcsc {
    namespace customer {

        WeekTours::WeekTours()
        {
        }

        WeekTours::~WeekTours()
        {
        }

        basar::VarString WeekTours::getTourId() const
        {
            return m_TourId;
        }

        basar::Int32 WeekTours::getFahrtZeit() const
        {
            return m_FahrtZeit;
        }

        basar::Int16 WeekTours::getWeekday() const
        {
            return m_Weekday;
        }

        basar::VarString WeekTours::getOrderType() const
        {
            return m_OrderType;
        }

        bool WeekTours::isIbtTour() const
        {
            return m_IsIbtTour;
        }

        bool WeekTours::isBtmTour() const
        {
            return m_IsBtmTour;
        }

        bool WeekTours::isKKTour() const
        {
            return m_IsKKTour;
        }

        bool WeekTours::isK08Tour() const
        {
            return m_IsK08Tour;
        }

        bool WeekTours::isK20Tour() const
        {
            return m_IsK20Tour;
        }

        bool WeekTours::isReturnsTour() const
        {
            return m_IsReturnsTour;
        }

        basar::Int32 WeekTours::getOrderPeriodFromTime() const
        {
            return m_OrderPeriodFromTime;
        }

        basar::Int32 WeekTours::getOrderPeriodToTime() const
        {
            return m_OrderPeriodToTime;
        }

        basar::Int32 WeekTours::getOrderPeriodMainTime() const
        {
            return m_OrderPeriodMainTime;
        }

    } // end namespace customer
} // end namespace libcsc
