#define ANZ_FKTN         213

#define AasrvDiscountMode							823
#define AasrvSelTourDelay                           822
#define AasrvGetBatchAdviceLink                     821
#define AasrvGetDocumentLink                        820
#define AasrvSelDeliveryAdviceVATTotals             819
#define AasrvSelDeliveryAdviceRemarks               818
#define AasrvSelDeliveryAdviceLineReturn            817
#define AasrvSelDeliveryAdviceLineIBTLink           816
#define AasrvSelDeliveryAdviceLineDiscount          815
#define AasrvSelDeliveryAdviceLineDetails           814
#define AasrvSelDeliveryAdviceLine                  813
#define AasrvSelDeliveryAdviceHead                  812
#define AasrvSelCscOrderType                        811
#define AasrvDelCscOrderType                        810
#define AasrvSelAllCscOrderType                     809
#define AasrvInsertCscOrderType                     808
#define AasrvUpdateCscOrderType                     807
#define AasrvCSCOrderImport                         806
#define AasrvInsertCSCOrderImportCSVColumns         805
#define AasrvUpdateCSCOrderImportCSVFormats         804
#define AasrvInsertCSCOrderImportCSVFormats         803
#define AasrvDeleteCSCOrderImportCSVColumns         802
#define AasrvGetCSCOrderImportCSVColumns            801
#define AasrvGetCSCOrderImportFields                800
#define AasrvGetCSCOrderImportCSVFormats            799
#define AasrvDeleteCSCOrderImportCSVFormats         798
#define AasrvDeleteReservationConfigcpgConfigID     797
#define AasrvGetReservationConfigListByOrderType    796
#define AasrvGetReservationConfigByID               795
#define AasrvInsertReservationConfig                794
#define AasrvUpdateReservationConfig                793
#define AasrvDeleteReservationConfig                792
#define AasrvGetReservationConfigcpgListByConfigID  791
#define AasrvInsertReservationConfigcpg             790
#define AasrvDeleteReservationConfigcpg             789
#define AasrvGetCSCReservationTypeList              788
#define AasrvGetCSCReservationTypeByTyp             787
#define AasrvSpecialPosDone      786
#define AasrvGetOMGRebates       785
#define AasrvSetOriginalInvoiceNo 784
#define AasrvOrderSpecialPosDone 783
#define AasrvCallbackGetMailLink 782
#define AasrvCloseorderDebtLimit    781
#define AasrvSetIVCVoucherNo    780
#define AasrvCheckIBTStockLevel 779
#define AasrvCancelorderDebtLimit   778
#define AasrvIBTOrderPosDone    777
#define AasrvIBTPosDone         776
#define AasrvIBTPossible        775
#define AasrvGetIBTStockLevel   774
#define AasrvSetOrderToCash     773
#define AasrvGetCustOrderType   772
#define AasrvReserveStockAbsArticleReservation 771
#define AasrvInsertBestandArticleReservation     770
#define AasrvDeleteArticleReservation  769
#define AasrvUpdateArticleReservation  768
#define AasrvInsertArticleReservation  767
#define AasrvSendEMail          766
#define AasrvGetBestTA          765
#define AasrvWriteProformaPos   764
#define AasrvCheckKippzeit      763
#define AasrvGetRangesBG        762
#define AasrvGetRanges          761
#define AasrvSetCashRebate      760
#define AasrvWriteProLink       759
#define AasrvConfirmRO          758
#define AasrvClearZU            757
#define AasrvSetNatra           756
#define AasrvClearROParam       755
#define AasrvChangeROMembers    754
#define AasrvGetROMembers       753
#define AasrvWriteInvoiceSettings   752
#define AasrvGetInvoiceSettings 751
#define AasrvWritePromoPos      750
#define AasrvGetRebatePrice     749
#define AasrvGetPromotions      748
#define AasrvGetRebates         747
#define AasrvCalcpos            746
#define AasrvSetROParam         745
#define AasrvSetBTMLicense      744
#define AasrvGetOrderVals       743
#define AasrvProforma           742
#define AasrvGetWeektouren      741
#define AasrvInsertReference    740
#define AasrvCheckReference     739
#define AasrvSetNoSeperate      738
#define AasrvSetdelayeddate     737
#define AasrvOpensessionNonVideo    736
#define AasrvWriteposition      735
#define AasrvGettourenAufArt    734
#define AasrvWriteposNL         733
#define AasrvSetprintdirect     732
#define AasrvSeldeforalphapos   731
#define AasrvChangeKzNachBearb  730
#define AasrvChangeCustomer     729
#define AasrvUnlock             727
#define AasrvGetVerbMoegl       726
#define AasrvGetOrderInfo       725
#define AasrvDelKopfZlnAuf      724
#define AasrvInsKopfZlnAuf      723
#define AasrvSelKopfZlnAuf      722
#define AasrvOpenInfoorder      721
#define AasrvSelposInfAuf       720
#define AasrvInfposnr           719
#define AasrvWritetextpos       718
#define AasrvChangetextpos      717
#define AasrvGetsession         716
#define AasrvAnzzrorder         715
#define AasrvSelpos             714
#define AasrvSelOrder           713
#define AasrvChangeOrdBem       712
#define AasrvChangeValuta       711
#define AasrvChangeTour         710
#define AasrvGettouren          709
#define AasrvGetaartes          708
#define AasrvChangepos          707
#define AasrvWritepos           706
#define AasrvChangeorder        705
#define AasrvCloseorder         704
#define AasrvOpenorder          703
#define AasrvNeworder           702
#define AasrvClosesession       701
#define AasrvOpensession        700
#define IftselSel_suchbez       900
#define IftselVers_kontr        901
#define IftselSel_tellistt      902
#define IftselUpd_tellistt      903
#define IftselIns_tellistt      904
#define IftselDel_tellistt      905
#define IftselSel_info          906

#define LieferselSel_info		920

#define AafilGet_filiale    7
#define AakundeSel_kndnr    8
#define AakundeSel_mc   9
#define AakundeSel_knd_info 10
#define AatartSel_art_nr    11
#define AatartSel_mc    12
#define AatartSel_mc_pkgr   13
#define AatartInf_art_nr    14
#define AafilWriteOldVersion    15
#define AatartInf_preis 16
#define AatartInf_verfall   17
#define AatartLagerinf  18
//#define   AatartNatraaktion   19
//#define   AatartNettoaktion   20
#define AafilGetdatetime    24
#define AakundeSel_aufart   25
#define AakundeSel_offen    26
#define AakundeSel_touren   27
#define AakundeSel_ausku    29
#define AatartAa_sel_artnr  30
#define AatartSel_art_altern    31
#define AafilReadpasswd 32
#define AafilSelaart    33
#define AafilUpdaart    34
#define AafilInsaart    35
#define AafilDelaart    36
#define AafilSelkoart   37
#define AafilUpdkoart   38
#define AafilInskoart   39
#define AafilDelkoart   40
#define AafilSelbuchart 41
#define AafilUpdbuchart 42
#define AafilInsbuchart 43
#define AafilDelbuchart 44
#define AafilSelkabakomb    45
#define AafilInskabakomb    47
#define AafilDelkabakomb    48
#define AafilSelkondgr  49
#define AafilUpdkondgr  50
#define AafilInskondgr  51
#define AafilDelkondgr  52
#define AafilSelkobehtyp    53
#define AafilUpdkobehtyp    54
#define AafilInskobehtyp    55
#define AafilDelkobehtyp    56
#define AafilSelnachart 57
#define AafilUpdnachart 58
#define AafilInsnachart 59
#define AafilDelnachart 60
#define AafilSelauferg  61
#define AafilUpdauferg  62
#define AafilInsauferg  63
#define AafilDelauferg  64
#define AafilSelaufbearb    65
#define AafilUpdaufbearb    66
#define AafilInsaufbearb    67
#define AafilDelaufbearb    68
#define AafilSelkommi   69
#define AafilUpdkommi   70
#define AafilInskommi   71
#define AafilDelkommi   72
#define AafilUpdpasswd  73
#define AafilGetversion 74
#define AafilInspasswd  75
#define AaauftSelzurauft    76
#define AaauftSelzurauft_o_tour 77
#define AaauftSelzurauft_o_idf  78
#define AaauftSelzurauft_o_ende 79
#define AaauftSelzurauftknde    80
#define AaauftAnz_zur_knd   81
#define AaauftAnz_zur_geraet    82
#define AaplanSel_mplan_idf 83
#define AaauftAusg_auft_ereig   84
#define AaauftStatusae  85
#define AaauftZeilenstatistik   86
#define AatourSel_tour_uebers   87
#define AatourSel_auf_tour  88
#define AatourUpd_sond_wann 89
#define AatourUpd_auf_tour  90
#define AatourUpd_folgenr   91
#define AatourGet_tour_kopf 92
#define AakritikSel_kritik  93
#define AakritikSel_kritik_idf  94
#define AakritikSchreibe_kopf   95
#define AakritikSchreibe_pos    96
#define AakritikSelect_pos  97
#define AaplanSel_tag_plan  98
#define AafilSel_altfil 99
#define AafilUpd_altfil 100
#define AafilIns_altfil 101
#define AafilSel_zeitarten  102
#define AafilUpd_zeitarten  103
#define AafilIns_zeitarten  104
#define AafilDel_altfil 105
#define AafilDel_zeitart    106
#define AaseraLes_dir   107
#define AaseraLes_data  108
#define AaplanIns_tag_plan  109
#define AaplanUpd_tag_plan  110
#define AatartSel_hersteller    111
#define AatartSel_offene_bstlng 112
#define AatartAa_sel_index  115
#define AafilSel_usertext   117
#define AafilIns_usertext   118
#define AafilDel_usertext   119
#define AaplanSel_tag_plan_inf  120
#define AaplanUni_tag_plan  121
#define AaauftSel_alt_kopf  122
#define AaauftSel_alt_auft  123
#define AaauftSel_alt_pos   124
#define AakundeSel_kndschalter  125
#define AaauftSel_nachl 126
#define AaauftLoe_nachl 127
#define AaauftUpd_nachl 128
#define AaplanSel_count 129
#define AaplanSel_tour  130
#define AafilSel_aa_passwd  131
#define AaplanVor_sel_uni   132
#define AaplanVor_sel_upd   133
#define AaplanVor_sel_ins   134
#define AaauftStatplan_sel  135
#define AaauftIns_auft_ereig    136
#define AatartSel_lagerbest 137
#define AafilSel_verbund    138
#define AaauftSel_nachlart  139
#define AaauftSel_frt   140
#define AaauftSel_end_kopf  141
#define AaauftSel_end_pos   142
#define AaauftSel_kndnl 143
#define AaauftSel_ean_uni   144
#define AaauftSel_art_pos   145
#define AaauftSel_end_art   146
#define AaauftIns_prot  147

#define AaauftGet_prot_nl   148
#define AafilSel_auftrendzeit   149
#define AafilDel_auftrendzeit   150
#define AafilIns_auftrendzeit   151

#define AaauftGetfirstordertime 152
#define AakundeIns_aufart   153
#define AakundeDel_aufart   154

#define AafilIs_new_order_possi 155
#define AakundeSel_monums   156

#define AaauftSel_tub_pos   159
#define AatartSel_artlief   160
#define AaauftSel_lager_auft_nr     161
#define AadruckNachl        162
#define AaauftSel_lauftnr   163
#define AatartSel_folge     164
#define AaauftIns_nachl     165
#define Aaauft_Sel_vblief   166
#define Aaauft_Sel_vbmoegl  167
#define AaauftSel_vbcount   168
#define AaauftSel_defekte   169
#define AaauftSperr_auft    170
#define AaauftSel_valutaauto 171
#define AaauftSel_kndnlprio 172
#define AaauftSelzurauftpzn 173
#define AafilChecktour      174
#define AadruckNachl_vbmoegl 175
#define AafilSet_actualfiliale 176
#define AakundeSel_idf      177
#define AadruckMasterplan   178
#define AakundeSel_nachttouren  179
#define AaauftSel_fili_auft_nr  180
#define AaauftCheck_auftnr  181
#define AaauftSelzurauft_o_aart 182
#define AakritikSel_kritikuser  183
#define AatartFetch_artnrlief   185
#define AakundeSel_telnr    186
#define AafilSet_sprache    187
#define AaauftSel_valutatage 188
#define AakundeSel_name 189
#define AatartSel_ean   190
#define AakundeSel_knd_info_hipath  191
#define AaauftSelzurauftDD  192
#define AadruckNachl_liefer 193
//#define   AatartCheck_natra   194
#define AaauftSelzurauft_o_kdklasse 195
#define AaauftSelzurauft_o_pos  196
#define AatartSel_Preferred 197
#define AatartSel_NoByCode  198
#define AafilSel_zeit_heute 199
#define AaauftSelProLink    200
#define AatartSel_herstname 201
#define AafilUpdkabakomb    202
#define AaauftSelzurauft_o_branch   203
#define AaauftSelzurauft_o_sortfield    204
#define AafilGet_filiale_Procenter  205
#define AaauftSelList_Auftrag   206
#define AaauftSelList_FCOrdersAll   207
#define AaauftSelList_FCOrdersToClose   208
#define AaauftSelList_FCOrdersToSolve   209
#define AatartAa_select 210
#define AafilLogParameter 211
#define AafilSelLogParameter 212
#define AafilSelLogParameterDefinitions 213
