/* ----------------------------------------------
 *  not generated by DADE
 * ---------------------------------------------- */

#ifndef CALLPLAN_H
#define CALLPLAN_H

#include <dadedb.h>
#include <allg.h>

/* from callplanday */
#include "callplanday.h"
retClient Mcustomercallplandayhist_DelAll     (mcustomercallplandayhistS *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplandayhist_DelAllOlder(mcustomercallplandayhistS *a, tError *stError, bool bIsTrans);

/* from callplanmaintenance */
#include "callplanmaintenance.h"
retClient Mcallplanload_GetInitializeData       (mcallplanloadS             *a, tError *stError, bool bIsTrans);
retClient Mcallplanload_DelCallPlanLoadOlder    (mcallplanloadS             *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplanphon_DelAll          (mcustomercallplanphonS     *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplanphon_DelAllOlder     (mcustomercallplanphonS     *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplanphon_Insert          (mcustomercallplanphonS     *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplanphonprot_DelAll      (mcustomercallplanphonprotS *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplanphonprot_DelAllOlder (mcustomercallplanphonprotS *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplanphonprot_Insert      (mcustomercallplanphonprotS *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplan_StartBrowseUndertake(mcustomercallplanS         *a, tError *stError, bool bIsTrans);
retClient Mcustomercallplan_SelListUndertake    (mcustomercallplanS         *a, tError *stError, bool bIsTrans);

/* from callplanundertake */
#include "callplanundertake.h"
retClient Mholiday_StartBrowse              (mholidayS           *a, tError *stError, bool bIsTrans);
retClient Mholiday_IsHoliday                (mholidayS           *a, tError *stError, bool bIsTrans);
retClient Mcallplanundertake_DelAllPhon     (mcallplanundertakeS *a, tError *stError, bool bIsTrans);
retClient Mcallplanundertake_DelAllPhonOlder(mcallplanundertakeS *a, tError *stError, bool bIsTrans);

/* from customer */
#include "customer.h"
retClient Mcustomervacation_SelUni(mcustomervacationS *a, tError *stError, bool bIsTrans);

/* must be implemented in calling project */
void WriteLogInfo(const char * error_msg, int rc, int errno);

#endif
