//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ITOURS_H
#define GUARD_LIBCSC_CUSTOMER_ITOURS_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class ITours
{
public:
    virtual ~ITours() {}

    virtual basar::VarString getTourId() const = 0;
    virtual basar::Int32 getIdfnr() const = 0;
    virtual basar::Int32 getDatumVersand() const = 0;
    virtual basar::Int32 getZeitVersand() const = 0;
    virtual basar::Int32 getFahrtZeit() const = 0;
    virtual bool getDelivered() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ITOURS_H
