//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_TOURS_H
#define GUARD_LIBCSC_CUSTOMER_TOURS_H

#include <customer/tours/itours.h>
#include <datatypes/varstring.h>
#include <datatypes/int32.h>
#include <datatypes/int16.h>

namespace libcsc {
namespace customer {

class Tours : public ITours
{
    // because of OR mapping
    friend class ToursMapperBase;

public:
    Tours();
    virtual ~Tours();

    virtual basar::VarString getTourId() const;
    virtual basar::Int32 getIdfnr() const;
    virtual basar::Int32 getDatumVersand() const;
    virtual basar::Int32 getZeitVersand() const;
    virtual basar::Int32 getFahrtZeit() const;
    virtual bool getDelivered() const;

private:
    libcsc::VarString m_TourId;
    libcsc::Int32 m_Idfnr;
    libcsc::Int32 m_DatumVersand;
    libcsc::Int32 m_ZeitVersand;
    libcsc::Int32 m_FahrtZeit;
    libcsc::Int16 m_Delivered;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_TOURS_H
