//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/tours/tours.h>

namespace libcsc {
namespace customer {

Tours::Tours()
{
}

Tours::~Tours()
{
}

basar::VarString Tours::getTourId() const
{
    return m_TourId;
}

basar::Int32 Tours::getIdfnr() const
{
    return m_Idfnr;
}

basar::Int32 Tours::getDatumVersand() const
{
    return m_DatumVersand;
}

basar::Int32 Tours::getZeitVersand() const
{
    return m_ZeitVersand;
}

basar::Int32 Tours::getFahrtZeit() const
{
    return m_FahrtZeit;
}

bool Tours::getDelivered() const
{
    return m_Delivered;
}

} // end namespace customer
} // end namespace libcsc
