//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_TOURSMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_TOURSMAPPERBASE_H

#include <customer/tours/toursptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class ToursMapperBase
{
public:
    ToursMapperBase(ToursPtr tours);

    void map();

protected:
    virtual ~ToursMapperBase();

    virtual void doMap() = 0;

    void setTourId(const basar::VarString& tourId);
    void setIdfnr(const basar::Int32& idfnr);
    void setDatumVersand(const basar::Int32& datumVersand);
    void setZeitVersand(const basar::Int32& zeitVersand);
    void setFahrtZeit(const basar::Int32& fahrtZeit);
    void setDelivered(const bool& delivered);

private:
    ToursPtr m_Tours;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_TOURSMAPPERBASE_H
