//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_TOURSSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_TOURSSQLMAPPER_H

#include <customer/tours/toursmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class ToursSqlMapper : public ToursMapperBase
{
public:
    ToursSqlMapper(ToursPtr tours, const basar::db::sql::ResultsetRef resultSet);
    virtual ~ToursSqlMapper();

protected:
    virtual void doMap();

private:
    ToursSqlMapper(const ToursSqlMapper&);
    ToursSqlMapper& operator=(const ToursSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_TOURSSQLMAPPER_H
