//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/tours/toursmapperbase.h>
#include <customer/tours/tours.h>

namespace libcsc {
namespace customer {

ToursMapperBase::ToursMapperBase(ToursPtr tours)
: m_Tours(tours)
{
}

ToursMapperBase::~ToursMapperBase()
{
}

void ToursMapperBase::map()
{
    doMap();
}

void ToursMapperBase::setTourId(const basar::VarString& tourId)
{
    m_Tours->m_TourId = tourId;
    m_Tours->m_TourId.setClean();
}

void ToursMapperBase::setIdfnr(const basar::Int32& idfnr)
{
    m_Tours->m_Idfnr = idfnr;
    m_Tours->m_Idfnr.setClean();
}

void ToursMapperBase::setDatumVersand(const basar::Int32& datumVersand)
{
    m_Tours->m_DatumVersand = datumVersand;
    m_Tours->m_DatumVersand.setClean();
}

void ToursMapperBase::setZeitVersand(const basar::Int32& zeitVersand)
{
    m_Tours->m_ZeitVersand = zeitVersand;
    m_Tours->m_ZeitVersand.setClean();
}

void ToursMapperBase::setFahrtZeit(const basar::Int32& fahrtZeit)
{
    m_Tours->m_FahrtZeit = fahrtZeit;
    m_Tours->m_FahrtZeit.setClean();
}

void ToursMapperBase::setDelivered(const bool& delivered)
{
    m_Tours->m_Delivered = delivered;
    m_Tours->m_Delivered.setClean();
}

} // end namespace customer
} // end namespace libcsc
