//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/tours/tourssqlmapper.h>

namespace libcsc {
namespace customer {

ToursSqlMapper::ToursSqlMapper(ToursPtr tours, const basar::db::sql::ResultsetRef resultSet)
: ToursMapperBase(tours), m_ResultSet(resultSet)
{
}

ToursSqlMapper::~ToursSqlMapper()
{
}

void ToursSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setTourId(m_ResultSet.getString("tourid"));
    setIdfnr(m_ResultSet.getInt32("idfnr"));
    setDatumVersand(m_ResultSet.getInt32("datumversand"));
    setZeitVersand(m_ResultSet.getInt32("zeitversand"));
    setFahrtZeit(m_ResultSet.getInt32("fahrtzeit"));
    setDelivered(m_ResultSet.getInt16("delivered"));
}

} // end namespace customer
} // end namespace libcsc
