//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_IUSERSUGGESTION_H
#define GUARD_LIBCSC_CREMA_IUSERSUGGESTION_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class IUserSuggestion
{
public:
    virtual ~IUserSuggestion() {}

    virtual basar::Int16 getChoice() const = 0;
    virtual basar::Int16 getChoiceReason() const = 0;
    virtual basar::VarString getChoiceComment() const = 0;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_IUSERSUGGESTION_H
