//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_IUSERSUGGESTIONPTR_H
#define GUARD_LIBCSC_CREMA_IUSERSUGGESTIONPTR_H

#include <boost/shared_ptr.hpp>

namespace libcsc {
namespace crema {

class IUserSuggestion;
typedef boost::shared_ptr<IUserSuggestion> IUserSuggestionPtr;

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_IUSERSUGGESTIONPTR_H
