//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/usersuggestion/usersuggestionsqlmapper.h>

namespace libcsc {
namespace crema {

UserSuggestionSqlMapper::UserSuggestionSqlMapper(UserSuggestionPtr userSuggestion, const basar::db::sql::ResultsetRef resultSet)
: UserSuggestionMapperBase(userSuggestion), m_ResultSet(resultSet)
{
}

UserSuggestionSqlMapper::~UserSuggestionSqlMapper()
{
}

void UserSuggestionSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setId(m_ResultSet.getInt32("id"));
    setChoice(m_ResultSet.getInt16("choice"));
    setChoiceReason(m_ResultSet.getInt16("choicereason"));
    setChoiceComment(m_ResultSet.getString("choicecomment"));
}

} // end namespace crema
} // end namespace libcsc
