//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/usersuggestion/usersuggestionmapperbase.h>
#include <crema/usersuggestion/usersuggestion.h>

namespace libcsc {
namespace crema {

UserSuggestionMapperBase::UserSuggestionMapperBase(UserSuggestionPtr userSuggestion)
: m_UserSuggestion(userSuggestion)
{
}

UserSuggestionMapperBase::~UserSuggestionMapperBase()
{
}

void UserSuggestionMapperBase::map()
{
    doMap();
}

void UserSuggestionMapperBase::setId(const basar::Int32& id)
{
    m_UserSuggestion->m_Id = id;
    m_UserSuggestion->m_Id.setClean();
}

void UserSuggestionMapperBase::setChoice(const basar::Int16& choice)
{
    m_UserSuggestion->m_Choice = choice;
    m_UserSuggestion->m_Choice.setClean();
}

void UserSuggestionMapperBase::setChoiceReason(const basar::Int16& choiceReason)
{
    m_UserSuggestion->m_ChoiceReason = choiceReason;
    m_UserSuggestion->m_ChoiceReason.setClean();
}

void UserSuggestionMapperBase::setChoiceComment(const basar::VarString& choiceComment)
{
    m_UserSuggestion->m_ChoiceComment = choiceComment;
    m_UserSuggestion->m_ChoiceComment.setClean();
}

} // end namespace crema
} // end namespace libcsc
