//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_USERSUGGESTIONSQLMAPPER_H
#define GUARD_LIBCSC_CREMA_USERSUGGESTIONSQLMAPPER_H

#include <crema/usersuggestion/usersuggestionmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class UserSuggestionSqlMapper : public UserSuggestionMapperBase
{
public:
    UserSuggestionSqlMapper(UserSuggestionPtr userSuggestion, const basar::db::sql::ResultsetRef resultSet);
    virtual ~UserSuggestionSqlMapper();

protected:
    virtual void doMap();

private:
    UserSuggestionSqlMapper(const UserSuggestionSqlMapper&);
    UserSuggestionSqlMapper& operator=(const UserSuggestionSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_USERSUGGESTIONSQLMAPPER_H
