//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_USERSUGGESTIONMAPPERBASE_H
#define GUARD_LIBCSC_CREMA_USERSUGGESTIONMAPPERBASE_H

#include <crema/usersuggestion/usersuggestionptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class UserSuggestionMapperBase
{
public:
    UserSuggestionMapperBase(UserSuggestionPtr userSuggestion);

    void map();

protected:
    virtual ~UserSuggestionMapperBase();

    virtual void doMap() = 0;

    void setId(const basar::Int32& id);
    void setChoice(const basar::Int16& choice);
    void setChoiceReason(const basar::Int16& choiceReason);
    void setChoiceComment(const basar::VarString& choiceComment);

private:
    UserSuggestionPtr m_UserSuggestion;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_USERSUGGESTIONMAPPERBASE_H
