//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/usersuggestion/usersuggestion.h>

namespace libcsc {
namespace crema {

UserSuggestion::UserSuggestion()
{
}

UserSuggestion::~UserSuggestion()
{
}

basar::Int32 UserSuggestion::getId() const
{
    return m_Id;
}

basar::Int16 UserSuggestion::getChoice() const
{
    return m_Choice;
}

basar::Int16 UserSuggestion::getChoiceReason() const
{
    return m_ChoiceReason;
}

basar::VarString UserSuggestion::getChoiceComment() const
{
    return m_ChoiceComment;
}

} // end namespace crema
} // end namespace libcsc
