//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_USERSUGGESTION_H
#define GUARD_LIBCSC_CREMA_USERSUGGESTION_H

#include <crema/usersuggestion/iusersuggestion.h>
#include <datatypes/int16.h>
#include <datatypes/int32.h>
#include <datatypes/varstring.h>

namespace libcsc {
namespace crema {

class UserSuggestion : public IUserSuggestion
{
    // because of OR mapping
    friend class UserSuggestionMapperBase;

public:
    UserSuggestion();
    virtual ~UserSuggestion();

    virtual basar::Int32 getId() const;
    virtual basar::Int16 getChoice() const;
    virtual basar::Int16 getChoiceReason() const;
    virtual basar::VarString getChoiceComment() const;

private:
    libcsc::Int32 m_Id;
    libcsc::Int16 m_Choice;
    libcsc::Int16 m_ChoiceReason;
    libcsc::VarString m_ChoiceComment;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_USERSUGGESTION_H
