//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=4.0.30319.1.
//
namespace swimp
{
    namespace Phoenix.Types.Config
    {

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class SalesWebConfig
        {

            private SalesWebConfigGeneral generalField;

            private SalesWebConfigXmlValidation xmlValidationField;

            private SalesWebConfigSmtp smtpField;

            private SalesWebConfigFrontend frontendField;

            private SalesWebConfigBackend backendField;

            /// <remarks/>
            public SalesWebConfigGeneral General
            {
                get
                {
                    return this.generalField;
                }
                set
                {
                    this.generalField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigXmlValidation XmlValidation
            {
                get
                {
                    return this.xmlValidationField;
                }
                set
                {
                    this.xmlValidationField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigSmtp Smtp
            {
                get
                {
                    return this.smtpField;
                }
                set
                {
                    this.smtpField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigFrontend Frontend
            {
                get
                {
                    return this.frontendField;
                }
                set
                {
                    this.frontendField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigBackend Backend
            {
                get
                {
                    return this.backendField;
                }
                set
                {
                    this.backendField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigGeneral
        {

            private SalesWebConfigGeneralCountry countryField;

            private SalesWebConfigGeneralLanguage languageField;

            private string domainField;

            private bool pzn8AktiveField;

            public SalesWebConfigGeneral()
            {
                this.domainField = "PHOENIXEXT";
                this.pzn8AktiveField = false;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public SalesWebConfigGeneralCountry Country
            {
                get
                {
                    return this.countryField;
                }
                set
                {
                    this.countryField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public SalesWebConfigGeneralLanguage Language
            {
                get
                {
                    return this.languageField;
                }
                set
                {
                    this.languageField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("PHOENIXEXT")]
            public string Domain
            {
                get
                {
                    return this.domainField;
                }
                set
                {
                    this.domainField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(false)]
            public bool Pzn8Aktive
            {
                get
                {
                    return this.pzn8AktiveField;
                }
                set
                {
                    this.pzn8AktiveField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public enum SalesWebConfigGeneralCountry
        {

            /// <remarks/>
            Empty,

            /// <remarks/>
            Austria,

            /// <remarks/>
            Bulgaria,

            /// <remarks/>
            Croatia,

            /// <remarks/>
            France,

            /// <remarks/>
            Germany,

            /// <remarks/>
            Serbia,

            /// <remarks/>
            Switzerland,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public enum SalesWebConfigGeneralLanguage
        {

            /// <remarks/>
            Empty,

            /// <remarks/>
            Bulgarian,

            /// <remarks/>
            Croatian,

            /// <remarks/>
            English,

            /// <remarks/>
            French,

            /// <remarks/>
            German,

            /// <remarks/>
            Serbian,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class Customer
        {

            private int numberField;

            private int branchField;

            private bool branchFieldSpecified;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Number
            {
                get
                {
                    return this.numberField;
                }
                set
                {
                    this.numberField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Branch
            {
                get
                {
                    return this.branchField;
                }
                set
                {
                    this.branchField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool BranchSpecified
            {
                get
                {
                    return this.branchFieldSpecified;
                }
                set
                {
                    this.branchFieldSpecified = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigXmlValidation
        {

            private bool validateXMLField;

            private string xsdPathField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public bool ValidateXML
            {
                get
                {
                    return this.validateXMLField;
                }
                set
                {
                    this.validateXMLField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string XsdPath
            {
                get
                {
                    return this.xsdPathField;
                }
                set
                {
                    this.xsdPathField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigSmtp
        {

            private string serverField;

            private int portField;

            private string mailAddressToField;

            private string mailAddressFromField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Server
            {
                get
                {
                    return this.serverField;
                }
                set
                {
                    this.serverField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Port
            {
                get
                {
                    return this.portField;
                }
                set
                {
                    this.portField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string MailAddressTo
            {
                get
                {
                    return this.mailAddressToField;
                }
                set
                {
                    this.mailAddressToField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string MailAddressFrom
            {
                get
                {
                    return this.mailAddressFromField;
                }
                set
                {
                    this.mailAddressFromField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigFrontend
        {

            private SalesWebConfigFrontendBackendEndpoint backendEndpointField;

            private SalesWebConfigFrontendSubmitDurations submitDurationsField;

            /// <remarks/>
            public SalesWebConfigFrontendBackendEndpoint BackendEndpoint
            {
                get
                {
                    return this.backendEndpointField;
                }
                set
                {
                    this.backendEndpointField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigFrontendSubmitDurations SubmitDurations
            {
                get
                {
                    return this.submitDurationsField;
                }
                set
                {
                    this.submitDurationsField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigFrontendBackendEndpoint
        {

            private int[] branchesField;

            private string nameField;

            private string addressField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Branch", IsNullable = false)]
            public int[] Branches
            {
                get
                {
                    return this.branchesField;
                }
                set
                {
                    this.branchesField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Address
            {
                get
                {
                    return this.addressField;
                }
                set
                {
                    this.addressField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigFrontendSubmitDurations
        {

            private SalesWebConfigFrontendSubmitDurationsUser[] userField;

            private bool submitField;

            private SalesWebConfigFrontendSubmitDurationsSubmitDurationType submitDurationTypeField;

            public SalesWebConfigFrontendSubmitDurations()
            {
                this.submitField = false;
                this.submitDurationTypeField = SalesWebConfigFrontendSubmitDurationsSubmitDurationType.Mail;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("User")]
            public SalesWebConfigFrontendSubmitDurationsUser[] User
            {
                get
                {
                    return this.userField;
                }
                set
                {
                    this.userField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(false)]
            public bool Submit
            {
                get
                {
                    return this.submitField;
                }
                set
                {
                    this.submitField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(SalesWebConfigFrontendSubmitDurationsSubmitDurationType.Mail)]
            public SalesWebConfigFrontendSubmitDurationsSubmitDurationType SubmitDurationType
            {
                get
                {
                    return this.submitDurationTypeField;
                }
                set
                {
                    this.submitDurationTypeField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigFrontendSubmitDurationsUser
        {

            private int branchNoField;

            private int idfField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int BranchNo
            {
                get
                {
                    return this.branchNoField;
                }
                set
                {
                    this.branchNoField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Idf
            {
                get
                {
                    return this.idfField;
                }
                set
                {
                    this.idfField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public enum SalesWebConfigFrontendSubmitDurationsSubmitDurationType
        {

            /// <remarks/>
            Mail,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackend
        {

            private SalesWebConfigBackendLog logField;

            private SalesWebConfigBackendBlacklisting blacklistingField;

            private SalesWebConfigBackendIfxServer[] ifxServersField;

            private SalesWebConfigBackendKscServer[] kscServersField;

            private SalesWebConfigBackendRequestQueue requestQueueField;

            private string[] specialUsersField;

            private Customer[] testCustomersField;

            private Customer[] blackListedCustomersField;

            private SalesWebConfigBackendBranch[] allowedBranchesField;

            /// <remarks/>
            public SalesWebConfigBackendLog Log
            {
                get
                {
                    return this.logField;
                }
                set
                {
                    this.logField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigBackendBlacklisting Blacklisting
            {
                get
                {
                    return this.blacklistingField;
                }
                set
                {
                    this.blacklistingField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("IfxServer", IsNullable = false)]
            public SalesWebConfigBackendIfxServer[] IfxServers
            {
                get
                {
                    return this.ifxServersField;
                }
                set
                {
                    this.ifxServersField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("KscServer", IsNullable = false)]
            public SalesWebConfigBackendKscServer[] KscServers
            {
                get
                {
                    return this.kscServersField;
                }
                set
                {
                    this.kscServersField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigBackendRequestQueue RequestQueue
            {
                get
                {
                    return this.requestQueueField;
                }
                set
                {
                    this.requestQueueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("SpecialUser", IsNullable = false)]
            public string[] SpecialUsers
            {
                get
                {
                    return this.specialUsersField;
                }
                set
                {
                    this.specialUsersField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Customer", IsNullable = false)]
            public Customer[] TestCustomers
            {
                get
                {
                    return this.testCustomersField;
                }
                set
                {
                    this.testCustomersField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Customer", IsNullable = false)]
            public Customer[] BlackListedCustomers
            {
                get
                {
                    return this.blackListedCustomersField;
                }
                set
                {
                    this.blackListedCustomersField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Branch", IsNullable = false)]
            public SalesWebConfigBackendBranch[] AllowedBranches
            {
                get
                {
                    return this.allowedBranchesField;
                }
                set
                {
                    this.allowedBranchesField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendLog
        {

            private string connectionStringField;

            private string queuePathField;

            private string logTableNameField;

            private SalesWebConfigBackendLogSeverity severityField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string ConnectionString
            {
                get
                {
                    return this.connectionStringField;
                }
                set
                {
                    this.connectionStringField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string QueuePath
            {
                get
                {
                    return this.queuePathField;
                }
                set
                {
                    this.queuePathField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string LogTableName
            {
                get
                {
                    return this.logTableNameField;
                }
                set
                {
                    this.logTableNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public SalesWebConfigBackendLogSeverity Severity
            {
                get
                {
                    return this.severityField;
                }
                set
                {
                    this.severityField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public enum SalesWebConfigBackendLogSeverity
        {

            /// <remarks/>
            None,

            /// <remarks/>
            Trace,

            /// <remarks/>
            Debug,

            /// <remarks/>
            Info,

            /// <remarks/>
            Warn,

            /// <remarks/>
            Error,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendBlacklisting
        {

            private SalesWebConfigBackendBlacklistingDuration[] durationField;

            private int maxPosCountField;

            public SalesWebConfigBackendBlacklisting()
            {
                this.maxPosCountField = 65568;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Duration")]
            public SalesWebConfigBackendBlacklistingDuration[] Duration
            {
                get
                {
                    return this.durationField;
                }
                set
                {
                    this.durationField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(65568)]
            public int MaxPosCount
            {
                get
                {
                    return this.maxPosCountField;
                }
                set
                {
                    this.maxPosCountField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendBlacklistingDuration
        {

            private string fromField;

            private string toField;

            public SalesWebConfigBackendBlacklistingDuration()
            {
                this.fromField = "12:00:00";
                this.toField = "12:00:00";
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("12:00:00")]
            public string From
            {
                get
                {
                    return this.fromField;
                }
                set
                {
                    this.fromField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("12:00:00")]
            public string To
            {
                get
                {
                    return this.toField;
                }
                set
                {
                    this.toField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendIfxServer
        {

            private int[] branchesField;

            private string regionField;

            private string connectionStringField;

            private string dBLocaleField;

            private string cultureInfoField;

            private bool overrideThreadCultureField;

            private string infoLevelField;

            public SalesWebConfigBackendIfxServer()
            {
                this.overrideThreadCultureField = false;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Branch", IsNullable = false)]
            public int[] Branches
            {
                get
                {
                    return this.branchesField;
                }
                set
                {
                    this.branchesField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Region
            {
                get
                {
                    return this.regionField;
                }
                set
                {
                    this.regionField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string ConnectionString
            {
                get
                {
                    return this.connectionStringField;
                }
                set
                {
                    this.connectionStringField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string DBLocale
            {
                get
                {
                    return this.dBLocaleField;
                }
                set
                {
                    this.dBLocaleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string CultureInfo
            {
                get
                {
                    return this.cultureInfoField;
                }
                set
                {
                    this.cultureInfoField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(false)]
            public bool OverrideThreadCulture
            {
                get
                {
                    return this.overrideThreadCultureField;
                }
                set
                {
                    this.overrideThreadCultureField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string InfoLevel
            {
                get
                {
                    return this.infoLevelField;
                }
                set
                {
                    this.infoLevelField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendKscServer
        {

            private int[] branchesField;

            private SalesWebConfigBackendKscServerSCP sCPField;

            private string regionField;

            private int encodingField;

            private string deviceNameField;

            private int uidField;

            private int portField;

            private string serverField;

            private string infoLevelField;

            private string stockLevelPathField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Branch", IsNullable = false)]
            public int[] Branches
            {
                get
                {
                    return this.branchesField;
                }
                set
                {
                    this.branchesField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigBackendKscServerSCP SCP
            {
                get
                {
                    return this.sCPField;
                }
                set
                {
                    this.sCPField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Region
            {
                get
                {
                    return this.regionField;
                }
                set
                {
                    this.regionField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Encoding
            {
                get
                {
                    return this.encodingField;
                }
                set
                {
                    this.encodingField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string DeviceName
            {
                get
                {
                    return this.deviceNameField;
                }
                set
                {
                    this.deviceNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Uid
            {
                get
                {
                    return this.uidField;
                }
                set
                {
                    this.uidField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Port
            {
                get
                {
                    return this.portField;
                }
                set
                {
                    this.portField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Server
            {
                get
                {
                    return this.serverField;
                }
                set
                {
                    this.serverField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string InfoLevel
            {
                get
                {
                    return this.infoLevelField;
                }
                set
                {
                    this.infoLevelField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string StockLevelPath
            {
                get
                {
                    return this.stockLevelPathField;
                }
                set
                {
                    this.stockLevelPathField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendKscServerSCP
        {

            private string sCPPathField;

            private string sCPUserField;

            private string sCPPasswordField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string SCPPath
            {
                get
                {
                    return this.sCPPathField;
                }
                set
                {
                    this.sCPPathField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string SCPUser
            {
                get
                {
                    return this.sCPUserField;
                }
                set
                {
                    this.sCPUserField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string SCPPassword
            {
                get
                {
                    return this.sCPPasswordField;
                }
                set
                {
                    this.sCPPasswordField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendRequestQueue
        {

            private string queuePathField;

            private int requeueTimeSpanMinutesField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string QueuePath
            {
                get
                {
                    return this.queuePathField;
                }
                set
                {
                    this.queuePathField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int RequeueTimeSpanMinutes
            {
                get
                {
                    return this.requeueTimeSpanMinutesField;
                }
                set
                {
                    this.requeueTimeSpanMinutesField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendBranch
        {

            private int numberField;

            private SalesWebConfigGeneralLanguage languageField;

            private bool treatDayIbtAsAvailField;

            private bool treatIbtAsAvailField;

            private bool ignoreIbtWindowField;

            private System.DateTime dayIBTEndField;

            public SalesWebConfigBackendBranch()
            {
                this.treatDayIbtAsAvailField = false;
                this.treatIbtAsAvailField = false;
                this.ignoreIbtWindowField = false;
                this.dayIBTEndField = new System.DateTime(720000000000);
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Number
            {
                get
                {
                    return this.numberField;
                }
                set
                {
                    this.numberField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public SalesWebConfigGeneralLanguage Language
            {
                get
                {
                    return this.languageField;
                }
                set
                {
                    this.languageField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(false)]
            public bool TreatDayIbtAsAvail
            {
                get
                {
                    return this.treatDayIbtAsAvailField;
                }
                set
                {
                    this.treatDayIbtAsAvailField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(false)]
            public bool TreatIbtAsAvail
            {
                get
                {
                    return this.treatIbtAsAvailField;
                }
                set
                {
                    this.treatIbtAsAvailField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(false)]
            public bool IgnoreIbtWindow
            {
                get
                {
                    return this.ignoreIbtWindowField;
                }
                set
                {
                    this.ignoreIbtWindowField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "time")]
            [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T20:00:00")]
            public System.DateTime DayIBTEnd
            {
                get
                {
                    return this.dayIBTEndField;
                }
                set
                {
                    this.dayIBTEndField = value;
                }
            }
        }
    }
}