#ifndef __PP_ARTIKELZENTRAL_H_
#define __PP_ARTIKELZENTRAL_H_

/******************************************************************************/
/* c:artikelzentral ***********************************************************/
/* produced by DADE 6.22.2 ****************************************************/
/******************************************************************************/

/* ppunixc */
#if defined (BUF_DESC) || defined (C_BUF_DESC)
#include <bufkon.h>
#endif

/* Length-Define of ARTIKELZENTRAL ********************************************/

#define L_ARTIKELZENTRAL_ARTIKEL_NR 11
#define L_ARTIKELZENTRAL_ARTIKEL_MC 12
#define L_ARTIKELZENTRAL_PACKGROESSE 11
#define L_ARTIKELZENTRAL_DARREICHFORM 3
#define L_ARTIKELZENTRAL_NORMPACKUNG 2
#define L_ARTIKELZENTRAL_EINHEIT 9
#define L_ARTIKELZENTRAL_ARTIKEL_NAME 30
#define L_ARTIKELZENTRAL_ETARTKLASSE1 5
#define L_ARTIKELZENTRAL_ETARTSCHALTER1 5
#define L_ARTIKELZENTRAL_ETARTSCHALTER2 5
#define L_ARTIKELZENTRAL_ETARTSCHALTER3 5
#define L_ARTIKELZENTRAL_ETARTSCHALTER4 5
#define L_ARTIKELZENTRAL_ETARTSCHALTER5 5
#define L_ARTIKELZENTRAL_HERSTELLER_NR 11
#define L_ARTIKELZENTRAL_WARENGRUPPE 5
#define L_ARTIKELZENTRAL_THERAPIEGRUPPE 5
#define L_ARTIKELZENTRAL_LAENGE 11
#define L_ARTIKELZENTRAL_HOEHE 11
#define L_ARTIKELZENTRAL_BREITE 11
#define L_ARTIKELZENTRAL_GEWICHT 11
#define L_ARTIKELZENTRAL_LAUFZEITMONATE 11
#define L_ARTIKELZENTRAL_WARENGRUPPEEIGEN 5
#define L_ARTIKELZENTRAL_HERSTELLER_CODE 5
#define L_ARTIKELZENTRAL_KZPSYCHOSTOFFE 1
#define L_ARTIKELZENTRAL_TAXLEVEL 6
#define L_ARTIKELZENTRAL_TEXTKEY_HOSPITAL 6
#define L_ARTIKELZENTRAL_KZRESERVEHOSPITAL 1
#define L_ARTIKELZENTRAL_STD_MENGE 6
#define L_ARTIKELZENTRAL_RUNDUNG_STD_MGE 1
#define L_ARTIKELZENTRAL_NICHT_UEBER_DAFUE 1
#define L_ARTIKELZENTRAL_NICHT_UEBER_XML 1
#define L_ARTIKELZENTRAL_KZZUSCHLAGSARTIKEL 1
#define L_ARTIKELZENTRAL_WIRKSTOFF_NR 3
#define L_ARTIKELZENTRAL_HEALTHFUNDCODE 5
#define L_ARTIKELZENTRAL_STELLER 1
#define L_ARTIKELZENTRAL_POSITIVLISTE 1
#define L_ARTIKELZENTRAL_ABDACODE 5
#define L_ARTIKELZENTRAL_KONSIG_PARTNER_NR 11
#define L_ARTIKELZENTRAL_ARTIKEL_LANGNAME 50
#define L_ARTIKELZENTRAL_PRICE_GROUP 6
#define L_ARTIKELZENTRAL_SORTIMENT_1 1
#define L_ARTIKELZENTRAL_SORTIMENT_2 1
#define L_ARTIKELZENTRAL_SORTIMENT_3 1
#define L_ARTIKELZENTRAL_SORTIMENT_4 1
#define L_ARTIKELZENTRAL_SORTIMENT_5 1
#define L_ARTIKELZENTRAL_DATUM_ANLAGE 11
#define L_ARTIKELZENTRAL_BUSINESSTYPENO 6
#define L_ARTIKELZENTRAL_LISTE_5 6
#define L_ARTIKELZENTRAL_UPD_FLAG 1
#define L_ARTIKELZENTRAL_ARTIKEL_NR_HERST 15
#define L_ARTIKELZENTRAL_MEDPROD_ABG_VERORD 1
#define L_ARTIKELZENTRAL_PRODUSERQUOTA 6
#define L_ARTIKELZENTRAL_MEDICALPRODUCT 6
#define L_ARTIKELZENTRAL_DATEOUTOFTRADE 11
#define L_ARTIKELZENTRAL_ARTIKEL_GESPERRT 1
#define L_ARTIKELZENTRAL_IKS_CODE 1
#define L_ARTIKELZENTRAL_BATCHRECALLDATERETURNS 11
#define L_ARTIKELZENTRAL_IMPORTARTICLE 6
#define L_ARTIKELZENTRAL_BTM_FAKTOR 8
#define N_ARTIKELZENTRAL_BTM_FAKTOR 3
#define L_ARTIKELZENTRAL_TFG 1
#define L_ARTIKELZENTRAL_KONTINGENT_PPE 1
#define L_ARTIKELZENTRAL_DATUM_LIEFERBAR_AB 11
#define L_ARTIKELZENTRAL_MEDIZINPRODUKT 1
#define L_ARTIKELZENTRAL_FROZEN 6
#define L_ARTIKELZENTRAL_DATUM_AENDER 11
#define L_ARTIKELZENTRAL_ATC_CODE 25
#define L_ARTIKELZENTRAL_MINISTRYPRODUCTCODE 25
#define L_ARTIKELZENTRAL_HEALTHFUNDCODEHOSPITAL 25
#define L_ARTIKELZENTRAL_CMI_FLAG 6
#define L_ARTIKELZENTRAL_TAXPFL 1

/* Length/Count-Define of ARTIKELZENTRAL **************************************/

#define LS_ARTIKELZENTRAL_ARTIKEL_NR 10 + 1
#define LS_ARTIKELZENTRAL_ARTIKEL_MC 12 + 1
#define LS_ARTIKELZENTRAL_PACKGROESSE 10 + 1
#define LS_ARTIKELZENTRAL_DARREICHFORM 3 + 1
#define LS_ARTIKELZENTRAL_NORMPACKUNG 2 + 1
#define LS_ARTIKELZENTRAL_EINHEIT 9 + 1
#define LS_ARTIKELZENTRAL_ARTIKEL_NAME 30 + 1
#define LS_ARTIKELZENTRAL_ETARTKLASSE1 5 + 1
#define LS_ARTIKELZENTRAL_ETARTSCHALTER1 5 + 1
#define LS_ARTIKELZENTRAL_ETARTSCHALTER2 5 + 1
#define LS_ARTIKELZENTRAL_ETARTSCHALTER3 5 + 1
#define LS_ARTIKELZENTRAL_ETARTSCHALTER4 5 + 1
#define LS_ARTIKELZENTRAL_ETARTSCHALTER5 5 + 1
#define LS_ARTIKELZENTRAL_HERSTELLER_NR 10 + 1
#define LS_ARTIKELZENTRAL_WARENGRUPPE 5 + 1
#define LS_ARTIKELZENTRAL_THERAPIEGRUPPE 5 + 1
#define LS_ARTIKELZENTRAL_LAENGE 10 + 1
#define LS_ARTIKELZENTRAL_HOEHE 10 + 1
#define LS_ARTIKELZENTRAL_BREITE 10 + 1
#define LS_ARTIKELZENTRAL_GEWICHT 10 + 1
#define LS_ARTIKELZENTRAL_LAUFZEITMONATE 10 + 1
#define LS_ARTIKELZENTRAL_WARENGRUPPEEIGEN 5 + 1
#define LS_ARTIKELZENTRAL_HERSTELLER_CODE 5 + 1
#define LS_ARTIKELZENTRAL_KZPSYCHOSTOFFE 1 + 1
#define LS_ARTIKELZENTRAL_TAXLEVEL 5 + 1
#define LS_ARTIKELZENTRAL_TEXTKEY_HOSPITAL 5 + 1
#define LS_ARTIKELZENTRAL_KZRESERVEHOSPITAL 1 + 1
#define LS_ARTIKELZENTRAL_STD_MENGE 5 + 1
#define LS_ARTIKELZENTRAL_RUNDUNG_STD_MGE 1 + 1
#define LS_ARTIKELZENTRAL_NICHT_UEBER_DAFUE 1 + 1
#define LS_ARTIKELZENTRAL_NICHT_UEBER_XML 1 + 1
#define LS_ARTIKELZENTRAL_KZZUSCHLAGSARTIKEL 1 + 1
#define LS_ARTIKELZENTRAL_WIRKSTOFF_NR 3 + 1
#define LS_ARTIKELZENTRAL_HEALTHFUNDCODE 5 + 1
#define LS_ARTIKELZENTRAL_STELLER 1 + 1
#define LS_ARTIKELZENTRAL_POSITIVLISTE 1 + 1
#define LS_ARTIKELZENTRAL_ABDACODE 5 + 1
#define LS_ARTIKELZENTRAL_KONSIG_PARTNER_NR 10 + 1
#define LS_ARTIKELZENTRAL_ARTIKEL_LANGNAME 50 + 1
#define LS_ARTIKELZENTRAL_PRICE_GROUP 5 + 1
#define LS_ARTIKELZENTRAL_SORTIMENT_1 1 + 1
#define LS_ARTIKELZENTRAL_SORTIMENT_2 1 + 1
#define LS_ARTIKELZENTRAL_SORTIMENT_3 1 + 1
#define LS_ARTIKELZENTRAL_SORTIMENT_4 1 + 1
#define LS_ARTIKELZENTRAL_SORTIMENT_5 1 + 1
#define LS_ARTIKELZENTRAL_DATUM_ANLAGE 10 + 1
#define LS_ARTIKELZENTRAL_BUSINESSTYPENO 5 + 1
#define LS_ARTIKELZENTRAL_LISTE_5 5 + 1
#define LS_ARTIKELZENTRAL_UPD_FLAG 1 + 1
#define LS_ARTIKELZENTRAL_ARTIKEL_NR_HERST 15 + 1
#define LS_ARTIKELZENTRAL_MEDPROD_ABG_VERORD 1 + 1
#define LS_ARTIKELZENTRAL_PRODUSERQUOTA 5 + 1
#define LS_ARTIKELZENTRAL_MEDICALPRODUCT 5 + 1
#define LS_ARTIKELZENTRAL_DATEOUTOFTRADE 10 + 1
#define LS_ARTIKELZENTRAL_ARTIKEL_GESPERRT 1 + 1
#define LS_ARTIKELZENTRAL_IKS_CODE 1 + 1
#define LS_ARTIKELZENTRAL_BATCHRECALLDATERETURNS 10 + 1
#define LS_ARTIKELZENTRAL_IMPORTARTICLE 5 + 1
#define LS_ARTIKELZENTRAL_BTM_FAKTOR 8 + 2
#define LS_ARTIKELZENTRAL_TFG 1 + 1
#define LS_ARTIKELZENTRAL_KONTINGENT_PPE 1 + 1
#define LS_ARTIKELZENTRAL_DATUM_LIEFERBAR_AB 10 + 1
#define LS_ARTIKELZENTRAL_MEDIZINPRODUKT 1 + 1
#define LS_ARTIKELZENTRAL_FROZEN 5 + 1
#define LS_ARTIKELZENTRAL_DATUM_AENDER 10 + 1
#define LS_ARTIKELZENTRAL_ATC_CODE 25 + 1
#define LS_ARTIKELZENTRAL_MINISTRYPRODUCTCODE 25 + 1
#define LS_ARTIKELZENTRAL_HEALTHFUNDCODEHOSPITAL 25 + 1
#define LS_ARTIKELZENTRAL_CMI_FLAG 5 + 1
#define LS_ARTIKELZENTRAL_TAXPFL 1 + 1

#define ARTIKELZENTRALARTIKEL_NR 0
#define ARTIKELZENTRALARTIKEL_MC 1
#define ARTIKELZENTRALPACKGROESSE 2
#define ARTIKELZENTRALDARREICHFORM 3
#define ARTIKELZENTRALNORMPACKUNG 4
#define ARTIKELZENTRALEINHEIT 5
#define ARTIKELZENTRALARTIKEL_NAME 6
#define ARTIKELZENTRALETARTKLASSE1 7
#define ARTIKELZENTRALETARTSCHALTER1 8
#define ARTIKELZENTRALETARTSCHALTER2 9
#define ARTIKELZENTRALETARTSCHALTER3 10
#define ARTIKELZENTRALETARTSCHALTER4 11
#define ARTIKELZENTRALETARTSCHALTER5 12
#define ARTIKELZENTRALHERSTELLER_NR 13
#define ARTIKELZENTRALWARENGRUPPE 14
#define ARTIKELZENTRALTHERAPIEGRUPPE 15
#define ARTIKELZENTRALLAENGE 16
#define ARTIKELZENTRALHOEHE 17
#define ARTIKELZENTRALBREITE 18
#define ARTIKELZENTRALGEWICHT 19
#define ARTIKELZENTRALLAUFZEITMONATE 20
#define ARTIKELZENTRALWARENGRUPPEEIGEN 21
#define ARTIKELZENTRALHERSTELLER_CODE 22
#define ARTIKELZENTRALKZPSYCHOSTOFFE 23
#define ARTIKELZENTRALTAXLEVEL 24
#define ARTIKELZENTRALTEXTKEY_HOSPITAL 25
#define ARTIKELZENTRALKZRESERVEHOSPITAL 26
#define ARTIKELZENTRALSTD_MENGE 27
#define ARTIKELZENTRALRUNDUNG_STD_MGE 28
#define ARTIKELZENTRALNICHT_UEBER_DAFUE 29
#define ARTIKELZENTRALNICHT_UEBER_XML 30
#define ARTIKELZENTRALKZZUSCHLAGSARTIKEL 31
#define ARTIKELZENTRALWIRKSTOFF_NR 32
#define ARTIKELZENTRALHEALTHFUNDCODE 33
#define ARTIKELZENTRALSTELLER 34
#define ARTIKELZENTRALPOSITIVLISTE 35
#define ARTIKELZENTRALABDACODE 36
#define ARTIKELZENTRALKONSIG_PARTNER_NR 37
#define ARTIKELZENTRALARTIKEL_LANGNAME 38
#define ARTIKELZENTRALPRICE_GROUP 39
#define ARTIKELZENTRALSORTIMENT_1 40
#define ARTIKELZENTRALSORTIMENT_2 41
#define ARTIKELZENTRALSORTIMENT_3 42
#define ARTIKELZENTRALSORTIMENT_4 43
#define ARTIKELZENTRALSORTIMENT_5 44
#define ARTIKELZENTRALDATUM_ANLAGE 45
#define ARTIKELZENTRALBUSINESSTYPENO 46
#define ARTIKELZENTRALLISTE_5 47
#define ARTIKELZENTRALUPD_FLAG 48
#define ARTIKELZENTRALARTIKEL_NR_HERST 49
#define ARTIKELZENTRALMEDPROD_ABG_VERORD 50
#define ARTIKELZENTRALPRODUSERQUOTA 51
#define ARTIKELZENTRALMEDICALPRODUCT 52
#define ARTIKELZENTRALDATEOUTOFTRADE 53
#define ARTIKELZENTRALARTIKEL_GESPERRT 54
#define ARTIKELZENTRALIKS_CODE 55
#define ARTIKELZENTRALBATCHRECALLDATERETURNS 56
#define ARTIKELZENTRALIMPORTARTICLE 57
#define ARTIKELZENTRALBTM_FAKTOR 58
#define ARTIKELZENTRALTFG 59
#define ARTIKELZENTRALKONTINGENT_PPE 60
#define ARTIKELZENTRALDATUM_LIEFERBAR_AB 61
#define ARTIKELZENTRALMEDIZINPRODUKT 62
#define ARTIKELZENTRALFROZEN 63
#define ARTIKELZENTRALDATUM_AENDER 64
#define ARTIKELZENTRALATC_CODE 65
#define ARTIKELZENTRALMINISTRYPRODUCTCODE 66
#define ARTIKELZENTRALHEALTHFUNDCODEHOSPITAL 67
#define ARTIKELZENTRALCMI_FLAG 68
#define ARTIKELZENTRALTAXPFL 69

/* define of Buf_Desc *********************************************************/

#if defined (BUF_DESC) || defined (C_BUF_DESC)
#define ARTIKELZENTRAL_H
#define ARTIKELZENTRAL_ANZ ( sizeof(ARTIKELZENTRAL_BES) / sizeof(struct buf_desc) )
#endif

/* SqlDefine of ARTIKELZENTRAL ************************************************/

#define ARTIKELZENTRAL_LISTE \
        ARTIKELZENTRAL.ARTIKEL_NR,\
        ARTIKELZENTRAL.ARTIKEL_MC,\
        ARTIKELZENTRAL.PACKGROESSE,\
        ARTIKELZENTRAL.DARREICHFORM,\
        ARTIKELZENTRAL.NORMPACKUNG,\
        ARTIKELZENTRAL.EINHEIT,\
        ARTIKELZENTRAL.ARTIKEL_NAME,\
        ARTIKELZENTRAL.ETARTKLASSE1,\
        ARTIKELZENTRAL.ETARTSCHALTER1,\
        ARTIKELZENTRAL.ETARTSCHALTER2,\
        ARTIKELZENTRAL.ETARTSCHALTER3,\
        ARTIKELZENTRAL.ETARTSCHALTER4,\
        ARTIKELZENTRAL.ETARTSCHALTER5,\
        ARTIKELZENTRAL.HERSTELLER_NR,\
        ARTIKELZENTRAL.WARENGRUPPE,\
        ARTIKELZENTRAL.THERAPIEGRUPPE,\
        ARTIKELZENTRAL.LAENGE,\
        ARTIKELZENTRAL.HOEHE,\
        ARTIKELZENTRAL.BREITE,\
        ARTIKELZENTRAL.GEWICHT,\
        ARTIKELZENTRAL.LAUFZEITMONATE,\
        ARTIKELZENTRAL.WARENGRUPPEEIGEN,\
        ARTIKELZENTRAL.HERSTELLER_CODE,\
        ARTIKELZENTRAL.KZPSYCHOSTOFFE,\
        ARTIKELZENTRAL.TAXLEVEL,\
        ARTIKELZENTRAL.TEXTKEY_HOSPITAL,\
        ARTIKELZENTRAL.KZRESERVEHOSPITAL,\
        ARTIKELZENTRAL.STD_MENGE,\
        ARTIKELZENTRAL.RUNDUNG_STD_MGE,\
        ARTIKELZENTRAL.NICHT_UEBER_DAFUE,\
        ARTIKELZENTRAL.NICHT_UEBER_XML,\
        ARTIKELZENTRAL.KZZUSCHLAGSARTIKEL,\
        ARTIKELZENTRAL.WIRKSTOFF_NR,\
        ARTIKELZENTRAL.HEALTHFUNDCODE,\
        ARTIKELZENTRAL.STELLER,\
        ARTIKELZENTRAL.POSITIVLISTE,\
        ARTIKELZENTRAL.ABDACODE,\
        ARTIKELZENTRAL.KONSIG_PARTNER_NR,\
        ARTIKELZENTRAL.ARTIKEL_LANGNAME,\
        ARTIKELZENTRAL.PRICE_GROUP,\
        ARTIKELZENTRAL.SORTIMENT_1,\
        ARTIKELZENTRAL.SORTIMENT_2,\
        ARTIKELZENTRAL.SORTIMENT_3,\
        ARTIKELZENTRAL.SORTIMENT_4,\
        ARTIKELZENTRAL.SORTIMENT_5,\
        ARTIKELZENTRAL.DATUM_ANLAGE,\
        ARTIKELZENTRAL.BUSINESSTYPENO,\
        ARTIKELZENTRAL.LISTE_5,\
        ARTIKELZENTRAL.UPD_FLAG,\
        ARTIKELZENTRAL.ARTIKEL_NR_HERST,\
        ARTIKELZENTRAL.MEDPROD_ABG_VERORD,\
        ARTIKELZENTRAL.PRODUSERQUOTA,\
        ARTIKELZENTRAL.MEDICALPRODUCT,\
        ARTIKELZENTRAL.DATEOUTOFTRADE,\
        ARTIKELZENTRAL.ARTIKEL_GESPERRT,\
        ARTIKELZENTRAL.IKS_CODE,\
        ARTIKELZENTRAL.BATCHRECALLDATERETURNS,\
        ARTIKELZENTRAL.IMPORTARTICLE,\
        ARTIKELZENTRAL.BTM_FAKTOR,\
        ARTIKELZENTRAL.TFG,\
        ARTIKELZENTRAL.KONTINGENT_PPE,\
        ARTIKELZENTRAL.DATUM_LIEFERBAR_AB,\
        ARTIKELZENTRAL.MEDIZINPRODUKT,\
        ARTIKELZENTRAL.FROZEN,\
        ARTIKELZENTRAL.DATUM_AENDER,\
        ARTIKELZENTRAL.ATC_CODE,\
        ARTIKELZENTRAL.MINISTRYPRODUCTCODE,\
        ARTIKELZENTRAL.HEALTHFUNDCODEHOSPITAL,\
        ARTIKELZENTRAL.CMI_FLAG,\
        ARTIKELZENTRAL.TAXPFL
#define ARTIKELZENTRAL_LISTE_390 \
        ARTIKEL_NR,\
        ARTIKEL_MC,\
        PACKGROESSE,\
        DARREICHFORM,\
        NORMPACKUNG,\
        EINHEIT,\
        ARTIKEL_NAME,\
        ETARTKLASSE1,\
        ETARTSCHALTER1,\
        ETARTSCHALTER2,\
        ETARTSCHALTER3,\
        ETARTSCHALTER4,\
        ETARTSCHALTER5,\
        HERSTELLER_NR,\
        WARENGRUPPE,\
        THERAPIEGRUPPE,\
        LAENGE,\
        HOEHE,\
        BREITE,\
        GEWICHT,\
        LAUFZEITMONATE,\
        WARENGRUPPEEIGEN,\
        HERSTELLER_CODE,\
        KZPSYCHOSTOFFE,\
        TAXLEVEL,\
        TEXTKEY_HOSPITAL,\
        KZRESERVEHOSPITAL,\
        STD_MENGE,\
        RUNDUNG_STD_MGE,\
        NICHT_UEBER_DAFUE,\
        NICHT_UEBER_XML,\
        KZZUSCHLAGSARTIKEL,\
        WIRKSTOFF_NR,\
        HEALTHFUNDCODE,\
        STELLER,\
        POSITIVLISTE,\
        ABDACODE,\
        KONSIG_PARTNER_NR,\
        ARTIKEL_LANGNAME,\
        PRICE_GROUP,\
        SORTIMENT_1,\
        SORTIMENT_2,\
        SORTIMENT_3,\
        SORTIMENT_4,\
        SORTIMENT_5,\
        DATUM_ANLAGE,\
        BUSINESSTYPENO,\
        LISTE_5,\
        UPD_FLAG,\
        ARTIKEL_NR_HERST,\
        MEDPROD_ABG_VERORD,\
        PRODUSERQUOTA,\
        MEDICALPRODUCT,\
        DATEOUTOFTRADE,\
        ARTIKEL_GESPERRT,\
        IKS_CODE,\
        BATCHRECALLDATERETURNS,\
        IMPORTARTICLE,\
        BTM_FAKTOR,\
        TFG,\
        KONTINGENT_PPE,\
        DATUM_LIEFERBAR_AB,\
        MEDIZINPRODUKT,\
        FROZEN,\
        DATUM_AENDER,\
        ATC_CODE,\
        MINISTRYPRODUCTCODE,\
        HEALTHFUNDCODEHOSPITAL,\
        CMI_FLAG,\
        TAXPFL
#define ARTIKELZENTRAL_PLISTE \
        "ARTIKELZENTRAL.ARTIKEL_NR,"\
        "ARTIKELZENTRAL.ARTIKEL_MC,"\
        "ARTIKELZENTRAL.PACKGROESSE,"\
        "ARTIKELZENTRAL.DARREICHFORM,"\
        "ARTIKELZENTRAL.NORMPACKUNG,"\
        "ARTIKELZENTRAL.EINHEIT,"\
        "ARTIKELZENTRAL.ARTIKEL_NAME,"\
        "ARTIKELZENTRAL.ETARTKLASSE1,"\
        "ARTIKELZENTRAL.ETARTSCHALTER1,"\
        "ARTIKELZENTRAL.ETARTSCHALTER2,"\
        "ARTIKELZENTRAL.ETARTSCHALTER3,"\
        "ARTIKELZENTRAL.ETARTSCHALTER4,"\
        "ARTIKELZENTRAL.ETARTSCHALTER5,"\
        "ARTIKELZENTRAL.HERSTELLER_NR,"\
        "ARTIKELZENTRAL.WARENGRUPPE,"\
        "ARTIKELZENTRAL.THERAPIEGRUPPE,"\
        "ARTIKELZENTRAL.LAENGE,"\
        "ARTIKELZENTRAL.HOEHE,"\
        "ARTIKELZENTRAL.BREITE,"\
        "ARTIKELZENTRAL.GEWICHT,"\
        "ARTIKELZENTRAL.LAUFZEITMONATE,"\
        "ARTIKELZENTRAL.WARENGRUPPEEIGEN,"\
        "ARTIKELZENTRAL.HERSTELLER_CODE,"\
        "ARTIKELZENTRAL.KZPSYCHOSTOFFE,"\
        "ARTIKELZENTRAL.TAXLEVEL,"\
        "ARTIKELZENTRAL.TEXTKEY_HOSPITAL,"\
        "ARTIKELZENTRAL.KZRESERVEHOSPITAL,"\
        "ARTIKELZENTRAL.STD_MENGE,"\
        "ARTIKELZENTRAL.RUNDUNG_STD_MGE,"\
        "ARTIKELZENTRAL.NICHT_UEBER_DAFUE,"\
        "ARTIKELZENTRAL.NICHT_UEBER_XML,"\
        "ARTIKELZENTRAL.KZZUSCHLAGSARTIKEL,"\
        "ARTIKELZENTRAL.WIRKSTOFF_NR,"\
        "ARTIKELZENTRAL.HEALTHFUNDCODE,"\
        "ARTIKELZENTRAL.STELLER,"\
        "ARTIKELZENTRAL.POSITIVLISTE,"\
        "ARTIKELZENTRAL.ABDACODE,"\
        "ARTIKELZENTRAL.KONSIG_PARTNER_NR,"\
        "ARTIKELZENTRAL.ARTIKEL_LANGNAME,"\
        "ARTIKELZENTRAL.PRICE_GROUP,"\
        "ARTIKELZENTRAL.SORTIMENT_1,"\
        "ARTIKELZENTRAL.SORTIMENT_2,"\
        "ARTIKELZENTRAL.SORTIMENT_3,"\
        "ARTIKELZENTRAL.SORTIMENT_4,"\
        "ARTIKELZENTRAL.SORTIMENT_5,"\
        "ARTIKELZENTRAL.DATUM_ANLAGE,"\
        "ARTIKELZENTRAL.BUSINESSTYPENO,"\
        "ARTIKELZENTRAL.LISTE_5,"\
        "ARTIKELZENTRAL.UPD_FLAG,"\
        "ARTIKELZENTRAL.ARTIKEL_NR_HERST,"\
        "ARTIKELZENTRAL.MEDPROD_ABG_VERORD,"\
        "ARTIKELZENTRAL.PRODUSERQUOTA,"\
        "ARTIKELZENTRAL.MEDICALPRODUCT,"\
        "ARTIKELZENTRAL.DATEOUTOFTRADE,"\
        "ARTIKELZENTRAL.ARTIKEL_GESPERRT,"\
        "ARTIKELZENTRAL.IKS_CODE,"\
        "ARTIKELZENTRAL.BATCHRECALLDATERETURNS,"\
        "ARTIKELZENTRAL.IMPORTARTICLE,"\
        "ARTIKELZENTRAL.BTM_FAKTOR,"\
        "ARTIKELZENTRAL.TFG,"\
        "ARTIKELZENTRAL.KONTINGENT_PPE,"\
        "ARTIKELZENTRAL.DATUM_LIEFERBAR_AB,"\
        "ARTIKELZENTRAL.MEDIZINPRODUKT,"\
        "ARTIKELZENTRAL.FROZEN,"\
        "ARTIKELZENTRAL.DATUM_AENDER,"\
        "ARTIKELZENTRAL.ATC_CODE,"\
        "ARTIKELZENTRAL.MINISTRYPRODUCTCODE,"\
        "ARTIKELZENTRAL.HEALTHFUNDCODEHOSPITAL,"\
        "ARTIKELZENTRAL.CMI_FLAG,"\
        "ARTIKELZENTRAL.TAXPFL"
#define ARTIKELZENTRAL_PELISTE \
        "ARTIKEL_NR,"\
        "ARTIKEL_MC,"\
        "PACKGROESSE,"\
        "DARREICHFORM,"\
        "NORMPACKUNG,"\
        "EINHEIT,"\
        "ARTIKEL_NAME,"\
        "ETARTKLASSE1,"\
        "ETARTSCHALTER1,"\
        "ETARTSCHALTER2,"\
        "ETARTSCHALTER3,"\
        "ETARTSCHALTER4,"\
        "ETARTSCHALTER5,"\
        "HERSTELLER_NR,"\
        "WARENGRUPPE,"\
        "THERAPIEGRUPPE,"\
        "LAENGE,"\
        "HOEHE,"\
        "BREITE,"\
        "GEWICHT,"\
        "LAUFZEITMONATE,"\
        "WARENGRUPPEEIGEN,"\
        "HERSTELLER_CODE,"\
        "KZPSYCHOSTOFFE,"\
        "TAXLEVEL,"\
        "TEXTKEY_HOSPITAL,"\
        "KZRESERVEHOSPITAL,"\
        "STD_MENGE,"\
        "RUNDUNG_STD_MGE,"\
        "NICHT_UEBER_DAFUE,"\
        "NICHT_UEBER_XML,"\
        "KZZUSCHLAGSARTIKEL,"\
        "WIRKSTOFF_NR,"\
        "HEALTHFUNDCODE,"\
        "STELLER,"\
        "POSITIVLISTE,"\
        "ABDACODE,"\
        "KONSIG_PARTNER_NR,"\
        "ARTIKEL_LANGNAME,"\
        "PRICE_GROUP,"\
        "SORTIMENT_1,"\
        "SORTIMENT_2,"\
        "SORTIMENT_3,"\
        "SORTIMENT_4,"\
        "SORTIMENT_5,"\
        "DATUM_ANLAGE,"\
        "BUSINESSTYPENO,"\
        "LISTE_5,"\
        "UPD_FLAG,"\
        "ARTIKEL_NR_HERST,"\
        "MEDPROD_ABG_VERORD,"\
        "PRODUSERQUOTA,"\
        "MEDICALPRODUCT,"\
        "DATEOUTOFTRADE,"\
        "ARTIKEL_GESPERRT,"\
        "IKS_CODE,"\
        "BATCHRECALLDATERETURNS,"\
        "IMPORTARTICLE,"\
        "BTM_FAKTOR,"\
        "TFG,"\
        "KONTINGENT_PPE,"\
        "DATUM_LIEFERBAR_AB,"\
        "MEDIZINPRODUKT,"\
        "FROZEN,"\
        "DATUM_AENDER,"\
        "ATC_CODE,"\
        "MINISTRYPRODUCTCODE,"\
        "HEALTHFUNDCODEHOSPITAL,"\
        "CMI_FLAG,"\
        "TAXPFL"
#define ARTIKELZENTRAL_UPDLISTE \
        "ARTIKEL_NR=?,"\
        "ARTIKEL_MC=?,"\
        "PACKGROESSE=?,"\
        "DARREICHFORM=?,"\
        "NORMPACKUNG=?,"\
        "EINHEIT=?,"\
        "ARTIKEL_NAME=?,"\
        "ETARTKLASSE1=?,"\
        "ETARTSCHALTER1=?,"\
        "ETARTSCHALTER2=?,"\
        "ETARTSCHALTER3=?,"\
        "ETARTSCHALTER4=?,"\
        "ETARTSCHALTER5=?,"\
        "HERSTELLER_NR=?,"\
        "WARENGRUPPE=?,"\
        "THERAPIEGRUPPE=?,"\
        "LAENGE=?,"\
        "HOEHE=?,"\
        "BREITE=?,"\
        "GEWICHT=?,"\
        "LAUFZEITMONATE=?,"\
        "WARENGRUPPEEIGEN=?,"\
        "HERSTELLER_CODE=?,"\
        "KZPSYCHOSTOFFE=?,"\
        "TAXLEVEL=?,"\
        "TEXTKEY_HOSPITAL=?,"\
        "KZRESERVEHOSPITAL=?,"\
        "STD_MENGE=?,"\
        "RUNDUNG_STD_MGE=?,"\
        "NICHT_UEBER_DAFUE=?,"\
        "NICHT_UEBER_XML=?,"\
        "KZZUSCHLAGSARTIKEL=?,"\
        "WIRKSTOFF_NR=?,"\
        "HEALTHFUNDCODE=?,"\
        "STELLER=?,"\
        "POSITIVLISTE=?,"\
        "ABDACODE=?,"\
        "KONSIG_PARTNER_NR=?,"\
        "ARTIKEL_LANGNAME=?,"\
        "PRICE_GROUP=?,"\
        "SORTIMENT_1=?,"\
        "SORTIMENT_2=?,"\
        "SORTIMENT_3=?,"\
        "SORTIMENT_4=?,"\
        "SORTIMENT_5=?,"\
        "DATUM_ANLAGE=?,"\
        "BUSINESSTYPENO=?,"\
        "LISTE_5=?,"\
        "UPD_FLAG=?,"\
        "ARTIKEL_NR_HERST=?,"\
        "MEDPROD_ABG_VERORD=?,"\
        "PRODUSERQUOTA=?,"\
        "MEDICALPRODUCT=?,"\
        "DATEOUTOFTRADE=?,"\
        "ARTIKEL_GESPERRT=?,"\
        "IKS_CODE=?,"\
        "BATCHRECALLDATERETURNS=?,"\
        "IMPORTARTICLE=?,"\
        "BTM_FAKTOR=?,"\
        "TFG=?,"\
        "KONTINGENT_PPE=?,"\
        "DATUM_LIEFERBAR_AB=?,"\
        "MEDIZINPRODUKT=?,"\
        "FROZEN=?,"\
        "DATUM_AENDER=?,"\
        "ATC_CODE=?,"\
        "MINISTRYPRODUCTCODE=?,"\
        "HEALTHFUNDCODEHOSPITAL=?,"\
        "CMI_FLAG=?,"\
        "TAXPFL=?"
/* SqlMacros-Define of ARTIKELZENTRAL *****************************************/

#define ARTIKELZENTRAL_ZEIGER(x) \
        :x->ARTIKEL_NR,\
        :x->ARTIKEL_MC,\
        :x->PACKGROESSE,\
        :x->DARREICHFORM,\
        :x->NORMPACKUNG,\
        :x->EINHEIT,\
        :x->ARTIKEL_NAME,\
        :x->ETARTKLASSE1,\
        :x->ETARTSCHALTER1,\
        :x->ETARTSCHALTER2,\
        :x->ETARTSCHALTER3,\
        :x->ETARTSCHALTER4,\
        :x->ETARTSCHALTER5,\
        :x->HERSTELLER_NR,\
        :x->WARENGRUPPE,\
        :x->THERAPIEGRUPPE,\
        :x->LAENGE,\
        :x->HOEHE,\
        :x->BREITE,\
        :x->GEWICHT,\
        :x->LAUFZEITMONATE,\
        :x->WARENGRUPPEEIGEN,\
        :x->HERSTELLER_CODE,\
        :x->KZPSYCHOSTOFFE,\
        :x->TAXLEVEL,\
        :x->TEXTKEY_HOSPITAL,\
        :x->KZRESERVEHOSPITAL,\
        :x->STD_MENGE,\
        :x->RUNDUNG_STD_MGE,\
        :x->NICHT_UEBER_DAFUE,\
        :x->NICHT_UEBER_XML,\
        :x->KZZUSCHLAGSARTIKEL,\
        :x->WIRKSTOFF_NR,\
        :x->HEALTHFUNDCODE,\
        :x->STELLER,\
        :x->POSITIVLISTE,\
        :x->ABDACODE,\
        :x->KONSIG_PARTNER_NR,\
        :x->ARTIKEL_LANGNAME,\
        :x->PRICE_GROUP,\
        :x->SORTIMENT_1,\
        :x->SORTIMENT_2,\
        :x->SORTIMENT_3,\
        :x->SORTIMENT_4,\
        :x->SORTIMENT_5,\
        :x->DATUM_ANLAGE,\
        :x->BUSINESSTYPENO,\
        :x->LISTE_5,\
        :x->UPD_FLAG,\
        :x->ARTIKEL_NR_HERST,\
        :x->MEDPROD_ABG_VERORD,\
        :x->PRODUSERQUOTA,\
        :x->MEDICALPRODUCT,\
        :x->DATEOUTOFTRADE,\
        :x->ARTIKEL_GESPERRT,\
        :x->IKS_CODE,\
        :x->BATCHRECALLDATERETURNS,\
        :x->IMPORTARTICLE,\
        :x->BTM_FAKTOR,\
        :x->TFG,\
        :x->KONTINGENT_PPE,\
        :x->DATUM_LIEFERBAR_AB,\
        :x->MEDIZINPRODUKT,\
        :x->FROZEN,\
        :x->DATUM_AENDER,\
        :x->ATC_CODE,\
        :x->MINISTRYPRODUCTCODE,\
        :x->HEALTHFUNDCODEHOSPITAL,\
        :x->CMI_FLAG,\
        :x->TAXPFL
#define ARTIKELZENTRAL_ZEIGERSEL(x) \
        :x->ARTIKEL_NR,\
        :x->ARTIKEL_MC,\
        :x->PACKGROESSE,\
        :x->DARREICHFORM,\
        :x->NORMPACKUNG,\
        :x->EINHEIT,\
        :x->ARTIKEL_NAME,\
        :x->ETARTKLASSE1,\
        :x->ETARTSCHALTER1,\
        :x->ETARTSCHALTER2,\
        :x->ETARTSCHALTER3,\
        :x->ETARTSCHALTER4,\
        :x->ETARTSCHALTER5,\
        :x->HERSTELLER_NR,\
        :x->WARENGRUPPE,\
        :x->THERAPIEGRUPPE,\
        :x->LAENGE,\
        :x->HOEHE,\
        :x->BREITE,\
        :x->GEWICHT,\
        :x->LAUFZEITMONATE,\
        :x->WARENGRUPPEEIGEN,\
        :x->HERSTELLER_CODE,\
        :x->KZPSYCHOSTOFFE,\
        :x->TAXLEVEL,\
        :x->TEXTKEY_HOSPITAL,\
        :x->KZRESERVEHOSPITAL,\
        :x->STD_MENGE,\
        :x->RUNDUNG_STD_MGE,\
        :x->NICHT_UEBER_DAFUE,\
        :x->NICHT_UEBER_XML,\
        :x->KZZUSCHLAGSARTIKEL,\
        :x->WIRKSTOFF_NR,\
        :x->HEALTHFUNDCODE,\
        :x->STELLER,\
        :x->POSITIVLISTE,\
        :x->ABDACODE,\
        :x->KONSIG_PARTNER_NR,\
        :x->ARTIKEL_LANGNAME,\
        :x->PRICE_GROUP,\
        :x->SORTIMENT_1,\
        :x->SORTIMENT_2,\
        :x->SORTIMENT_3,\
        :x->SORTIMENT_4,\
        :x->SORTIMENT_5,\
        :x->DATUM_ANLAGE,\
        :x->BUSINESSTYPENO,\
        :x->LISTE_5,\
        :x->UPD_FLAG,\
        :x->ARTIKEL_NR_HERST,\
        :x->MEDPROD_ABG_VERORD,\
        :x->PRODUSERQUOTA,\
        :x->MEDICALPRODUCT,\
        :x->DATEOUTOFTRADE,\
        :x->ARTIKEL_GESPERRT,\
        :x->IKS_CODE,\
        :x->BATCHRECALLDATERETURNS,\
        :x->IMPORTARTICLE,\
        :x->BTM_FAKTOR,\
        :x->TFG,\
        :x->KONTINGENT_PPE,\
        :x->DATUM_LIEFERBAR_AB,\
        :x->MEDIZINPRODUKT,\
        :x->FROZEN,\
        :x->DATUM_AENDER,\
        :x->ATC_CODE,\
        :x->MINISTRYPRODUCTCODE,\
        :x->HEALTHFUNDCODEHOSPITAL,\
        :x->CMI_FLAG,\
        :x->TAXPFL
#define ARTIKELZENTRAL_UPDATE(x) \
        ARTIKELZENTRAL.ARTIKEL_NR=:x->ARTIKEL_NR,\
        ARTIKELZENTRAL.ARTIKEL_MC=:x->ARTIKEL_MC,\
        ARTIKELZENTRAL.PACKGROESSE=:x->PACKGROESSE,\
        ARTIKELZENTRAL.DARREICHFORM=:x->DARREICHFORM,\
        ARTIKELZENTRAL.NORMPACKUNG=:x->NORMPACKUNG,\
        ARTIKELZENTRAL.EINHEIT=:x->EINHEIT,\
        ARTIKELZENTRAL.ARTIKEL_NAME=:x->ARTIKEL_NAME,\
        ARTIKELZENTRAL.ETARTKLASSE1=:x->ETARTKLASSE1,\
        ARTIKELZENTRAL.ETARTSCHALTER1=:x->ETARTSCHALTER1,\
        ARTIKELZENTRAL.ETARTSCHALTER2=:x->ETARTSCHALTER2,\
        ARTIKELZENTRAL.ETARTSCHALTER3=:x->ETARTSCHALTER3,\
        ARTIKELZENTRAL.ETARTSCHALTER4=:x->ETARTSCHALTER4,\
        ARTIKELZENTRAL.ETARTSCHALTER5=:x->ETARTSCHALTER5,\
        ARTIKELZENTRAL.HERSTELLER_NR=:x->HERSTELLER_NR,\
        ARTIKELZENTRAL.WARENGRUPPE=:x->WARENGRUPPE,\
        ARTIKELZENTRAL.THERAPIEGRUPPE=:x->THERAPIEGRUPPE,\
        ARTIKELZENTRAL.LAENGE=:x->LAENGE,\
        ARTIKELZENTRAL.HOEHE=:x->HOEHE,\
        ARTIKELZENTRAL.BREITE=:x->BREITE,\
        ARTIKELZENTRAL.GEWICHT=:x->GEWICHT,\
        ARTIKELZENTRAL.LAUFZEITMONATE=:x->LAUFZEITMONATE,\
        ARTIKELZENTRAL.WARENGRUPPEEIGEN=:x->WARENGRUPPEEIGEN,\
        ARTIKELZENTRAL.HERSTELLER_CODE=:x->HERSTELLER_CODE,\
        ARTIKELZENTRAL.KZPSYCHOSTOFFE=:x->KZPSYCHOSTOFFE,\
        ARTIKELZENTRAL.TAXLEVEL=:x->TAXLEVEL,\
        ARTIKELZENTRAL.TEXTKEY_HOSPITAL=:x->TEXTKEY_HOSPITAL,\
        ARTIKELZENTRAL.KZRESERVEHOSPITAL=:x->KZRESERVEHOSPITAL,\
        ARTIKELZENTRAL.STD_MENGE=:x->STD_MENGE,\
        ARTIKELZENTRAL.RUNDUNG_STD_MGE=:x->RUNDUNG_STD_MGE,\
        ARTIKELZENTRAL.NICHT_UEBER_DAFUE=:x->NICHT_UEBER_DAFUE,\
        ARTIKELZENTRAL.NICHT_UEBER_XML=:x->NICHT_UEBER_XML,\
        ARTIKELZENTRAL.KZZUSCHLAGSARTIKEL=:x->KZZUSCHLAGSARTIKEL,\
        ARTIKELZENTRAL.WIRKSTOFF_NR=:x->WIRKSTOFF_NR,\
        ARTIKELZENTRAL.HEALTHFUNDCODE=:x->HEALTHFUNDCODE,\
        ARTIKELZENTRAL.STELLER=:x->STELLER,\
        ARTIKELZENTRAL.POSITIVLISTE=:x->POSITIVLISTE,\
        ARTIKELZENTRAL.ABDACODE=:x->ABDACODE,\
        ARTIKELZENTRAL.KONSIG_PARTNER_NR=:x->KONSIG_PARTNER_NR,\
        ARTIKELZENTRAL.ARTIKEL_LANGNAME=:x->ARTIKEL_LANGNAME,\
        ARTIKELZENTRAL.PRICE_GROUP=:x->PRICE_GROUP,\
        ARTIKELZENTRAL.SORTIMENT_1=:x->SORTIMENT_1,\
        ARTIKELZENTRAL.SORTIMENT_2=:x->SORTIMENT_2,\
        ARTIKELZENTRAL.SORTIMENT_3=:x->SORTIMENT_3,\
        ARTIKELZENTRAL.SORTIMENT_4=:x->SORTIMENT_4,\
        ARTIKELZENTRAL.SORTIMENT_5=:x->SORTIMENT_5,\
        ARTIKELZENTRAL.DATUM_ANLAGE=:x->DATUM_ANLAGE,\
        ARTIKELZENTRAL.BUSINESSTYPENO=:x->BUSINESSTYPENO,\
        ARTIKELZENTRAL.LISTE_5=:x->LISTE_5,\
        ARTIKELZENTRAL.UPD_FLAG=:x->UPD_FLAG,\
        ARTIKELZENTRAL.ARTIKEL_NR_HERST=:x->ARTIKEL_NR_HERST,\
        ARTIKELZENTRAL.MEDPROD_ABG_VERORD=:x->MEDPROD_ABG_VERORD,\
        ARTIKELZENTRAL.PRODUSERQUOTA=:x->PRODUSERQUOTA,\
        ARTIKELZENTRAL.MEDICALPRODUCT=:x->MEDICALPRODUCT,\
        ARTIKELZENTRAL.DATEOUTOFTRADE=:x->DATEOUTOFTRADE,\
        ARTIKELZENTRAL.ARTIKEL_GESPERRT=:x->ARTIKEL_GESPERRT,\
        ARTIKELZENTRAL.IKS_CODE=:x->IKS_CODE,\
        ARTIKELZENTRAL.BATCHRECALLDATERETURNS=:x->BATCHRECALLDATERETURNS,\
        ARTIKELZENTRAL.IMPORTARTICLE=:x->IMPORTARTICLE,\
        ARTIKELZENTRAL.BTM_FAKTOR=:x->BTM_FAKTOR,\
        ARTIKELZENTRAL.TFG=:x->TFG,\
        ARTIKELZENTRAL.KONTINGENT_PPE=:x->KONTINGENT_PPE,\
        ARTIKELZENTRAL.DATUM_LIEFERBAR_AB=:x->DATUM_LIEFERBAR_AB,\
        ARTIKELZENTRAL.MEDIZINPRODUKT=:x->MEDIZINPRODUKT,\
        ARTIKELZENTRAL.FROZEN=:x->FROZEN,\
        ARTIKELZENTRAL.DATUM_AENDER=:x->DATUM_AENDER,\
        ARTIKELZENTRAL.ATC_CODE=:x->ATC_CODE,\
        ARTIKELZENTRAL.MINISTRYPRODUCTCODE=:x->MINISTRYPRODUCTCODE,\
        ARTIKELZENTRAL.HEALTHFUNDCODEHOSPITAL=:x->HEALTHFUNDCODEHOSPITAL,\
        ARTIKELZENTRAL.CMI_FLAG=:x->CMI_FLAG,\
        ARTIKELZENTRAL.TAXPFL=:x->TAXPFL
/* SqlMacros390-Define of ARTIKELZENTRAL **************************************/

#define ARTIKELZENTRAL_ZEIGER_390 \
        :ARTIKEL_NR,\
        :ARTIKEL_MC,\
        :PACKGROESSE,\
        :DARREICHFORM,\
        :NORMPACKUNG,\
        :EINHEIT,\
        :ARTIKEL_NAME,\
        :ETARTKLASSE1,\
        :ETARTSCHALTER1,\
        :ETARTSCHALTER2,\
        :ETARTSCHALTER3,\
        :ETARTSCHALTER4,\
        :ETARTSCHALTER5,\
        :HERSTELLER_NR,\
        :WARENGRUPPE,\
        :THERAPIEGRUPPE,\
        :LAENGE,\
        :HOEHE,\
        :BREITE,\
        :GEWICHT,\
        :LAUFZEITMONATE,\
        :WARENGRUPPEEIGEN,\
        :HERSTELLER_CODE,\
        :KZPSYCHOSTOFFE,\
        :TAXLEVEL,\
        :TEXTKEY_HOSPITAL,\
        :KZRESERVEHOSPITAL,\
        :STD_MENGE,\
        :RUNDUNG_STD_MGE,\
        :NICHT_UEBER_DAFUE,\
        :NICHT_UEBER_XML,\
        :KZZUSCHLAGSARTIKEL,\
        :WIRKSTOFF_NR,\
        :HEALTHFUNDCODE,\
        :STELLER,\
        :POSITIVLISTE,\
        :ABDACODE,\
        :KONSIG_PARTNER_NR,\
        :ARTIKEL_LANGNAME,\
        :PRICE_GROUP,\
        :SORTIMENT_1,\
        :SORTIMENT_2,\
        :SORTIMENT_3,\
        :SORTIMENT_4,\
        :SORTIMENT_5,\
        :DATUM_ANLAGE,\
        :BUSINESSTYPENO,\
        :LISTE_5,\
        :UPD_FLAG,\
        :ARTIKEL_NR_HERST,\
        :MEDPROD_ABG_VERORD,\
        :PRODUSERQUOTA,\
        :MEDICALPRODUCT,\
        :DATEOUTOFTRADE,\
        :ARTIKEL_GESPERRT,\
        :IKS_CODE,\
        :BATCHRECALLDATERETURNS,\
        :IMPORTARTICLE,\
        :BTM_FAKTOR,\
        :TFG,\
        :KONTINGENT_PPE,\
        :DATUM_LIEFERBAR_AB,\
        :MEDIZINPRODUKT,\
        :FROZEN,\
        :DATUM_AENDER,\
        :ATC_CODE,\
        :MINISTRYPRODUCTCODE,\
        :HEALTHFUNDCODEHOSPITAL,\
        :CMI_FLAG,\
        :TAXPFL
#define ARTIKELZENTRAL_UPDATE_390 \
        ARTIKEL_NR=:ARTIKEL_NR,\
        ARTIKEL_MC=:ARTIKEL_MC,\
        PACKGROESSE=:PACKGROESSE,\
        DARREICHFORM=:DARREICHFORM,\
        NORMPACKUNG=:NORMPACKUNG,\
        EINHEIT=:EINHEIT,\
        ARTIKEL_NAME=:ARTIKEL_NAME,\
        ETARTKLASSE1=:ETARTKLASSE1,\
        ETARTSCHALTER1=:ETARTSCHALTER1,\
        ETARTSCHALTER2=:ETARTSCHALTER2,\
        ETARTSCHALTER3=:ETARTSCHALTER3,\
        ETARTSCHALTER4=:ETARTSCHALTER4,\
        ETARTSCHALTER5=:ETARTSCHALTER5,\
        HERSTELLER_NR=:HERSTELLER_NR,\
        WARENGRUPPE=:WARENGRUPPE,\
        THERAPIEGRUPPE=:THERAPIEGRUPPE,\
        LAENGE=:LAENGE,\
        HOEHE=:HOEHE,\
        BREITE=:BREITE,\
        GEWICHT=:GEWICHT,\
        LAUFZEITMONATE=:LAUFZEITMONATE,\
        WARENGRUPPEEIGEN=:WARENGRUPPEEIGEN,\
        HERSTELLER_CODE=:HERSTELLER_CODE,\
        KZPSYCHOSTOFFE=:KZPSYCHOSTOFFE,\
        TAXLEVEL=:TAXLEVEL,\
        TEXTKEY_HOSPITAL=:TEXTKEY_HOSPITAL,\
        KZRESERVEHOSPITAL=:KZRESERVEHOSPITAL,\
        STD_MENGE=:STD_MENGE,\
        RUNDUNG_STD_MGE=:RUNDUNG_STD_MGE,\
        NICHT_UEBER_DAFUE=:NICHT_UEBER_DAFUE,\
        NICHT_UEBER_XML=:NICHT_UEBER_XML,\
        KZZUSCHLAGSARTIKEL=:KZZUSCHLAGSARTIKEL,\
        WIRKSTOFF_NR=:WIRKSTOFF_NR,\
        HEALTHFUNDCODE=:HEALTHFUNDCODE,\
        STELLER=:STELLER,\
        POSITIVLISTE=:POSITIVLISTE,\
        ABDACODE=:ABDACODE,\
        KONSIG_PARTNER_NR=:KONSIG_PARTNER_NR,\
        ARTIKEL_LANGNAME=:ARTIKEL_LANGNAME,\
        PRICE_GROUP=:PRICE_GROUP,\
        SORTIMENT_1=:SORTIMENT_1,\
        SORTIMENT_2=:SORTIMENT_2,\
        SORTIMENT_3=:SORTIMENT_3,\
        SORTIMENT_4=:SORTIMENT_4,\
        SORTIMENT_5=:SORTIMENT_5,\
        DATUM_ANLAGE=:DATUM_ANLAGE,\
        BUSINESSTYPENO=:BUSINESSTYPENO,\
        LISTE_5=:LISTE_5,\
        UPD_FLAG=:UPD_FLAG,\
        ARTIKEL_NR_HERST=:ARTIKEL_NR_HERST,\
        MEDPROD_ABG_VERORD=:MEDPROD_ABG_VERORD,\
        PRODUSERQUOTA=:PRODUSERQUOTA,\
        MEDICALPRODUCT=:MEDICALPRODUCT,\
        DATEOUTOFTRADE=:DATEOUTOFTRADE,\
        ARTIKEL_GESPERRT=:ARTIKEL_GESPERRT,\
        IKS_CODE=:IKS_CODE,\
        BATCHRECALLDATERETURNS=:BATCHRECALLDATERETURNS,\
        IMPORTARTICLE=:IMPORTARTICLE,\
        BTM_FAKTOR=:BTM_FAKTOR,\
        TFG=:TFG,\
        KONTINGENT_PPE=:KONTINGENT_PPE,\
        DATUM_LIEFERBAR_AB=:DATUM_LIEFERBAR_AB,\
        MEDIZINPRODUKT=:MEDIZINPRODUKT,\
        FROZEN=:FROZEN,\
        DATUM_AENDER=:DATUM_AENDER,\
        ATC_CODE=:ATC_CODE,\
        MINISTRYPRODUCTCODE=:MINISTRYPRODUCTCODE,\
        HEALTHFUNDCODEHOSPITAL=:HEALTHFUNDCODEHOSPITAL,\
        CMI_FLAG=:CMI_FLAG,\
        TAXPFL=:TAXPFL
#ifdef TRANSCLASS
#include <string.h>
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* original struct of ARTIKELZENTRAL ******************************************/

#ifndef TRANSCLASS
typedef struct N_ARTIKELZENTRAL {
    long ARTIKEL_NR;
    char ARTIKEL_MC[13];
    long PACKGROESSE;
    char DARREICHFORM[4];
    char NORMPACKUNG[3];
    char EINHEIT[10];
    char ARTIKEL_NAME[31];
    long ETARTKLASSE1;
    long ETARTSCHALTER1;
    long ETARTSCHALTER2;
    long ETARTSCHALTER3;
    long ETARTSCHALTER4;
    long ETARTSCHALTER5;
    long HERSTELLER_NR;
    char WARENGRUPPE[6];
    char THERAPIEGRUPPE[6];
    long LAENGE;
    long HOEHE;
    long BREITE;
    long GEWICHT;
    long LAUFZEITMONATE;
    char WARENGRUPPEEIGEN[6];
    char HERSTELLER_CODE[6];
    char KZPSYCHOSTOFFE[2];
    short TAXLEVEL;
    short TEXTKEY_HOSPITAL;
    char KZRESERVEHOSPITAL[2];
    short STD_MENGE;
    char RUNDUNG_STD_MGE[2];
    char NICHT_UEBER_DAFUE[2];
    char NICHT_UEBER_XML[2];
    char KZZUSCHLAGSARTIKEL[2];
    char WIRKSTOFF_NR[4];
    char HEALTHFUNDCODE[6];
    char STELLER[2];
    char POSITIVLISTE[2];
    char ABDACODE[6];
    long KONSIG_PARTNER_NR;
    char ARTIKEL_LANGNAME[51];
    short PRICE_GROUP;
    char SORTIMENT_1[2];
    char SORTIMENT_2[2];
    char SORTIMENT_3[2];
    char SORTIMENT_4[2];
    char SORTIMENT_5[2];
    long DATUM_ANLAGE;
    short BUSINESSTYPENO;
    short LISTE_5;
    char UPD_FLAG[2];
    char ARTIKEL_NR_HERST[16];
    char MEDPROD_ABG_VERORD[2];
    short PRODUSERQUOTA;
    short MEDICALPRODUCT;
    long DATEOUTOFTRADE;
    char ARTIKEL_GESPERRT[2];
    char IKS_CODE[2];
    long BATCHRECALLDATERETURNS;
    short IMPORTARTICLE;
    double BTM_FAKTOR;
    char TFG[2];
    char KONTINGENT_PPE[2];
    long DATUM_LIEFERBAR_AB;
    char MEDIZINPRODUKT[2];
    short FROZEN;
    long DATUM_AENDER;
    char ATC_CODE[26];
    char MINISTRYPRODUCTCODE[26];
    char HEALTHFUNDCODEHOSPITAL[26];
    short CMI_FLAG;
    char TAXPFL[2];
} artikelzentralS;
#else /* TRANSCLASS */
typedef struct N_ARTIKELZENTRAL {
    long ARTIKEL_NR;
    char ARTIKEL_MC[13];
    long PACKGROESSE;
    char DARREICHFORM[4];
    char NORMPACKUNG[3];
    char EINHEIT[10];
    char ARTIKEL_NAME[31];
    long ETARTKLASSE1;
    long ETARTSCHALTER1;
    long ETARTSCHALTER2;
    long ETARTSCHALTER3;
    long ETARTSCHALTER4;
    long ETARTSCHALTER5;
    long HERSTELLER_NR;
    char WARENGRUPPE[6];
    char THERAPIEGRUPPE[6];
    long LAENGE;
    long HOEHE;
    long BREITE;
    long GEWICHT;
    long LAUFZEITMONATE;
    char WARENGRUPPEEIGEN[6];
    char HERSTELLER_CODE[6];
    char KZPSYCHOSTOFFE[2];
    short TAXLEVEL;
    short TEXTKEY_HOSPITAL;
    char KZRESERVEHOSPITAL[2];
    short STD_MENGE;
    char RUNDUNG_STD_MGE[2];
    char NICHT_UEBER_DAFUE[2];
    char NICHT_UEBER_XML[2];
    char KZZUSCHLAGSARTIKEL[2];
    char WIRKSTOFF_NR[4];
    char HEALTHFUNDCODE[6];
    char STELLER[2];
    char POSITIVLISTE[2];
    char ABDACODE[6];
    long KONSIG_PARTNER_NR;
    char ARTIKEL_LANGNAME[51];
    short PRICE_GROUP;
    char SORTIMENT_1[2];
    char SORTIMENT_2[2];
    char SORTIMENT_3[2];
    char SORTIMENT_4[2];
    char SORTIMENT_5[2];
    long DATUM_ANLAGE;
    short BUSINESSTYPENO;
    short LISTE_5;
    char UPD_FLAG[2];
    char ARTIKEL_NR_HERST[16];
    char MEDPROD_ABG_VERORD[2];
    short PRODUSERQUOTA;
    short MEDICALPRODUCT;
    long DATEOUTOFTRADE;
    char ARTIKEL_GESPERRT[2];
    char IKS_CODE[2];
    long BATCHRECALLDATERETURNS;
    short IMPORTARTICLE;
    double BTM_FAKTOR;
    char TFG[2];
    char KONTINGENT_PPE[2];
    long DATUM_LIEFERBAR_AB;
    char MEDIZINPRODUKT[2];
    short FROZEN;
    long DATUM_AENDER;
    char ATC_CODE[26];
    char MINISTRYPRODUCTCODE[26];
    char HEALTHFUNDCODEHOSPITAL[26];
    short CMI_FLAG;
    char TAXPFL[2];

    bool operator == (const N_ARTIKELZENTRAL& right) const {
        return (
            ARTIKEL_NR == right.ARTIKEL_NR &&
            !strcmp(ARTIKEL_MC, right.ARTIKEL_MC) &&
            PACKGROESSE == right.PACKGROESSE &&
            !strcmp(DARREICHFORM, right.DARREICHFORM) &&
            !strcmp(NORMPACKUNG, right.NORMPACKUNG) &&
            !strcmp(EINHEIT, right.EINHEIT) &&
            !strcmp(ARTIKEL_NAME, right.ARTIKEL_NAME) &&
            ETARTKLASSE1 == right.ETARTKLASSE1 &&
            ETARTSCHALTER1 == right.ETARTSCHALTER1 &&
            ETARTSCHALTER2 == right.ETARTSCHALTER2 &&
            ETARTSCHALTER3 == right.ETARTSCHALTER3 &&
            ETARTSCHALTER4 == right.ETARTSCHALTER4 &&
            ETARTSCHALTER5 == right.ETARTSCHALTER5 &&
            HERSTELLER_NR == right.HERSTELLER_NR &&
            !strcmp(WARENGRUPPE, right.WARENGRUPPE) &&
            !strcmp(THERAPIEGRUPPE, right.THERAPIEGRUPPE) &&
            LAENGE == right.LAENGE &&
            HOEHE == right.HOEHE &&
            BREITE == right.BREITE &&
            GEWICHT == right.GEWICHT &&
            LAUFZEITMONATE == right.LAUFZEITMONATE &&
            !strcmp(WARENGRUPPEEIGEN, right.WARENGRUPPEEIGEN) &&
            !strcmp(HERSTELLER_CODE, right.HERSTELLER_CODE) &&
            !strcmp(KZPSYCHOSTOFFE, right.KZPSYCHOSTOFFE) &&
            TAXLEVEL == right.TAXLEVEL &&
            TEXTKEY_HOSPITAL == right.TEXTKEY_HOSPITAL &&
            !strcmp(KZRESERVEHOSPITAL, right.KZRESERVEHOSPITAL) &&
            STD_MENGE == right.STD_MENGE &&
            !strcmp(RUNDUNG_STD_MGE, right.RUNDUNG_STD_MGE) &&
            !strcmp(NICHT_UEBER_DAFUE, right.NICHT_UEBER_DAFUE) &&
            !strcmp(NICHT_UEBER_XML, right.NICHT_UEBER_XML) &&
            !strcmp(KZZUSCHLAGSARTIKEL, right.KZZUSCHLAGSARTIKEL) &&
            !strcmp(WIRKSTOFF_NR, right.WIRKSTOFF_NR) &&
            !strcmp(HEALTHFUNDCODE, right.HEALTHFUNDCODE) &&
            !strcmp(STELLER, right.STELLER) &&
            !strcmp(POSITIVLISTE, right.POSITIVLISTE) &&
            !strcmp(ABDACODE, right.ABDACODE) &&
            KONSIG_PARTNER_NR == right.KONSIG_PARTNER_NR &&
            !strcmp(ARTIKEL_LANGNAME, right.ARTIKEL_LANGNAME) &&
            PRICE_GROUP == right.PRICE_GROUP &&
            !strcmp(SORTIMENT_1, right.SORTIMENT_1) &&
            !strcmp(SORTIMENT_2, right.SORTIMENT_2) &&
            !strcmp(SORTIMENT_3, right.SORTIMENT_3) &&
            !strcmp(SORTIMENT_4, right.SORTIMENT_4) &&
            !strcmp(SORTIMENT_5, right.SORTIMENT_5) &&
            DATUM_ANLAGE == right.DATUM_ANLAGE &&
            BUSINESSTYPENO == right.BUSINESSTYPENO &&
            LISTE_5 == right.LISTE_5 &&
            !strcmp(UPD_FLAG, right.UPD_FLAG) &&
            !strcmp(ARTIKEL_NR_HERST, right.ARTIKEL_NR_HERST) &&
            !strcmp(MEDPROD_ABG_VERORD, right.MEDPROD_ABG_VERORD) &&
            PRODUSERQUOTA == right.PRODUSERQUOTA &&
            MEDICALPRODUCT == right.MEDICALPRODUCT &&
            DATEOUTOFTRADE == right.DATEOUTOFTRADE &&
            !strcmp(ARTIKEL_GESPERRT, right.ARTIKEL_GESPERRT) &&
            !strcmp(IKS_CODE, right.IKS_CODE) &&
            BATCHRECALLDATERETURNS == right.BATCHRECALLDATERETURNS &&
            IMPORTARTICLE == right.IMPORTARTICLE &&
            BTM_FAKTOR == right.BTM_FAKTOR &&
            !strcmp(TFG, right.TFG) &&
            !strcmp(KONTINGENT_PPE, right.KONTINGENT_PPE) &&
            DATUM_LIEFERBAR_AB == right.DATUM_LIEFERBAR_AB &&
            !strcmp(MEDIZINPRODUKT, right.MEDIZINPRODUKT) &&
            FROZEN == right.FROZEN &&
            DATUM_AENDER == right.DATUM_AENDER &&
            !strcmp(ATC_CODE, right.ATC_CODE) &&
            !strcmp(MINISTRYPRODUCTCODE, right.MINISTRYPRODUCTCODE) &&
            !strcmp(HEALTHFUNDCODEHOSPITAL, right.HEALTHFUNDCODEHOSPITAL) &&
            CMI_FLAG == right.CMI_FLAG &&
            !strcmp(TAXPFL, right.TAXPFL)
        );
    }
    void clear() {
#ifdef WIN32
        memset((char*)this, 0, sizeof(*this));
#else
        ARTIKEL_NR = 0;
        strcpy(ARTIKEL_MC, " " );
        PACKGROESSE = 0;
        strcpy(DARREICHFORM, " " );
        strcpy(NORMPACKUNG, " " );
        strcpy(EINHEIT, " " );
        strcpy(ARTIKEL_NAME, " " );
        ETARTKLASSE1 = 0;
        ETARTSCHALTER1 = 0;
        ETARTSCHALTER2 = 0;
        ETARTSCHALTER3 = 0;
        ETARTSCHALTER4 = 0;
        ETARTSCHALTER5 = 0;
        HERSTELLER_NR = 0;
        strcpy(WARENGRUPPE, " " );
        strcpy(THERAPIEGRUPPE, " " );
        LAENGE = 0;
        HOEHE = 0;
        BREITE = 0;
        GEWICHT = 0;
        LAUFZEITMONATE = 0;
        strcpy(WARENGRUPPEEIGEN, " " );
        strcpy(HERSTELLER_CODE, " " );
        strcpy(KZPSYCHOSTOFFE, " " );
        TAXLEVEL = 0;
        TEXTKEY_HOSPITAL = 0;
        strcpy(KZRESERVEHOSPITAL, " " );
        STD_MENGE = 0;
        strcpy(RUNDUNG_STD_MGE, " " );
        strcpy(NICHT_UEBER_DAFUE, " " );
        strcpy(NICHT_UEBER_XML, " " );
        strcpy(KZZUSCHLAGSARTIKEL, " " );
        strcpy(WIRKSTOFF_NR, " " );
        strcpy(HEALTHFUNDCODE, " " );
        strcpy(STELLER, " " );
        strcpy(POSITIVLISTE, " " );
        strcpy(ABDACODE, " " );
        KONSIG_PARTNER_NR = 0;
        strcpy(ARTIKEL_LANGNAME, " " );
        PRICE_GROUP = 0;
        strcpy(SORTIMENT_1, " " );
        strcpy(SORTIMENT_2, " " );
        strcpy(SORTIMENT_3, " " );
        strcpy(SORTIMENT_4, " " );
        strcpy(SORTIMENT_5, " " );
        DATUM_ANLAGE = 0;
        BUSINESSTYPENO = 0;
        LISTE_5 = 0;
        strcpy(UPD_FLAG, " " );
        strcpy(ARTIKEL_NR_HERST, " " );
        strcpy(MEDPROD_ABG_VERORD, " " );
        PRODUSERQUOTA = 0;
        MEDICALPRODUCT = 0;
        DATEOUTOFTRADE = 0;
        strcpy(ARTIKEL_GESPERRT, " " );
        strcpy(IKS_CODE, " " );
        BATCHRECALLDATERETURNS = 0;
        IMPORTARTICLE = 0;
        BTM_FAKTOR = 0;
        strcpy(TFG, " " );
        strcpy(KONTINGENT_PPE, " " );
        DATUM_LIEFERBAR_AB = 0;
        strcpy(MEDIZINPRODUKT, " " );
        FROZEN = 0;
        DATUM_AENDER = 0;
        strcpy(ATC_CODE, " " );
        strcpy(MINISTRYPRODUCTCODE, " " );
        strcpy(HEALTHFUNDCODEHOSPITAL, " " );
        CMI_FLAG = 0;
        strcpy(TAXPFL, " " );
#endif
    }
} artikelzentralS;
#endif /* TRANSCLASS */

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Stringbuffer Structur of ARTIKELZENTRAL ************************************/

struct S_ARTIKELZENTRAL {
    char ARTIKEL_NR[11];
    char ARTIKEL_MC[12 + 1];
    char PACKGROESSE[11];
    char DARREICHFORM[3 + 1];
    char NORMPACKUNG[2 + 1];
    char EINHEIT[9 + 1];
    char ARTIKEL_NAME[30 + 1];
    char ETARTKLASSE1[5 + 1];
    char ETARTSCHALTER1[5 + 1];
    char ETARTSCHALTER2[5 + 1];
    char ETARTSCHALTER3[5 + 1];
    char ETARTSCHALTER4[5 + 1];
    char ETARTSCHALTER5[5 + 1];
    char HERSTELLER_NR[11];
    char WARENGRUPPE[5 + 1];
    char THERAPIEGRUPPE[5 + 1];
    char LAENGE[11];
    char HOEHE[11];
    char BREITE[11];
    char GEWICHT[11];
    char LAUFZEITMONATE[11];
    char WARENGRUPPEEIGEN[5 + 1];
    char HERSTELLER_CODE[5 + 1];
    char KZPSYCHOSTOFFE[1 + 1];
    char TAXLEVEL[7];
    char TEXTKEY_HOSPITAL[7];
    char KZRESERVEHOSPITAL[1 + 1];
    char STD_MENGE[7];
    char RUNDUNG_STD_MGE[1 + 1];
    char NICHT_UEBER_DAFUE[1 + 1];
    char NICHT_UEBER_XML[1 + 1];
    char KZZUSCHLAGSARTIKEL[1 + 1];
    char WIRKSTOFF_NR[3 + 1];
    char HEALTHFUNDCODE[5 + 1];
    char STELLER[1 + 1];
    char POSITIVLISTE[1 + 1];
    char ABDACODE[5 + 1];
    char KONSIG_PARTNER_NR[11];
    char ARTIKEL_LANGNAME[50 + 1];
    char PRICE_GROUP[7];
    char SORTIMENT_1[1 + 1];
    char SORTIMENT_2[1 + 1];
    char SORTIMENT_3[1 + 1];
    char SORTIMENT_4[1 + 1];
    char SORTIMENT_5[1 + 1];
    char DATUM_ANLAGE[11];
    char BUSINESSTYPENO[7];
    char LISTE_5[7];
    char UPD_FLAG[1 + 1];
    char ARTIKEL_NR_HERST[15 + 1];
    char MEDPROD_ABG_VERORD[1 + 1];
    char PRODUSERQUOTA[7];
    char MEDICALPRODUCT[7];
    char DATEOUTOFTRADE[11];
    char ARTIKEL_GESPERRT[1 + 1];
    char IKS_CODE[1 + 1];
    char BATCHRECALLDATERETURNS[11];
    char IMPORTARTICLE[7];
    char BTM_FAKTOR[8 + 2];
    char TFG[1 + 1];
    char KONTINGENT_PPE[1 + 1];
    char DATUM_LIEFERBAR_AB[11];
    char MEDIZINPRODUKT[1 + 1];
    char FROZEN[7];
    char DATUM_AENDER[11];
    char ATC_CODE[25 + 1];
    char MINISTRYPRODUCTCODE[25 + 1];
    char HEALTHFUNDCODEHOSPITAL[25 + 1];
    char CMI_FLAG[7];
    char TAXPFL[1 + 1];
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Stringbuffer (without strend) Structur of ARTIKELZENTRAL *******************/

struct O_ARTIKELZENTRAL {
    char ARTIKEL_NR[11];
    char ARTIKEL_MC[12];
    char PACKGROESSE[11];
    char DARREICHFORM[3];
    char NORMPACKUNG[2];
    char EINHEIT[9];
    char ARTIKEL_NAME[30];
    char ETARTKLASSE1[5];
    char ETARTSCHALTER1[5];
    char ETARTSCHALTER2[5];
    char ETARTSCHALTER3[5];
    char ETARTSCHALTER4[5];
    char ETARTSCHALTER5[5];
    char HERSTELLER_NR[11];
    char WARENGRUPPE[5];
    char THERAPIEGRUPPE[5];
    char LAENGE[11];
    char HOEHE[11];
    char BREITE[11];
    char GEWICHT[11];
    char LAUFZEITMONATE[11];
    char WARENGRUPPEEIGEN[5];
    char HERSTELLER_CODE[5];
    char KZPSYCHOSTOFFE[1];
    char TAXLEVEL[7];
    char TEXTKEY_HOSPITAL[7];
    char KZRESERVEHOSPITAL[1];
    char STD_MENGE[7];
    char RUNDUNG_STD_MGE[1];
    char NICHT_UEBER_DAFUE[1];
    char NICHT_UEBER_XML[1];
    char KZZUSCHLAGSARTIKEL[1];
    char WIRKSTOFF_NR[3];
    char HEALTHFUNDCODE[5];
    char STELLER[1];
    char POSITIVLISTE[1];
    char ABDACODE[5];
    char KONSIG_PARTNER_NR[11];
    char ARTIKEL_LANGNAME[50];
    char PRICE_GROUP[7];
    char SORTIMENT_1[1];
    char SORTIMENT_2[1];
    char SORTIMENT_3[1];
    char SORTIMENT_4[1];
    char SORTIMENT_5[1];
    char DATUM_ANLAGE[11];
    char BUSINESSTYPENO[7];
    char LISTE_5[7];
    char UPD_FLAG[1];
    char ARTIKEL_NR_HERST[15];
    char MEDPROD_ABG_VERORD[1];
    char PRODUSERQUOTA[7];
    char MEDICALPRODUCT[7];
    char DATEOUTOFTRADE[11];
    char ARTIKEL_GESPERRT[1];
    char IKS_CODE[1];
    char BATCHRECALLDATERETURNS[11];
    char IMPORTARTICLE[7];
    char BTM_FAKTOR[8];
    char TFG[1];
    char KONTINGENT_PPE[1];
    char DATUM_LIEFERBAR_AB[11];
    char MEDIZINPRODUKT[1];
    char FROZEN[7];
    char DATUM_AENDER[11];
    char ATC_CODE[25];
    char MINISTRYPRODUCTCODE[25];
    char HEALTHFUNDCODEHOSPITAL[25];
    char CMI_FLAG[7];
    char TAXPFL[1];
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Structur with real chartype of ARTIKELZENTRAL ******************************/

struct C_ARTIKELZENTRAL {
    long ARTIKEL_NR;
    char ARTIKEL_MC[13];
    long PACKGROESSE;
    char DARREICHFORM[4];
    char NORMPACKUNG[3];
    char EINHEIT[10];
    char ARTIKEL_NAME[31];
    long ETARTKLASSE1;
    long ETARTSCHALTER1;
    long ETARTSCHALTER2;
    long ETARTSCHALTER3;
    long ETARTSCHALTER4;
    long ETARTSCHALTER5;
    long HERSTELLER_NR;
    char WARENGRUPPE[6];
    char THERAPIEGRUPPE[6];
    long LAENGE;
    long HOEHE;
    long BREITE;
    long GEWICHT;
    long LAUFZEITMONATE;
    char WARENGRUPPEEIGEN[6];
    char HERSTELLER_CODE[6];
    char KZPSYCHOSTOFFE;
    short TAXLEVEL;
    short TEXTKEY_HOSPITAL;
    char KZRESERVEHOSPITAL;
    short STD_MENGE;
    char RUNDUNG_STD_MGE;
    char NICHT_UEBER_DAFUE;
    char NICHT_UEBER_XML;
    char KZZUSCHLAGSARTIKEL;
    char WIRKSTOFF_NR[4];
    char HEALTHFUNDCODE[6];
    char STELLER;
    char POSITIVLISTE;
    char ABDACODE[6];
    long KONSIG_PARTNER_NR;
    char ARTIKEL_LANGNAME[51];
    short PRICE_GROUP;
    char SORTIMENT_1;
    char SORTIMENT_2;
    char SORTIMENT_3;
    char SORTIMENT_4;
    char SORTIMENT_5;
    long DATUM_ANLAGE;
    short BUSINESSTYPENO;
    short LISTE_5;
    char UPD_FLAG;
    char ARTIKEL_NR_HERST[16];
    char MEDPROD_ABG_VERORD;
    short PRODUSERQUOTA;
    short MEDICALPRODUCT;
    long DATEOUTOFTRADE;
    char ARTIKEL_GESPERRT;
    char IKS_CODE;
    long BATCHRECALLDATERETURNS;
    short IMPORTARTICLE;
    double BTM_FAKTOR;
    char TFG;
    char KONTINGENT_PPE;
    long DATUM_LIEFERBAR_AB;
    char MEDIZINPRODUKT;
    short FROZEN;
    long DATUM_AENDER;
    char ATC_CODE[26];
    char MINISTRYPRODUCTCODE[26];
    char HEALTHFUNDCODEHOSPITAL[26];
    short CMI_FLAG;
    char TAXPFL;
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Sizetype  Structur (buf_desc) of ARTIKELZENTRAL ****************************/

struct I_ARTIKELZENTRAL {
    short ARTIKEL_NR;
    short ARTIKEL_MC;
    short PACKGROESSE;
    short DARREICHFORM;
    short NORMPACKUNG;
    short EINHEIT;
    short ARTIKEL_NAME;
    short ETARTKLASSE1;
    short ETARTSCHALTER1;
    short ETARTSCHALTER2;
    short ETARTSCHALTER3;
    short ETARTSCHALTER4;
    short ETARTSCHALTER5;
    short HERSTELLER_NR;
    short WARENGRUPPE;
    short THERAPIEGRUPPE;
    short LAENGE;
    short HOEHE;
    short BREITE;
    short GEWICHT;
    short LAUFZEITMONATE;
    short WARENGRUPPEEIGEN;
    short HERSTELLER_CODE;
    short KZPSYCHOSTOFFE;
    short TAXLEVEL;
    short TEXTKEY_HOSPITAL;
    short KZRESERVEHOSPITAL;
    short STD_MENGE;
    short RUNDUNG_STD_MGE;
    short NICHT_UEBER_DAFUE;
    short NICHT_UEBER_XML;
    short KZZUSCHLAGSARTIKEL;
    short WIRKSTOFF_NR;
    short HEALTHFUNDCODE;
    short STELLER;
    short POSITIVLISTE;
    short ABDACODE;
    short KONSIG_PARTNER_NR;
    short ARTIKEL_LANGNAME;
    short PRICE_GROUP;
    short SORTIMENT_1;
    short SORTIMENT_2;
    short SORTIMENT_3;
    short SORTIMENT_4;
    short SORTIMENT_5;
    short DATUM_ANLAGE;
    short BUSINESSTYPENO;
    short LISTE_5;
    short UPD_FLAG;
    short ARTIKEL_NR_HERST;
    short MEDPROD_ABG_VERORD;
    short PRODUSERQUOTA;
    short MEDICALPRODUCT;
    short DATEOUTOFTRADE;
    short ARTIKEL_GESPERRT;
    short IKS_CODE;
    short BATCHRECALLDATERETURNS;
    short IMPORTARTICLE;
    short BTM_FAKTOR;
    short TFG;
    short KONTINGENT_PPE;
    short DATUM_LIEFERBAR_AB;
    short MEDIZINPRODUKT;
    short FROZEN;
    short DATUM_AENDER;
    short ATC_CODE;
    short MINISTRYPRODUCTCODE;
    short HEALTHFUNDCODEHOSPITAL;
    short CMI_FLAG;
    short TAXPFL;
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

/* structures of Buf_Desc *****************************************************/

/* Structur (buf_desc) of ARTIKELZENTRAL **************************************/

#if defined (BUF_DESC)
static struct buf_desc ARTIKELZENTRAL_BES [] = {
   { TYP_L , 11, 0 },
   { TYP_C, 12, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 3, 0 },
   { TYP_C, 2, 0 },
   { TYP_C, 9, 0 },
   { TYP_C, 30, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 5, 0 },
   { TYP_C, 5, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 5, 0 },
   { TYP_C, 5, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 3, 0 },
   { TYP_C, 5, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 5, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 50, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 15, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_D, 8, 3 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 25, 0 },
   { TYP_C, 25, 0 },
   { TYP_C, 25, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
};
#elif defined (C_BUF_DESC)
static struct buf_desc ARTIKELZENTRAL_BES [] = {
   { TYP_L , 11, 0 },
   { TYP_C, 12, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 3, 0 },
   { TYP_C, 2, 0 },
   { TYP_C, 9, 0 },
   { TYP_C, 30, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 5, 0 },
   { TYP_C, 5, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 5, 0 },
   { TYP_C, 5, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 3, 0 },
   { TYP_C, 5, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 5, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 50, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 15, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_D, 8, 3 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 25, 0 },
   { TYP_C, 25, 0 },
   { TYP_C, 25, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
};
#endif

/* description for datatypes of ARTIKELZENTRAL ********************************/

 #define ARTIKELZENTRAL_S390 \
         long ARTIKEL_NR; \
         char ARTIKEL_MC[13]; \
         long PACKGROESSE; \
         char DARREICHFORM[4]; \
         char NORMPACKUNG[3]; \
         char EINHEIT[10]; \
         char ARTIKEL_NAME[31]; \
         long ETARTKLASSE1; \
         long ETARTSCHALTER1; \
         long ETARTSCHALTER2; \
         long ETARTSCHALTER3; \
         long ETARTSCHALTER4; \
         long ETARTSCHALTER5; \
         long HERSTELLER_NR; \
         char WARENGRUPPE[6]; \
         char THERAPIEGRUPPE[6]; \
         long LAENGE; \
         long HOEHE; \
         long BREITE; \
         long GEWICHT; \
         long LAUFZEITMONATE; \
         char WARENGRUPPEEIGEN[6]; \
         char HERSTELLER_CODE[6]; \
         char KZPSYCHOSTOFFE; \
         short TAXLEVEL; \
         short TEXTKEY_HOSPITAL; \
         char KZRESERVEHOSPITAL; \
         short STD_MENGE; \
         char RUNDUNG_STD_MGE; \
         char NICHT_UEBER_DAFUE; \
         char NICHT_UEBER_XML; \
         char KZZUSCHLAGSARTIKEL; \
         char WIRKSTOFF_NR[4]; \
         char HEALTHFUNDCODE[6]; \
         char STELLER; \
         char POSITIVLISTE; \
         char ABDACODE[6]; \
         long KONSIG_PARTNER_NR; \
         char ARTIKEL_LANGNAME[51]; \
         short PRICE_GROUP; \
         char SORTIMENT_1; \
         char SORTIMENT_2; \
         char SORTIMENT_3; \
         char SORTIMENT_4; \
         char SORTIMENT_5; \
         long DATUM_ANLAGE; \
         short BUSINESSTYPENO; \
         short LISTE_5; \
         char UPD_FLAG; \
         char ARTIKEL_NR_HERST[16]; \
         char MEDPROD_ABG_VERORD; \
         short PRODUSERQUOTA; \
         short MEDICALPRODUCT; \
         long DATEOUTOFTRADE; \
         char ARTIKEL_GESPERRT; \
         char IKS_CODE; \
         long BATCHRECALLDATERETURNS; \
         short IMPORTARTICLE; \
         double BTM_FAKTOR; \
         char TFG; \
         char KONTINGENT_PPE; \
         long DATUM_LIEFERBAR_AB; \
         char MEDIZINPRODUKT; \
         short FROZEN; \
         long DATUM_AENDER; \
         char ATC_CODE[26]; \
         char MINISTRYPRODUCTCODE[26]; \
         char HEALTHFUNDCODEHOSPITAL[26]; \
         short CMI_FLAG; \
         char TAXPFL; \



/* Copy-Function Struct to single Data ARTIKELZENTRAL *************************/

 #define ARTIKELZENTRAL_S390_COPY_TO_SINGLE(_x_) \
         ARTIKEL_NR=_x_->ARTIKEL_NR;\
          strcpy(ARTIKEL_MC,_x_->ARTIKEL_MC);\
         PACKGROESSE=_x_->PACKGROESSE;\
          strcpy(DARREICHFORM,_x_->DARREICHFORM);\
          strcpy(NORMPACKUNG,_x_->NORMPACKUNG);\
          strcpy(EINHEIT,_x_->EINHEIT);\
          strcpy(ARTIKEL_NAME,_x_->ARTIKEL_NAME);\
         ETARTKLASSE1=_x_->ETARTKLASSE1;\
         ETARTSCHALTER1=_x_->ETARTSCHALTER1;\
         ETARTSCHALTER2=_x_->ETARTSCHALTER2;\
         ETARTSCHALTER3=_x_->ETARTSCHALTER3;\
         ETARTSCHALTER4=_x_->ETARTSCHALTER4;\
         ETARTSCHALTER5=_x_->ETARTSCHALTER5;\
         HERSTELLER_NR=_x_->HERSTELLER_NR;\
          strcpy(WARENGRUPPE,_x_->WARENGRUPPE);\
          strcpy(THERAPIEGRUPPE,_x_->THERAPIEGRUPPE);\
         LAENGE=_x_->LAENGE;\
         HOEHE=_x_->HOEHE;\
         BREITE=_x_->BREITE;\
         GEWICHT=_x_->GEWICHT;\
         LAUFZEITMONATE=_x_->LAUFZEITMONATE;\
          strcpy(WARENGRUPPEEIGEN,_x_->WARENGRUPPEEIGEN);\
          strcpy(HERSTELLER_CODE,_x_->HERSTELLER_CODE);\
         KZPSYCHOSTOFFE=_x_->KZPSYCHOSTOFFE;\
         TAXLEVEL=_x_->TAXLEVEL;\
         TEXTKEY_HOSPITAL=_x_->TEXTKEY_HOSPITAL;\
         KZRESERVEHOSPITAL=_x_->KZRESERVEHOSPITAL;\
         STD_MENGE=_x_->STD_MENGE;\
         RUNDUNG_STD_MGE=_x_->RUNDUNG_STD_MGE;\
         NICHT_UEBER_DAFUE=_x_->NICHT_UEBER_DAFUE;\
         NICHT_UEBER_XML=_x_->NICHT_UEBER_XML;\
         KZZUSCHLAGSARTIKEL=_x_->KZZUSCHLAGSARTIKEL;\
          strcpy(WIRKSTOFF_NR,_x_->WIRKSTOFF_NR);\
          strcpy(HEALTHFUNDCODE,_x_->HEALTHFUNDCODE);\
         STELLER=_x_->STELLER;\
         POSITIVLISTE=_x_->POSITIVLISTE;\
          strcpy(ABDACODE,_x_->ABDACODE);\
         KONSIG_PARTNER_NR=_x_->KONSIG_PARTNER_NR;\
          strcpy(ARTIKEL_LANGNAME,_x_->ARTIKEL_LANGNAME);\
         PRICE_GROUP=_x_->PRICE_GROUP;\
         SORTIMENT_1=_x_->SORTIMENT_1;\
         SORTIMENT_2=_x_->SORTIMENT_2;\
         SORTIMENT_3=_x_->SORTIMENT_3;\
         SORTIMENT_4=_x_->SORTIMENT_4;\
         SORTIMENT_5=_x_->SORTIMENT_5;\
         DATUM_ANLAGE=_x_->DATUM_ANLAGE;\
         BUSINESSTYPENO=_x_->BUSINESSTYPENO;\
         LISTE_5=_x_->LISTE_5;\
         UPD_FLAG=_x_->UPD_FLAG;\
          strcpy(ARTIKEL_NR_HERST,_x_->ARTIKEL_NR_HERST);\
         MEDPROD_ABG_VERORD=_x_->MEDPROD_ABG_VERORD;\
         PRODUSERQUOTA=_x_->PRODUSERQUOTA;\
         MEDICALPRODUCT=_x_->MEDICALPRODUCT;\
         DATEOUTOFTRADE=_x_->DATEOUTOFTRADE;\
         ARTIKEL_GESPERRT=_x_->ARTIKEL_GESPERRT;\
         IKS_CODE=_x_->IKS_CODE;\
         BATCHRECALLDATERETURNS=_x_->BATCHRECALLDATERETURNS;\
         IMPORTARTICLE=_x_->IMPORTARTICLE;\
         BTM_FAKTOR=_x_->BTM_FAKTOR;\
         TFG=_x_->TFG;\
         KONTINGENT_PPE=_x_->KONTINGENT_PPE;\
         DATUM_LIEFERBAR_AB=_x_->DATUM_LIEFERBAR_AB;\
         MEDIZINPRODUKT=_x_->MEDIZINPRODUKT;\
         FROZEN=_x_->FROZEN;\
         DATUM_AENDER=_x_->DATUM_AENDER;\
          strcpy(ATC_CODE,_x_->ATC_CODE);\
          strcpy(MINISTRYPRODUCTCODE,_x_->MINISTRYPRODUCTCODE);\
          strcpy(HEALTHFUNDCODEHOSPITAL,_x_->HEALTHFUNDCODEHOSPITAL);\
         CMI_FLAG=_x_->CMI_FLAG;\
         TAXPFL=_x_->TAXPFL;\

 #define ARTIKELZENTRAL_S390_COPY_TO_STRUCT(_x_) \
          _x_->ARTIKEL_NR=ARTIKEL_NR;\
          strcpy(_x_->ARTIKEL_MC,ARTIKEL_MC);\
          _x_->PACKGROESSE=PACKGROESSE;\
          strcpy(_x_->DARREICHFORM,DARREICHFORM);\
          strcpy(_x_->NORMPACKUNG,NORMPACKUNG);\
          strcpy(_x_->EINHEIT,EINHEIT);\
          strcpy(_x_->ARTIKEL_NAME,ARTIKEL_NAME);\
          _x_->ETARTKLASSE1=ETARTKLASSE1;\
          _x_->ETARTSCHALTER1=ETARTSCHALTER1;\
          _x_->ETARTSCHALTER2=ETARTSCHALTER2;\
          _x_->ETARTSCHALTER3=ETARTSCHALTER3;\
          _x_->ETARTSCHALTER4=ETARTSCHALTER4;\
          _x_->ETARTSCHALTER5=ETARTSCHALTER5;\
          _x_->HERSTELLER_NR=HERSTELLER_NR;\
          strcpy(_x_->WARENGRUPPE,WARENGRUPPE);\
          strcpy(_x_->THERAPIEGRUPPE,THERAPIEGRUPPE);\
          _x_->LAENGE=LAENGE;\
          _x_->HOEHE=HOEHE;\
          _x_->BREITE=BREITE;\
          _x_->GEWICHT=GEWICHT;\
          _x_->LAUFZEITMONATE=LAUFZEITMONATE;\
          strcpy(_x_->WARENGRUPPEEIGEN,WARENGRUPPEEIGEN);\
          strcpy(_x_->HERSTELLER_CODE,HERSTELLER_CODE);\
          _x_->KZPSYCHOSTOFFE=KZPSYCHOSTOFFE;\
          _x_->TAXLEVEL=TAXLEVEL;\
          _x_->TEXTKEY_HOSPITAL=TEXTKEY_HOSPITAL;\
          _x_->KZRESERVEHOSPITAL=KZRESERVEHOSPITAL;\
          _x_->STD_MENGE=STD_MENGE;\
          _x_->RUNDUNG_STD_MGE=RUNDUNG_STD_MGE;\
          _x_->NICHT_UEBER_DAFUE=NICHT_UEBER_DAFUE;\
          _x_->NICHT_UEBER_XML=NICHT_UEBER_XML;\
          _x_->KZZUSCHLAGSARTIKEL=KZZUSCHLAGSARTIKEL;\
          strcpy(_x_->WIRKSTOFF_NR,WIRKSTOFF_NR);\
          strcpy(_x_->HEALTHFUNDCODE,HEALTHFUNDCODE);\
          _x_->STELLER=STELLER;\
          _x_->POSITIVLISTE=POSITIVLISTE;\
          strcpy(_x_->ABDACODE,ABDACODE);\
          _x_->KONSIG_PARTNER_NR=KONSIG_PARTNER_NR;\
          strcpy(_x_->ARTIKEL_LANGNAME,ARTIKEL_LANGNAME);\
          _x_->PRICE_GROUP=PRICE_GROUP;\
          _x_->SORTIMENT_1=SORTIMENT_1;\
          _x_->SORTIMENT_2=SORTIMENT_2;\
          _x_->SORTIMENT_3=SORTIMENT_3;\
          _x_->SORTIMENT_4=SORTIMENT_4;\
          _x_->SORTIMENT_5=SORTIMENT_5;\
          _x_->DATUM_ANLAGE=DATUM_ANLAGE;\
          _x_->BUSINESSTYPENO=BUSINESSTYPENO;\
          _x_->LISTE_5=LISTE_5;\
          _x_->UPD_FLAG=UPD_FLAG;\
          strcpy(_x_->ARTIKEL_NR_HERST,ARTIKEL_NR_HERST);\
          _x_->MEDPROD_ABG_VERORD=MEDPROD_ABG_VERORD;\
          _x_->PRODUSERQUOTA=PRODUSERQUOTA;\
          _x_->MEDICALPRODUCT=MEDICALPRODUCT;\
          _x_->DATEOUTOFTRADE=DATEOUTOFTRADE;\
          _x_->ARTIKEL_GESPERRT=ARTIKEL_GESPERRT;\
          _x_->IKS_CODE=IKS_CODE;\
          _x_->BATCHRECALLDATERETURNS=BATCHRECALLDATERETURNS;\
          _x_->IMPORTARTICLE=IMPORTARTICLE;\
          _x_->BTM_FAKTOR=BTM_FAKTOR;\
          _x_->TFG=TFG;\
          _x_->KONTINGENT_PPE=KONTINGENT_PPE;\
          _x_->DATUM_LIEFERBAR_AB=DATUM_LIEFERBAR_AB;\
          _x_->MEDIZINPRODUKT=MEDIZINPRODUKT;\
          _x_->FROZEN=FROZEN;\
          _x_->DATUM_AENDER=DATUM_AENDER;\
          strcpy(_x_->ATC_CODE,ATC_CODE);\
          strcpy(_x_->MINISTRYPRODUCTCODE,MINISTRYPRODUCTCODE);\
          strcpy(_x_->HEALTHFUNDCODEHOSPITAL,HEALTHFUNDCODEHOSPITAL);\
          _x_->CMI_FLAG=CMI_FLAG;\
          _x_->TAXPFL=TAXPFL;\



/* FunctionNumber-Define of artikelzentral ************************************/


#ifdef PRZ_OLD_FUNCTION
/* Old-FunctionNumber-Define of artikelzentral ********************************/


#endif

/* C++ Class ******************************************************************/

#ifdef TRANSCLASS

#include<vector>
using namespace std;

/* ppunixc */
#include <sockclient.h>
#include <ppstring.h>
#include <ppgeneric.h>

/* must be implemented */
void FehlerBehandlung(int rc, const char * const error_msg);

#ifndef __VIRTUAL_DADE_CLASS__
#define __VIRTUAL_DADE_CLASS__

class ppDadeVirtual {
public:
    virtual    ~ppDadeVirtual() {};
    virtual int SelList      (int FetchRel = 1, int pos = 0) = 0;
    virtual int SelListHist  (int FetchRel = 1, int pos = 0) = 0;
    virtual int SelListFuture(int FetchRel = 1, int pos = 0) = 0;
    virtual int Load         (int pos = 0                  ) = 0;
    virtual int Delete       (int pos = 0                  ) = 0;
    virtual int Save         (int pos = 0                  ) = 0;
};
#endif

class CARTIKELZENTRAL : public ppDadeVirtual {
public:
    artikelzentralS s;
    int  rc;
    char error_msg[81];
private:
    bool bOpenCursor;
    bool bEndOfSelect;
    int  FncNumber;
    int  CursorPos;
    int  AnzPos;
    vector<artikelzentralS> lst; // class list

public:
    unsigned int GetSize() const { return static_cast<unsigned int>(lst.size()); };
    void         ClearStruct() { s.clear(); }
    bool         SetData(unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     s = lst.at(i);
                     return true;
                 }
    bool         SetList(const unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     vector< artikelzentralS >::iterator it = lst.begin() + i;
                     *it = s;
                     return true;
                 }
    bool         InsList() {
                     Strip(s);
                     artikelzentralS c = s;
                     lst.insert(lst.end(), c);
                     AnzPos++;
                     return true;
                 }
    bool         DelList(const unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     vector< artikelzentralS >::iterator it = lst.begin() + i;
                     if (it != lst.end())
                         lst.erase(it);
                     if (--AnzPos < 0)
                         AnzPos = 0;
                     return true;
                 }

    vector<artikelzentralS>::iterator
                 beginList() { return lst.begin(); }
    vector<artikelzentralS>::iterator
                 endList  () { return lst.end  (); }

    long         GetArtikel_nr() const { return s.ARTIKEL_NR; }
    const char*  GetArtikel_mc(ppString & t) const { t = s.ARTIKEL_MC; t.erasespace(ppString::END); return t.c_str(); }
    long         GetPackgroesse() const { return s.PACKGROESSE; }
    const char*  GetDarreichform(ppString & t) const { t = s.DARREICHFORM; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetNormpackung(ppString & t) const { t = s.NORMPACKUNG; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetEinheit(ppString & t) const { t = s.EINHEIT; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetArtikel_name(ppString & t) const { t = s.ARTIKEL_NAME; t.erasespace(ppString::END); return t.c_str(); }
    long         GetEtartklasse1() const { return s.ETARTKLASSE1; }
    long         GetEtartschalter1() const { return s.ETARTSCHALTER1; }
    long         GetEtartschalter2() const { return s.ETARTSCHALTER2; }
    long         GetEtartschalter3() const { return s.ETARTSCHALTER3; }
    long         GetEtartschalter4() const { return s.ETARTSCHALTER4; }
    long         GetEtartschalter5() const { return s.ETARTSCHALTER5; }
    long         GetHersteller_nr() const { return s.HERSTELLER_NR; }
    const char*  GetWarengruppe(ppString & t) const { t = s.WARENGRUPPE; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetTherapiegruppe(ppString & t) const { t = s.THERAPIEGRUPPE; t.erasespace(ppString::END); return t.c_str(); }
    long         GetLaenge() const { return s.LAENGE; }
    long         GetHoehe() const { return s.HOEHE; }
    long         GetBreite() const { return s.BREITE; }
    long         GetGewicht() const { return s.GEWICHT; }
    long         GetLaufzeitmonate() const { return s.LAUFZEITMONATE; }
    const char*  GetWarengruppeeigen(ppString & t) const { t = s.WARENGRUPPEEIGEN; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetHersteller_code(ppString & t) const { t = s.HERSTELLER_CODE; t.erasespace(ppString::END); return t.c_str(); }
    char         GetKzpsychostoffe() const { return s.KZPSYCHOSTOFFE[0]; }
    short        GetTaxlevel() const { return s.TAXLEVEL; }
    short        GetTextkey_hospital() const { return s.TEXTKEY_HOSPITAL; }
    char         GetKzreservehospital() const { return s.KZRESERVEHOSPITAL[0]; }
    short        GetStd_menge() const { return s.STD_MENGE; }
    char         GetRundung_std_mge() const { return s.RUNDUNG_STD_MGE[0]; }
    char         GetNicht_ueber_dafue() const { return s.NICHT_UEBER_DAFUE[0]; }
    char         GetNicht_ueber_xml() const { return s.NICHT_UEBER_XML[0]; }
    char         GetKzzuschlagsartikel() const { return s.KZZUSCHLAGSARTIKEL[0]; }
    const char*  GetWirkstoff_nr(ppString & t) const { t = s.WIRKSTOFF_NR; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetHealthfundcode(ppString & t) const { t = s.HEALTHFUNDCODE; t.erasespace(ppString::END); return t.c_str(); }
    char         GetSteller() const { return s.STELLER[0]; }
    char         GetPositivliste() const { return s.POSITIVLISTE[0]; }
    const char*  GetAbdacode(ppString & t) const { t = s.ABDACODE; t.erasespace(ppString::END); return t.c_str(); }
    long         GetKonsig_partner_nr() const { return s.KONSIG_PARTNER_NR; }
    const char*  GetArtikel_langname(ppString & t) const { t = s.ARTIKEL_LANGNAME; t.erasespace(ppString::END); return t.c_str(); }
    short        GetPrice_group() const { return s.PRICE_GROUP; }
    char         GetSortiment_1() const { return s.SORTIMENT_1[0]; }
    char         GetSortiment_2() const { return s.SORTIMENT_2[0]; }
    char         GetSortiment_3() const { return s.SORTIMENT_3[0]; }
    char         GetSortiment_4() const { return s.SORTIMENT_4[0]; }
    char         GetSortiment_5() const { return s.SORTIMENT_5[0]; }
    long         GetDatum_anlage() const { return s.DATUM_ANLAGE; }
    short        GetBusinesstypeno() const { return s.BUSINESSTYPENO; }
    short        GetListe_5() const { return s.LISTE_5; }
    char         GetUpd_flag() const { return s.UPD_FLAG[0]; }
    const char*  GetArtikel_nr_herst(ppString & t) const { t = s.ARTIKEL_NR_HERST; t.erasespace(ppString::END); return t.c_str(); }
    char         GetMedprod_abg_verord() const { return s.MEDPROD_ABG_VERORD[0]; }
    short        GetProduserquota() const { return s.PRODUSERQUOTA; }
    short        GetMedicalproduct() const { return s.MEDICALPRODUCT; }
    long         GetDateoutoftrade() const { return s.DATEOUTOFTRADE; }
    char         GetArtikel_gesperrt() const { return s.ARTIKEL_GESPERRT[0]; }
    char         GetIks_code() const { return s.IKS_CODE[0]; }
    long         GetBatchrecalldatereturns() const { return s.BATCHRECALLDATERETURNS; }
    short        GetImportarticle() const { return s.IMPORTARTICLE; }
    double       GetBtm_faktor() const { return s.BTM_FAKTOR; }
    char         GetTfg() const { return s.TFG[0]; }
    char         GetKontingent_ppe() const { return s.KONTINGENT_PPE[0]; }
    long         GetDatum_lieferbar_ab() const { return s.DATUM_LIEFERBAR_AB; }
    char         GetMedizinprodukt() const { return s.MEDIZINPRODUKT[0]; }
    short        GetFrozen() const { return s.FROZEN; }
    long         GetDatum_aender() const { return s.DATUM_AENDER; }
    const char*  GetAtc_code(ppString & t) const { t = s.ATC_CODE; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetMinistryproductcode(ppString & t) const { t = s.MINISTRYPRODUCTCODE; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetHealthfundcodehospital(ppString & t) const { t = s.HEALTHFUNDCODEHOSPITAL; t.erasespace(ppString::END); return t.c_str(); }
    short        GetCmi_flag() const { return s.CMI_FLAG; }
    char         GetTaxpfl() const { return s.TAXPFL[0]; }

    const artikelzentralS &
                 GetStruct() const { return s; }
    void         SetArtikel_nr(long t) { s.ARTIKEL_NR = t; }
    void         SetArtikel_mc(const ppString & t) { ppGStrCopy(s.ARTIKEL_MC, t.c_str(), L_ARTIKELZENTRAL_ARTIKEL_MC); }
    void         SetPackgroesse(long t) { s.PACKGROESSE = t; }
    void         SetDarreichform(const ppString & t) { ppGStrCopy(s.DARREICHFORM, t.c_str(), L_ARTIKELZENTRAL_DARREICHFORM); }
    void         SetNormpackung(const ppString & t) { ppGStrCopy(s.NORMPACKUNG, t.c_str(), L_ARTIKELZENTRAL_NORMPACKUNG); }
    void         SetEinheit(const ppString & t) { ppGStrCopy(s.EINHEIT, t.c_str(), L_ARTIKELZENTRAL_EINHEIT); }
    void         SetArtikel_name(const ppString & t) { ppGStrCopy(s.ARTIKEL_NAME, t.c_str(), L_ARTIKELZENTRAL_ARTIKEL_NAME); }
    void         SetEtartklasse1(long t) { s.ETARTKLASSE1 = t; }
    void         SetEtartschalter1(long t) { s.ETARTSCHALTER1 = t; }
    void         SetEtartschalter2(long t) { s.ETARTSCHALTER2 = t; }
    void         SetEtartschalter3(long t) { s.ETARTSCHALTER3 = t; }
    void         SetEtartschalter4(long t) { s.ETARTSCHALTER4 = t; }
    void         SetEtartschalter5(long t) { s.ETARTSCHALTER5 = t; }
    void         SetHersteller_nr(long t) { s.HERSTELLER_NR = t; }
    void         SetWarengruppe(const ppString & t) { ppGStrCopy(s.WARENGRUPPE, t.c_str(), L_ARTIKELZENTRAL_WARENGRUPPE); }
    void         SetTherapiegruppe(const ppString & t) { ppGStrCopy(s.THERAPIEGRUPPE, t.c_str(), L_ARTIKELZENTRAL_THERAPIEGRUPPE); }
    void         SetLaenge(long t) { s.LAENGE = t; }
    void         SetHoehe(long t) { s.HOEHE = t; }
    void         SetBreite(long t) { s.BREITE = t; }
    void         SetGewicht(long t) { s.GEWICHT = t; }
    void         SetLaufzeitmonate(long t) { s.LAUFZEITMONATE = t; }
    void         SetWarengruppeeigen(const ppString & t) { ppGStrCopy(s.WARENGRUPPEEIGEN, t.c_str(), L_ARTIKELZENTRAL_WARENGRUPPEEIGEN); }
    void         SetHersteller_code(const ppString & t) { ppGStrCopy(s.HERSTELLER_CODE, t.c_str(), L_ARTIKELZENTRAL_HERSTELLER_CODE); }
    void         SetKzpsychostoffe(char t) { s.KZPSYCHOSTOFFE[0] = t; s.KZPSYCHOSTOFFE[1] = '\0';}
    void         SetTaxlevel(short t) { s.TAXLEVEL = t; }
    void         SetTextkey_hospital(short t) { s.TEXTKEY_HOSPITAL = t; }
    void         SetKzreservehospital(char t) { s.KZRESERVEHOSPITAL[0] = t; s.KZRESERVEHOSPITAL[1] = '\0';}
    void         SetStd_menge(short t) { s.STD_MENGE = t; }
    void         SetRundung_std_mge(char t) { s.RUNDUNG_STD_MGE[0] = t; s.RUNDUNG_STD_MGE[1] = '\0';}
    void         SetNicht_ueber_dafue(char t) { s.NICHT_UEBER_DAFUE[0] = t; s.NICHT_UEBER_DAFUE[1] = '\0';}
    void         SetNicht_ueber_xml(char t) { s.NICHT_UEBER_XML[0] = t; s.NICHT_UEBER_XML[1] = '\0';}
    void         SetKzzuschlagsartikel(char t) { s.KZZUSCHLAGSARTIKEL[0] = t; s.KZZUSCHLAGSARTIKEL[1] = '\0';}
    void         SetWirkstoff_nr(const ppString & t) { ppGStrCopy(s.WIRKSTOFF_NR, t.c_str(), L_ARTIKELZENTRAL_WIRKSTOFF_NR); }
    void         SetHealthfundcode(const ppString & t) { ppGStrCopy(s.HEALTHFUNDCODE, t.c_str(), L_ARTIKELZENTRAL_HEALTHFUNDCODE); }
    void         SetSteller(char t) { s.STELLER[0] = t; s.STELLER[1] = '\0';}
    void         SetPositivliste(char t) { s.POSITIVLISTE[0] = t; s.POSITIVLISTE[1] = '\0';}
    void         SetAbdacode(const ppString & t) { ppGStrCopy(s.ABDACODE, t.c_str(), L_ARTIKELZENTRAL_ABDACODE); }
    void         SetKonsig_partner_nr(long t) { s.KONSIG_PARTNER_NR = t; }
    void         SetArtikel_langname(const ppString & t) { ppGStrCopy(s.ARTIKEL_LANGNAME, t.c_str(), L_ARTIKELZENTRAL_ARTIKEL_LANGNAME); }
    void         SetPrice_group(short t) { s.PRICE_GROUP = t; }
    void         SetSortiment_1(char t) { s.SORTIMENT_1[0] = t; s.SORTIMENT_1[1] = '\0';}
    void         SetSortiment_2(char t) { s.SORTIMENT_2[0] = t; s.SORTIMENT_2[1] = '\0';}
    void         SetSortiment_3(char t) { s.SORTIMENT_3[0] = t; s.SORTIMENT_3[1] = '\0';}
    void         SetSortiment_4(char t) { s.SORTIMENT_4[0] = t; s.SORTIMENT_4[1] = '\0';}
    void         SetSortiment_5(char t) { s.SORTIMENT_5[0] = t; s.SORTIMENT_5[1] = '\0';}
    void         SetDatum_anlage(long t) { s.DATUM_ANLAGE = t; }
    void         SetBusinesstypeno(short t) { s.BUSINESSTYPENO = t; }
    void         SetListe_5(short t) { s.LISTE_5 = t; }
    void         SetUpd_flag(char t) { s.UPD_FLAG[0] = t; s.UPD_FLAG[1] = '\0';}
    void         SetArtikel_nr_herst(const ppString & t) { ppGStrCopy(s.ARTIKEL_NR_HERST, t.c_str(), L_ARTIKELZENTRAL_ARTIKEL_NR_HERST); }
    void         SetMedprod_abg_verord(char t) { s.MEDPROD_ABG_VERORD[0] = t; s.MEDPROD_ABG_VERORD[1] = '\0';}
    void         SetProduserquota(short t) { s.PRODUSERQUOTA = t; }
    void         SetMedicalproduct(short t) { s.MEDICALPRODUCT = t; }
    void         SetDateoutoftrade(long t) { s.DATEOUTOFTRADE = t; }
    void         SetArtikel_gesperrt(char t) { s.ARTIKEL_GESPERRT[0] = t; s.ARTIKEL_GESPERRT[1] = '\0';}
    void         SetIks_code(char t) { s.IKS_CODE[0] = t; s.IKS_CODE[1] = '\0';}
    void         SetBatchrecalldatereturns(long t) { s.BATCHRECALLDATERETURNS = t; }
    void         SetImportarticle(short t) { s.IMPORTARTICLE = t; }
    void         SetBtm_faktor(double t) { s.BTM_FAKTOR = t; }
    void         SetTfg(char t) { s.TFG[0] = t; s.TFG[1] = '\0';}
    void         SetKontingent_ppe(char t) { s.KONTINGENT_PPE[0] = t; s.KONTINGENT_PPE[1] = '\0';}
    void         SetDatum_lieferbar_ab(long t) { s.DATUM_LIEFERBAR_AB = t; }
    void         SetMedizinprodukt(char t) { s.MEDIZINPRODUKT[0] = t; s.MEDIZINPRODUKT[1] = '\0';}
    void         SetFrozen(short t) { s.FROZEN = t; }
    void         SetDatum_aender(long t) { s.DATUM_AENDER = t; }
    void         SetAtc_code(const ppString & t) { ppGStrCopy(s.ATC_CODE, t.c_str(), L_ARTIKELZENTRAL_ATC_CODE); }
    void         SetMinistryproductcode(const ppString & t) { ppGStrCopy(s.MINISTRYPRODUCTCODE, t.c_str(), L_ARTIKELZENTRAL_MINISTRYPRODUCTCODE); }
    void         SetHealthfundcodehospital(const ppString & t) { ppGStrCopy(s.HEALTHFUNDCODEHOSPITAL, t.c_str(), L_ARTIKELZENTRAL_HEALTHFUNDCODEHOSPITAL); }
    void         SetCmi_flag(short t) { s.CMI_FLAG = t; }
    void         SetTaxpfl(char t) { s.TAXPFL[0] = t; s.TAXPFL[1] = '\0';}

    void         SetStruct(const artikelzentralS & t) { s = t; }


    // virtual functions
public:
    int          Load(int pos = 0) { pos = pos; return 1; }
    int          Save(int pos = 0) { pos = pos; return 1; }
    int          Delete(int pos = 0) { pos = pos; return 1; }
    int          SelList(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }
    int          SelListHist(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }
    int          SelListFuture(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }

    // constructor
    CARTIKELZENTRAL() {
        ::buf_default((void *)&s, ARTIKELZENTRAL_BES, ARTIKELZENTRAL_ANZ);
        bOpenCursor   = false;
        bEndOfSelect  = false;
        FncNumber     = 0;
        CursorPos     = 0;
        AnzPos        = 0;
        rc            = 0;
        s.clear();
    }

    // destructor
    virtual ~CARTIKELZENTRAL() {
    }

    // buffer init
    void buf_default() {
        ::buf_default((void *)&s, ARTIKELZENTRAL_BES, ARTIKELZENTRAL_ANZ);
    }

    // socket server call
    int Server(int fkt_nr, int pos = 0) {
    #ifdef WIN32
        rc = ::ServerNr(pos, fkt_nr, (void *)&s, ARTIKELZENTRAL_BES, (int)ARTIKELZENTRAL_ANZ, error_msg);
    #else
        rc = ::Server(fkt_nr, (void *)&s, ARTIKELZENTRAL_BES, (int)ARTIKELZENTRAL_ANZ, error_msg);
    #endif
        if (rc < 0)
            FehlerBehandlung( rc, error_msg );
        return rc;
    }

private:
    void Strip(N_ARTIKELZENTRAL & d) {
        d = d;
    #ifdef WIN32
        ppGStripLast(d.ARTIKEL_MC);
        ppGStripLast(d.DARREICHFORM);
        ppGStripLast(d.NORMPACKUNG);
        ppGStripLast(d.EINHEIT);
        ppGStripLast(d.ARTIKEL_NAME);
        ppGStripLast(d.WARENGRUPPE);
        ppGStripLast(d.THERAPIEGRUPPE);
        ppGStripLast(d.WARENGRUPPEEIGEN);
        ppGStripLast(d.HERSTELLER_CODE);
        ppGStripLast(d.WIRKSTOFF_NR);
        ppGStripLast(d.HEALTHFUNDCODE);
        ppGStripLast(d.ABDACODE);
        ppGStripLast(d.ARTIKEL_LANGNAME);
        ppGStripLast(d.ARTIKEL_NR_HERST);
        ppGStripLast(d.ATC_CODE);
        ppGStripLast(d.MINISTRYPRODUCTCODE);
        ppGStripLast(d.HEALTHFUNDCODEHOSPITAL);
    #endif
    }

    int UniqueServerCall(int FncNr, int pos = 0) {
    #ifndef __DADE_LOAD__
       rc = ::ServerNr(pos, FncNr, (void *)&s, ARTIKELZENTRAL_BES, (int)ARTIKELZENTRAL_ANZ, error_msg);
    #else
       pos = pos;
       rc = DistributorFunSelect(FncNr, (void *)&s, error_msg, &rc);
    #endif
       if (rc < 0)
           FehlerBehandlung( rc, error_msg );
       return rc;
    }
};
#endif    // TRANSCLASS
/* CreateSqlStatement of ARTIKELZENTRAL ***************************************/

 #define ARTIKELZENTRAL_CREATE(x) EXEC SQL create table x (\
         ARTIKEL_NR integer default 0 not null,\
         ARTIKEL_MC char(12) default " " not null,\
         PACKGROESSE integer default 0 not null,\
         DARREICHFORM char(3) default " " not null,\
         NORMPACKUNG char(2) default " " not null,\
         EINHEIT char(9) default " " not null,\
         ARTIKEL_NAME char(30) default " " not null,\
         ETARTKLASSE1 integer default 0 not null,\
         ETARTSCHALTER1 integer default 0 not null,\
         ETARTSCHALTER2 integer default 0 not null,\
         ETARTSCHALTER3 integer default 0 not null,\
         ETARTSCHALTER4 integer default 0 not null,\
         ETARTSCHALTER5 integer default 0 not null,\
         HERSTELLER_NR integer default 0 not null,\
         WARENGRUPPE char(5) default " " not null,\
         THERAPIEGRUPPE char(5) default " " not null,\
         LAENGE integer default 0 not null,\
         HOEHE integer default 0 not null,\
         BREITE integer default 0 not null,\
         GEWICHT integer default 0 not null,\
         LAUFZEITMONATE integer default 0 not null,\
         WARENGRUPPEEIGEN char(5) default " " not null,\
         HERSTELLER_CODE char(5) default " " not null,\
         KZPSYCHOSTOFFE char(1) default " " not null,\
         TAXLEVEL smallint default 0 not null,\
         TEXTKEY_HOSPITAL smallint default 0 not null,\
         KZRESERVEHOSPITAL char(1) default " " not null,\
         STD_MENGE smallint default 0 not null,\
         RUNDUNG_STD_MGE char(1) default " " not null,\
         NICHT_UEBER_DAFUE char(1) default " " not null,\
         NICHT_UEBER_XML char(1) default " " not null,\
         KZZUSCHLAGSARTIKEL char(1) default " " not null,\
         WIRKSTOFF_NR char(3) default " " not null,\
         HEALTHFUNDCODE char(5) default " " not null,\
         STELLER char(1) default " " not null,\
         POSITIVLISTE char(1) default " " not null,\
         ABDACODE char(5) default " " not null,\
         KONSIG_PARTNER_NR integer default 0 not null,\
         ARTIKEL_LANGNAME char(50) default " " not null,\
         PRICE_GROUP smallint default 0 not null,\
         SORTIMENT_1 char(1) default " " not null,\
         SORTIMENT_2 char(1) default " " not null,\
         SORTIMENT_3 char(1) default " " not null,\
         SORTIMENT_4 char(1) default " " not null,\
         SORTIMENT_5 char(1) default " " not null,\
         DATUM_ANLAGE integer default 0 not null,\
         BUSINESSTYPENO smallint default 0 not null,\
         LISTE_5 smallint default 0 not null,\
         UPD_FLAG char(1) default " " not null,\
         ARTIKEL_NR_HERST char(15) default " " not null,\
         MEDPROD_ABG_VERORD char(1) default " " not null,\
         PRODUSERQUOTA smallint default 0 not null,\
         MEDICALPRODUCT smallint default 0 not null,\
         DATEOUTOFTRADE integer default 0 not null,\
         ARTIKEL_GESPERRT char(1) default " " not null,\
         IKS_CODE char(1) default " " not null,\
         BATCHRECALLDATERETURNS integer default 0 not null,\
         IMPORTARTICLE smallint default 0 not null,\
         BTM_FAKTOR decimal(8,3) default 0 not null,\
         TFG char(1) default " " not null,\
         KONTINGENT_PPE char(1) default " " not null,\
         DATUM_LIEFERBAR_AB integer default 0 not null,\
         MEDIZINPRODUKT char(1) default " " not null,\
         FROZEN smallint default 0 not null,\
         DATUM_AENDER integer default 0 not null,\
         ATC_CODE varchar(25,0) default " " not null,\
         MINISTRYPRODUCTCODE varchar(25,0) default " " not null,\
         HEALTHFUNDCODEHOSPITAL varchar(25,0) default " " not null,\
         CMI_FLAG smallint default 0 not null,\
         TAXPFL char(1) default " " not null) in KscOrder extent size 3920 next size 392 lock mode row;



/* CreateIndexStatement of ARTIKELZENTRAL *************************************/

 #define ARTIKELZENTRAL_CREATE_INDEX(_X_,_Y_)\
              _Y_ = 0;\
         EXEC SQL create unique index i_artikelzentral_1 on _X_(\
              artikel_nr ) in KscOrderIdx;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_artikelzentral_2 on _X_(\
              artikel_mc ) in KscOrderIdx;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_artikelzentral_3 on _X_(\
              hersteller_code ) in KscOrderIdx;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_artikelzentral_4 on _X_(\
              wirkstoff_nr ) in KscOrderIdx;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_artikelzentral_5 on _X_(\
              artikel_nr_herst ) in KscOrderIdx;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\


/* DeleteIndexStatement of ARTIKELZENTRAL *************************************/

 #define ARTIKELZENTRAL_DELETE_INDEX(_X_)\
              _X_ = 0;\
         EXEC SQL drop index i_artikelzentral_1;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_artikelzentral_2;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_artikelzentral_3;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_artikelzentral_4;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_artikelzentral_5;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\




#endif   // GUARD
