#ifndef __PP_TAUFTRAG_H_
#define __PP_TAUFTRAG_H_

/******************************************************************************/
/* d:\kdauftrag ***************************************************************/
/* produced by DADE 6.21.4 ****************************************************/
/******************************************************************************/

/* ppunixc */
#if defined (BUF_DESC) || defined (C_BUF_DESC)
#include <bufkon.h>
#endif

/* Length-Define of KDAUFTRAG *************************************************/

#define L_KDAUFTRAG_KDAUFTRAGNR 11
#define L_KDAUFTRAG_KDAUFTRAGSTAT 16
#define L_KDAUFTRAG_IDFNR 11
#define L_KDAUFTRAG_GERAETNAME 8
#define L_KDAUFTRAG_TOURID 6
#define L_KDAUFTRAG_TOURIDALT 6
#define L_KDAUFTRAG_PERSONALNR 11
#define L_KDAUFTRAG_MATCHCODE 12
#define L_KDAUFTRAG_RECHNUNGNR 11
#define L_KDAUFTRAG_FILIALNR 6
#define L_KDAUFTRAG_ETAUFTRAGSCHALTER1 5
#define L_KDAUFTRAG_ETAUFTRAGSCHALTER2 5
#define L_KDAUFTRAG_ETAUFTRAGSCHALTER3 5
#define L_KDAUFTRAG_ETAUFTRAGSCHALTER4 5
#define L_KDAUFTRAG_KDAUFTRAGART 2
#define L_KDAUFTRAG_KOART 1
#define L_KDAUFTRAG_BUCHART 1
#define L_KDAUFTRAG_DATUMVALUTA 11
#define L_KDAUFTRAG_WERTAUFTRAG 11
#define N_KDAUFTRAG_WERTAUFTRAG 2
#define L_KDAUFTRAG_WERTLIEFERUNG 11
#define N_KDAUFTRAG_WERTLIEFERUNG 2
#define L_KDAUFTRAG_WERTZEILEN 11
#define N_KDAUFTRAG_WERTZEILEN 2
#define L_KDAUFTRAG_ANZPOS 11
#define L_KDAUFTRAG_ANZPOSOB 11
#define L_KDAUFTRAG_ANZPOSLETZTE 11
#define L_KDAUFTRAG_ANZPOSDAFUE 11
#define L_KDAUFTRAG_ANZPOSDAFUEFEHLER 11
#define L_KDAUFTRAG_ANZALPHATEXT 11
#define L_KDAUFTRAG_ANZBTM 11
#define L_KDAUFTRAG_ANZCONTAINER 11
#define L_KDAUFTRAG_ANZBEHAELTWECHSEL 11
#define L_KDAUFTRAG_ANZBEHAELT 11
#define L_KDAUFTRAG_ANZSONDERWANNE 11
#define L_KDAUFTRAG_BEHAELTERGEWICHT 11
#define L_KDAUFTRAG_RABATTBARPROZ 5
#define N_KDAUFTRAG_RABATTBARPROZ 2
#define L_KDAUFTRAG_ZEITENDEAM 11
#define L_KDAUFTRAG_ZEITENDEPM 11
#define L_KDAUFTRAG_LAGERNRRECHNUNG 1
#define L_KDAUFTRAG_AUFTRAGNRKO 11
#define L_KDAUFTRAG_DMOBILPLATZNR 11
#define L_KDAUFTRAG_SKDDEFEKTABSAGEN 1
#define L_KDAUFTRAG_DRUCKPOSITION 11
#define L_KDAUFTRAG_BATCHSCHREIBEN 11
#define L_KDAUFTRAG_BEMERKUNGEN 240
#define L_KDAUFTRAG_KUNDETEXT 240
#define L_KDAUFTRAG_HERKUNFTFILIALE 6
#define L_KDAUFTRAG_NAECHSTETOUR 6
#define L_KDAUFTRAG_LETZTETOUR 6
#define L_KDAUFTRAG_DAFUEAUFTRAGNR 11
#define L_KDAUFTRAG_DAFUEGERAETENAME 2
#define L_KDAUFTRAG_VERTRIEBSZENTRUMNR 6
#define L_KDAUFTRAG_KUNDENNR 11
#define L_KDAUFTRAG_KDAUFTRAGNRFILIALE 11
#define L_KDAUFTRAG_SENDESTATUS 6
#define L_KDAUFTRAG_POOLTYP 6
#define L_KDAUFTRAG_POOLNR 6
#define L_KDAUFTRAG_ZUGRUND 16
#define L_KDAUFTRAG_DATUMAUSLIEFERUNG 11
#define L_KDAUFTRAG_KDAUFTRAGNRORG 11
#define L_KDAUFTRAG_DATUMORG 11
#define L_KDAUFTRAG_KZRESTORED 1
#define L_KDAUFTRAG_BATCHAUFTRAGNR 11
#define L_KDAUFTRAG_SUB_ORDER_TYPE 3
#define L_KDAUFTRAG_PAYMENT_TERM 4
#define L_KDAUFTRAG_ANZAUF 6
#define L_KDAUFTRAG_DATUMVALUTABATCH 11
#define L_KDAUFTRAG_VALUTAMONAUTO 6
#define L_KDAUFTRAG_VALUTAMONMANUELL 6
#define L_KDAUFTRAG_TENDERNO 11
#define L_KDAUFTRAG_DATUMVERSAND 11
#define L_KDAUFTRAG_DATUMBTM 11
#define L_KDAUFTRAG_BTMFORMULARNR 10
#define L_KDAUFTRAG_WERTNETTO 11
#define N_KDAUFTRAG_WERTNETTO 2
#define L_KDAUFTRAG_WERTRABATT 11
#define N_KDAUFTRAG_WERTRABATT 2
#define L_KDAUFTRAG_INVOICENUMBER 15
#define L_KDAUFTRAG_PAYMENTDATE 11
#define L_KDAUFTRAG_PAYMENTTYPE 1
#define L_KDAUFTRAG_ETAUFTRAGSCHALTER5 5
#define L_KDAUFTRAG_ETAUFTRAGSCHALTER6 5
#define L_KDAUFTRAG_DRIVERID 11
#define L_KDAUFTRAG_XMLREFERENCENO 9
#define L_KDAUFTRAG_LOGISTICVOLUME 11
#define L_KDAUFTRAG_ORDERLABEL 40
#define L_KDAUFTRAG_DPODAYS 6
#define L_KDAUFTRAG_ORDERPERIODID 11

/* Length/Count-Define of KDAUFTRAG *******************************************/

#define LS_KDAUFTRAG_KDAUFTRAGNR 10 + 1
#define LS_KDAUFTRAG_KDAUFTRAGSTAT 16 + 1
#define LS_KDAUFTRAG_IDFNR 10 + 1
#define LS_KDAUFTRAG_GERAETNAME 8 + 1
#define LS_KDAUFTRAG_TOURID 6 + 1
#define LS_KDAUFTRAG_TOURIDALT 6 + 1
#define LS_KDAUFTRAG_PERSONALNR 10 + 1
#define LS_KDAUFTRAG_MATCHCODE 12 + 1
#define LS_KDAUFTRAG_RECHNUNGNR 10 + 1
#define LS_KDAUFTRAG_FILIALNR 5 + 1
#define LS_KDAUFTRAG_ETAUFTRAGSCHALTER1 5 + 1
#define LS_KDAUFTRAG_ETAUFTRAGSCHALTER2 5 + 1
#define LS_KDAUFTRAG_ETAUFTRAGSCHALTER3 5 + 1
#define LS_KDAUFTRAG_ETAUFTRAGSCHALTER4 5 + 1
#define LS_KDAUFTRAG_KDAUFTRAGART 2 + 1
#define LS_KDAUFTRAG_KOART 1 + 1
#define LS_KDAUFTRAG_BUCHART 1 + 1
#define LS_KDAUFTRAG_DATUMVALUTA 10 + 1
#define LS_KDAUFTRAG_WERTAUFTRAG 11 + 2
#define LS_KDAUFTRAG_WERTLIEFERUNG 11 + 2
#define LS_KDAUFTRAG_WERTZEILEN 11 + 2
#define LS_KDAUFTRAG_ANZPOS 10 + 1
#define LS_KDAUFTRAG_ANZPOSOB 10 + 1
#define LS_KDAUFTRAG_ANZPOSLETZTE 10 + 1
#define LS_KDAUFTRAG_ANZPOSDAFUE 10 + 1
#define LS_KDAUFTRAG_ANZPOSDAFUEFEHLER 10 + 1
#define LS_KDAUFTRAG_ANZALPHATEXT 10 + 1
#define LS_KDAUFTRAG_ANZBTM 10 + 1
#define LS_KDAUFTRAG_ANZCONTAINER 10 + 1
#define LS_KDAUFTRAG_ANZBEHAELTWECHSEL 10 + 1
#define LS_KDAUFTRAG_ANZBEHAELT 10 + 1
#define LS_KDAUFTRAG_ANZSONDERWANNE 10 + 1
#define LS_KDAUFTRAG_BEHAELTERGEWICHT 10 + 1
#define LS_KDAUFTRAG_RABATTBARPROZ 5 + 2
#define LS_KDAUFTRAG_ZEITENDEAM 10 + 1
#define LS_KDAUFTRAG_ZEITENDEPM 10 + 1
#define LS_KDAUFTRAG_LAGERNRRECHNUNG 1 + 1
#define LS_KDAUFTRAG_AUFTRAGNRKO 10 + 1
#define LS_KDAUFTRAG_DMOBILPLATZNR 10 + 1
#define LS_KDAUFTRAG_SKDDEFEKTABSAGEN 1 + 1
#define LS_KDAUFTRAG_DRUCKPOSITION 10 + 1
#define LS_KDAUFTRAG_BATCHSCHREIBEN 10 + 1
#define LS_KDAUFTRAG_BEMERKUNGEN 240 + 1
#define LS_KDAUFTRAG_KUNDETEXT 240 + 1
#define LS_KDAUFTRAG_HERKUNFTFILIALE 5 + 1
#define LS_KDAUFTRAG_NAECHSTETOUR 6 + 1
#define LS_KDAUFTRAG_LETZTETOUR 6 + 1
#define LS_KDAUFTRAG_DAFUEAUFTRAGNR 10 + 1
#define LS_KDAUFTRAG_DAFUEGERAETENAME 2 + 1
#define LS_KDAUFTRAG_VERTRIEBSZENTRUMNR 5 + 1
#define LS_KDAUFTRAG_KUNDENNR 10 + 1
#define LS_KDAUFTRAG_KDAUFTRAGNRFILIALE 10 + 1
#define LS_KDAUFTRAG_SENDESTATUS 5 + 1
#define LS_KDAUFTRAG_POOLTYP 5 + 1
#define LS_KDAUFTRAG_POOLNR 5 + 1
#define LS_KDAUFTRAG_ZUGRUND 16 + 1
#define LS_KDAUFTRAG_DATUMAUSLIEFERUNG 10 + 1
#define LS_KDAUFTRAG_KDAUFTRAGNRORG 10 + 1
#define LS_KDAUFTRAG_DATUMORG 10 + 1
#define LS_KDAUFTRAG_KZRESTORED 1 + 1
#define LS_KDAUFTRAG_BATCHAUFTRAGNR 10 + 1
#define LS_KDAUFTRAG_SUB_ORDER_TYPE 3 + 1
#define LS_KDAUFTRAG_PAYMENT_TERM 4 + 1
#define LS_KDAUFTRAG_ANZAUF 5 + 1
#define LS_KDAUFTRAG_DATUMVALUTABATCH 10 + 1
#define LS_KDAUFTRAG_VALUTAMONAUTO 5 + 1
#define LS_KDAUFTRAG_VALUTAMONMANUELL 5 + 1
#define LS_KDAUFTRAG_TENDERNO 10 + 1
#define LS_KDAUFTRAG_DATUMVERSAND 10 + 1
#define LS_KDAUFTRAG_DATUMBTM 10 + 1
#define LS_KDAUFTRAG_BTMFORMULARNR 10 + 1
#define LS_KDAUFTRAG_WERTNETTO 11 + 2
#define LS_KDAUFTRAG_WERTRABATT 11 + 2
#define LS_KDAUFTRAG_INVOICENUMBER 15 + 1
#define LS_KDAUFTRAG_PAYMENTDATE 10 + 1
#define LS_KDAUFTRAG_PAYMENTTYPE 1 + 1
#define LS_KDAUFTRAG_ETAUFTRAGSCHALTER5 5 + 1
#define LS_KDAUFTRAG_ETAUFTRAGSCHALTER6 5 + 1
#define LS_KDAUFTRAG_DRIVERID 10 + 1
#define LS_KDAUFTRAG_XMLREFERENCENO 9 + 1
#define LS_KDAUFTRAG_LOGISTICVOLUME 10 + 1
#define LS_KDAUFTRAG_ORDERLABEL 40 + 1
#define LS_KDAUFTRAG_DPODAYS 5 + 1
#define LS_KDAUFTRAG_ORDERPERIODID 10 + 1

#define KDAUFTRAGKDAUFTRAGNR 0
#define KDAUFTRAGKDAUFTRAGSTAT 1
#define KDAUFTRAGIDFNR 2
#define KDAUFTRAGGERAETNAME 3
#define KDAUFTRAGTOURID 4
#define KDAUFTRAGTOURIDALT 5
#define KDAUFTRAGPERSONALNR 6
#define KDAUFTRAGMATCHCODE 7
#define KDAUFTRAGRECHNUNGNR 8
#define KDAUFTRAGFILIALNR 9
#define KDAUFTRAGETAUFTRAGSCHALTER1 10
#define KDAUFTRAGETAUFTRAGSCHALTER2 11
#define KDAUFTRAGETAUFTRAGSCHALTER3 12
#define KDAUFTRAGETAUFTRAGSCHALTER4 13
#define KDAUFTRAGKDAUFTRAGART 14
#define KDAUFTRAGKOART 15
#define KDAUFTRAGBUCHART 16
#define KDAUFTRAGDATUMVALUTA 17
#define KDAUFTRAGWERTAUFTRAG 18
#define KDAUFTRAGWERTLIEFERUNG 19
#define KDAUFTRAGWERTZEILEN 20
#define KDAUFTRAGANZPOS 21
#define KDAUFTRAGANZPOSOB 22
#define KDAUFTRAGANZPOSLETZTE 23
#define KDAUFTRAGANZPOSDAFUE 24
#define KDAUFTRAGANZPOSDAFUEFEHLER 25
#define KDAUFTRAGANZALPHATEXT 26
#define KDAUFTRAGANZBTM 27
#define KDAUFTRAGANZCONTAINER 28
#define KDAUFTRAGANZBEHAELTWECHSEL 29
#define KDAUFTRAGANZBEHAELT 30
#define KDAUFTRAGANZSONDERWANNE 31
#define KDAUFTRAGBEHAELTERGEWICHT 32
#define KDAUFTRAGRABATTBARPROZ 33
#define KDAUFTRAGZEITENDEAM 34
#define KDAUFTRAGZEITENDEPM 35
#define KDAUFTRAGLAGERNRRECHNUNG 36
#define KDAUFTRAGAUFTRAGNRKO 37
#define KDAUFTRAGDMOBILPLATZNR 38
#define KDAUFTRAGSKDDEFEKTABSAGEN 39
#define KDAUFTRAGDRUCKPOSITION 40
#define KDAUFTRAGBATCHSCHREIBEN 41
#define KDAUFTRAGBEMERKUNGEN 42
#define KDAUFTRAGKUNDETEXT 43
#define KDAUFTRAGHERKUNFTFILIALE 44
#define KDAUFTRAGNAECHSTETOUR 45
#define KDAUFTRAGLETZTETOUR 46
#define KDAUFTRAGDAFUEAUFTRAGNR 47
#define KDAUFTRAGDAFUEGERAETENAME 48
#define KDAUFTRAGVERTRIEBSZENTRUMNR 49
#define KDAUFTRAGKUNDENNR 50
#define KDAUFTRAGKDAUFTRAGNRFILIALE 51
#define KDAUFTRAGSENDESTATUS 52
#define KDAUFTRAGPOOLTYP 53
#define KDAUFTRAGPOOLNR 54
#define KDAUFTRAGZUGRUND 55
#define KDAUFTRAGDATUMAUSLIEFERUNG 56
#define KDAUFTRAGKDAUFTRAGNRORG 57
#define KDAUFTRAGDATUMORG 58
#define KDAUFTRAGKZRESTORED 59
#define KDAUFTRAGBATCHAUFTRAGNR 60
#define KDAUFTRAGSUB_ORDER_TYPE 61
#define KDAUFTRAGPAYMENT_TERM 62
#define KDAUFTRAGANZAUF 63
#define KDAUFTRAGDATUMVALUTABATCH 64
#define KDAUFTRAGVALUTAMONAUTO 65
#define KDAUFTRAGVALUTAMONMANUELL 66
#define KDAUFTRAGTENDERNO 67
#define KDAUFTRAGDATUMVERSAND 68
#define KDAUFTRAGDATUMBTM 69
#define KDAUFTRAGBTMFORMULARNR 70
#define KDAUFTRAGWERTNETTO 71
#define KDAUFTRAGWERTRABATT 72
#define KDAUFTRAGINVOICENUMBER 73
#define KDAUFTRAGPAYMENTDATE 74
#define KDAUFTRAGPAYMENTTYPE 75
#define KDAUFTRAGETAUFTRAGSCHALTER5 76
#define KDAUFTRAGETAUFTRAGSCHALTER6 77
#define KDAUFTRAGDRIVERID 78
#define KDAUFTRAGXMLREFERENCENO 79
#define KDAUFTRAGLOGISTICVOLUME 80
#define KDAUFTRAGORDERLABEL 81
#define KDAUFTRAGDPODAYS 82
#define KDAUFTRAGORDERPERIODID 83

/* define of Buf_Desc *********************************************************/

#if defined (BUF_DESC) || defined (C_BUF_DESC)
#define KDAUFTRAG_H
#define KDAUFTRAG_ANZ ( sizeof(KDAUFTRAG_BES) / sizeof(struct buf_desc) )
#endif

/* SqlDefine of KDAUFTRAG *****************************************************/

#define KDAUFTRAG_LISTE \
        KDAUFTRAG.KDAUFTRAGNR,\
        KDAUFTRAG.KDAUFTRAGSTAT,\
        KDAUFTRAG.IDFNR,\
        KDAUFTRAG.GERAETNAME,\
        KDAUFTRAG.TOURID,\
        KDAUFTRAG.TOURIDALT,\
        KDAUFTRAG.PERSONALNR,\
        KDAUFTRAG.MATCHCODE,\
        KDAUFTRAG.RECHNUNGNR,\
        KDAUFTRAG.FILIALNR,\
        KDAUFTRAG.ETAUFTRAGSCHALTER1,\
        KDAUFTRAG.ETAUFTRAGSCHALTER2,\
        KDAUFTRAG.ETAUFTRAGSCHALTER3,\
        KDAUFTRAG.ETAUFTRAGSCHALTER4,\
        KDAUFTRAG.KDAUFTRAGART,\
        KDAUFTRAG.KOART,\
        KDAUFTRAG.BUCHART,\
        KDAUFTRAG.DATUMVALUTA,\
        KDAUFTRAG.WERTAUFTRAG,\
        KDAUFTRAG.WERTLIEFERUNG,\
        KDAUFTRAG.WERTZEILEN,\
        KDAUFTRAG.ANZPOS,\
        KDAUFTRAG.ANZPOSOB,\
        KDAUFTRAG.ANZPOSLETZTE,\
        KDAUFTRAG.ANZPOSDAFUE,\
        KDAUFTRAG.ANZPOSDAFUEFEHLER,\
        KDAUFTRAG.ANZALPHATEXT,\
        KDAUFTRAG.ANZBTM,\
        KDAUFTRAG.ANZCONTAINER,\
        KDAUFTRAG.ANZBEHAELTWECHSEL,\
        KDAUFTRAG.ANZBEHAELT,\
        KDAUFTRAG.ANZSONDERWANNE,\
        KDAUFTRAG.BEHAELTERGEWICHT,\
        KDAUFTRAG.RABATTBARPROZ,\
        KDAUFTRAG.ZEITENDEAM,\
        KDAUFTRAG.ZEITENDEPM,\
        KDAUFTRAG.LAGERNRRECHNUNG,\
        KDAUFTRAG.AUFTRAGNRKO,\
        KDAUFTRAG.DMOBILPLATZNR,\
        KDAUFTRAG.SKDDEFEKTABSAGEN,\
        KDAUFTRAG.DRUCKPOSITION,\
        KDAUFTRAG.BATCHSCHREIBEN,\
        KDAUFTRAG.BEMERKUNGEN,\
        KDAUFTRAG.KUNDETEXT,\
        KDAUFTRAG.HERKUNFTFILIALE,\
        KDAUFTRAG.NAECHSTETOUR,\
        KDAUFTRAG.LETZTETOUR,\
        KDAUFTRAG.DAFUEAUFTRAGNR,\
        KDAUFTRAG.DAFUEGERAETENAME,\
        KDAUFTRAG.VERTRIEBSZENTRUMNR,\
        KDAUFTRAG.KUNDENNR,\
        KDAUFTRAG.KDAUFTRAGNRFILIALE,\
        KDAUFTRAG.SENDESTATUS,\
        KDAUFTRAG.POOLTYP,\
        KDAUFTRAG.POOLNR,\
        KDAUFTRAG.ZUGRUND,\
        KDAUFTRAG.DATUMAUSLIEFERUNG,\
        KDAUFTRAG.KDAUFTRAGNRORG,\
        KDAUFTRAG.DATUMORG,\
        KDAUFTRAG.KZRESTORED,\
        KDAUFTRAG.BATCHAUFTRAGNR,\
        KDAUFTRAG.SUB_ORDER_TYPE,\
        KDAUFTRAG.PAYMENT_TERM,\
        KDAUFTRAG.ANZAUF,\
        KDAUFTRAG.DATUMVALUTABATCH,\
        KDAUFTRAG.VALUTAMONAUTO,\
        KDAUFTRAG.VALUTAMONMANUELL,\
        KDAUFTRAG.TENDERNO,\
        KDAUFTRAG.DATUMVERSAND,\
        KDAUFTRAG.DATUMBTM,\
        KDAUFTRAG.BTMFORMULARNR,\
        KDAUFTRAG.WERTNETTO,\
        KDAUFTRAG.WERTRABATT,\
        KDAUFTRAG.INVOICENUMBER,\
        KDAUFTRAG.PAYMENTDATE,\
        KDAUFTRAG.PAYMENTTYPE,\
        KDAUFTRAG.ETAUFTRAGSCHALTER5,\
        KDAUFTRAG.ETAUFTRAGSCHALTER6,\
        KDAUFTRAG.DRIVERID,\
        KDAUFTRAG.XMLREFERENCENO,\
        KDAUFTRAG.LOGISTICVOLUME,\
        KDAUFTRAG.ORDERLABEL,\
        KDAUFTRAG.DPODAYS,\
        KDAUFTRAG.ORDERPERIODID
#define KDAUFTRAG_LISTE_390 \
        KDAUFTRAGNR,\
        KDAUFTRAGSTAT,\
        IDFNR,\
        GERAETNAME,\
        TOURID,\
        TOURIDALT,\
        PERSONALNR,\
        MATCHCODE,\
        RECHNUNGNR,\
        FILIALNR,\
        ETAUFTRAGSCHALTER1,\
        ETAUFTRAGSCHALTER2,\
        ETAUFTRAGSCHALTER3,\
        ETAUFTRAGSCHALTER4,\
        KDAUFTRAGART,\
        KOART,\
        BUCHART,\
        DATUMVALUTA,\
        WERTAUFTRAG,\
        WERTLIEFERUNG,\
        WERTZEILEN,\
        ANZPOS,\
        ANZPOSOB,\
        ANZPOSLETZTE,\
        ANZPOSDAFUE,\
        ANZPOSDAFUEFEHLER,\
        ANZALPHATEXT,\
        ANZBTM,\
        ANZCONTAINER,\
        ANZBEHAELTWECHSEL,\
        ANZBEHAELT,\
        ANZSONDERWANNE,\
        BEHAELTERGEWICHT,\
        RABATTBARPROZ,\
        ZEITENDEAM,\
        ZEITENDEPM,\
        LAGERNRRECHNUNG,\
        AUFTRAGNRKO,\
        DMOBILPLATZNR,\
        SKDDEFEKTABSAGEN,\
        DRUCKPOSITION,\
        BATCHSCHREIBEN,\
        BEMERKUNGEN,\
        KUNDETEXT,\
        HERKUNFTFILIALE,\
        NAECHSTETOUR,\
        LETZTETOUR,\
        DAFUEAUFTRAGNR,\
        DAFUEGERAETENAME,\
        VERTRIEBSZENTRUMNR,\
        KUNDENNR,\
        KDAUFTRAGNRFILIALE,\
        SENDESTATUS,\
        POOLTYP,\
        POOLNR,\
        ZUGRUND,\
        DATUMAUSLIEFERUNG,\
        KDAUFTRAGNRORG,\
        DATUMORG,\
        KZRESTORED,\
        BATCHAUFTRAGNR,\
        SUB_ORDER_TYPE,\
        PAYMENT_TERM,\
        ANZAUF,\
        DATUMVALUTABATCH,\
        VALUTAMONAUTO,\
        VALUTAMONMANUELL,\
        TENDERNO,\
        DATUMVERSAND,\
        DATUMBTM,\
        BTMFORMULARNR,\
        WERTNETTO,\
        WERTRABATT,\
        INVOICENUMBER,\
        PAYMENTDATE,\
        PAYMENTTYPE,\
        ETAUFTRAGSCHALTER5,\
        ETAUFTRAGSCHALTER6,\
        DRIVERID,\
        XMLREFERENCENO,\
        LOGISTICVOLUME,\
        ORDERLABEL,\
        DPODAYS,\
        ORDERPERIODID
#define KDAUFTRAG_PLISTE \
        "KDAUFTRAG.KDAUFTRAGNR,"\
        "KDAUFTRAG.KDAUFTRAGSTAT,"\
        "KDAUFTRAG.IDFNR,"\
        "KDAUFTRAG.GERAETNAME,"\
        "KDAUFTRAG.TOURID,"\
        "KDAUFTRAG.TOURIDALT,"\
        "KDAUFTRAG.PERSONALNR,"\
        "KDAUFTRAG.MATCHCODE,"\
        "KDAUFTRAG.RECHNUNGNR,"\
        "KDAUFTRAG.FILIALNR,"\
        "KDAUFTRAG.ETAUFTRAGSCHALTER1,"\
        "KDAUFTRAG.ETAUFTRAGSCHALTER2,"\
        "KDAUFTRAG.ETAUFTRAGSCHALTER3,"\
        "KDAUFTRAG.ETAUFTRAGSCHALTER4,"\
        "KDAUFTRAG.KDAUFTRAGART,"\
        "KDAUFTRAG.KOART,"\
        "KDAUFTRAG.BUCHART,"\
        "KDAUFTRAG.DATUMVALUTA,"\
        "KDAUFTRAG.WERTAUFTRAG,"\
        "KDAUFTRAG.WERTLIEFERUNG,"\
        "KDAUFTRAG.WERTZEILEN,"\
        "KDAUFTRAG.ANZPOS,"\
        "KDAUFTRAG.ANZPOSOB,"\
        "KDAUFTRAG.ANZPOSLETZTE,"\
        "KDAUFTRAG.ANZPOSDAFUE,"\
        "KDAUFTRAG.ANZPOSDAFUEFEHLER,"\
        "KDAUFTRAG.ANZALPHATEXT,"\
        "KDAUFTRAG.ANZBTM,"\
        "KDAUFTRAG.ANZCONTAINER,"\
        "KDAUFTRAG.ANZBEHAELTWECHSEL,"\
        "KDAUFTRAG.ANZBEHAELT,"\
        "KDAUFTRAG.ANZSONDERWANNE,"\
        "KDAUFTRAG.BEHAELTERGEWICHT,"\
        "KDAUFTRAG.RABATTBARPROZ,"\
        "KDAUFTRAG.ZEITENDEAM,"\
        "KDAUFTRAG.ZEITENDEPM,"\
        "KDAUFTRAG.LAGERNRRECHNUNG,"\
        "KDAUFTRAG.AUFTRAGNRKO,"\
        "KDAUFTRAG.DMOBILPLATZNR,"\
        "KDAUFTRAG.SKDDEFEKTABSAGEN,"\
        "KDAUFTRAG.DRUCKPOSITION,"\
        "KDAUFTRAG.BATCHSCHREIBEN,"\
        "KDAUFTRAG.BEMERKUNGEN,"\
        "KDAUFTRAG.KUNDETEXT,"\
        "KDAUFTRAG.HERKUNFTFILIALE,"\
        "KDAUFTRAG.NAECHSTETOUR,"\
        "KDAUFTRAG.LETZTETOUR,"\
        "KDAUFTRAG.DAFUEAUFTRAGNR,"\
        "KDAUFTRAG.DAFUEGERAETENAME,"\
        "KDAUFTRAG.VERTRIEBSZENTRUMNR,"\
        "KDAUFTRAG.KUNDENNR,"\
        "KDAUFTRAG.KDAUFTRAGNRFILIALE,"\
        "KDAUFTRAG.SENDESTATUS,"\
        "KDAUFTRAG.POOLTYP,"\
        "KDAUFTRAG.POOLNR,"\
        "KDAUFTRAG.ZUGRUND,"\
        "KDAUFTRAG.DATUMAUSLIEFERUNG,"\
        "KDAUFTRAG.KDAUFTRAGNRORG,"\
        "KDAUFTRAG.DATUMORG,"\
        "KDAUFTRAG.KZRESTORED,"\
        "KDAUFTRAG.BATCHAUFTRAGNR,"\
        "KDAUFTRAG.SUB_ORDER_TYPE,"\
        "KDAUFTRAG.PAYMENT_TERM,"\
        "KDAUFTRAG.ANZAUF,"\
        "KDAUFTRAG.DATUMVALUTABATCH,"\
        "KDAUFTRAG.VALUTAMONAUTO,"\
        "KDAUFTRAG.VALUTAMONMANUELL,"\
        "KDAUFTRAG.TENDERNO,"\
        "KDAUFTRAG.DATUMVERSAND,"\
        "KDAUFTRAG.DATUMBTM,"\
        "KDAUFTRAG.BTMFORMULARNR,"\
        "KDAUFTRAG.WERTNETTO,"\
        "KDAUFTRAG.WERTRABATT,"\
        "KDAUFTRAG.INVOICENUMBER,"\
        "KDAUFTRAG.PAYMENTDATE,"\
        "KDAUFTRAG.PAYMENTTYPE,"\
        "KDAUFTRAG.ETAUFTRAGSCHALTER5,"\
        "KDAUFTRAG.ETAUFTRAGSCHALTER6,"\
        "KDAUFTRAG.DRIVERID,"\
        "KDAUFTRAG.XMLREFERENCENO,"\
        "KDAUFTRAG.LOGISTICVOLUME,"\
        "KDAUFTRAG.ORDERLABEL,"\
        "KDAUFTRAG.DPODAYS,"\
        "KDAUFTRAG.ORDERPERIODID"
#define KDAUFTRAG_PELISTE \
        "KDAUFTRAGNR,"\
        "KDAUFTRAGSTAT,"\
        "IDFNR,"\
        "GERAETNAME,"\
        "TOURID,"\
        "TOURIDALT,"\
        "PERSONALNR,"\
        "MATCHCODE,"\
        "RECHNUNGNR,"\
        "FILIALNR,"\
        "ETAUFTRAGSCHALTER1,"\
        "ETAUFTRAGSCHALTER2,"\
        "ETAUFTRAGSCHALTER3,"\
        "ETAUFTRAGSCHALTER4,"\
        "KDAUFTRAGART,"\
        "KOART,"\
        "BUCHART,"\
        "DATUMVALUTA,"\
        "WERTAUFTRAG,"\
        "WERTLIEFERUNG,"\
        "WERTZEILEN,"\
        "ANZPOS,"\
        "ANZPOSOB,"\
        "ANZPOSLETZTE,"\
        "ANZPOSDAFUE,"\
        "ANZPOSDAFUEFEHLER,"\
        "ANZALPHATEXT,"\
        "ANZBTM,"\
        "ANZCONTAINER,"\
        "ANZBEHAELTWECHSEL,"\
        "ANZBEHAELT,"\
        "ANZSONDERWANNE,"\
        "BEHAELTERGEWICHT,"\
        "RABATTBARPROZ,"\
        "ZEITENDEAM,"\
        "ZEITENDEPM,"\
        "LAGERNRRECHNUNG,"\
        "AUFTRAGNRKO,"\
        "DMOBILPLATZNR,"\
        "SKDDEFEKTABSAGEN,"\
        "DRUCKPOSITION,"\
        "BATCHSCHREIBEN,"\
        "BEMERKUNGEN,"\
        "KUNDETEXT,"\
        "HERKUNFTFILIALE,"\
        "NAECHSTETOUR,"\
        "LETZTETOUR,"\
        "DAFUEAUFTRAGNR,"\
        "DAFUEGERAETENAME,"\
        "VERTRIEBSZENTRUMNR,"\
        "KUNDENNR,"\
        "KDAUFTRAGNRFILIALE,"\
        "SENDESTATUS,"\
        "POOLTYP,"\
        "POOLNR,"\
        "ZUGRUND,"\
        "DATUMAUSLIEFERUNG,"\
        "KDAUFTRAGNRORG,"\
        "DATUMORG,"\
        "KZRESTORED,"\
        "BATCHAUFTRAGNR,"\
        "SUB_ORDER_TYPE,"\
        "PAYMENT_TERM,"\
        "ANZAUF,"\
        "DATUMVALUTABATCH,"\
        "VALUTAMONAUTO,"\
        "VALUTAMONMANUELL,"\
        "TENDERNO,"\
        "DATUMVERSAND,"\
        "DATUMBTM,"\
        "BTMFORMULARNR,"\
        "WERTNETTO,"\
        "WERTRABATT,"\
        "INVOICENUMBER,"\
        "PAYMENTDATE,"\
        "PAYMENTTYPE,"\
        "ETAUFTRAGSCHALTER5,"\
        "ETAUFTRAGSCHALTER6,"\
        "DRIVERID,"\
        "XMLREFERENCENO,"\
        "LOGISTICVOLUME,"\
        "ORDERLABEL,"\
        "DPODAYS,"\
        "ORDERPERIODID"
#define KDAUFTRAG_UPDLISTE \
        "KDAUFTRAGNR=?,"\
        "KDAUFTRAGSTAT=?,"\
        "IDFNR=?,"\
        "GERAETNAME=?,"\
        "TOURID=?,"\
        "TOURIDALT=?,"\
        "PERSONALNR=?,"\
        "MATCHCODE=?,"\
        "RECHNUNGNR=?,"\
        "FILIALNR=?,"\
        "ETAUFTRAGSCHALTER1=?,"\
        "ETAUFTRAGSCHALTER2=?,"\
        "ETAUFTRAGSCHALTER3=?,"\
        "ETAUFTRAGSCHALTER4=?,"\
        "KDAUFTRAGART=?,"\
        "KOART=?,"\
        "BUCHART=?,"\
        "DATUMVALUTA=?,"\
        "WERTAUFTRAG=?,"\
        "WERTLIEFERUNG=?,"\
        "WERTZEILEN=?,"\
        "ANZPOS=?,"\
        "ANZPOSOB=?,"\
        "ANZPOSLETZTE=?,"\
        "ANZPOSDAFUE=?,"\
        "ANZPOSDAFUEFEHLER=?,"\
        "ANZALPHATEXT=?,"\
        "ANZBTM=?,"\
        "ANZCONTAINER=?,"\
        "ANZBEHAELTWECHSEL=?,"\
        "ANZBEHAELT=?,"\
        "ANZSONDERWANNE=?,"\
        "BEHAELTERGEWICHT=?,"\
        "RABATTBARPROZ=?,"\
        "ZEITENDEAM=?,"\
        "ZEITENDEPM=?,"\
        "LAGERNRRECHNUNG=?,"\
        "AUFTRAGNRKO=?,"\
        "DMOBILPLATZNR=?,"\
        "SKDDEFEKTABSAGEN=?,"\
        "DRUCKPOSITION=?,"\
        "BATCHSCHREIBEN=?,"\
        "BEMERKUNGEN=?,"\
        "KUNDETEXT=?,"\
        "HERKUNFTFILIALE=?,"\
        "NAECHSTETOUR=?,"\
        "LETZTETOUR=?,"\
        "DAFUEAUFTRAGNR=?,"\
        "DAFUEGERAETENAME=?,"\
        "VERTRIEBSZENTRUMNR=?,"\
        "KUNDENNR=?,"\
        "KDAUFTRAGNRFILIALE=?,"\
        "SENDESTATUS=?,"\
        "POOLTYP=?,"\
        "POOLNR=?,"\
        "ZUGRUND=?,"\
        "DATUMAUSLIEFERUNG=?,"\
        "KDAUFTRAGNRORG=?,"\
        "DATUMORG=?,"\
        "KZRESTORED=?,"\
        "BATCHAUFTRAGNR=?,"\
        "SUB_ORDER_TYPE=?,"\
        "PAYMENT_TERM=?,"\
        "ANZAUF=?,"\
        "DATUMVALUTABATCH=?,"\
        "VALUTAMONAUTO=?,"\
        "VALUTAMONMANUELL=?,"\
        "TENDERNO=?,"\
        "DATUMVERSAND=?,"\
        "DATUMBTM=?,"\
        "BTMFORMULARNR=?,"\
        "WERTNETTO=?,"\
        "WERTRABATT=?,"\
        "INVOICENUMBER=?,"\
        "PAYMENTDATE=?,"\
        "PAYMENTTYPE=?,"\
        "ETAUFTRAGSCHALTER5=?,"\
        "ETAUFTRAGSCHALTER6=?,"\
        "DRIVERID=?,"\
        "XMLREFERENCENO=?,"\
        "LOGISTICVOLUME=?,"\
        "ORDERLABEL=?,"\
        "DPODAYS=?,"\
        "ORDERPERIODID=?"
/* SqlMacros-Define of KDAUFTRAG **********************************************/

#define KDAUFTRAG_ZEIGER(x) \
        :x->KDAUFTRAGNR,\
        :x->KDAUFTRAGSTAT,\
        :x->IDFNR,\
        :x->GERAETNAME,\
        :x->TOURID,\
        :x->TOURIDALT,\
        :x->PERSONALNR,\
        :x->MATCHCODE,\
        :x->RECHNUNGNR,\
        :x->FILIALNR,\
        :x->ETAUFTRAGSCHALTER1,\
        :x->ETAUFTRAGSCHALTER2,\
        :x->ETAUFTRAGSCHALTER3,\
        :x->ETAUFTRAGSCHALTER4,\
        :x->KDAUFTRAGART,\
        :x->KOART,\
        :x->BUCHART,\
        :x->DATUMVALUTA,\
        :x->WERTAUFTRAG,\
        :x->WERTLIEFERUNG,\
        :x->WERTZEILEN,\
        :x->ANZPOS,\
        :x->ANZPOSOB,\
        :x->ANZPOSLETZTE,\
        :x->ANZPOSDAFUE,\
        :x->ANZPOSDAFUEFEHLER,\
        :x->ANZALPHATEXT,\
        :x->ANZBTM,\
        :x->ANZCONTAINER,\
        :x->ANZBEHAELTWECHSEL,\
        :x->ANZBEHAELT,\
        :x->ANZSONDERWANNE,\
        :x->BEHAELTERGEWICHT,\
        :x->RABATTBARPROZ,\
        :x->ZEITENDEAM,\
        :x->ZEITENDEPM,\
        :x->LAGERNRRECHNUNG,\
        :x->AUFTRAGNRKO,\
        :x->DMOBILPLATZNR,\
        :x->SKDDEFEKTABSAGEN,\
        :x->DRUCKPOSITION,\
        :x->BATCHSCHREIBEN,\
        :x->BEMERKUNGEN,\
        :x->KUNDETEXT,\
        :x->HERKUNFTFILIALE,\
        :x->NAECHSTETOUR,\
        :x->LETZTETOUR,\
        :x->DAFUEAUFTRAGNR,\
        :x->DAFUEGERAETENAME,\
        :x->VERTRIEBSZENTRUMNR,\
        :x->KUNDENNR,\
        :x->KDAUFTRAGNRFILIALE,\
        :x->SENDESTATUS,\
        :x->POOLTYP,\
        :x->POOLNR,\
        :x->ZUGRUND,\
        :x->DATUMAUSLIEFERUNG,\
        :x->KDAUFTRAGNRORG,\
        :x->DATUMORG,\
        :x->KZRESTORED,\
        :x->BATCHAUFTRAGNR,\
        :x->SUB_ORDER_TYPE,\
        :x->PAYMENT_TERM,\
        :x->ANZAUF,\
        :x->DATUMVALUTABATCH,\
        :x->VALUTAMONAUTO,\
        :x->VALUTAMONMANUELL,\
        :x->TENDERNO,\
        :x->DATUMVERSAND,\
        :x->DATUMBTM,\
        :x->BTMFORMULARNR,\
        :x->WERTNETTO,\
        :x->WERTRABATT,\
        :x->INVOICENUMBER,\
        :x->PAYMENTDATE,\
        :x->PAYMENTTYPE,\
        :x->ETAUFTRAGSCHALTER5,\
        :x->ETAUFTRAGSCHALTER6,\
        :x->DRIVERID,\
        :x->XMLREFERENCENO,\
        :x->LOGISTICVOLUME,\
        :x->ORDERLABEL,\
        :x->DPODAYS,\
        :x->ORDERPERIODID
#define KDAUFTRAG_ZEIGERSEL(x) \
        :x->KDAUFTRAGNR,\
        :x->KDAUFTRAGSTAT,\
        :x->IDFNR,\
        :x->GERAETNAME,\
        :x->TOURID,\
        :x->TOURIDALT,\
        :x->PERSONALNR,\
        :x->MATCHCODE,\
        :x->RECHNUNGNR,\
        :x->FILIALNR,\
        :x->ETAUFTRAGSCHALTER1,\
        :x->ETAUFTRAGSCHALTER2,\
        :x->ETAUFTRAGSCHALTER3,\
        :x->ETAUFTRAGSCHALTER4,\
        :x->KDAUFTRAGART,\
        :x->KOART,\
        :x->BUCHART,\
        :x->DATUMVALUTA,\
        :x->WERTAUFTRAG,\
        :x->WERTLIEFERUNG,\
        :x->WERTZEILEN,\
        :x->ANZPOS,\
        :x->ANZPOSOB,\
        :x->ANZPOSLETZTE,\
        :x->ANZPOSDAFUE,\
        :x->ANZPOSDAFUEFEHLER,\
        :x->ANZALPHATEXT,\
        :x->ANZBTM,\
        :x->ANZCONTAINER,\
        :x->ANZBEHAELTWECHSEL,\
        :x->ANZBEHAELT,\
        :x->ANZSONDERWANNE,\
        :x->BEHAELTERGEWICHT,\
        :x->RABATTBARPROZ,\
        :x->ZEITENDEAM,\
        :x->ZEITENDEPM,\
        :x->LAGERNRRECHNUNG,\
        :x->AUFTRAGNRKO,\
        :x->DMOBILPLATZNR,\
        :x->SKDDEFEKTABSAGEN,\
        :x->DRUCKPOSITION,\
        :x->BATCHSCHREIBEN,\
        :x->BEMERKUNGEN,\
        :x->KUNDETEXT,\
        :x->HERKUNFTFILIALE,\
        :x->NAECHSTETOUR,\
        :x->LETZTETOUR,\
        :x->DAFUEAUFTRAGNR,\
        :x->DAFUEGERAETENAME,\
        :x->VERTRIEBSZENTRUMNR,\
        :x->KUNDENNR,\
        :x->KDAUFTRAGNRFILIALE,\
        :x->SENDESTATUS,\
        :x->POOLTYP,\
        :x->POOLNR,\
        :x->ZUGRUND,\
        :x->DATUMAUSLIEFERUNG,\
        :x->KDAUFTRAGNRORG,\
        :x->DATUMORG,\
        :x->KZRESTORED,\
        :x->BATCHAUFTRAGNR,\
        :x->SUB_ORDER_TYPE,\
        :x->PAYMENT_TERM,\
        :x->ANZAUF,\
        :x->DATUMVALUTABATCH,\
        :x->VALUTAMONAUTO,\
        :x->VALUTAMONMANUELL,\
        :x->TENDERNO,\
        :x->DATUMVERSAND,\
        :x->DATUMBTM,\
        :x->BTMFORMULARNR,\
        :x->WERTNETTO,\
        :x->WERTRABATT,\
        :x->INVOICENUMBER,\
        :x->PAYMENTDATE,\
        :x->PAYMENTTYPE,\
        :x->ETAUFTRAGSCHALTER5,\
        :x->ETAUFTRAGSCHALTER6,\
        :x->DRIVERID,\
        :x->XMLREFERENCENO,\
        :x->LOGISTICVOLUME,\
        :x->ORDERLABEL,\
        :x->DPODAYS,\
        :x->ORDERPERIODID
#define KDAUFTRAG_UPDATE(x) \
        KDAUFTRAG.KDAUFTRAGNR=:x->KDAUFTRAGNR,\
        KDAUFTRAG.KDAUFTRAGSTAT=:x->KDAUFTRAGSTAT,\
        KDAUFTRAG.IDFNR=:x->IDFNR,\
        KDAUFTRAG.GERAETNAME=:x->GERAETNAME,\
        KDAUFTRAG.TOURID=:x->TOURID,\
        KDAUFTRAG.TOURIDALT=:x->TOURIDALT,\
        KDAUFTRAG.PERSONALNR=:x->PERSONALNR,\
        KDAUFTRAG.MATCHCODE=:x->MATCHCODE,\
        KDAUFTRAG.RECHNUNGNR=:x->RECHNUNGNR,\
        KDAUFTRAG.FILIALNR=:x->FILIALNR,\
        KDAUFTRAG.ETAUFTRAGSCHALTER1=:x->ETAUFTRAGSCHALTER1,\
        KDAUFTRAG.ETAUFTRAGSCHALTER2=:x->ETAUFTRAGSCHALTER2,\
        KDAUFTRAG.ETAUFTRAGSCHALTER3=:x->ETAUFTRAGSCHALTER3,\
        KDAUFTRAG.ETAUFTRAGSCHALTER4=:x->ETAUFTRAGSCHALTER4,\
        KDAUFTRAG.KDAUFTRAGART=:x->KDAUFTRAGART,\
        KDAUFTRAG.KOART=:x->KOART,\
        KDAUFTRAG.BUCHART=:x->BUCHART,\
        KDAUFTRAG.DATUMVALUTA=:x->DATUMVALUTA,\
        KDAUFTRAG.WERTAUFTRAG=:x->WERTAUFTRAG,\
        KDAUFTRAG.WERTLIEFERUNG=:x->WERTLIEFERUNG,\
        KDAUFTRAG.WERTZEILEN=:x->WERTZEILEN,\
        KDAUFTRAG.ANZPOS=:x->ANZPOS,\
        KDAUFTRAG.ANZPOSOB=:x->ANZPOSOB,\
        KDAUFTRAG.ANZPOSLETZTE=:x->ANZPOSLETZTE,\
        KDAUFTRAG.ANZPOSDAFUE=:x->ANZPOSDAFUE,\
        KDAUFTRAG.ANZPOSDAFUEFEHLER=:x->ANZPOSDAFUEFEHLER,\
        KDAUFTRAG.ANZALPHATEXT=:x->ANZALPHATEXT,\
        KDAUFTRAG.ANZBTM=:x->ANZBTM,\
        KDAUFTRAG.ANZCONTAINER=:x->ANZCONTAINER,\
        KDAUFTRAG.ANZBEHAELTWECHSEL=:x->ANZBEHAELTWECHSEL,\
        KDAUFTRAG.ANZBEHAELT=:x->ANZBEHAELT,\
        KDAUFTRAG.ANZSONDERWANNE=:x->ANZSONDERWANNE,\
        KDAUFTRAG.BEHAELTERGEWICHT=:x->BEHAELTERGEWICHT,\
        KDAUFTRAG.RABATTBARPROZ=:x->RABATTBARPROZ,\
        KDAUFTRAG.ZEITENDEAM=:x->ZEITENDEAM,\
        KDAUFTRAG.ZEITENDEPM=:x->ZEITENDEPM,\
        KDAUFTRAG.LAGERNRRECHNUNG=:x->LAGERNRRECHNUNG,\
        KDAUFTRAG.AUFTRAGNRKO=:x->AUFTRAGNRKO,\
        KDAUFTRAG.DMOBILPLATZNR=:x->DMOBILPLATZNR,\
        KDAUFTRAG.SKDDEFEKTABSAGEN=:x->SKDDEFEKTABSAGEN,\
        KDAUFTRAG.DRUCKPOSITION=:x->DRUCKPOSITION,\
        KDAUFTRAG.BATCHSCHREIBEN=:x->BATCHSCHREIBEN,\
        KDAUFTRAG.BEMERKUNGEN=:x->BEMERKUNGEN,\
        KDAUFTRAG.KUNDETEXT=:x->KUNDETEXT,\
        KDAUFTRAG.HERKUNFTFILIALE=:x->HERKUNFTFILIALE,\
        KDAUFTRAG.NAECHSTETOUR=:x->NAECHSTETOUR,\
        KDAUFTRAG.LETZTETOUR=:x->LETZTETOUR,\
        KDAUFTRAG.DAFUEAUFTRAGNR=:x->DAFUEAUFTRAGNR,\
        KDAUFTRAG.DAFUEGERAETENAME=:x->DAFUEGERAETENAME,\
        KDAUFTRAG.VERTRIEBSZENTRUMNR=:x->VERTRIEBSZENTRUMNR,\
        KDAUFTRAG.KUNDENNR=:x->KUNDENNR,\
        KDAUFTRAG.KDAUFTRAGNRFILIALE=:x->KDAUFTRAGNRFILIALE,\
        KDAUFTRAG.SENDESTATUS=:x->SENDESTATUS,\
        KDAUFTRAG.POOLTYP=:x->POOLTYP,\
        KDAUFTRAG.POOLNR=:x->POOLNR,\
        KDAUFTRAG.ZUGRUND=:x->ZUGRUND,\
        KDAUFTRAG.DATUMAUSLIEFERUNG=:x->DATUMAUSLIEFERUNG,\
        KDAUFTRAG.KDAUFTRAGNRORG=:x->KDAUFTRAGNRORG,\
        KDAUFTRAG.DATUMORG=:x->DATUMORG,\
        KDAUFTRAG.KZRESTORED=:x->KZRESTORED,\
        KDAUFTRAG.BATCHAUFTRAGNR=:x->BATCHAUFTRAGNR,\
        KDAUFTRAG.SUB_ORDER_TYPE=:x->SUB_ORDER_TYPE,\
        KDAUFTRAG.PAYMENT_TERM=:x->PAYMENT_TERM,\
        KDAUFTRAG.ANZAUF=:x->ANZAUF,\
        KDAUFTRAG.DATUMVALUTABATCH=:x->DATUMVALUTABATCH,\
        KDAUFTRAG.VALUTAMONAUTO=:x->VALUTAMONAUTO,\
        KDAUFTRAG.VALUTAMONMANUELL=:x->VALUTAMONMANUELL,\
        KDAUFTRAG.TENDERNO=:x->TENDERNO,\
        KDAUFTRAG.DATUMVERSAND=:x->DATUMVERSAND,\
        KDAUFTRAG.DATUMBTM=:x->DATUMBTM,\
        KDAUFTRAG.BTMFORMULARNR=:x->BTMFORMULARNR,\
        KDAUFTRAG.WERTNETTO=:x->WERTNETTO,\
        KDAUFTRAG.WERTRABATT=:x->WERTRABATT,\
        KDAUFTRAG.INVOICENUMBER=:x->INVOICENUMBER,\
        KDAUFTRAG.PAYMENTDATE=:x->PAYMENTDATE,\
        KDAUFTRAG.PAYMENTTYPE=:x->PAYMENTTYPE,\
        KDAUFTRAG.ETAUFTRAGSCHALTER5=:x->ETAUFTRAGSCHALTER5,\
        KDAUFTRAG.ETAUFTRAGSCHALTER6=:x->ETAUFTRAGSCHALTER6,\
        KDAUFTRAG.DRIVERID=:x->DRIVERID,\
        KDAUFTRAG.XMLREFERENCENO=:x->XMLREFERENCENO,\
        KDAUFTRAG.LOGISTICVOLUME=:x->LOGISTICVOLUME,\
        KDAUFTRAG.ORDERLABEL=:x->ORDERLABEL,\
        KDAUFTRAG.DPODAYS=:x->DPODAYS,\
        KDAUFTRAG.ORDERPERIODID=:x->ORDERPERIODID
/* SqlMacros390-Define of KDAUFTRAG *******************************************/

#define KDAUFTRAG_ZEIGER_390 \
        :KDAUFTRAGNR,\
        :KDAUFTRAGSTAT,\
        :IDFNR,\
        :GERAETNAME,\
        :TOURID,\
        :TOURIDALT,\
        :PERSONALNR,\
        :MATCHCODE,\
        :RECHNUNGNR,\
        :FILIALNR,\
        :ETAUFTRAGSCHALTER1,\
        :ETAUFTRAGSCHALTER2,\
        :ETAUFTRAGSCHALTER3,\
        :ETAUFTRAGSCHALTER4,\
        :KDAUFTRAGART,\
        :KOART,\
        :BUCHART,\
        :DATUMVALUTA,\
        :WERTAUFTRAG,\
        :WERTLIEFERUNG,\
        :WERTZEILEN,\
        :ANZPOS,\
        :ANZPOSOB,\
        :ANZPOSLETZTE,\
        :ANZPOSDAFUE,\
        :ANZPOSDAFUEFEHLER,\
        :ANZALPHATEXT,\
        :ANZBTM,\
        :ANZCONTAINER,\
        :ANZBEHAELTWECHSEL,\
        :ANZBEHAELT,\
        :ANZSONDERWANNE,\
        :BEHAELTERGEWICHT,\
        :RABATTBARPROZ,\
        :ZEITENDEAM,\
        :ZEITENDEPM,\
        :LAGERNRRECHNUNG,\
        :AUFTRAGNRKO,\
        :DMOBILPLATZNR,\
        :SKDDEFEKTABSAGEN,\
        :DRUCKPOSITION,\
        :BATCHSCHREIBEN,\
        :BEMERKUNGEN,\
        :KUNDETEXT,\
        :HERKUNFTFILIALE,\
        :NAECHSTETOUR,\
        :LETZTETOUR,\
        :DAFUEAUFTRAGNR,\
        :DAFUEGERAETENAME,\
        :VERTRIEBSZENTRUMNR,\
        :KUNDENNR,\
        :KDAUFTRAGNRFILIALE,\
        :SENDESTATUS,\
        :POOLTYP,\
        :POOLNR,\
        :ZUGRUND,\
        :DATUMAUSLIEFERUNG,\
        :KDAUFTRAGNRORG,\
        :DATUMORG,\
        :KZRESTORED,\
        :BATCHAUFTRAGNR,\
        :SUB_ORDER_TYPE,\
        :PAYMENT_TERM,\
        :ANZAUF,\
        :DATUMVALUTABATCH,\
        :VALUTAMONAUTO,\
        :VALUTAMONMANUELL,\
        :TENDERNO,\
        :DATUMVERSAND,\
        :DATUMBTM,\
        :BTMFORMULARNR,\
        :WERTNETTO,\
        :WERTRABATT,\
        :INVOICENUMBER,\
        :PAYMENTDATE,\
        :PAYMENTTYPE,\
        :ETAUFTRAGSCHALTER5,\
        :ETAUFTRAGSCHALTER6,\
        :DRIVERID,\
        :XMLREFERENCENO,\
        :LOGISTICVOLUME,\
        :ORDERLABEL,\
        :DPODAYS,\
        :ORDERPERIODID
#define KDAUFTRAG_UPDATE_390 \
        KDAUFTRAGNR=:KDAUFTRAGNR,\
        KDAUFTRAGSTAT=:KDAUFTRAGSTAT,\
        IDFNR=:IDFNR,\
        GERAETNAME=:GERAETNAME,\
        TOURID=:TOURID,\
        TOURIDALT=:TOURIDALT,\
        PERSONALNR=:PERSONALNR,\
        MATCHCODE=:MATCHCODE,\
        RECHNUNGNR=:RECHNUNGNR,\
        FILIALNR=:FILIALNR,\
        ETAUFTRAGSCHALTER1=:ETAUFTRAGSCHALTER1,\
        ETAUFTRAGSCHALTER2=:ETAUFTRAGSCHALTER2,\
        ETAUFTRAGSCHALTER3=:ETAUFTRAGSCHALTER3,\
        ETAUFTRAGSCHALTER4=:ETAUFTRAGSCHALTER4,\
        KDAUFTRAGART=:KDAUFTRAGART,\
        KOART=:KOART,\
        BUCHART=:BUCHART,\
        DATUMVALUTA=:DATUMVALUTA,\
        WERTAUFTRAG=:WERTAUFTRAG,\
        WERTLIEFERUNG=:WERTLIEFERUNG,\
        WERTZEILEN=:WERTZEILEN,\
        ANZPOS=:ANZPOS,\
        ANZPOSOB=:ANZPOSOB,\
        ANZPOSLETZTE=:ANZPOSLETZTE,\
        ANZPOSDAFUE=:ANZPOSDAFUE,\
        ANZPOSDAFUEFEHLER=:ANZPOSDAFUEFEHLER,\
        ANZALPHATEXT=:ANZALPHATEXT,\
        ANZBTM=:ANZBTM,\
        ANZCONTAINER=:ANZCONTAINER,\
        ANZBEHAELTWECHSEL=:ANZBEHAELTWECHSEL,\
        ANZBEHAELT=:ANZBEHAELT,\
        ANZSONDERWANNE=:ANZSONDERWANNE,\
        BEHAELTERGEWICHT=:BEHAELTERGEWICHT,\
        RABATTBARPROZ=:RABATTBARPROZ,\
        ZEITENDEAM=:ZEITENDEAM,\
        ZEITENDEPM=:ZEITENDEPM,\
        LAGERNRRECHNUNG=:LAGERNRRECHNUNG,\
        AUFTRAGNRKO=:AUFTRAGNRKO,\
        DMOBILPLATZNR=:DMOBILPLATZNR,\
        SKDDEFEKTABSAGEN=:SKDDEFEKTABSAGEN,\
        DRUCKPOSITION=:DRUCKPOSITION,\
        BATCHSCHREIBEN=:BATCHSCHREIBEN,\
        BEMERKUNGEN=:BEMERKUNGEN,\
        KUNDETEXT=:KUNDETEXT,\
        HERKUNFTFILIALE=:HERKUNFTFILIALE,\
        NAECHSTETOUR=:NAECHSTETOUR,\
        LETZTETOUR=:LETZTETOUR,\
        DAFUEAUFTRAGNR=:DAFUEAUFTRAGNR,\
        DAFUEGERAETENAME=:DAFUEGERAETENAME,\
        VERTRIEBSZENTRUMNR=:VERTRIEBSZENTRUMNR,\
        KUNDENNR=:KUNDENNR,\
        KDAUFTRAGNRFILIALE=:KDAUFTRAGNRFILIALE,\
        SENDESTATUS=:SENDESTATUS,\
        POOLTYP=:POOLTYP,\
        POOLNR=:POOLNR,\
        ZUGRUND=:ZUGRUND,\
        DATUMAUSLIEFERUNG=:DATUMAUSLIEFERUNG,\
        KDAUFTRAGNRORG=:KDAUFTRAGNRORG,\
        DATUMORG=:DATUMORG,\
        KZRESTORED=:KZRESTORED,\
        BATCHAUFTRAGNR=:BATCHAUFTRAGNR,\
        SUB_ORDER_TYPE=:SUB_ORDER_TYPE,\
        PAYMENT_TERM=:PAYMENT_TERM,\
        ANZAUF=:ANZAUF,\
        DATUMVALUTABATCH=:DATUMVALUTABATCH,\
        VALUTAMONAUTO=:VALUTAMONAUTO,\
        VALUTAMONMANUELL=:VALUTAMONMANUELL,\
        TENDERNO=:TENDERNO,\
        DATUMVERSAND=:DATUMVERSAND,\
        DATUMBTM=:DATUMBTM,\
        BTMFORMULARNR=:BTMFORMULARNR,\
        WERTNETTO=:WERTNETTO,\
        WERTRABATT=:WERTRABATT,\
        INVOICENUMBER=:INVOICENUMBER,\
        PAYMENTDATE=:PAYMENTDATE,\
        PAYMENTTYPE=:PAYMENTTYPE,\
        ETAUFTRAGSCHALTER5=:ETAUFTRAGSCHALTER5,\
        ETAUFTRAGSCHALTER6=:ETAUFTRAGSCHALTER6,\
        DRIVERID=:DRIVERID,\
        XMLREFERENCENO=:XMLREFERENCENO,\
        LOGISTICVOLUME=:LOGISTICVOLUME,\
        ORDERLABEL=:ORDERLABEL,\
        DPODAYS=:DPODAYS,\
        ORDERPERIODID=:ORDERPERIODID
#ifdef TRANSCLASS
#include <string.h>
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* original struct of KDAUFTRAG ***********************************************/

#ifndef TRANSCLASS
typedef struct N_KDAUFTRAG {
    long KDAUFTRAGNR;
    char KDAUFTRAGSTAT[17];
    long IDFNR;
    char GERAETNAME[9];
    char TOURID[7];
    char TOURIDALT[7];
    long PERSONALNR;
    char MATCHCODE[13];
    long RECHNUNGNR;
    short FILIALNR;
    long ETAUFTRAGSCHALTER1;
    long ETAUFTRAGSCHALTER2;
    long ETAUFTRAGSCHALTER3;
    long ETAUFTRAGSCHALTER4;
    char KDAUFTRAGART[3];
    char KOART[2];
    char BUCHART[2];
    long DATUMVALUTA;
    double WERTAUFTRAG;
    double WERTLIEFERUNG;
    double WERTZEILEN;
    long ANZPOS;
    long ANZPOSOB;
    long ANZPOSLETZTE;
    long ANZPOSDAFUE;
    long ANZPOSDAFUEFEHLER;
    long ANZALPHATEXT;
    long ANZBTM;
    long ANZCONTAINER;
    long ANZBEHAELTWECHSEL;
    long ANZBEHAELT;
    long ANZSONDERWANNE;
    long BEHAELTERGEWICHT;
    double RABATTBARPROZ;
    long ZEITENDEAM;
    long ZEITENDEPM;
    char LAGERNRRECHNUNG[2];
    long AUFTRAGNRKO;
    long DMOBILPLATZNR;
    char SKDDEFEKTABSAGEN[2];
    long DRUCKPOSITION;
    long BATCHSCHREIBEN;
    char BEMERKUNGEN[241];
    char KUNDETEXT[241];
    short HERKUNFTFILIALE;
    char NAECHSTETOUR[7];
    char LETZTETOUR[7];
    long DAFUEAUFTRAGNR;
    char DAFUEGERAETENAME[3];
    short VERTRIEBSZENTRUMNR;
    long KUNDENNR;
    long KDAUFTRAGNRFILIALE;
    short SENDESTATUS;
    short POOLTYP;
    short POOLNR;
    char ZUGRUND[17];
    long DATUMAUSLIEFERUNG;
    long KDAUFTRAGNRORG;
    long DATUMORG;
    char KZRESTORED[2];
    long BATCHAUFTRAGNR;
    char SUB_ORDER_TYPE[4];
    char PAYMENT_TERM[5];
    short ANZAUF;
    long DATUMVALUTABATCH;
    short VALUTAMONAUTO;
    short VALUTAMONMANUELL;
    long TENDERNO;
    long DATUMVERSAND;
    long DATUMBTM;
    char BTMFORMULARNR[11];
    double WERTNETTO;
    double WERTRABATT;
    char INVOICENUMBER[16];
    long PAYMENTDATE;
    char PAYMENTTYPE[2];
    long ETAUFTRAGSCHALTER5;
    long ETAUFTRAGSCHALTER6;
    long DRIVERID;
    char XMLREFERENCENO[10];
    long LOGISTICVOLUME;
    char ORDERLABEL[41];
    short DPODAYS;
    long ORDERPERIODID;
} kdauftragS;
#else /* TRANSCLASS */
typedef struct N_KDAUFTRAG {
    long KDAUFTRAGNR;
    char KDAUFTRAGSTAT[17];
    long IDFNR;
    char GERAETNAME[9];
    char TOURID[7];
    char TOURIDALT[7];
    long PERSONALNR;
    char MATCHCODE[13];
    long RECHNUNGNR;
    short FILIALNR;
    long ETAUFTRAGSCHALTER1;
    long ETAUFTRAGSCHALTER2;
    long ETAUFTRAGSCHALTER3;
    long ETAUFTRAGSCHALTER4;
    char KDAUFTRAGART[3];
    char KOART[2];
    char BUCHART[2];
    long DATUMVALUTA;
    double WERTAUFTRAG;
    double WERTLIEFERUNG;
    double WERTZEILEN;
    long ANZPOS;
    long ANZPOSOB;
    long ANZPOSLETZTE;
    long ANZPOSDAFUE;
    long ANZPOSDAFUEFEHLER;
    long ANZALPHATEXT;
    long ANZBTM;
    long ANZCONTAINER;
    long ANZBEHAELTWECHSEL;
    long ANZBEHAELT;
    long ANZSONDERWANNE;
    long BEHAELTERGEWICHT;
    double RABATTBARPROZ;
    long ZEITENDEAM;
    long ZEITENDEPM;
    char LAGERNRRECHNUNG[2];
    long AUFTRAGNRKO;
    long DMOBILPLATZNR;
    char SKDDEFEKTABSAGEN[2];
    long DRUCKPOSITION;
    long BATCHSCHREIBEN;
    char BEMERKUNGEN[241];
    char KUNDETEXT[241];
    short HERKUNFTFILIALE;
    char NAECHSTETOUR[7];
    char LETZTETOUR[7];
    long DAFUEAUFTRAGNR;
    char DAFUEGERAETENAME[3];
    short VERTRIEBSZENTRUMNR;
    long KUNDENNR;
    long KDAUFTRAGNRFILIALE;
    short SENDESTATUS;
    short POOLTYP;
    short POOLNR;
    char ZUGRUND[17];
    long DATUMAUSLIEFERUNG;
    long KDAUFTRAGNRORG;
    long DATUMORG;
    char KZRESTORED[2];
    long BATCHAUFTRAGNR;
    char SUB_ORDER_TYPE[4];
    char PAYMENT_TERM[5];
    short ANZAUF;
    long DATUMVALUTABATCH;
    short VALUTAMONAUTO;
    short VALUTAMONMANUELL;
    long TENDERNO;
    long DATUMVERSAND;
    long DATUMBTM;
    char BTMFORMULARNR[11];
    double WERTNETTO;
    double WERTRABATT;
    char INVOICENUMBER[16];
    long PAYMENTDATE;
    char PAYMENTTYPE[2];
    long ETAUFTRAGSCHALTER5;
    long ETAUFTRAGSCHALTER6;
    long DRIVERID;
    char XMLREFERENCENO[10];
    long LOGISTICVOLUME;
    char ORDERLABEL[41];
    short DPODAYS;
    long ORDERPERIODID;

    bool operator == (const N_KDAUFTRAG& right) const {
        return (
            KDAUFTRAGNR == right.KDAUFTRAGNR &&
            !strcmp(KDAUFTRAGSTAT, right.KDAUFTRAGSTAT) &&
            IDFNR == right.IDFNR &&
            !strcmp(GERAETNAME, right.GERAETNAME) &&
            !strcmp(TOURID, right.TOURID) &&
            !strcmp(TOURIDALT, right.TOURIDALT) &&
            PERSONALNR == right.PERSONALNR &&
            !strcmp(MATCHCODE, right.MATCHCODE) &&
            RECHNUNGNR == right.RECHNUNGNR &&
            FILIALNR == right.FILIALNR &&
            ETAUFTRAGSCHALTER1 == right.ETAUFTRAGSCHALTER1 &&
            ETAUFTRAGSCHALTER2 == right.ETAUFTRAGSCHALTER2 &&
            ETAUFTRAGSCHALTER3 == right.ETAUFTRAGSCHALTER3 &&
            ETAUFTRAGSCHALTER4 == right.ETAUFTRAGSCHALTER4 &&
            !strcmp(KDAUFTRAGART, right.KDAUFTRAGART) &&
            !strcmp(KOART, right.KOART) &&
            !strcmp(BUCHART, right.BUCHART) &&
            DATUMVALUTA == right.DATUMVALUTA &&
            WERTAUFTRAG == right.WERTAUFTRAG &&
            WERTLIEFERUNG == right.WERTLIEFERUNG &&
            WERTZEILEN == right.WERTZEILEN &&
            ANZPOS == right.ANZPOS &&
            ANZPOSOB == right.ANZPOSOB &&
            ANZPOSLETZTE == right.ANZPOSLETZTE &&
            ANZPOSDAFUE == right.ANZPOSDAFUE &&
            ANZPOSDAFUEFEHLER == right.ANZPOSDAFUEFEHLER &&
            ANZALPHATEXT == right.ANZALPHATEXT &&
            ANZBTM == right.ANZBTM &&
            ANZCONTAINER == right.ANZCONTAINER &&
            ANZBEHAELTWECHSEL == right.ANZBEHAELTWECHSEL &&
            ANZBEHAELT == right.ANZBEHAELT &&
            ANZSONDERWANNE == right.ANZSONDERWANNE &&
            BEHAELTERGEWICHT == right.BEHAELTERGEWICHT &&
            RABATTBARPROZ == right.RABATTBARPROZ &&
            ZEITENDEAM == right.ZEITENDEAM &&
            ZEITENDEPM == right.ZEITENDEPM &&
            !strcmp(LAGERNRRECHNUNG, right.LAGERNRRECHNUNG) &&
            AUFTRAGNRKO == right.AUFTRAGNRKO &&
            DMOBILPLATZNR == right.DMOBILPLATZNR &&
            !strcmp(SKDDEFEKTABSAGEN, right.SKDDEFEKTABSAGEN) &&
            DRUCKPOSITION == right.DRUCKPOSITION &&
            BATCHSCHREIBEN == right.BATCHSCHREIBEN &&
            !strcmp(BEMERKUNGEN, right.BEMERKUNGEN) &&
            !strcmp(KUNDETEXT, right.KUNDETEXT) &&
            HERKUNFTFILIALE == right.HERKUNFTFILIALE &&
            !strcmp(NAECHSTETOUR, right.NAECHSTETOUR) &&
            !strcmp(LETZTETOUR, right.LETZTETOUR) &&
            DAFUEAUFTRAGNR == right.DAFUEAUFTRAGNR &&
            !strcmp(DAFUEGERAETENAME, right.DAFUEGERAETENAME) &&
            VERTRIEBSZENTRUMNR == right.VERTRIEBSZENTRUMNR &&
            KUNDENNR == right.KUNDENNR &&
            KDAUFTRAGNRFILIALE == right.KDAUFTRAGNRFILIALE &&
            SENDESTATUS == right.SENDESTATUS &&
            POOLTYP == right.POOLTYP &&
            POOLNR == right.POOLNR &&
            !strcmp(ZUGRUND, right.ZUGRUND) &&
            DATUMAUSLIEFERUNG == right.DATUMAUSLIEFERUNG &&
            KDAUFTRAGNRORG == right.KDAUFTRAGNRORG &&
            DATUMORG == right.DATUMORG &&
            !strcmp(KZRESTORED, right.KZRESTORED) &&
            BATCHAUFTRAGNR == right.BATCHAUFTRAGNR &&
            !strcmp(SUB_ORDER_TYPE, right.SUB_ORDER_TYPE) &&
            !strcmp(PAYMENT_TERM, right.PAYMENT_TERM) &&
            ANZAUF == right.ANZAUF &&
            DATUMVALUTABATCH == right.DATUMVALUTABATCH &&
            VALUTAMONAUTO == right.VALUTAMONAUTO &&
            VALUTAMONMANUELL == right.VALUTAMONMANUELL &&
            TENDERNO == right.TENDERNO &&
            DATUMVERSAND == right.DATUMVERSAND &&
            DATUMBTM == right.DATUMBTM &&
            !strcmp(BTMFORMULARNR, right.BTMFORMULARNR) &&
            WERTNETTO == right.WERTNETTO &&
            WERTRABATT == right.WERTRABATT &&
            !strcmp(INVOICENUMBER, right.INVOICENUMBER) &&
            PAYMENTDATE == right.PAYMENTDATE &&
            !strcmp(PAYMENTTYPE, right.PAYMENTTYPE) &&
            ETAUFTRAGSCHALTER5 == right.ETAUFTRAGSCHALTER5 &&
            ETAUFTRAGSCHALTER6 == right.ETAUFTRAGSCHALTER6 &&
            DRIVERID == right.DRIVERID &&
            !strcmp(XMLREFERENCENO, right.XMLREFERENCENO) &&
            LOGISTICVOLUME == right.LOGISTICVOLUME &&
            !strcmp(ORDERLABEL, right.ORDERLABEL) &&
            DPODAYS == right.DPODAYS &&
            ORDERPERIODID == right.ORDERPERIODID
        );
    }
    void clear() {
#ifdef WIN32
        memset((char*)this, 0, sizeof(*this));
#else
        KDAUFTRAGNR = 0;
        strcpy(KDAUFTRAGSTAT, " " );
        IDFNR = 0;
        strcpy(GERAETNAME, " " );
        strcpy(TOURID, " " );
        strcpy(TOURIDALT, " " );
        PERSONALNR = 0;
        strcpy(MATCHCODE, " " );
        RECHNUNGNR = 0;
        FILIALNR = 0;
        ETAUFTRAGSCHALTER1 = 0;
        ETAUFTRAGSCHALTER2 = 0;
        ETAUFTRAGSCHALTER3 = 0;
        ETAUFTRAGSCHALTER4 = 0;
        strcpy(KDAUFTRAGART, " " );
        strcpy(KOART, " " );
        strcpy(BUCHART, " " );
        DATUMVALUTA = 0;
        WERTAUFTRAG = 0;
        WERTLIEFERUNG = 0;
        WERTZEILEN = 0;
        ANZPOS = 0;
        ANZPOSOB = 0;
        ANZPOSLETZTE = 0;
        ANZPOSDAFUE = 0;
        ANZPOSDAFUEFEHLER = 0;
        ANZALPHATEXT = 0;
        ANZBTM = 0;
        ANZCONTAINER = 0;
        ANZBEHAELTWECHSEL = 0;
        ANZBEHAELT = 0;
        ANZSONDERWANNE = 0;
        BEHAELTERGEWICHT = 0;
        RABATTBARPROZ = 0;
        ZEITENDEAM = 0;
        ZEITENDEPM = 0;
        strcpy(LAGERNRRECHNUNG, " " );
        AUFTRAGNRKO = 0;
        DMOBILPLATZNR = 0;
        strcpy(SKDDEFEKTABSAGEN, " " );
        DRUCKPOSITION = 0;
        BATCHSCHREIBEN = 0;
        strcpy(BEMERKUNGEN, " " );
        strcpy(KUNDETEXT, " " );
        HERKUNFTFILIALE = 0;
        strcpy(NAECHSTETOUR, " " );
        strcpy(LETZTETOUR, " " );
        DAFUEAUFTRAGNR = 0;
        strcpy(DAFUEGERAETENAME, " " );
        VERTRIEBSZENTRUMNR = 0;
        KUNDENNR = 0;
        KDAUFTRAGNRFILIALE = 0;
        SENDESTATUS = 0;
        POOLTYP = 0;
        POOLNR = 0;
        strcpy(ZUGRUND, " " );
        DATUMAUSLIEFERUNG = 0;
        KDAUFTRAGNRORG = 0;
        DATUMORG = 0;
        strcpy(KZRESTORED, " " );
        BATCHAUFTRAGNR = 0;
        strcpy(SUB_ORDER_TYPE, " " );
        strcpy(PAYMENT_TERM, " " );
        ANZAUF = 0;
        DATUMVALUTABATCH = 0;
        VALUTAMONAUTO = 0;
        VALUTAMONMANUELL = 0;
        TENDERNO = 0;
        DATUMVERSAND = 0;
        DATUMBTM = 0;
        strcpy(BTMFORMULARNR, " " );
        WERTNETTO = 0;
        WERTRABATT = 0;
        strcpy(INVOICENUMBER, " " );
        PAYMENTDATE = 0;
        strcpy(PAYMENTTYPE, " " );
        ETAUFTRAGSCHALTER5 = 0;
        ETAUFTRAGSCHALTER6 = 0;
        DRIVERID = 0;
        strcpy(XMLREFERENCENO, " " );
        LOGISTICVOLUME = 0;
        strcpy(ORDERLABEL, " " );
        DPODAYS = 0;
        ORDERPERIODID = 0;
#endif
    }
} kdauftragS;
#endif /* TRANSCLASS */

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Stringbuffer Structur of KDAUFTRAG *****************************************/

struct S_KDAUFTRAG {
    char KDAUFTRAGNR[11];
    char KDAUFTRAGSTAT[16 + 1];
    char IDFNR[11];
    char GERAETNAME[8 + 1];
    char TOURID[6 + 1];
    char TOURIDALT[6 + 1];
    char PERSONALNR[11];
    char MATCHCODE[12 + 1];
    char RECHNUNGNR[11];
    char FILIALNR[7];
    char ETAUFTRAGSCHALTER1[5 + 1];
    char ETAUFTRAGSCHALTER2[5 + 1];
    char ETAUFTRAGSCHALTER3[5 + 1];
    char ETAUFTRAGSCHALTER4[5 + 1];
    char KDAUFTRAGART[2 + 1];
    char KOART[1 + 1];
    char BUCHART[1 + 1];
    char DATUMVALUTA[11];
    char WERTAUFTRAG[11 + 2];
    char WERTLIEFERUNG[11 + 2];
    char WERTZEILEN[11 + 2];
    char ANZPOS[11];
    char ANZPOSOB[11];
    char ANZPOSLETZTE[11];
    char ANZPOSDAFUE[11];
    char ANZPOSDAFUEFEHLER[11];
    char ANZALPHATEXT[11];
    char ANZBTM[11];
    char ANZCONTAINER[11];
    char ANZBEHAELTWECHSEL[11];
    char ANZBEHAELT[11];
    char ANZSONDERWANNE[11];
    char BEHAELTERGEWICHT[11];
    char RABATTBARPROZ[5 + 2];
    char ZEITENDEAM[11];
    char ZEITENDEPM[11];
    char LAGERNRRECHNUNG[1 + 1];
    char AUFTRAGNRKO[11];
    char DMOBILPLATZNR[11];
    char SKDDEFEKTABSAGEN[1 + 1];
    char DRUCKPOSITION[11];
    char BATCHSCHREIBEN[11];
    char BEMERKUNGEN[240 + 1];
    char KUNDETEXT[240 + 1];
    char HERKUNFTFILIALE[7];
    char NAECHSTETOUR[6 + 1];
    char LETZTETOUR[6 + 1];
    char DAFUEAUFTRAGNR[11];
    char DAFUEGERAETENAME[2 + 1];
    char VERTRIEBSZENTRUMNR[7];
    char KUNDENNR[11];
    char KDAUFTRAGNRFILIALE[11];
    char SENDESTATUS[7];
    char POOLTYP[7];
    char POOLNR[7];
    char ZUGRUND[16 + 1];
    char DATUMAUSLIEFERUNG[11];
    char KDAUFTRAGNRORG[11];
    char DATUMORG[11];
    char KZRESTORED[1 + 1];
    char BATCHAUFTRAGNR[11];
    char SUB_ORDER_TYPE[3 + 1];
    char PAYMENT_TERM[4 + 1];
    char ANZAUF[7];
    char DATUMVALUTABATCH[11];
    char VALUTAMONAUTO[7];
    char VALUTAMONMANUELL[7];
    char TENDERNO[11];
    char DATUMVERSAND[11];
    char DATUMBTM[11];
    char BTMFORMULARNR[10 + 1];
    char WERTNETTO[11 + 2];
    char WERTRABATT[11 + 2];
    char INVOICENUMBER[15 + 1];
    char PAYMENTDATE[11];
    char PAYMENTTYPE[1 + 1];
    char ETAUFTRAGSCHALTER5[5 + 1];
    char ETAUFTRAGSCHALTER6[5 + 1];
    char DRIVERID[11];
    char XMLREFERENCENO[9 + 1];
    char LOGISTICVOLUME[11];
    char ORDERLABEL[40 + 1];
    char DPODAYS[7];
    char ORDERPERIODID[11];
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Stringbuffer (without strend) Structur of KDAUFTRAG ************************/

struct O_KDAUFTRAG {
    char KDAUFTRAGNR[11];
    char KDAUFTRAGSTAT[16];
    char IDFNR[11];
    char GERAETNAME[8];
    char TOURID[6];
    char TOURIDALT[6];
    char PERSONALNR[11];
    char MATCHCODE[12];
    char RECHNUNGNR[11];
    char FILIALNR[7];
    char ETAUFTRAGSCHALTER1[5];
    char ETAUFTRAGSCHALTER2[5];
    char ETAUFTRAGSCHALTER3[5];
    char ETAUFTRAGSCHALTER4[5];
    char KDAUFTRAGART[2];
    char KOART[1];
    char BUCHART[1];
    char DATUMVALUTA[11];
    char WERTAUFTRAG[11];
    char WERTLIEFERUNG[11];
    char WERTZEILEN[11];
    char ANZPOS[11];
    char ANZPOSOB[11];
    char ANZPOSLETZTE[11];
    char ANZPOSDAFUE[11];
    char ANZPOSDAFUEFEHLER[11];
    char ANZALPHATEXT[11];
    char ANZBTM[11];
    char ANZCONTAINER[11];
    char ANZBEHAELTWECHSEL[11];
    char ANZBEHAELT[11];
    char ANZSONDERWANNE[11];
    char BEHAELTERGEWICHT[11];
    char RABATTBARPROZ[5];
    char ZEITENDEAM[11];
    char ZEITENDEPM[11];
    char LAGERNRRECHNUNG[1];
    char AUFTRAGNRKO[11];
    char DMOBILPLATZNR[11];
    char SKDDEFEKTABSAGEN[1];
    char DRUCKPOSITION[11];
    char BATCHSCHREIBEN[11];
    char BEMERKUNGEN[240];
    char KUNDETEXT[240];
    char HERKUNFTFILIALE[7];
    char NAECHSTETOUR[6];
    char LETZTETOUR[6];
    char DAFUEAUFTRAGNR[11];
    char DAFUEGERAETENAME[2];
    char VERTRIEBSZENTRUMNR[7];
    char KUNDENNR[11];
    char KDAUFTRAGNRFILIALE[11];
    char SENDESTATUS[7];
    char POOLTYP[7];
    char POOLNR[7];
    char ZUGRUND[16];
    char DATUMAUSLIEFERUNG[11];
    char KDAUFTRAGNRORG[11];
    char DATUMORG[11];
    char KZRESTORED[1];
    char BATCHAUFTRAGNR[11];
    char SUB_ORDER_TYPE[3];
    char PAYMENT_TERM[4];
    char ANZAUF[7];
    char DATUMVALUTABATCH[11];
    char VALUTAMONAUTO[7];
    char VALUTAMONMANUELL[7];
    char TENDERNO[11];
    char DATUMVERSAND[11];
    char DATUMBTM[11];
    char BTMFORMULARNR[10];
    char WERTNETTO[11];
    char WERTRABATT[11];
    char INVOICENUMBER[15];
    char PAYMENTDATE[11];
    char PAYMENTTYPE[1];
    char ETAUFTRAGSCHALTER5[5];
    char ETAUFTRAGSCHALTER6[5];
    char DRIVERID[11];
    char XMLREFERENCENO[9];
    char LOGISTICVOLUME[11];
    char ORDERLABEL[40];
    char DPODAYS[7];
    char ORDERPERIODID[11];
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Structur with real chartype of KDAUFTRAG ***********************************/

struct C_KDAUFTRAG {
    long KDAUFTRAGNR;
    char KDAUFTRAGSTAT[17];
    long IDFNR;
    char GERAETNAME[9];
    char TOURID[7];
    char TOURIDALT[7];
    long PERSONALNR;
    char MATCHCODE[13];
    long RECHNUNGNR;
    short FILIALNR;
    long ETAUFTRAGSCHALTER1;
    long ETAUFTRAGSCHALTER2;
    long ETAUFTRAGSCHALTER3;
    long ETAUFTRAGSCHALTER4;
    char KDAUFTRAGART[3];
    char KOART;
    char BUCHART;
    long DATUMVALUTA;
    double WERTAUFTRAG;
    double WERTLIEFERUNG;
    double WERTZEILEN;
    long ANZPOS;
    long ANZPOSOB;
    long ANZPOSLETZTE;
    long ANZPOSDAFUE;
    long ANZPOSDAFUEFEHLER;
    long ANZALPHATEXT;
    long ANZBTM;
    long ANZCONTAINER;
    long ANZBEHAELTWECHSEL;
    long ANZBEHAELT;
    long ANZSONDERWANNE;
    long BEHAELTERGEWICHT;
    double RABATTBARPROZ;
    long ZEITENDEAM;
    long ZEITENDEPM;
    char LAGERNRRECHNUNG;
    long AUFTRAGNRKO;
    long DMOBILPLATZNR;
    char SKDDEFEKTABSAGEN;
    long DRUCKPOSITION;
    long BATCHSCHREIBEN;
    char BEMERKUNGEN[241];
    char KUNDETEXT[241];
    short HERKUNFTFILIALE;
    char NAECHSTETOUR[7];
    char LETZTETOUR[7];
    long DAFUEAUFTRAGNR;
    char DAFUEGERAETENAME[3];
    short VERTRIEBSZENTRUMNR;
    long KUNDENNR;
    long KDAUFTRAGNRFILIALE;
    short SENDESTATUS;
    short POOLTYP;
    short POOLNR;
    char ZUGRUND[17];
    long DATUMAUSLIEFERUNG;
    long KDAUFTRAGNRORG;
    long DATUMORG;
    char KZRESTORED;
    long BATCHAUFTRAGNR;
    char SUB_ORDER_TYPE[4];
    char PAYMENT_TERM[5];
    short ANZAUF;
    long DATUMVALUTABATCH;
    short VALUTAMONAUTO;
    short VALUTAMONMANUELL;
    long TENDERNO;
    long DATUMVERSAND;
    long DATUMBTM;
    char BTMFORMULARNR[11];
    double WERTNETTO;
    double WERTRABATT;
    char INVOICENUMBER[16];
    long PAYMENTDATE;
    char PAYMENTTYPE;
    long ETAUFTRAGSCHALTER5;
    long ETAUFTRAGSCHALTER6;
    long DRIVERID;
    char XMLREFERENCENO[10];
    long LOGISTICVOLUME;
    char ORDERLABEL[41];
    short DPODAYS;
    long ORDERPERIODID;
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Sizetype  Structur (buf_desc) of KDAUFTRAG *********************************/

struct I_KDAUFTRAG {
    short KDAUFTRAGNR;
    short KDAUFTRAGSTAT;
    short IDFNR;
    short GERAETNAME;
    short TOURID;
    short TOURIDALT;
    short PERSONALNR;
    short MATCHCODE;
    short RECHNUNGNR;
    short FILIALNR;
    short ETAUFTRAGSCHALTER1;
    short ETAUFTRAGSCHALTER2;
    short ETAUFTRAGSCHALTER3;
    short ETAUFTRAGSCHALTER4;
    short KDAUFTRAGART;
    short KOART;
    short BUCHART;
    short DATUMVALUTA;
    short WERTAUFTRAG;
    short WERTLIEFERUNG;
    short WERTZEILEN;
    short ANZPOS;
    short ANZPOSOB;
    short ANZPOSLETZTE;
    short ANZPOSDAFUE;
    short ANZPOSDAFUEFEHLER;
    short ANZALPHATEXT;
    short ANZBTM;
    short ANZCONTAINER;
    short ANZBEHAELTWECHSEL;
    short ANZBEHAELT;
    short ANZSONDERWANNE;
    short BEHAELTERGEWICHT;
    short RABATTBARPROZ;
    short ZEITENDEAM;
    short ZEITENDEPM;
    short LAGERNRRECHNUNG;
    short AUFTRAGNRKO;
    short DMOBILPLATZNR;
    short SKDDEFEKTABSAGEN;
    short DRUCKPOSITION;
    short BATCHSCHREIBEN;
    short BEMERKUNGEN;
    short KUNDETEXT;
    short HERKUNFTFILIALE;
    short NAECHSTETOUR;
    short LETZTETOUR;
    short DAFUEAUFTRAGNR;
    short DAFUEGERAETENAME;
    short VERTRIEBSZENTRUMNR;
    short KUNDENNR;
    short KDAUFTRAGNRFILIALE;
    short SENDESTATUS;
    short POOLTYP;
    short POOLNR;
    short ZUGRUND;
    short DATUMAUSLIEFERUNG;
    short KDAUFTRAGNRORG;
    short DATUMORG;
    short KZRESTORED;
    short BATCHAUFTRAGNR;
    short SUB_ORDER_TYPE;
    short PAYMENT_TERM;
    short ANZAUF;
    short DATUMVALUTABATCH;
    short VALUTAMONAUTO;
    short VALUTAMONMANUELL;
    short TENDERNO;
    short DATUMVERSAND;
    short DATUMBTM;
    short BTMFORMULARNR;
    short WERTNETTO;
    short WERTRABATT;
    short INVOICENUMBER;
    short PAYMENTDATE;
    short PAYMENTTYPE;
    short ETAUFTRAGSCHALTER5;
    short ETAUFTRAGSCHALTER6;
    short DRIVERID;
    short XMLREFERENCENO;
    short LOGISTICVOLUME;
    short ORDERLABEL;
    short DPODAYS;
    short ORDERPERIODID;
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

/* structures of Buf_Desc *****************************************************/

/* Structur (buf_desc) of KDAUFTRAG *******************************************/

#if defined (BUF_DESC)
static struct buf_desc KDAUFTRAG_BES [] = {
   { TYP_L , 11, 0 },
   { TYP_C, 16, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 8, 0 },
   { TYP_C, 6, 0 },
   { TYP_C, 6, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 12, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_C, 2, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_D, 5, 2 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 240, 0 },
   { TYP_C, 240, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 6, 0 },
   { TYP_C, 6, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 2, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 16, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 3, 0 },
   { TYP_C, 4, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 10, 0 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_C, 15, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 9, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 40, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
};
#elif defined (C_BUF_DESC)
static struct buf_desc KDAUFTRAG_BES [] = {
   { TYP_L , 11, 0 },
   { TYP_C, 16, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 8, 0 },
   { TYP_C, 6, 0 },
   { TYP_C, 6, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 12, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_C, 2, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_D, 5, 2 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 240, 0 },
   { TYP_C, 240, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 6, 0 },
   { TYP_C, 6, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 2, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 16, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 3, 0 },
   { TYP_C, 4, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 10, 0 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_C, 15, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 9, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 40, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
};
#endif

/* description for datatypes of KDAUFTRAG *************************************/

 #define KDAUFTRAG_S390 \
         long KDAUFTRAGNR; \
         char KDAUFTRAGSTAT[17]; \
         long IDFNR; \
         char GERAETNAME[9]; \
         char TOURID[7]; \
         char TOURIDALT[7]; \
         long PERSONALNR; \
         char MATCHCODE[13]; \
         long RECHNUNGNR; \
         short FILIALNR; \
         long ETAUFTRAGSCHALTER1; \
         long ETAUFTRAGSCHALTER2; \
         long ETAUFTRAGSCHALTER3; \
         long ETAUFTRAGSCHALTER4; \
         char KDAUFTRAGART[3]; \
         char KOART; \
         char BUCHART; \
         long DATUMVALUTA; \
         double WERTAUFTRAG; \
         double WERTLIEFERUNG; \
         double WERTZEILEN; \
         long ANZPOS; \
         long ANZPOSOB; \
         long ANZPOSLETZTE; \
         long ANZPOSDAFUE; \
         long ANZPOSDAFUEFEHLER; \
         long ANZALPHATEXT; \
         long ANZBTM; \
         long ANZCONTAINER; \
         long ANZBEHAELTWECHSEL; \
         long ANZBEHAELT; \
         long ANZSONDERWANNE; \
         long BEHAELTERGEWICHT; \
         double RABATTBARPROZ; \
         long ZEITENDEAM; \
         long ZEITENDEPM; \
         char LAGERNRRECHNUNG; \
         long AUFTRAGNRKO; \
         long DMOBILPLATZNR; \
         char SKDDEFEKTABSAGEN; \
         long DRUCKPOSITION; \
         long BATCHSCHREIBEN; \
         char BEMERKUNGEN[241]; \
         char KUNDETEXT[241]; \
         short HERKUNFTFILIALE; \
         char NAECHSTETOUR[7]; \
         char LETZTETOUR[7]; \
         long DAFUEAUFTRAGNR; \
         char DAFUEGERAETENAME[3]; \
         short VERTRIEBSZENTRUMNR; \
         long KUNDENNR; \
         long KDAUFTRAGNRFILIALE; \
         short SENDESTATUS; \
         short POOLTYP; \
         short POOLNR; \
         char ZUGRUND[17]; \
         long DATUMAUSLIEFERUNG; \
         long KDAUFTRAGNRORG; \
         long DATUMORG; \
         char KZRESTORED; \
         long BATCHAUFTRAGNR; \
         char SUB_ORDER_TYPE[4]; \
         char PAYMENT_TERM[5]; \
         short ANZAUF; \
         long DATUMVALUTABATCH; \
         short VALUTAMONAUTO; \
         short VALUTAMONMANUELL; \
         long TENDERNO; \
         long DATUMVERSAND; \
         long DATUMBTM; \
         char BTMFORMULARNR[11]; \
         double WERTNETTO; \
         double WERTRABATT; \
         char INVOICENUMBER[16]; \
         long PAYMENTDATE; \
         char PAYMENTTYPE; \
         long ETAUFTRAGSCHALTER5; \
         long ETAUFTRAGSCHALTER6; \
         long DRIVERID; \
         char XMLREFERENCENO[10]; \
         long LOGISTICVOLUME; \
         char ORDERLABEL[41]; \
         short DPODAYS; \
         long ORDERPERIODID; \



/* Copy-Function Struct to single Data KDAUFTRAG ******************************/

 #define KDAUFTRAG_S390_COPY_TO_SINGLE(_x_) \
         KDAUFTRAGNR=_x_->KDAUFTRAGNR;\
          strcpy(KDAUFTRAGSTAT,_x_->KDAUFTRAGSTAT);\
         IDFNR=_x_->IDFNR;\
          strcpy(GERAETNAME,_x_->GERAETNAME);\
          strcpy(TOURID,_x_->TOURID);\
          strcpy(TOURIDALT,_x_->TOURIDALT);\
         PERSONALNR=_x_->PERSONALNR;\
          strcpy(MATCHCODE,_x_->MATCHCODE);\
         RECHNUNGNR=_x_->RECHNUNGNR;\
         FILIALNR=_x_->FILIALNR;\
         ETAUFTRAGSCHALTER1=_x_->ETAUFTRAGSCHALTER1;\
         ETAUFTRAGSCHALTER2=_x_->ETAUFTRAGSCHALTER2;\
         ETAUFTRAGSCHALTER3=_x_->ETAUFTRAGSCHALTER3;\
         ETAUFTRAGSCHALTER4=_x_->ETAUFTRAGSCHALTER4;\
          strcpy(KDAUFTRAGART,_x_->KDAUFTRAGART);\
         KOART=_x_->KOART;\
         BUCHART=_x_->BUCHART;\
         DATUMVALUTA=_x_->DATUMVALUTA;\
         WERTAUFTRAG=_x_->WERTAUFTRAG;\
         WERTLIEFERUNG=_x_->WERTLIEFERUNG;\
         WERTZEILEN=_x_->WERTZEILEN;\
         ANZPOS=_x_->ANZPOS;\
         ANZPOSOB=_x_->ANZPOSOB;\
         ANZPOSLETZTE=_x_->ANZPOSLETZTE;\
         ANZPOSDAFUE=_x_->ANZPOSDAFUE;\
         ANZPOSDAFUEFEHLER=_x_->ANZPOSDAFUEFEHLER;\
         ANZALPHATEXT=_x_->ANZALPHATEXT;\
         ANZBTM=_x_->ANZBTM;\
         ANZCONTAINER=_x_->ANZCONTAINER;\
         ANZBEHAELTWECHSEL=_x_->ANZBEHAELTWECHSEL;\
         ANZBEHAELT=_x_->ANZBEHAELT;\
         ANZSONDERWANNE=_x_->ANZSONDERWANNE;\
         BEHAELTERGEWICHT=_x_->BEHAELTERGEWICHT;\
         RABATTBARPROZ=_x_->RABATTBARPROZ;\
         ZEITENDEAM=_x_->ZEITENDEAM;\
         ZEITENDEPM=_x_->ZEITENDEPM;\
         LAGERNRRECHNUNG=_x_->LAGERNRRECHNUNG;\
         AUFTRAGNRKO=_x_->AUFTRAGNRKO;\
         DMOBILPLATZNR=_x_->DMOBILPLATZNR;\
         SKDDEFEKTABSAGEN=_x_->SKDDEFEKTABSAGEN;\
         DRUCKPOSITION=_x_->DRUCKPOSITION;\
         BATCHSCHREIBEN=_x_->BATCHSCHREIBEN;\
          strcpy(BEMERKUNGEN,_x_->BEMERKUNGEN);\
          strcpy(KUNDETEXT,_x_->KUNDETEXT);\
         HERKUNFTFILIALE=_x_->HERKUNFTFILIALE;\
          strcpy(NAECHSTETOUR,_x_->NAECHSTETOUR);\
          strcpy(LETZTETOUR,_x_->LETZTETOUR);\
         DAFUEAUFTRAGNR=_x_->DAFUEAUFTRAGNR;\
          strcpy(DAFUEGERAETENAME,_x_->DAFUEGERAETENAME);\
         VERTRIEBSZENTRUMNR=_x_->VERTRIEBSZENTRUMNR;\
         KUNDENNR=_x_->KUNDENNR;\
         KDAUFTRAGNRFILIALE=_x_->KDAUFTRAGNRFILIALE;\
         SENDESTATUS=_x_->SENDESTATUS;\
         POOLTYP=_x_->POOLTYP;\
         POOLNR=_x_->POOLNR;\
          strcpy(ZUGRUND,_x_->ZUGRUND);\
         DATUMAUSLIEFERUNG=_x_->DATUMAUSLIEFERUNG;\
         KDAUFTRAGNRORG=_x_->KDAUFTRAGNRORG;\
         DATUMORG=_x_->DATUMORG;\
         KZRESTORED=_x_->KZRESTORED;\
         BATCHAUFTRAGNR=_x_->BATCHAUFTRAGNR;\
          strcpy(SUB_ORDER_TYPE,_x_->SUB_ORDER_TYPE);\
          strcpy(PAYMENT_TERM,_x_->PAYMENT_TERM);\
         ANZAUF=_x_->ANZAUF;\
         DATUMVALUTABATCH=_x_->DATUMVALUTABATCH;\
         VALUTAMONAUTO=_x_->VALUTAMONAUTO;\
         VALUTAMONMANUELL=_x_->VALUTAMONMANUELL;\
         TENDERNO=_x_->TENDERNO;\
         DATUMVERSAND=_x_->DATUMVERSAND;\
         DATUMBTM=_x_->DATUMBTM;\
          strcpy(BTMFORMULARNR,_x_->BTMFORMULARNR);\
         WERTNETTO=_x_->WERTNETTO;\
         WERTRABATT=_x_->WERTRABATT;\
          strcpy(INVOICENUMBER,_x_->INVOICENUMBER);\
         PAYMENTDATE=_x_->PAYMENTDATE;\
         PAYMENTTYPE=_x_->PAYMENTTYPE;\
         ETAUFTRAGSCHALTER5=_x_->ETAUFTRAGSCHALTER5;\
         ETAUFTRAGSCHALTER6=_x_->ETAUFTRAGSCHALTER6;\
         DRIVERID=_x_->DRIVERID;\
          strcpy(XMLREFERENCENO,_x_->XMLREFERENCENO);\
         LOGISTICVOLUME=_x_->LOGISTICVOLUME;\
          strcpy(ORDERLABEL,_x_->ORDERLABEL);\
         DPODAYS=_x_->DPODAYS;\
         ORDERPERIODID=_x_->ORDERPERIODID;\

 #define KDAUFTRAG_S390_COPY_TO_STRUCT(_x_) \
          _x_->KDAUFTRAGNR=KDAUFTRAGNR;\
          strcpy(_x_->KDAUFTRAGSTAT,KDAUFTRAGSTAT);\
          _x_->IDFNR=IDFNR;\
          strcpy(_x_->GERAETNAME,GERAETNAME);\
          strcpy(_x_->TOURID,TOURID);\
          strcpy(_x_->TOURIDALT,TOURIDALT);\
          _x_->PERSONALNR=PERSONALNR;\
          strcpy(_x_->MATCHCODE,MATCHCODE);\
          _x_->RECHNUNGNR=RECHNUNGNR;\
          _x_->FILIALNR=FILIALNR;\
          _x_->ETAUFTRAGSCHALTER1=ETAUFTRAGSCHALTER1;\
          _x_->ETAUFTRAGSCHALTER2=ETAUFTRAGSCHALTER2;\
          _x_->ETAUFTRAGSCHALTER3=ETAUFTRAGSCHALTER3;\
          _x_->ETAUFTRAGSCHALTER4=ETAUFTRAGSCHALTER4;\
          strcpy(_x_->KDAUFTRAGART,KDAUFTRAGART);\
          _x_->KOART=KOART;\
          _x_->BUCHART=BUCHART;\
          _x_->DATUMVALUTA=DATUMVALUTA;\
          _x_->WERTAUFTRAG=WERTAUFTRAG;\
          _x_->WERTLIEFERUNG=WERTLIEFERUNG;\
          _x_->WERTZEILEN=WERTZEILEN;\
          _x_->ANZPOS=ANZPOS;\
          _x_->ANZPOSOB=ANZPOSOB;\
          _x_->ANZPOSLETZTE=ANZPOSLETZTE;\
          _x_->ANZPOSDAFUE=ANZPOSDAFUE;\
          _x_->ANZPOSDAFUEFEHLER=ANZPOSDAFUEFEHLER;\
          _x_->ANZALPHATEXT=ANZALPHATEXT;\
          _x_->ANZBTM=ANZBTM;\
          _x_->ANZCONTAINER=ANZCONTAINER;\
          _x_->ANZBEHAELTWECHSEL=ANZBEHAELTWECHSEL;\
          _x_->ANZBEHAELT=ANZBEHAELT;\
          _x_->ANZSONDERWANNE=ANZSONDERWANNE;\
          _x_->BEHAELTERGEWICHT=BEHAELTERGEWICHT;\
          _x_->RABATTBARPROZ=RABATTBARPROZ;\
          _x_->ZEITENDEAM=ZEITENDEAM;\
          _x_->ZEITENDEPM=ZEITENDEPM;\
          _x_->LAGERNRRECHNUNG=LAGERNRRECHNUNG;\
          _x_->AUFTRAGNRKO=AUFTRAGNRKO;\
          _x_->DMOBILPLATZNR=DMOBILPLATZNR;\
          _x_->SKDDEFEKTABSAGEN=SKDDEFEKTABSAGEN;\
          _x_->DRUCKPOSITION=DRUCKPOSITION;\
          _x_->BATCHSCHREIBEN=BATCHSCHREIBEN;\
          strcpy(_x_->BEMERKUNGEN,BEMERKUNGEN);\
          strcpy(_x_->KUNDETEXT,KUNDETEXT);\
          _x_->HERKUNFTFILIALE=HERKUNFTFILIALE;\
          strcpy(_x_->NAECHSTETOUR,NAECHSTETOUR);\
          strcpy(_x_->LETZTETOUR,LETZTETOUR);\
          _x_->DAFUEAUFTRAGNR=DAFUEAUFTRAGNR;\
          strcpy(_x_->DAFUEGERAETENAME,DAFUEGERAETENAME);\
          _x_->VERTRIEBSZENTRUMNR=VERTRIEBSZENTRUMNR;\
          _x_->KUNDENNR=KUNDENNR;\
          _x_->KDAUFTRAGNRFILIALE=KDAUFTRAGNRFILIALE;\
          _x_->SENDESTATUS=SENDESTATUS;\
          _x_->POOLTYP=POOLTYP;\
          _x_->POOLNR=POOLNR;\
          strcpy(_x_->ZUGRUND,ZUGRUND);\
          _x_->DATUMAUSLIEFERUNG=DATUMAUSLIEFERUNG;\
          _x_->KDAUFTRAGNRORG=KDAUFTRAGNRORG;\
          _x_->DATUMORG=DATUMORG;\
          _x_->KZRESTORED=KZRESTORED;\
          _x_->BATCHAUFTRAGNR=BATCHAUFTRAGNR;\
          strcpy(_x_->SUB_ORDER_TYPE,SUB_ORDER_TYPE);\
          strcpy(_x_->PAYMENT_TERM,PAYMENT_TERM);\
          _x_->ANZAUF=ANZAUF;\
          _x_->DATUMVALUTABATCH=DATUMVALUTABATCH;\
          _x_->VALUTAMONAUTO=VALUTAMONAUTO;\
          _x_->VALUTAMONMANUELL=VALUTAMONMANUELL;\
          _x_->TENDERNO=TENDERNO;\
          _x_->DATUMVERSAND=DATUMVERSAND;\
          _x_->DATUMBTM=DATUMBTM;\
          strcpy(_x_->BTMFORMULARNR,BTMFORMULARNR);\
          _x_->WERTNETTO=WERTNETTO;\
          _x_->WERTRABATT=WERTRABATT;\
          strcpy(_x_->INVOICENUMBER,INVOICENUMBER);\
          _x_->PAYMENTDATE=PAYMENTDATE;\
          _x_->PAYMENTTYPE=PAYMENTTYPE;\
          _x_->ETAUFTRAGSCHALTER5=ETAUFTRAGSCHALTER5;\
          _x_->ETAUFTRAGSCHALTER6=ETAUFTRAGSCHALTER6;\
          _x_->DRIVERID=DRIVERID;\
          strcpy(_x_->XMLREFERENCENO,XMLREFERENCENO);\
          _x_->LOGISTICVOLUME=LOGISTICVOLUME;\
          strcpy(_x_->ORDERLABEL,ORDERLABEL);\
          _x_->DPODAYS=DPODAYS;\
          _x_->ORDERPERIODID=ORDERPERIODID;\



/* FunctionNumber-Define of kdauftrag *****************************************/


#ifdef PRZ_OLD_FUNCTION
/* Old-FunctionNumber-Define of kdauftrag *************************************/


#endif

/* C++ Class ******************************************************************/

#ifdef TRANSCLASS

#include<vector>
using namespace std;

/* ppunixc */
#include <sockclient.h>
#include <ppstring.h>
#include <ppgeneric.h>

/* must be implemented */
void FehlerBehandlung(int rc, const char * const error_msg);

#ifndef __VIRTUAL_DADE_CLASS__
#define __VIRTUAL_DADE_CLASS__

class ppDadeVirtual {
public:
    virtual    ~ppDadeVirtual() {};
    virtual int SelList      (int FetchRel = 1, int pos = 0) = 0;
    virtual int SelListHist  (int FetchRel = 1, int pos = 0) = 0;
    virtual int SelListFuture(int FetchRel = 1, int pos = 0) = 0;
    virtual int Load         (int pos = 0                  ) = 0;
    virtual int Delete       (int pos = 0                  ) = 0;
    virtual int Save         (int pos = 0                  ) = 0;
};
#endif

class CKDAUFTRAG : public ppDadeVirtual {
public:
    kdauftragS s;
    int  rc;
    char error_msg[81];
private:
    bool bOpenCursor;
    bool bEndOfSelect;
    int  FncNumber;
    int  CursorPos;
    int  AnzPos;
    vector<kdauftragS> lst; // class list

public:
    unsigned int GetSize() const { return static_cast<unsigned int>(lst.size()); };
    void         ClearStruct() { s.clear(); }
    bool         SetData(unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     s = lst.at(i);
                     return true;
                 }
    bool         SetList(const unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     vector< kdauftragS >::iterator it = lst.begin() + i;
                     *it = s;
                     return true;
                 }
    bool         InsList() {
                     Strip(s);
                     kdauftragS c = s;
                     lst.insert(lst.end(), c);
                     AnzPos++;
                     return true;
                 }
    bool         DelList(const unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     vector< kdauftragS >::iterator it = lst.begin() + i;
                     if (it != lst.end())
                         lst.erase(it);
                     if (--AnzPos < 0)
                         AnzPos = 0;
                     return true;
                 }

    vector<kdauftragS>::iterator
                 beginList() { return lst.begin(); }
    vector<kdauftragS>::iterator
                 endList  () { return lst.end  (); }

    long         GetKdauftragnr() const { return s.KDAUFTRAGNR; }
    const char*  GetKdauftragstat(ppString & t) const { t = s.KDAUFTRAGSTAT; t.erasespace(ppString::END); return t.c_str(); }
    long         GetIdfnr() const { return s.IDFNR; }
    const char*  GetGeraetname(ppString & t) const { t = s.GERAETNAME; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetTourid(ppString & t) const { t = s.TOURID; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetTouridalt(ppString & t) const { t = s.TOURIDALT; t.erasespace(ppString::END); return t.c_str(); }
    long         GetPersonalnr() const { return s.PERSONALNR; }
    const char*  GetMatchcode(ppString & t) const { t = s.MATCHCODE; t.erasespace(ppString::END); return t.c_str(); }
    long         GetRechnungnr() const { return s.RECHNUNGNR; }
    short        GetFilialnr() const { return s.FILIALNR; }
    long         GetEtauftragschalter1() const { return s.ETAUFTRAGSCHALTER1; }
    long         GetEtauftragschalter2() const { return s.ETAUFTRAGSCHALTER2; }
    long         GetEtauftragschalter3() const { return s.ETAUFTRAGSCHALTER3; }
    long         GetEtauftragschalter4() const { return s.ETAUFTRAGSCHALTER4; }
    const char*  GetKdauftragart(ppString & t) const { t = s.KDAUFTRAGART; t.erasespace(ppString::END); return t.c_str(); }
    char         GetKoart() const { return s.KOART[0]; }
    char         GetBuchart() const { return s.BUCHART[0]; }
    long         GetDatumvaluta() const { return s.DATUMVALUTA; }
    double       GetWertauftrag() const { return s.WERTAUFTRAG; }
    double       GetWertlieferung() const { return s.WERTLIEFERUNG; }
    double       GetWertzeilen() const { return s.WERTZEILEN; }
    long         GetAnzpos() const { return s.ANZPOS; }
    long         GetAnzposob() const { return s.ANZPOSOB; }
    long         GetAnzposletzte() const { return s.ANZPOSLETZTE; }
    long         GetAnzposdafue() const { return s.ANZPOSDAFUE; }
    long         GetAnzposdafuefehler() const { return s.ANZPOSDAFUEFEHLER; }
    long         GetAnzalphatext() const { return s.ANZALPHATEXT; }
    long         GetAnzbtm() const { return s.ANZBTM; }
    long         GetAnzcontainer() const { return s.ANZCONTAINER; }
    long         GetAnzbehaeltwechsel() const { return s.ANZBEHAELTWECHSEL; }
    long         GetAnzbehaelt() const { return s.ANZBEHAELT; }
    long         GetAnzsonderwanne() const { return s.ANZSONDERWANNE; }
    long         GetBehaeltergewicht() const { return s.BEHAELTERGEWICHT; }
    double       GetRabattbarproz() const { return s.RABATTBARPROZ; }
    long         GetZeitendeam() const { return s.ZEITENDEAM; }
    long         GetZeitendepm() const { return s.ZEITENDEPM; }
    char         GetLagernrrechnung() const { return s.LAGERNRRECHNUNG[0]; }
    long         GetAuftragnrko() const { return s.AUFTRAGNRKO; }
    long         GetDmobilplatznr() const { return s.DMOBILPLATZNR; }
    char         GetSkddefektabsagen() const { return s.SKDDEFEKTABSAGEN[0]; }
    long         GetDruckposition() const { return s.DRUCKPOSITION; }
    long         GetBatchschreiben() const { return s.BATCHSCHREIBEN; }
    const char*  GetBemerkungen(ppString & t) const { t = s.BEMERKUNGEN; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetKundetext(ppString & t) const { t = s.KUNDETEXT; t.erasespace(ppString::END); return t.c_str(); }
    short        GetHerkunftfiliale() const { return s.HERKUNFTFILIALE; }
    const char*  GetNaechstetour(ppString & t) const { t = s.NAECHSTETOUR; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetLetztetour(ppString & t) const { t = s.LETZTETOUR; t.erasespace(ppString::END); return t.c_str(); }
    long         GetDafueauftragnr() const { return s.DAFUEAUFTRAGNR; }
    const char*  GetDafuegeraetename(ppString & t) const { t = s.DAFUEGERAETENAME; t.erasespace(ppString::END); return t.c_str(); }
    short        GetVertriebszentrumnr() const { return s.VERTRIEBSZENTRUMNR; }
    long         GetKundennr() const { return s.KUNDENNR; }
    long         GetKdauftragnrfiliale() const { return s.KDAUFTRAGNRFILIALE; }
    short        GetSendestatus() const { return s.SENDESTATUS; }
    short        GetPooltyp() const { return s.POOLTYP; }
    short        GetPoolnr() const { return s.POOLNR; }
    const char*  GetZugrund(ppString & t) const { t = s.ZUGRUND; t.erasespace(ppString::END); return t.c_str(); }
    long         GetDatumauslieferung() const { return s.DATUMAUSLIEFERUNG; }
    long         GetKdauftragnrorg() const { return s.KDAUFTRAGNRORG; }
    long         GetDatumorg() const { return s.DATUMORG; }
    char         GetKzrestored() const { return s.KZRESTORED[0]; }
    long         GetBatchauftragnr() const { return s.BATCHAUFTRAGNR; }
    const char*  GetSub_order_type(ppString & t) const { t = s.SUB_ORDER_TYPE; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetPayment_term(ppString & t) const { t = s.PAYMENT_TERM; t.erasespace(ppString::END); return t.c_str(); }
    short        GetAnzauf() const { return s.ANZAUF; }
    long         GetDatumvalutabatch() const { return s.DATUMVALUTABATCH; }
    short        GetValutamonauto() const { return s.VALUTAMONAUTO; }
    short        GetValutamonmanuell() const { return s.VALUTAMONMANUELL; }
    long         GetTenderno() const { return s.TENDERNO; }
    long         GetDatumversand() const { return s.DATUMVERSAND; }
    long         GetDatumbtm() const { return s.DATUMBTM; }
    const char*  GetBtmformularnr(ppString & t) const { t = s.BTMFORMULARNR; t.erasespace(ppString::END); return t.c_str(); }
    double       GetWertnetto() const { return s.WERTNETTO; }
    double       GetWertrabatt() const { return s.WERTRABATT; }
    const char*  GetInvoicenumber(ppString & t) const { t = s.INVOICENUMBER; t.erasespace(ppString::END); return t.c_str(); }
    long         GetPaymentdate() const { return s.PAYMENTDATE; }
    char         GetPaymenttype() const { return s.PAYMENTTYPE[0]; }
    long         GetEtauftragschalter5() const { return s.ETAUFTRAGSCHALTER5; }
    long         GetEtauftragschalter6() const { return s.ETAUFTRAGSCHALTER6; }
    long         GetDriverid() const { return s.DRIVERID; }
    const char*  GetXmlreferenceno(ppString & t) const { t = s.XMLREFERENCENO; t.erasespace(ppString::END); return t.c_str(); }
    long         GetLogisticvolume() const { return s.LOGISTICVOLUME; }
    const char*  GetOrderlabel(ppString & t) const { t = s.ORDERLABEL; t.erasespace(ppString::END); return t.c_str(); }
    short        GetDpodays() const { return s.DPODAYS; }
    long         GetOrderperiodid() const { return s.ORDERPERIODID; }

    const kdauftragS &
                 GetStruct() const { return s; }
    void         SetKdauftragnr(long t) { s.KDAUFTRAGNR = t; }
    void         SetKdauftragstat(const ppString & t) { ppGStrCopy(s.KDAUFTRAGSTAT, t.c_str(), L_KDAUFTRAG_KDAUFTRAGSTAT); }
    void         SetIdfnr(long t) { s.IDFNR = t; }
    void         SetGeraetname(const ppString & t) { ppGStrCopy(s.GERAETNAME, t.c_str(), L_KDAUFTRAG_GERAETNAME); }
    void         SetTourid(const ppString & t) { ppGStrCopy(s.TOURID, t.c_str(), L_KDAUFTRAG_TOURID); }
    void         SetTouridalt(const ppString & t) { ppGStrCopy(s.TOURIDALT, t.c_str(), L_KDAUFTRAG_TOURIDALT); }
    void         SetPersonalnr(long t) { s.PERSONALNR = t; }
    void         SetMatchcode(const ppString & t) { ppGStrCopy(s.MATCHCODE, t.c_str(), L_KDAUFTRAG_MATCHCODE); }
    void         SetRechnungnr(long t) { s.RECHNUNGNR = t; }
    void         SetFilialnr(short t) { s.FILIALNR = t; }
    void         SetEtauftragschalter1(long t) { s.ETAUFTRAGSCHALTER1 = t; }
    void         SetEtauftragschalter2(long t) { s.ETAUFTRAGSCHALTER2 = t; }
    void         SetEtauftragschalter3(long t) { s.ETAUFTRAGSCHALTER3 = t; }
    void         SetEtauftragschalter4(long t) { s.ETAUFTRAGSCHALTER4 = t; }
    void         SetKdauftragart(const ppString & t) { ppGStrCopy(s.KDAUFTRAGART, t.c_str(), L_KDAUFTRAG_KDAUFTRAGART); }
    void         SetKoart(char t) { s.KOART[0] = t; s.KOART[1] = '\0';}
    void         SetBuchart(char t) { s.BUCHART[0] = t; s.BUCHART[1] = '\0';}
    void         SetDatumvaluta(long t) { s.DATUMVALUTA = t; }
    void         SetWertauftrag(double t) { s.WERTAUFTRAG = t; }
    void         SetWertlieferung(double t) { s.WERTLIEFERUNG = t; }
    void         SetWertzeilen(double t) { s.WERTZEILEN = t; }
    void         SetAnzpos(long t) { s.ANZPOS = t; }
    void         SetAnzposob(long t) { s.ANZPOSOB = t; }
    void         SetAnzposletzte(long t) { s.ANZPOSLETZTE = t; }
    void         SetAnzposdafue(long t) { s.ANZPOSDAFUE = t; }
    void         SetAnzposdafuefehler(long t) { s.ANZPOSDAFUEFEHLER = t; }
    void         SetAnzalphatext(long t) { s.ANZALPHATEXT = t; }
    void         SetAnzbtm(long t) { s.ANZBTM = t; }
    void         SetAnzcontainer(long t) { s.ANZCONTAINER = t; }
    void         SetAnzbehaeltwechsel(long t) { s.ANZBEHAELTWECHSEL = t; }
    void         SetAnzbehaelt(long t) { s.ANZBEHAELT = t; }
    void         SetAnzsonderwanne(long t) { s.ANZSONDERWANNE = t; }
    void         SetBehaeltergewicht(long t) { s.BEHAELTERGEWICHT = t; }
    void         SetRabattbarproz(double t) { s.RABATTBARPROZ = t; }
    void         SetZeitendeam(long t) { s.ZEITENDEAM = t; }
    void         SetZeitendepm(long t) { s.ZEITENDEPM = t; }
    void         SetLagernrrechnung(char t) { s.LAGERNRRECHNUNG[0] = t; s.LAGERNRRECHNUNG[1] = '\0';}
    void         SetAuftragnrko(long t) { s.AUFTRAGNRKO = t; }
    void         SetDmobilplatznr(long t) { s.DMOBILPLATZNR = t; }
    void         SetSkddefektabsagen(char t) { s.SKDDEFEKTABSAGEN[0] = t; s.SKDDEFEKTABSAGEN[1] = '\0';}
    void         SetDruckposition(long t) { s.DRUCKPOSITION = t; }
    void         SetBatchschreiben(long t) { s.BATCHSCHREIBEN = t; }
    void         SetBemerkungen(const ppString & t) { ppGStrCopy(s.BEMERKUNGEN, t.c_str(), L_KDAUFTRAG_BEMERKUNGEN); }
    void         SetKundetext(const ppString & t) { ppGStrCopy(s.KUNDETEXT, t.c_str(), L_KDAUFTRAG_KUNDETEXT); }
    void         SetHerkunftfiliale(short t) { s.HERKUNFTFILIALE = t; }
    void         SetNaechstetour(const ppString & t) { ppGStrCopy(s.NAECHSTETOUR, t.c_str(), L_KDAUFTRAG_NAECHSTETOUR); }
    void         SetLetztetour(const ppString & t) { ppGStrCopy(s.LETZTETOUR, t.c_str(), L_KDAUFTRAG_LETZTETOUR); }
    void         SetDafueauftragnr(long t) { s.DAFUEAUFTRAGNR = t; }
    void         SetDafuegeraetename(const ppString & t) { ppGStrCopy(s.DAFUEGERAETENAME, t.c_str(), L_KDAUFTRAG_DAFUEGERAETENAME); }
    void         SetVertriebszentrumnr(short t) { s.VERTRIEBSZENTRUMNR = t; }
    void         SetKundennr(long t) { s.KUNDENNR = t; }
    void         SetKdauftragnrfiliale(long t) { s.KDAUFTRAGNRFILIALE = t; }
    void         SetSendestatus(short t) { s.SENDESTATUS = t; }
    void         SetPooltyp(short t) { s.POOLTYP = t; }
    void         SetPoolnr(short t) { s.POOLNR = t; }
    void         SetZugrund(const ppString & t) { ppGStrCopy(s.ZUGRUND, t.c_str(), L_KDAUFTRAG_ZUGRUND); }
    void         SetDatumauslieferung(long t) { s.DATUMAUSLIEFERUNG = t; }
    void         SetKdauftragnrorg(long t) { s.KDAUFTRAGNRORG = t; }
    void         SetDatumorg(long t) { s.DATUMORG = t; }
    void         SetKzrestored(char t) { s.KZRESTORED[0] = t; s.KZRESTORED[1] = '\0';}
    void         SetBatchauftragnr(long t) { s.BATCHAUFTRAGNR = t; }
    void         SetSub_order_type(const ppString & t) { ppGStrCopy(s.SUB_ORDER_TYPE, t.c_str(), L_KDAUFTRAG_SUB_ORDER_TYPE); }
    void         SetPayment_term(const ppString & t) { ppGStrCopy(s.PAYMENT_TERM, t.c_str(), L_KDAUFTRAG_PAYMENT_TERM); }
    void         SetAnzauf(short t) { s.ANZAUF = t; }
    void         SetDatumvalutabatch(long t) { s.DATUMVALUTABATCH = t; }
    void         SetValutamonauto(short t) { s.VALUTAMONAUTO = t; }
    void         SetValutamonmanuell(short t) { s.VALUTAMONMANUELL = t; }
    void         SetTenderno(long t) { s.TENDERNO = t; }
    void         SetDatumversand(long t) { s.DATUMVERSAND = t; }
    void         SetDatumbtm(long t) { s.DATUMBTM = t; }
    void         SetBtmformularnr(const ppString & t) { ppGStrCopy(s.BTMFORMULARNR, t.c_str(), L_KDAUFTRAG_BTMFORMULARNR); }
    void         SetWertnetto(double t) { s.WERTNETTO = t; }
    void         SetWertrabatt(double t) { s.WERTRABATT = t; }
    void         SetInvoicenumber(const ppString & t) { ppGStrCopy(s.INVOICENUMBER, t.c_str(), L_KDAUFTRAG_INVOICENUMBER); }
    void         SetPaymentdate(long t) { s.PAYMENTDATE = t; }
    void         SetPaymenttype(char t) { s.PAYMENTTYPE[0] = t; s.PAYMENTTYPE[1] = '\0';}
    void         SetEtauftragschalter5(long t) { s.ETAUFTRAGSCHALTER5 = t; }
    void         SetEtauftragschalter6(long t) { s.ETAUFTRAGSCHALTER6 = t; }
    void         SetDriverid(long t) { s.DRIVERID = t; }
    void         SetXmlreferenceno(const ppString & t) { ppGStrCopy(s.XMLREFERENCENO, t.c_str(), L_KDAUFTRAG_XMLREFERENCENO); }
    void         SetLogisticvolume(long t) { s.LOGISTICVOLUME = t; }
    void         SetOrderlabel(const ppString & t) { ppGStrCopy(s.ORDERLABEL, t.c_str(), L_KDAUFTRAG_ORDERLABEL); }
    void         SetDpodays(short t) { s.DPODAYS = t; }
    void         SetOrderperiodid(long t) { s.ORDERPERIODID = t; }

    void         SetStruct(const kdauftragS & t) { s = t; }


    // virtual functions
public:
    int          Load(int pos = 0) { pos = pos; return 1; }
    int          Save(int pos = 0) { pos = pos; return 1; }
    int          Delete(int pos = 0) { pos = pos; return 1; }
    int          SelList(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }
    int          SelListHist(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }
    int          SelListFuture(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }

    // constructor
    CKDAUFTRAG() {
        ::buf_default((void *)&s, KDAUFTRAG_BES, KDAUFTRAG_ANZ);
        bOpenCursor   = false;
        bEndOfSelect  = false;
        FncNumber     = 0;
        CursorPos     = 0;
        AnzPos        = 0;
        rc            = 0;
        s.clear();
    }

    // destructor
    virtual ~CKDAUFTRAG() {
    }

    // buffer init
    void buf_default() {
        ::buf_default((void *)&s, KDAUFTRAG_BES, KDAUFTRAG_ANZ);
    }

    // socket server call
    int Server(int fkt_nr, int pos = 0) {
    #ifdef WIN32
        rc = ::ServerNr(pos, fkt_nr, (void *)&s, KDAUFTRAG_BES, (int)KDAUFTRAG_ANZ, error_msg);
    #else
        rc = ::Server(fkt_nr, (void *)&s, KDAUFTRAG_BES, (int)KDAUFTRAG_ANZ, error_msg);
    #endif
        if (rc < 0)
            FehlerBehandlung( rc, error_msg );
        return rc;
    }

private:
    void Strip(N_KDAUFTRAG & d) {
        d = d;
    #ifdef WIN32
        ppGStripLast(d.KDAUFTRAGSTAT);
        ppGStripLast(d.GERAETNAME);
        ppGStripLast(d.TOURID);
        ppGStripLast(d.TOURIDALT);
        ppGStripLast(d.MATCHCODE);
        ppGStripLast(d.KDAUFTRAGART);
        ppGStripLast(d.BEMERKUNGEN);
        ppGStripLast(d.KUNDETEXT);
        ppGStripLast(d.NAECHSTETOUR);
        ppGStripLast(d.LETZTETOUR);
        ppGStripLast(d.DAFUEGERAETENAME);
        ppGStripLast(d.ZUGRUND);
        ppGStripLast(d.SUB_ORDER_TYPE);
        ppGStripLast(d.PAYMENT_TERM);
        ppGStripLast(d.BTMFORMULARNR);
        ppGStripLast(d.INVOICENUMBER);
        ppGStripLast(d.XMLREFERENCENO);
        ppGStripLast(d.ORDERLABEL);
    #endif
    }

    int UniqueServerCall(int FncNr, int pos = 0) {
    #ifndef __DADE_LOAD__
       rc = ::ServerNr(pos, FncNr, (void *)&s, KDAUFTRAG_BES, (int)KDAUFTRAG_ANZ, error_msg);
    #else
       pos = pos;
       rc = DistributorFunSelect(FncNr, (void *)&s, error_msg, &rc);
    #endif
       if (rc < 0)
           FehlerBehandlung( rc, error_msg );
       return rc;
    }
};
#endif    // TRANSCLASS
/* CreateSqlStatement of KDAUFTRAG ********************************************/

 #define KDAUFTRAG_CREATE(x) EXEC SQL create table x (\
         KDAUFTRAGNR integer default 0 not null,\
         KDAUFTRAGSTAT char(16) default " " not null,\
         IDFNR integer default 0 not null,\
         GERAETNAME char(8) default " " not null,\
         TOURID char(6) default " " not null,\
         TOURIDALT char(6) default " " not null,\
         PERSONALNR integer default 0 not null,\
         MATCHCODE char(12) default " " not null,\
         RECHNUNGNR integer default 0 not null,\
         FILIALNR smallint default 0 not null,\
         ETAUFTRAGSCHALTER1 integer default 0 not null,\
         ETAUFTRAGSCHALTER2 integer default 0 not null,\
         ETAUFTRAGSCHALTER3 integer default 0 not null,\
         ETAUFTRAGSCHALTER4 integer default 0 not null,\
         KDAUFTRAGART char(2) default " " not null,\
         KOART char(1) default " " not null,\
         BUCHART char(1) default " " not null,\
         DATUMVALUTA integer default 0 not null,\
         WERTAUFTRAG decimal(11,2) default 0 not null,\
         WERTLIEFERUNG decimal(11,2) default 0 not null,\
         WERTZEILEN decimal(11,2) default 0 not null,\
         ANZPOS integer default 0 not null,\
         ANZPOSOB integer default 0 not null,\
         ANZPOSLETZTE integer default 0 not null,\
         ANZPOSDAFUE integer default 0 not null,\
         ANZPOSDAFUEFEHLER integer default 0 not null,\
         ANZALPHATEXT integer default 0 not null,\
         ANZBTM integer default 0 not null,\
         ANZCONTAINER integer default 0 not null,\
         ANZBEHAELTWECHSEL integer default 0 not null,\
         ANZBEHAELT integer default 0 not null,\
         ANZSONDERWANNE integer default 0 not null,\
         BEHAELTERGEWICHT integer default 0 not null,\
         RABATTBARPROZ decimal(5,2) default 0 not null,\
         ZEITENDEAM integer default 0 not null,\
         ZEITENDEPM integer default 0 not null,\
         LAGERNRRECHNUNG char(1) default " " not null,\
         AUFTRAGNRKO integer default 0 not null,\
         DMOBILPLATZNR integer default 0 not null,\
         SKDDEFEKTABSAGEN char(1) default " " not null,\
         DRUCKPOSITION integer default 0 not null,\
         BATCHSCHREIBEN integer default 0 not null,\
         BEMERKUNGEN varchar(240,0) default " " not null,\
         KUNDETEXT varchar(240,0) default " " not null,\
         HERKUNFTFILIALE smallint default 0 not null,\
         NAECHSTETOUR char(6) default " " not null,\
         LETZTETOUR char(6) default " " not null,\
         DAFUEAUFTRAGNR integer default 0 not null,\
         DAFUEGERAETENAME char(2) default " " not null,\
         VERTRIEBSZENTRUMNR smallint default 0 not null,\
         KUNDENNR integer default 0 not null,\
         KDAUFTRAGNRFILIALE integer default 0 not null,\
         SENDESTATUS smallint default 0 not null,\
         POOLTYP smallint default 0 not null,\
         POOLNR smallint default 0 not null,\
         ZUGRUND char(16) default " " not null,\
         DATUMAUSLIEFERUNG integer default 0 not null,\
         KDAUFTRAGNRORG integer default 0 not null,\
         DATUMORG integer default 0 not null,\
         KZRESTORED char(1) default " " not null,\
         BATCHAUFTRAGNR integer default 0 not null,\
         SUB_ORDER_TYPE char(3) default " " not null,\
         PAYMENT_TERM char(4) default " " not null,\
         ANZAUF smallint default 0 not null,\
         DATUMVALUTABATCH integer default 0 not null,\
         VALUTAMONAUTO smallint default 0 not null,\
         VALUTAMONMANUELL smallint default 0 not null,\
         TENDERNO integer default 0 not null,\
         DATUMVERSAND integer default 0 not null,\
         DATUMBTM integer default 0 not null,\
         BTMFORMULARNR char(10) default " " not null,\
         WERTNETTO decimal(11,2) default 0 not null,\
         WERTRABATT decimal(11,2) default 0 not null,\
         INVOICENUMBER char(15) default " " not null,\
         PAYMENTDATE integer default 0 not null,\
         PAYMENTTYPE char(1) default " " not null,\
         ETAUFTRAGSCHALTER5 integer default 0 not null,\
         ETAUFTRAGSCHALTER6 integer default 0 not null,\
         DRIVERID integer default 0 not null,\
         XMLREFERENCENO char(9) default " " not null,\
         LOGISTICVOLUME integer default 0 not null,\
         ORDERLABEL varchar(40,0) default " " not null,\
         DPODAYS smallint default 0 not null,\
         ORDERPERIODID integer default 0 not null) in phosix extent size 940 next size 96 lock mode row;



/* CreateIndexStatement of KDAUFTRAG ******************************************/

 #define KDAUFTRAG_CREATE_INDEX(_X_,_Y_)\
              _Y_ = 0;\
         EXEC SQL create   index i_kdauftrag_303 on _X_(\
              kdauftragstat ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_kdauftrag_304 on _X_(\
              idfnr ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_kdauftrag_305 on _X_(\
              geraetname ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_kdauftrag_306 on _X_(\
              filialnr ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_kdauftrag_307 on _X_(\
              VertriebszentrumNr,\
              KundenNr ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_kdauftrag_308 on _X_(\
              KdauftragNrFiliale ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_kdauftrag_309 on _X_(\
              datumauslieferung ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index i_kdauftrag_310 on _X_(\
              InvoiceNumber ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create   index kdauftragtourx on _X_(\
              tourid ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create unique index kdauftragx on _X_(\
              kdauftragnr ) in phosix1;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\


/* DeleteIndexStatement of KDAUFTRAG ******************************************/

 #define KDAUFTRAG_DELETE_INDEX(_X_)\
              _X_ = 0;\
         EXEC SQL drop index i_kdauftrag_303;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_kdauftrag_304;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_kdauftrag_305;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_kdauftrag_306;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_kdauftrag_307;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_kdauftrag_308;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_kdauftrag_309;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index i_kdauftrag_310;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index kdauftragtourx;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index kdauftragx;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\




#endif   // GUARD __PP_TAUFTRAG_H_
