#ifndef __PP_KDAUFTRAGPOS_H_
#define __PP_KDAUFTRAGPOS_H_

/******************************************************************************/
/* c:\dade\kdauftragpos *******************************************************/
/* produced by DADE 6.22.2 ****************************************************/
/******************************************************************************/

/* ppunixc */
#if defined (BUF_DESC) || defined (C_BUF_DESC)
#include <bufkon.h>
#endif

/* Length-Define of KDAUFTRAGPOS **********************************************/

#define L_KDAUFTRAGPOS_KDAUFTRAGNR 11
#define L_KDAUFTRAGPOS_POSNR 11
#define L_KDAUFTRAGPOS_ARTIKEL_NR 11
#define L_KDAUFTRAGPOS_POSTYP 6
#define L_KDAUFTRAGPOS_GERAETTYP 6
#define L_KDAUFTRAGPOS_FEHLERMENGE 6
#define L_KDAUFTRAGPOS_FEHLERARTIKEL 6
#define L_KDAUFTRAGPOS_ETPOSSCHALTER1 5
#define L_KDAUFTRAGPOS_ETPOSSCHALTER2 5
#define L_KDAUFTRAGPOS_ETPOSSCHALTER3 5
#define L_KDAUFTRAGPOS_ETPOSSCHALTER4 5
#define L_KDAUFTRAGPOS_ETPOSSCHALTER5 5
#define L_KDAUFTRAGPOS_ETPOSSCHALTER6 5
#define L_KDAUFTRAGPOS_MENGEBESTELLT 11
#define L_KDAUFTRAGPOS_MENGEBESTAETIGT 11
#define L_KDAUFTRAGPOS_MENGEGELIEFERT 11
#define L_KDAUFTRAGPOS_MENGEABGEBUCHT 11
#define L_KDAUFTRAGPOS_MENGENATRA 11
#define L_KDAUFTRAGPOS_MENGENATRABASIS 11
#define L_KDAUFTRAGPOS_MENGENATRAGROSSH 11
#define L_KDAUFTRAGPOS_MENGENATRAHERST 11
#define L_KDAUFTRAGPOS_PREISEKAPO 9
#define N_KDAUFTRAGPOS_PREISEKAPO 2
#define L_KDAUFTRAGPOS_PREISVKAPO 9
#define N_KDAUFTRAGPOS_PREISVKAPO 2
#define L_KDAUFTRAGPOS_PREISEKAPONETTO 9
#define N_KDAUFTRAGPOS_PREISEKAPONETTO 2
#define L_KDAUFTRAGPOS_PREISEKGROSSO 9
#define N_KDAUFTRAGPOS_PREISEKGROSSO 2
#define L_KDAUFTRAGPOS_PREISEKGROSSONA 9
#define N_KDAUFTRAGPOS_PREISEKGROSSONA 2
#define L_KDAUFTRAGPOS_RABATTFESTDM 9
#define N_KDAUFTRAGPOS_RABATTFESTDM 2
#define L_KDAUFTRAGPOS_PREISFEST 9
#define N_KDAUFTRAGPOS_PREISFEST 2
#define L_KDAUFTRAGPOS_RABATTFEST 7
#define N_KDAUFTRAGPOS_RABATTFEST 2
#define L_KDAUFTRAGPOS_PREISPROZENT 5
#define N_KDAUFTRAGPOS_PREISPROZENT 2
#define L_KDAUFTRAGPOS_KOBEHAELTNR 11
#define L_KDAUFTRAGPOS_RABATTHILFE 1
#define L_KDAUFTRAGPOS_RABATTFAEHIG 2
#define L_KDAUFTRAGPOS_ARTBESTNACHUPD 11
#define L_KDAUFTRAGPOS_UHRZEITBESTNACHUPD 11
#define L_KDAUFTRAGPOS_DATUMVERFALL 11
#define L_KDAUFTRAGPOS_MENGEGUTSCHRIFT 11
#define L_KDAUFTRAGPOS_LAGERBEREICHNR 6
#define L_KDAUFTRAGPOS_STATIONNR 2
#define L_KDAUFTRAGPOS_LAGERFACHNR 10
#define L_KDAUFTRAGPOS_ZUZAHLUNG 1
#define L_KDAUFTRAGPOS_BEMERKUNGEN 240
#define L_KDAUFTRAGPOS_ETARTKLASSE1 5
#define L_KDAUFTRAGPOS_ETARTSCHALTER1 5
#define L_KDAUFTRAGPOS_ETARTSCHALTER2 5
#define L_KDAUFTRAGPOS_ETARTSCHALTER3 5
#define L_KDAUFTRAGPOS_CONTSPLITMENGE 11
#define L_KDAUFTRAGPOS_SENDESTATUS 6
#define L_KDAUFTRAGPOS_HINWEIS 2
#define L_KDAUFTRAGPOS_WANNENNR 11
#define L_KDAUFTRAGPOS_MENGEVORAUSBEZUG 11
#define L_KDAUFTRAGPOS_BATCHPOSNR 11
#define L_KDAUFTRAGPOS_BEWEGUNGSART 1
#define L_KDAUFTRAGPOS_SALESTAXRATE 5
#define N_KDAUFTRAGPOS_SALESTAXRATE 2
#define L_KDAUFTRAGPOS_KDAUFTRAGBESTELLNR 9
#define L_KDAUFTRAGPOS_CODEBLOCAGE 1
#define L_KDAUFTRAGPOS_PREISEKAPOFREE 9
#define N_KDAUFTRAGPOS_PREISEKAPOFREE 2
#define L_KDAUFTRAGPOS_LINKPOSNR 11
#define L_KDAUFTRAGPOS_PREIS_TYP 6
#define L_KDAUFTRAGPOS_ARTICLE_NO_PACK 11
#define L_KDAUFTRAGPOS_PREISFAKTUR 9
#define N_KDAUFTRAGPOS_PREISFAKTUR 2
#define L_KDAUFTRAGPOS_MAXTARGETNO 6
#define L_KDAUFTRAGPOS_CONTAINERLEVEL 6
#define L_KDAUFTRAGPOS_REFUNDVALUE 9
#define N_KDAUFTRAGPOS_REFUNDVALUE 2
#define L_KDAUFTRAGPOS_PROMOTION_NO 6
#define L_KDAUFTRAGPOS_PROMOTYP 6
#define L_KDAUFTRAGPOS_CODE_TYPE 6
#define L_KDAUFTRAGPOS_ARTICLE_CODE 25
#define L_KDAUFTRAGPOS_PROBLEMSTATE 6
#define L_KDAUFTRAGPOS_ETPOSSCHALTER7 5
#define L_KDAUFTRAGPOS_ETPOSSCHALTER8 5
#define L_KDAUFTRAGPOS_SUBGERAETTYP 6
#define L_KDAUFTRAGPOS_KZPRISO 1
#define L_KDAUFTRAGPOS_BUSINESSTYPENO 6
#define L_KDAUFTRAGPOS_TOURIDIBT 6
#define L_KDAUFTRAGPOS_IBTTOURWEEKDAY 6
#define L_KDAUFTRAGPOS_IBTTYPE 6
#define L_KDAUFTRAGPOS_ISDAYIBT 6
#define L_KDAUFTRAGPOS_IBTTYPEID 6
#define L_KDAUFTRAGPOS_PURCHASERELEVANTQTY 11
#define L_KDAUFTRAGPOS_MENGEBESTELLT_ORG 11
#define L_KDAUFTRAGPOS_MENGEBESTELLTNATRA 11
#define L_KDAUFTRAGPOS_NATRACATEGORY 6
#define L_KDAUFTRAGPOS_NATRAPHARMACYGROUP 3
#define L_KDAUFTRAGPOS_PREISEKAGP 9
#define N_KDAUFTRAGPOS_PREISEKAGP 2

/* Length/Count-Define of KDAUFTRAGPOS ****************************************/

#define LS_KDAUFTRAGPOS_KDAUFTRAGNR 10 + 1
#define LS_KDAUFTRAGPOS_POSNR 10 + 1
#define LS_KDAUFTRAGPOS_ARTIKEL_NR 10 + 1
#define LS_KDAUFTRAGPOS_POSTYP 5 + 1
#define LS_KDAUFTRAGPOS_GERAETTYP 5 + 1
#define LS_KDAUFTRAGPOS_FEHLERMENGE 5 + 1
#define LS_KDAUFTRAGPOS_FEHLERARTIKEL 5 + 1
#define LS_KDAUFTRAGPOS_ETPOSSCHALTER1 5 + 1
#define LS_KDAUFTRAGPOS_ETPOSSCHALTER2 5 + 1
#define LS_KDAUFTRAGPOS_ETPOSSCHALTER3 5 + 1
#define LS_KDAUFTRAGPOS_ETPOSSCHALTER4 5 + 1
#define LS_KDAUFTRAGPOS_ETPOSSCHALTER5 5 + 1
#define LS_KDAUFTRAGPOS_ETPOSSCHALTER6 5 + 1
#define LS_KDAUFTRAGPOS_MENGEBESTELLT 10 + 1
#define LS_KDAUFTRAGPOS_MENGEBESTAETIGT 10 + 1
#define LS_KDAUFTRAGPOS_MENGEGELIEFERT 10 + 1
#define LS_KDAUFTRAGPOS_MENGEABGEBUCHT 10 + 1
#define LS_KDAUFTRAGPOS_MENGENATRA 10 + 1
#define LS_KDAUFTRAGPOS_MENGENATRABASIS 10 + 1
#define LS_KDAUFTRAGPOS_MENGENATRAGROSSH 10 + 1
#define LS_KDAUFTRAGPOS_MENGENATRAHERST 10 + 1
#define LS_KDAUFTRAGPOS_PREISEKAPO 9 + 2
#define LS_KDAUFTRAGPOS_PREISVKAPO 9 + 2
#define LS_KDAUFTRAGPOS_PREISEKAPONETTO 9 + 2
#define LS_KDAUFTRAGPOS_PREISEKGROSSO 9 + 2
#define LS_KDAUFTRAGPOS_PREISEKGROSSONA 9 + 2
#define LS_KDAUFTRAGPOS_RABATTFESTDM 9 + 2
#define LS_KDAUFTRAGPOS_PREISFEST 9 + 2
#define LS_KDAUFTRAGPOS_RABATTFEST 7 + 2
#define LS_KDAUFTRAGPOS_PREISPROZENT 5 + 2
#define LS_KDAUFTRAGPOS_KOBEHAELTNR 10 + 1
#define LS_KDAUFTRAGPOS_RABATTHILFE 1 + 1
#define LS_KDAUFTRAGPOS_RABATTFAEHIG 2 + 1
#define LS_KDAUFTRAGPOS_ARTBESTNACHUPD 10 + 1
#define LS_KDAUFTRAGPOS_UHRZEITBESTNACHUPD 10 + 1
#define LS_KDAUFTRAGPOS_DATUMVERFALL 10 + 1
#define LS_KDAUFTRAGPOS_MENGEGUTSCHRIFT 10 + 1
#define LS_KDAUFTRAGPOS_LAGERBEREICHNR 5 + 1
#define LS_KDAUFTRAGPOS_STATIONNR 2 + 1
#define LS_KDAUFTRAGPOS_LAGERFACHNR 10 + 1
#define LS_KDAUFTRAGPOS_ZUZAHLUNG 1 + 1
#define LS_KDAUFTRAGPOS_BEMERKUNGEN 240 + 1
#define LS_KDAUFTRAGPOS_ETARTKLASSE1 5 + 1
#define LS_KDAUFTRAGPOS_ETARTSCHALTER1 5 + 1
#define LS_KDAUFTRAGPOS_ETARTSCHALTER2 5 + 1
#define LS_KDAUFTRAGPOS_ETARTSCHALTER3 5 + 1
#define LS_KDAUFTRAGPOS_CONTSPLITMENGE 10 + 1
#define LS_KDAUFTRAGPOS_SENDESTATUS 5 + 1
#define LS_KDAUFTRAGPOS_HINWEIS 2 + 1
#define LS_KDAUFTRAGPOS_WANNENNR 10 + 1
#define LS_KDAUFTRAGPOS_MENGEVORAUSBEZUG 10 + 1
#define LS_KDAUFTRAGPOS_BATCHPOSNR 10 + 1
#define LS_KDAUFTRAGPOS_BEWEGUNGSART 1 + 1
#define LS_KDAUFTRAGPOS_SALESTAXRATE 5 + 2
#define LS_KDAUFTRAGPOS_KDAUFTRAGBESTELLNR 9 + 1
#define LS_KDAUFTRAGPOS_CODEBLOCAGE 1 + 1
#define LS_KDAUFTRAGPOS_PREISEKAPOFREE 9 + 2
#define LS_KDAUFTRAGPOS_LINKPOSNR 10 + 1
#define LS_KDAUFTRAGPOS_PREIS_TYP 5 + 1
#define LS_KDAUFTRAGPOS_ARTICLE_NO_PACK 10 + 1
#define LS_KDAUFTRAGPOS_PREISFAKTUR 9 + 2
#define LS_KDAUFTRAGPOS_MAXTARGETNO 5 + 1
#define LS_KDAUFTRAGPOS_CONTAINERLEVEL 5 + 1
#define LS_KDAUFTRAGPOS_REFUNDVALUE 9 + 2
#define LS_KDAUFTRAGPOS_PROMOTION_NO 5 + 1
#define LS_KDAUFTRAGPOS_PROMOTYP 5 + 1
#define LS_KDAUFTRAGPOS_CODE_TYPE 5 + 1
#define LS_KDAUFTRAGPOS_ARTICLE_CODE 25 + 1
#define LS_KDAUFTRAGPOS_PROBLEMSTATE 5 + 1
#define LS_KDAUFTRAGPOS_ETPOSSCHALTER7 5 + 1
#define LS_KDAUFTRAGPOS_ETPOSSCHALTER8 5 + 1
#define LS_KDAUFTRAGPOS_SUBGERAETTYP 5 + 1
#define LS_KDAUFTRAGPOS_KZPRISO 1 + 1
#define LS_KDAUFTRAGPOS_BUSINESSTYPENO 5 + 1
#define LS_KDAUFTRAGPOS_TOURIDIBT 6 + 1
#define LS_KDAUFTRAGPOS_IBTTOURWEEKDAY 5 + 1
#define LS_KDAUFTRAGPOS_IBTTYPE 5 + 1
#define LS_KDAUFTRAGPOS_ISDAYIBT 5 + 1
#define LS_KDAUFTRAGPOS_IBTTYPEID 5 + 1
#define LS_KDAUFTRAGPOS_PURCHASERELEVANTQTY 10 + 1
#define LS_KDAUFTRAGPOS_MENGEBESTELLT_ORG 10 + 1
#define LS_KDAUFTRAGPOS_MENGEBESTELLTNATRA 10 + 1
#define LS_KDAUFTRAGPOS_NATRACATEGORY 5 + 1
#define LS_KDAUFTRAGPOS_NATRAPHARMACYGROUP 3 + 1
#define LS_KDAUFTRAGPOS_PREISEKAGP 9 + 2

#define KDAUFTRAGPOSKDAUFTRAGNR 0
#define KDAUFTRAGPOSPOSNR 1
#define KDAUFTRAGPOSARTIKEL_NR 2
#define KDAUFTRAGPOSPOSTYP 3
#define KDAUFTRAGPOSGERAETTYP 4
#define KDAUFTRAGPOSFEHLERMENGE 5
#define KDAUFTRAGPOSFEHLERARTIKEL 6
#define KDAUFTRAGPOSETPOSSCHALTER1 7
#define KDAUFTRAGPOSETPOSSCHALTER2 8
#define KDAUFTRAGPOSETPOSSCHALTER3 9
#define KDAUFTRAGPOSETPOSSCHALTER4 10
#define KDAUFTRAGPOSETPOSSCHALTER5 11
#define KDAUFTRAGPOSETPOSSCHALTER6 12
#define KDAUFTRAGPOSMENGEBESTELLT 13
#define KDAUFTRAGPOSMENGEBESTAETIGT 14
#define KDAUFTRAGPOSMENGEGELIEFERT 15
#define KDAUFTRAGPOSMENGEABGEBUCHT 16
#define KDAUFTRAGPOSMENGENATRA 17
#define KDAUFTRAGPOSMENGENATRABASIS 18
#define KDAUFTRAGPOSMENGENATRAGROSSH 19
#define KDAUFTRAGPOSMENGENATRAHERST 20
#define KDAUFTRAGPOSPREISEKAPO 21
#define KDAUFTRAGPOSPREISVKAPO 22
#define KDAUFTRAGPOSPREISEKAPONETTO 23
#define KDAUFTRAGPOSPREISEKGROSSO 24
#define KDAUFTRAGPOSPREISEKGROSSONA 25
#define KDAUFTRAGPOSRABATTFESTDM 26
#define KDAUFTRAGPOSPREISFEST 27
#define KDAUFTRAGPOSRABATTFEST 28
#define KDAUFTRAGPOSPREISPROZENT 29
#define KDAUFTRAGPOSKOBEHAELTNR 30
#define KDAUFTRAGPOSRABATTHILFE 31
#define KDAUFTRAGPOSRABATTFAEHIG 32
#define KDAUFTRAGPOSARTBESTNACHUPD 33
#define KDAUFTRAGPOSUHRZEITBESTNACHUPD 34
#define KDAUFTRAGPOSDATUMVERFALL 35
#define KDAUFTRAGPOSMENGEGUTSCHRIFT 36
#define KDAUFTRAGPOSLAGERBEREICHNR 37
#define KDAUFTRAGPOSSTATIONNR 38
#define KDAUFTRAGPOSLAGERFACHNR 39
#define KDAUFTRAGPOSZUZAHLUNG 40
#define KDAUFTRAGPOSBEMERKUNGEN 41
#define KDAUFTRAGPOSETARTKLASSE1 42
#define KDAUFTRAGPOSETARTSCHALTER1 43
#define KDAUFTRAGPOSETARTSCHALTER2 44
#define KDAUFTRAGPOSETARTSCHALTER3 45
#define KDAUFTRAGPOSCONTSPLITMENGE 46
#define KDAUFTRAGPOSSENDESTATUS 47
#define KDAUFTRAGPOSHINWEIS 48
#define KDAUFTRAGPOSWANNENNR 49
#define KDAUFTRAGPOSMENGEVORAUSBEZUG 50
#define KDAUFTRAGPOSBATCHPOSNR 51
#define KDAUFTRAGPOSBEWEGUNGSART 52
#define KDAUFTRAGPOSSALESTAXRATE 53
#define KDAUFTRAGPOSKDAUFTRAGBESTELLNR 54
#define KDAUFTRAGPOSCODEBLOCAGE 55
#define KDAUFTRAGPOSPREISEKAPOFREE 56
#define KDAUFTRAGPOSLINKPOSNR 57
#define KDAUFTRAGPOSPREIS_TYP 58
#define KDAUFTRAGPOSARTICLE_NO_PACK 59
#define KDAUFTRAGPOSPREISFAKTUR 60
#define KDAUFTRAGPOSMAXTARGETNO 61
#define KDAUFTRAGPOSCONTAINERLEVEL 62
#define KDAUFTRAGPOSREFUNDVALUE 63
#define KDAUFTRAGPOSPROMOTION_NO 64
#define KDAUFTRAGPOSPROMOTYP 65
#define KDAUFTRAGPOSCODE_TYPE 66
#define KDAUFTRAGPOSARTICLE_CODE 67
#define KDAUFTRAGPOSPROBLEMSTATE 68
#define KDAUFTRAGPOSETPOSSCHALTER7 69
#define KDAUFTRAGPOSETPOSSCHALTER8 70
#define KDAUFTRAGPOSSUBGERAETTYP 71
#define KDAUFTRAGPOSKZPRISO 72
#define KDAUFTRAGPOSBUSINESSTYPENO 73
#define KDAUFTRAGPOSTOURIDIBT 74
#define KDAUFTRAGPOSIBTTOURWEEKDAY 75
#define KDAUFTRAGPOSIBTTYPE 76
#define KDAUFTRAGPOSISDAYIBT 77
#define KDAUFTRAGPOSIBTTYPEID 78
#define KDAUFTRAGPOSPURCHASERELEVANTQTY 79
#define KDAUFTRAGPOSMENGEBESTELLT_ORG 80
#define KDAUFTRAGPOSMENGEBESTELLTNATRA 81
#define KDAUFTRAGPOSNATRACATEGORY 82
#define KDAUFTRAGPOSNATRAPHARMACYGROUP 83
#define KDAUFTRAGPOSPREISEKAGP 84

/* define of Buf_Desc *********************************************************/

#if defined (BUF_DESC) || defined (C_BUF_DESC)
#define KDAUFTRAGPOS_H
#define KDAUFTRAGPOS_ANZ ( sizeof(KDAUFTRAGPOS_BES) / sizeof(struct buf_desc) )
#endif

/* SqlDefine of KDAUFTRAGPOS **************************************************/

#define KDAUFTRAGPOS_LISTE \
        KDAUFTRAGPOS.KDAUFTRAGNR,\
        KDAUFTRAGPOS.POSNR,\
        KDAUFTRAGPOS.ARTIKEL_NR,\
        KDAUFTRAGPOS.POSTYP,\
        KDAUFTRAGPOS.GERAETTYP,\
        KDAUFTRAGPOS.FEHLERMENGE,\
        KDAUFTRAGPOS.FEHLERARTIKEL,\
        KDAUFTRAGPOS.ETPOSSCHALTER1,\
        KDAUFTRAGPOS.ETPOSSCHALTER2,\
        KDAUFTRAGPOS.ETPOSSCHALTER3,\
        KDAUFTRAGPOS.ETPOSSCHALTER4,\
        KDAUFTRAGPOS.ETPOSSCHALTER5,\
        KDAUFTRAGPOS.ETPOSSCHALTER6,\
        KDAUFTRAGPOS.MENGEBESTELLT,\
        KDAUFTRAGPOS.MENGEBESTAETIGT,\
        KDAUFTRAGPOS.MENGEGELIEFERT,\
        KDAUFTRAGPOS.MENGEABGEBUCHT,\
        KDAUFTRAGPOS.MENGENATRA,\
        KDAUFTRAGPOS.MENGENATRABASIS,\
        KDAUFTRAGPOS.MENGENATRAGROSSH,\
        KDAUFTRAGPOS.MENGENATRAHERST,\
        KDAUFTRAGPOS.PREISEKAPO,\
        KDAUFTRAGPOS.PREISVKAPO,\
        KDAUFTRAGPOS.PREISEKAPONETTO,\
        KDAUFTRAGPOS.PREISEKGROSSO,\
        KDAUFTRAGPOS.PREISEKGROSSONA,\
        KDAUFTRAGPOS.RABATTFESTDM,\
        KDAUFTRAGPOS.PREISFEST,\
        KDAUFTRAGPOS.RABATTFEST,\
        KDAUFTRAGPOS.PREISPROZENT,\
        KDAUFTRAGPOS.KOBEHAELTNR,\
        KDAUFTRAGPOS.RABATTHILFE,\
        KDAUFTRAGPOS.RABATTFAEHIG,\
        KDAUFTRAGPOS.ARTBESTNACHUPD,\
        KDAUFTRAGPOS.UHRZEITBESTNACHUPD,\
        KDAUFTRAGPOS.DATUMVERFALL,\
        KDAUFTRAGPOS.MENGEGUTSCHRIFT,\
        KDAUFTRAGPOS.LAGERBEREICHNR,\
        KDAUFTRAGPOS.STATIONNR,\
        KDAUFTRAGPOS.LAGERFACHNR,\
        KDAUFTRAGPOS.ZUZAHLUNG,\
        KDAUFTRAGPOS.BEMERKUNGEN,\
        KDAUFTRAGPOS.ETARTKLASSE1,\
        KDAUFTRAGPOS.ETARTSCHALTER1,\
        KDAUFTRAGPOS.ETARTSCHALTER2,\
        KDAUFTRAGPOS.ETARTSCHALTER3,\
        KDAUFTRAGPOS.CONTSPLITMENGE,\
        KDAUFTRAGPOS.SENDESTATUS,\
        KDAUFTRAGPOS.HINWEIS,\
        KDAUFTRAGPOS.WANNENNR,\
        KDAUFTRAGPOS.MENGEVORAUSBEZUG,\
        KDAUFTRAGPOS.BATCHPOSNR,\
        KDAUFTRAGPOS.BEWEGUNGSART,\
        KDAUFTRAGPOS.SALESTAXRATE,\
        KDAUFTRAGPOS.KDAUFTRAGBESTELLNR,\
        KDAUFTRAGPOS.CODEBLOCAGE,\
        KDAUFTRAGPOS.PREISEKAPOFREE,\
        KDAUFTRAGPOS.LINKPOSNR,\
        KDAUFTRAGPOS.PREIS_TYP,\
        KDAUFTRAGPOS.ARTICLE_NO_PACK,\
        KDAUFTRAGPOS.PREISFAKTUR,\
        KDAUFTRAGPOS.MAXTARGETNO,\
        KDAUFTRAGPOS.CONTAINERLEVEL,\
        KDAUFTRAGPOS.REFUNDVALUE,\
        KDAUFTRAGPOS.PROMOTION_NO,\
        KDAUFTRAGPOS.PROMOTYP,\
        KDAUFTRAGPOS.CODE_TYPE,\
        KDAUFTRAGPOS.ARTICLE_CODE,\
        KDAUFTRAGPOS.PROBLEMSTATE,\
        KDAUFTRAGPOS.ETPOSSCHALTER7,\
        KDAUFTRAGPOS.ETPOSSCHALTER8,\
        KDAUFTRAGPOS.SUBGERAETTYP,\
        KDAUFTRAGPOS.KZPRISO,\
        KDAUFTRAGPOS.BUSINESSTYPENO,\
        KDAUFTRAGPOS.TOURIDIBT,\
        KDAUFTRAGPOS.IBTTOURWEEKDAY,\
        KDAUFTRAGPOS.IBTTYPE,\
        KDAUFTRAGPOS.ISDAYIBT,\
        KDAUFTRAGPOS.IBTTYPEID,\
        KDAUFTRAGPOS.PURCHASERELEVANTQTY,\
        KDAUFTRAGPOS.MENGEBESTELLT_ORG,\
        KDAUFTRAGPOS.MENGEBESTELLTNATRA,\
        KDAUFTRAGPOS.NATRACATEGORY,\
        KDAUFTRAGPOS.NATRAPHARMACYGROUP,\
        KDAUFTRAGPOS.PREISEKAGP
#define KDAUFTRAGPOS_LISTE_390 \
        KDAUFTRAGNR,\
        POSNR,\
        ARTIKEL_NR,\
        POSTYP,\
        GERAETTYP,\
        FEHLERMENGE,\
        FEHLERARTIKEL,\
        ETPOSSCHALTER1,\
        ETPOSSCHALTER2,\
        ETPOSSCHALTER3,\
        ETPOSSCHALTER4,\
        ETPOSSCHALTER5,\
        ETPOSSCHALTER6,\
        MENGEBESTELLT,\
        MENGEBESTAETIGT,\
        MENGEGELIEFERT,\
        MENGEABGEBUCHT,\
        MENGENATRA,\
        MENGENATRABASIS,\
        MENGENATRAGROSSH,\
        MENGENATRAHERST,\
        PREISEKAPO,\
        PREISVKAPO,\
        PREISEKAPONETTO,\
        PREISEKGROSSO,\
        PREISEKGROSSONA,\
        RABATTFESTDM,\
        PREISFEST,\
        RABATTFEST,\
        PREISPROZENT,\
        KOBEHAELTNR,\
        RABATTHILFE,\
        RABATTFAEHIG,\
        ARTBESTNACHUPD,\
        UHRZEITBESTNACHUPD,\
        DATUMVERFALL,\
        MENGEGUTSCHRIFT,\
        LAGERBEREICHNR,\
        STATIONNR,\
        LAGERFACHNR,\
        ZUZAHLUNG,\
        BEMERKUNGEN,\
        ETARTKLASSE1,\
        ETARTSCHALTER1,\
        ETARTSCHALTER2,\
        ETARTSCHALTER3,\
        CONTSPLITMENGE,\
        SENDESTATUS,\
        HINWEIS,\
        WANNENNR,\
        MENGEVORAUSBEZUG,\
        BATCHPOSNR,\
        BEWEGUNGSART,\
        SALESTAXRATE,\
        KDAUFTRAGBESTELLNR,\
        CODEBLOCAGE,\
        PREISEKAPOFREE,\
        LINKPOSNR,\
        PREIS_TYP,\
        ARTICLE_NO_PACK,\
        PREISFAKTUR,\
        MAXTARGETNO,\
        CONTAINERLEVEL,\
        REFUNDVALUE,\
        PROMOTION_NO,\
        PROMOTYP,\
        CODE_TYPE,\
        ARTICLE_CODE,\
        PROBLEMSTATE,\
        ETPOSSCHALTER7,\
        ETPOSSCHALTER8,\
        SUBGERAETTYP,\
        KZPRISO,\
        BUSINESSTYPENO,\
        TOURIDIBT,\
        IBTTOURWEEKDAY,\
        IBTTYPE,\
        ISDAYIBT,\
        IBTTYPEID,\
        PURCHASERELEVANTQTY,\
        MENGEBESTELLT_ORG,\
        MENGEBESTELLTNATRA,\
        NATRACATEGORY,\
        NATRAPHARMACYGROUP,\
        PREISEKAGP
#define KDAUFTRAGPOS_PLISTE \
        "KDAUFTRAGPOS.KDAUFTRAGNR,"\
        "KDAUFTRAGPOS.POSNR,"\
        "KDAUFTRAGPOS.ARTIKEL_NR,"\
        "KDAUFTRAGPOS.POSTYP,"\
        "KDAUFTRAGPOS.GERAETTYP,"\
        "KDAUFTRAGPOS.FEHLERMENGE,"\
        "KDAUFTRAGPOS.FEHLERARTIKEL,"\
        "KDAUFTRAGPOS.ETPOSSCHALTER1,"\
        "KDAUFTRAGPOS.ETPOSSCHALTER2,"\
        "KDAUFTRAGPOS.ETPOSSCHALTER3,"\
        "KDAUFTRAGPOS.ETPOSSCHALTER4,"\
        "KDAUFTRAGPOS.ETPOSSCHALTER5,"\
        "KDAUFTRAGPOS.ETPOSSCHALTER6,"\
        "KDAUFTRAGPOS.MENGEBESTELLT,"\
        "KDAUFTRAGPOS.MENGEBESTAETIGT,"\
        "KDAUFTRAGPOS.MENGEGELIEFERT,"\
        "KDAUFTRAGPOS.MENGEABGEBUCHT,"\
        "KDAUFTRAGPOS.MENGENATRA,"\
        "KDAUFTRAGPOS.MENGENATRABASIS,"\
        "KDAUFTRAGPOS.MENGENATRAGROSSH,"\
        "KDAUFTRAGPOS.MENGENATRAHERST,"\
        "KDAUFTRAGPOS.PREISEKAPO,"\
        "KDAUFTRAGPOS.PREISVKAPO,"\
        "KDAUFTRAGPOS.PREISEKAPONETTO,"\
        "KDAUFTRAGPOS.PREISEKGROSSO,"\
        "KDAUFTRAGPOS.PREISEKGROSSONA,"\
        "KDAUFTRAGPOS.RABATTFESTDM,"\
        "KDAUFTRAGPOS.PREISFEST,"\
        "KDAUFTRAGPOS.RABATTFEST,"\
        "KDAUFTRAGPOS.PREISPROZENT,"\
        "KDAUFTRAGPOS.KOBEHAELTNR,"\
        "KDAUFTRAGPOS.RABATTHILFE,"\
        "KDAUFTRAGPOS.RABATTFAEHIG,"\
        "KDAUFTRAGPOS.ARTBESTNACHUPD,"\
        "KDAUFTRAGPOS.UHRZEITBESTNACHUPD,"\
        "KDAUFTRAGPOS.DATUMVERFALL,"\
        "KDAUFTRAGPOS.MENGEGUTSCHRIFT,"\
        "KDAUFTRAGPOS.LAGERBEREICHNR,"\
        "KDAUFTRAGPOS.STATIONNR,"\
        "KDAUFTRAGPOS.LAGERFACHNR,"\
        "KDAUFTRAGPOS.ZUZAHLUNG,"\
        "KDAUFTRAGPOS.BEMERKUNGEN,"\
        "KDAUFTRAGPOS.ETARTKLASSE1,"\
        "KDAUFTRAGPOS.ETARTSCHALTER1,"\
        "KDAUFTRAGPOS.ETARTSCHALTER2,"\
        "KDAUFTRAGPOS.ETARTSCHALTER3,"\
        "KDAUFTRAGPOS.CONTSPLITMENGE,"\
        "KDAUFTRAGPOS.SENDESTATUS,"\
        "KDAUFTRAGPOS.HINWEIS,"\
        "KDAUFTRAGPOS.WANNENNR,"\
        "KDAUFTRAGPOS.MENGEVORAUSBEZUG,"\
        "KDAUFTRAGPOS.BATCHPOSNR,"\
        "KDAUFTRAGPOS.BEWEGUNGSART,"\
        "KDAUFTRAGPOS.SALESTAXRATE,"\
        "KDAUFTRAGPOS.KDAUFTRAGBESTELLNR,"\
        "KDAUFTRAGPOS.CODEBLOCAGE,"\
        "KDAUFTRAGPOS.PREISEKAPOFREE,"\
        "KDAUFTRAGPOS.LINKPOSNR,"\
        "KDAUFTRAGPOS.PREIS_TYP,"\
        "KDAUFTRAGPOS.ARTICLE_NO_PACK,"\
        "KDAUFTRAGPOS.PREISFAKTUR,"\
        "KDAUFTRAGPOS.MAXTARGETNO,"\
        "KDAUFTRAGPOS.CONTAINERLEVEL,"\
        "KDAUFTRAGPOS.REFUNDVALUE,"\
        "KDAUFTRAGPOS.PROMOTION_NO,"\
        "KDAUFTRAGPOS.PROMOTYP,"\
        "KDAUFTRAGPOS.CODE_TYPE,"\
        "KDAUFTRAGPOS.ARTICLE_CODE,"\
        "KDAUFTRAGPOS.PROBLEMSTATE,"\
        "KDAUFTRAGPOS.ETPOSSCHALTER7,"\
        "KDAUFTRAGPOS.ETPOSSCHALTER8,"\
        "KDAUFTRAGPOS.SUBGERAETTYP,"\
        "KDAUFTRAGPOS.KZPRISO,"\
        "KDAUFTRAGPOS.BUSINESSTYPENO,"\
        "KDAUFTRAGPOS.TOURIDIBT,"\
        "KDAUFTRAGPOS.IBTTOURWEEKDAY,"\
        "KDAUFTRAGPOS.IBTTYPE,"\
        "KDAUFTRAGPOS.ISDAYIBT,"\
        "KDAUFTRAGPOS.IBTTYPEID,"\
        "KDAUFTRAGPOS.PURCHASERELEVANTQTY,"\
        "KDAUFTRAGPOS.MENGEBESTELLT_ORG,"\
        "KDAUFTRAGPOS.MENGEBESTELLTNATRA,"\
        "KDAUFTRAGPOS.NATRACATEGORY,"\
        "KDAUFTRAGPOS.NATRAPHARMACYGROUP,"\
        "KDAUFTRAGPOS.PREISEKAGP"
#define KDAUFTRAGPOS_PELISTE \
        "KDAUFTRAGNR,"\
        "POSNR,"\
        "ARTIKEL_NR,"\
        "POSTYP,"\
        "GERAETTYP,"\
        "FEHLERMENGE,"\
        "FEHLERARTIKEL,"\
        "ETPOSSCHALTER1,"\
        "ETPOSSCHALTER2,"\
        "ETPOSSCHALTER3,"\
        "ETPOSSCHALTER4,"\
        "ETPOSSCHALTER5,"\
        "ETPOSSCHALTER6,"\
        "MENGEBESTELLT,"\
        "MENGEBESTAETIGT,"\
        "MENGEGELIEFERT,"\
        "MENGEABGEBUCHT,"\
        "MENGENATRA,"\
        "MENGENATRABASIS,"\
        "MENGENATRAGROSSH,"\
        "MENGENATRAHERST,"\
        "PREISEKAPO,"\
        "PREISVKAPO,"\
        "PREISEKAPONETTO,"\
        "PREISEKGROSSO,"\
        "PREISEKGROSSONA,"\
        "RABATTFESTDM,"\
        "PREISFEST,"\
        "RABATTFEST,"\
        "PREISPROZENT,"\
        "KOBEHAELTNR,"\
        "RABATTHILFE,"\
        "RABATTFAEHIG,"\
        "ARTBESTNACHUPD,"\
        "UHRZEITBESTNACHUPD,"\
        "DATUMVERFALL,"\
        "MENGEGUTSCHRIFT,"\
        "LAGERBEREICHNR,"\
        "STATIONNR,"\
        "LAGERFACHNR,"\
        "ZUZAHLUNG,"\
        "BEMERKUNGEN,"\
        "ETARTKLASSE1,"\
        "ETARTSCHALTER1,"\
        "ETARTSCHALTER2,"\
        "ETARTSCHALTER3,"\
        "CONTSPLITMENGE,"\
        "SENDESTATUS,"\
        "HINWEIS,"\
        "WANNENNR,"\
        "MENGEVORAUSBEZUG,"\
        "BATCHPOSNR,"\
        "BEWEGUNGSART,"\
        "SALESTAXRATE,"\
        "KDAUFTRAGBESTELLNR,"\
        "CODEBLOCAGE,"\
        "PREISEKAPOFREE,"\
        "LINKPOSNR,"\
        "PREIS_TYP,"\
        "ARTICLE_NO_PACK,"\
        "PREISFAKTUR,"\
        "MAXTARGETNO,"\
        "CONTAINERLEVEL,"\
        "REFUNDVALUE,"\
        "PROMOTION_NO,"\
        "PROMOTYP,"\
        "CODE_TYPE,"\
        "ARTICLE_CODE,"\
        "PROBLEMSTATE,"\
        "ETPOSSCHALTER7,"\
        "ETPOSSCHALTER8,"\
        "SUBGERAETTYP,"\
        "KZPRISO,"\
        "BUSINESSTYPENO,"\
        "TOURIDIBT,"\
        "IBTTOURWEEKDAY,"\
        "IBTTYPE,"\
        "ISDAYIBT,"\
        "IBTTYPEID,"\
        "PURCHASERELEVANTQTY,"\
        "MENGEBESTELLT_ORG,"\
        "MENGEBESTELLTNATRA,"\
        "NATRACATEGORY,"\
        "NATRAPHARMACYGROUP,"\
        "PREISEKAGP"
#define KDAUFTRAGPOS_UPDLISTE \
        "KDAUFTRAGNR=?,"\
        "POSNR=?,"\
        "ARTIKEL_NR=?,"\
        "POSTYP=?,"\
        "GERAETTYP=?,"\
        "FEHLERMENGE=?,"\
        "FEHLERARTIKEL=?,"\
        "ETPOSSCHALTER1=?,"\
        "ETPOSSCHALTER2=?,"\
        "ETPOSSCHALTER3=?,"\
        "ETPOSSCHALTER4=?,"\
        "ETPOSSCHALTER5=?,"\
        "ETPOSSCHALTER6=?,"\
        "MENGEBESTELLT=?,"\
        "MENGEBESTAETIGT=?,"\
        "MENGEGELIEFERT=?,"\
        "MENGEABGEBUCHT=?,"\
        "MENGENATRA=?,"\
        "MENGENATRABASIS=?,"\
        "MENGENATRAGROSSH=?,"\
        "MENGENATRAHERST=?,"\
        "PREISEKAPO=?,"\
        "PREISVKAPO=?,"\
        "PREISEKAPONETTO=?,"\
        "PREISEKGROSSO=?,"\
        "PREISEKGROSSONA=?,"\
        "RABATTFESTDM=?,"\
        "PREISFEST=?,"\
        "RABATTFEST=?,"\
        "PREISPROZENT=?,"\
        "KOBEHAELTNR=?,"\
        "RABATTHILFE=?,"\
        "RABATTFAEHIG=?,"\
        "ARTBESTNACHUPD=?,"\
        "UHRZEITBESTNACHUPD=?,"\
        "DATUMVERFALL=?,"\
        "MENGEGUTSCHRIFT=?,"\
        "LAGERBEREICHNR=?,"\
        "STATIONNR=?,"\
        "LAGERFACHNR=?,"\
        "ZUZAHLUNG=?,"\
        "BEMERKUNGEN=?,"\
        "ETARTKLASSE1=?,"\
        "ETARTSCHALTER1=?,"\
        "ETARTSCHALTER2=?,"\
        "ETARTSCHALTER3=?,"\
        "CONTSPLITMENGE=?,"\
        "SENDESTATUS=?,"\
        "HINWEIS=?,"\
        "WANNENNR=?,"\
        "MENGEVORAUSBEZUG=?,"\
        "BATCHPOSNR=?,"\
        "BEWEGUNGSART=?,"\
        "SALESTAXRATE=?,"\
        "KDAUFTRAGBESTELLNR=?,"\
        "CODEBLOCAGE=?,"\
        "PREISEKAPOFREE=?,"\
        "LINKPOSNR=?,"\
        "PREIS_TYP=?,"\
        "ARTICLE_NO_PACK=?,"\
        "PREISFAKTUR=?,"\
        "MAXTARGETNO=?,"\
        "CONTAINERLEVEL=?,"\
        "REFUNDVALUE=?,"\
        "PROMOTION_NO=?,"\
        "PROMOTYP=?,"\
        "CODE_TYPE=?,"\
        "ARTICLE_CODE=?,"\
        "PROBLEMSTATE=?,"\
        "ETPOSSCHALTER7=?,"\
        "ETPOSSCHALTER8=?,"\
        "SUBGERAETTYP=?,"\
        "KZPRISO=?,"\
        "BUSINESSTYPENO=?,"\
        "TOURIDIBT=?,"\
        "IBTTOURWEEKDAY=?,"\
        "IBTTYPE=?,"\
        "ISDAYIBT=?,"\
        "IBTTYPEID=?,"\
        "PURCHASERELEVANTQTY=?,"\
        "MENGEBESTELLT_ORG=?,"\
        "MENGEBESTELLTNATRA=?,"\
        "NATRACATEGORY=?,"\
        "NATRAPHARMACYGROUP=?,"\
        "PREISEKAGP=?"
/* SqlMacros-Define of KDAUFTRAGPOS *******************************************/

#define KDAUFTRAGPOS_ZEIGER(x) \
        :x->KDAUFTRAGNR,\
        :x->POSNR,\
        :x->ARTIKEL_NR,\
        :x->POSTYP,\
        :x->GERAETTYP,\
        :x->FEHLERMENGE,\
        :x->FEHLERARTIKEL,\
        :x->ETPOSSCHALTER1,\
        :x->ETPOSSCHALTER2,\
        :x->ETPOSSCHALTER3,\
        :x->ETPOSSCHALTER4,\
        :x->ETPOSSCHALTER5,\
        :x->ETPOSSCHALTER6,\
        :x->MENGEBESTELLT,\
        :x->MENGEBESTAETIGT,\
        :x->MENGEGELIEFERT,\
        :x->MENGEABGEBUCHT,\
        :x->MENGENATRA,\
        :x->MENGENATRABASIS,\
        :x->MENGENATRAGROSSH,\
        :x->MENGENATRAHERST,\
        :x->PREISEKAPO,\
        :x->PREISVKAPO,\
        :x->PREISEKAPONETTO,\
        :x->PREISEKGROSSO,\
        :x->PREISEKGROSSONA,\
        :x->RABATTFESTDM,\
        :x->PREISFEST,\
        :x->RABATTFEST,\
        :x->PREISPROZENT,\
        :x->KOBEHAELTNR,\
        :x->RABATTHILFE,\
        :x->RABATTFAEHIG,\
        :x->ARTBESTNACHUPD,\
        :x->UHRZEITBESTNACHUPD,\
        :x->DATUMVERFALL,\
        :x->MENGEGUTSCHRIFT,\
        :x->LAGERBEREICHNR,\
        :x->STATIONNR,\
        :x->LAGERFACHNR,\
        :x->ZUZAHLUNG,\
        :x->BEMERKUNGEN,\
        :x->ETARTKLASSE1,\
        :x->ETARTSCHALTER1,\
        :x->ETARTSCHALTER2,\
        :x->ETARTSCHALTER3,\
        :x->CONTSPLITMENGE,\
        :x->SENDESTATUS,\
        :x->HINWEIS,\
        :x->WANNENNR,\
        :x->MENGEVORAUSBEZUG,\
        :x->BATCHPOSNR,\
        :x->BEWEGUNGSART,\
        :x->SALESTAXRATE,\
        :x->KDAUFTRAGBESTELLNR,\
        :x->CODEBLOCAGE,\
        :x->PREISEKAPOFREE,\
        :x->LINKPOSNR,\
        :x->PREIS_TYP,\
        :x->ARTICLE_NO_PACK,\
        :x->PREISFAKTUR,\
        :x->MAXTARGETNO,\
        :x->CONTAINERLEVEL,\
        :x->REFUNDVALUE,\
        :x->PROMOTION_NO,\
        :x->PROMOTYP,\
        :x->CODE_TYPE,\
        :x->ARTICLE_CODE,\
        :x->PROBLEMSTATE,\
        :x->ETPOSSCHALTER7,\
        :x->ETPOSSCHALTER8,\
        :x->SUBGERAETTYP,\
        :x->KZPRISO,\
        :x->BUSINESSTYPENO,\
        :x->TOURIDIBT,\
        :x->IBTTOURWEEKDAY,\
        :x->IBTTYPE,\
        :x->ISDAYIBT,\
        :x->IBTTYPEID,\
        :x->PURCHASERELEVANTQTY,\
        :x->MENGEBESTELLT_ORG,\
        :x->MENGEBESTELLTNATRA,\
        :x->NATRACATEGORY,\
        :x->NATRAPHARMACYGROUP,\
        :x->PREISEKAGP
#define KDAUFTRAGPOS_ZEIGERSEL(x) \
        :x->KDAUFTRAGNR,\
        :x->POSNR,\
        :x->ARTIKEL_NR,\
        :x->POSTYP,\
        :x->GERAETTYP,\
        :x->FEHLERMENGE,\
        :x->FEHLERARTIKEL,\
        :x->ETPOSSCHALTER1,\
        :x->ETPOSSCHALTER2,\
        :x->ETPOSSCHALTER3,\
        :x->ETPOSSCHALTER4,\
        :x->ETPOSSCHALTER5,\
        :x->ETPOSSCHALTER6,\
        :x->MENGEBESTELLT,\
        :x->MENGEBESTAETIGT,\
        :x->MENGEGELIEFERT,\
        :x->MENGEABGEBUCHT,\
        :x->MENGENATRA,\
        :x->MENGENATRABASIS,\
        :x->MENGENATRAGROSSH,\
        :x->MENGENATRAHERST,\
        :x->PREISEKAPO,\
        :x->PREISVKAPO,\
        :x->PREISEKAPONETTO,\
        :x->PREISEKGROSSO,\
        :x->PREISEKGROSSONA,\
        :x->RABATTFESTDM,\
        :x->PREISFEST,\
        :x->RABATTFEST,\
        :x->PREISPROZENT,\
        :x->KOBEHAELTNR,\
        :x->RABATTHILFE,\
        :x->RABATTFAEHIG,\
        :x->ARTBESTNACHUPD,\
        :x->UHRZEITBESTNACHUPD,\
        :x->DATUMVERFALL,\
        :x->MENGEGUTSCHRIFT,\
        :x->LAGERBEREICHNR,\
        :x->STATIONNR,\
        :x->LAGERFACHNR,\
        :x->ZUZAHLUNG,\
        :x->BEMERKUNGEN,\
        :x->ETARTKLASSE1,\
        :x->ETARTSCHALTER1,\
        :x->ETARTSCHALTER2,\
        :x->ETARTSCHALTER3,\
        :x->CONTSPLITMENGE,\
        :x->SENDESTATUS,\
        :x->HINWEIS,\
        :x->WANNENNR,\
        :x->MENGEVORAUSBEZUG,\
        :x->BATCHPOSNR,\
        :x->BEWEGUNGSART,\
        :x->SALESTAXRATE,\
        :x->KDAUFTRAGBESTELLNR,\
        :x->CODEBLOCAGE,\
        :x->PREISEKAPOFREE,\
        :x->LINKPOSNR,\
        :x->PREIS_TYP,\
        :x->ARTICLE_NO_PACK,\
        :x->PREISFAKTUR,\
        :x->MAXTARGETNO,\
        :x->CONTAINERLEVEL,\
        :x->REFUNDVALUE,\
        :x->PROMOTION_NO,\
        :x->PROMOTYP,\
        :x->CODE_TYPE,\
        :x->ARTICLE_CODE,\
        :x->PROBLEMSTATE,\
        :x->ETPOSSCHALTER7,\
        :x->ETPOSSCHALTER8,\
        :x->SUBGERAETTYP,\
        :x->KZPRISO,\
        :x->BUSINESSTYPENO,\
        :x->TOURIDIBT,\
        :x->IBTTOURWEEKDAY,\
        :x->IBTTYPE,\
        :x->ISDAYIBT,\
        :x->IBTTYPEID,\
        :x->PURCHASERELEVANTQTY,\
        :x->MENGEBESTELLT_ORG,\
        :x->MENGEBESTELLTNATRA,\
        :x->NATRACATEGORY,\
        :x->NATRAPHARMACYGROUP,\
        :x->PREISEKAGP
#define KDAUFTRAGPOS_UPDATE(x) \
        KDAUFTRAGPOS.KDAUFTRAGNR=:x->KDAUFTRAGNR,\
        KDAUFTRAGPOS.POSNR=:x->POSNR,\
        KDAUFTRAGPOS.ARTIKEL_NR=:x->ARTIKEL_NR,\
        KDAUFTRAGPOS.POSTYP=:x->POSTYP,\
        KDAUFTRAGPOS.GERAETTYP=:x->GERAETTYP,\
        KDAUFTRAGPOS.FEHLERMENGE=:x->FEHLERMENGE,\
        KDAUFTRAGPOS.FEHLERARTIKEL=:x->FEHLERARTIKEL,\
        KDAUFTRAGPOS.ETPOSSCHALTER1=:x->ETPOSSCHALTER1,\
        KDAUFTRAGPOS.ETPOSSCHALTER2=:x->ETPOSSCHALTER2,\
        KDAUFTRAGPOS.ETPOSSCHALTER3=:x->ETPOSSCHALTER3,\
        KDAUFTRAGPOS.ETPOSSCHALTER4=:x->ETPOSSCHALTER4,\
        KDAUFTRAGPOS.ETPOSSCHALTER5=:x->ETPOSSCHALTER5,\
        KDAUFTRAGPOS.ETPOSSCHALTER6=:x->ETPOSSCHALTER6,\
        KDAUFTRAGPOS.MENGEBESTELLT=:x->MENGEBESTELLT,\
        KDAUFTRAGPOS.MENGEBESTAETIGT=:x->MENGEBESTAETIGT,\
        KDAUFTRAGPOS.MENGEGELIEFERT=:x->MENGEGELIEFERT,\
        KDAUFTRAGPOS.MENGEABGEBUCHT=:x->MENGEABGEBUCHT,\
        KDAUFTRAGPOS.MENGENATRA=:x->MENGENATRA,\
        KDAUFTRAGPOS.MENGENATRABASIS=:x->MENGENATRABASIS,\
        KDAUFTRAGPOS.MENGENATRAGROSSH=:x->MENGENATRAGROSSH,\
        KDAUFTRAGPOS.MENGENATRAHERST=:x->MENGENATRAHERST,\
        KDAUFTRAGPOS.PREISEKAPO=:x->PREISEKAPO,\
        KDAUFTRAGPOS.PREISVKAPO=:x->PREISVKAPO,\
        KDAUFTRAGPOS.PREISEKAPONETTO=:x->PREISEKAPONETTO,\
        KDAUFTRAGPOS.PREISEKGROSSO=:x->PREISEKGROSSO,\
        KDAUFTRAGPOS.PREISEKGROSSONA=:x->PREISEKGROSSONA,\
        KDAUFTRAGPOS.RABATTFESTDM=:x->RABATTFESTDM,\
        KDAUFTRAGPOS.PREISFEST=:x->PREISFEST,\
        KDAUFTRAGPOS.RABATTFEST=:x->RABATTFEST,\
        KDAUFTRAGPOS.PREISPROZENT=:x->PREISPROZENT,\
        KDAUFTRAGPOS.KOBEHAELTNR=:x->KOBEHAELTNR,\
        KDAUFTRAGPOS.RABATTHILFE=:x->RABATTHILFE,\
        KDAUFTRAGPOS.RABATTFAEHIG=:x->RABATTFAEHIG,\
        KDAUFTRAGPOS.ARTBESTNACHUPD=:x->ARTBESTNACHUPD,\
        KDAUFTRAGPOS.UHRZEITBESTNACHUPD=:x->UHRZEITBESTNACHUPD,\
        KDAUFTRAGPOS.DATUMVERFALL=:x->DATUMVERFALL,\
        KDAUFTRAGPOS.MENGEGUTSCHRIFT=:x->MENGEGUTSCHRIFT,\
        KDAUFTRAGPOS.LAGERBEREICHNR=:x->LAGERBEREICHNR,\
        KDAUFTRAGPOS.STATIONNR=:x->STATIONNR,\
        KDAUFTRAGPOS.LAGERFACHNR=:x->LAGERFACHNR,\
        KDAUFTRAGPOS.ZUZAHLUNG=:x->ZUZAHLUNG,\
        KDAUFTRAGPOS.BEMERKUNGEN=:x->BEMERKUNGEN,\
        KDAUFTRAGPOS.ETARTKLASSE1=:x->ETARTKLASSE1,\
        KDAUFTRAGPOS.ETARTSCHALTER1=:x->ETARTSCHALTER1,\
        KDAUFTRAGPOS.ETARTSCHALTER2=:x->ETARTSCHALTER2,\
        KDAUFTRAGPOS.ETARTSCHALTER3=:x->ETARTSCHALTER3,\
        KDAUFTRAGPOS.CONTSPLITMENGE=:x->CONTSPLITMENGE,\
        KDAUFTRAGPOS.SENDESTATUS=:x->SENDESTATUS,\
        KDAUFTRAGPOS.HINWEIS=:x->HINWEIS,\
        KDAUFTRAGPOS.WANNENNR=:x->WANNENNR,\
        KDAUFTRAGPOS.MENGEVORAUSBEZUG=:x->MENGEVORAUSBEZUG,\
        KDAUFTRAGPOS.BATCHPOSNR=:x->BATCHPOSNR,\
        KDAUFTRAGPOS.BEWEGUNGSART=:x->BEWEGUNGSART,\
        KDAUFTRAGPOS.SALESTAXRATE=:x->SALESTAXRATE,\
        KDAUFTRAGPOS.KDAUFTRAGBESTELLNR=:x->KDAUFTRAGBESTELLNR,\
        KDAUFTRAGPOS.CODEBLOCAGE=:x->CODEBLOCAGE,\
        KDAUFTRAGPOS.PREISEKAPOFREE=:x->PREISEKAPOFREE,\
        KDAUFTRAGPOS.LINKPOSNR=:x->LINKPOSNR,\
        KDAUFTRAGPOS.PREIS_TYP=:x->PREIS_TYP,\
        KDAUFTRAGPOS.ARTICLE_NO_PACK=:x->ARTICLE_NO_PACK,\
        KDAUFTRAGPOS.PREISFAKTUR=:x->PREISFAKTUR,\
        KDAUFTRAGPOS.MAXTARGETNO=:x->MAXTARGETNO,\
        KDAUFTRAGPOS.CONTAINERLEVEL=:x->CONTAINERLEVEL,\
        KDAUFTRAGPOS.REFUNDVALUE=:x->REFUNDVALUE,\
        KDAUFTRAGPOS.PROMOTION_NO=:x->PROMOTION_NO,\
        KDAUFTRAGPOS.PROMOTYP=:x->PROMOTYP,\
        KDAUFTRAGPOS.CODE_TYPE=:x->CODE_TYPE,\
        KDAUFTRAGPOS.ARTICLE_CODE=:x->ARTICLE_CODE,\
        KDAUFTRAGPOS.PROBLEMSTATE=:x->PROBLEMSTATE,\
        KDAUFTRAGPOS.ETPOSSCHALTER7=:x->ETPOSSCHALTER7,\
        KDAUFTRAGPOS.ETPOSSCHALTER8=:x->ETPOSSCHALTER8,\
        KDAUFTRAGPOS.SUBGERAETTYP=:x->SUBGERAETTYP,\
        KDAUFTRAGPOS.KZPRISO=:x->KZPRISO,\
        KDAUFTRAGPOS.BUSINESSTYPENO=:x->BUSINESSTYPENO,\
        KDAUFTRAGPOS.TOURIDIBT=:x->TOURIDIBT,\
        KDAUFTRAGPOS.IBTTOURWEEKDAY=:x->IBTTOURWEEKDAY,\
        KDAUFTRAGPOS.IBTTYPE=:x->IBTTYPE,\
        KDAUFTRAGPOS.ISDAYIBT=:x->ISDAYIBT,\
        KDAUFTRAGPOS.IBTTYPEID=:x->IBTTYPEID,\
        KDAUFTRAGPOS.PURCHASERELEVANTQTY=:x->PURCHASERELEVANTQTY,\
        KDAUFTRAGPOS.MENGEBESTELLT_ORG=:x->MENGEBESTELLT_ORG,\
        KDAUFTRAGPOS.MENGEBESTELLTNATRA=:x->MENGEBESTELLTNATRA,\
        KDAUFTRAGPOS.NATRACATEGORY=:x->NATRACATEGORY,\
        KDAUFTRAGPOS.NATRAPHARMACYGROUP=:x->NATRAPHARMACYGROUP,\
        KDAUFTRAGPOS.PREISEKAGP=:x->PREISEKAGP
/* SqlMacros390-Define of KDAUFTRAGPOS ****************************************/

#define KDAUFTRAGPOS_ZEIGER_390 \
        :KDAUFTRAGNR,\
        :POSNR,\
        :ARTIKEL_NR,\
        :POSTYP,\
        :GERAETTYP,\
        :FEHLERMENGE,\
        :FEHLERARTIKEL,\
        :ETPOSSCHALTER1,\
        :ETPOSSCHALTER2,\
        :ETPOSSCHALTER3,\
        :ETPOSSCHALTER4,\
        :ETPOSSCHALTER5,\
        :ETPOSSCHALTER6,\
        :MENGEBESTELLT,\
        :MENGEBESTAETIGT,\
        :MENGEGELIEFERT,\
        :MENGEABGEBUCHT,\
        :MENGENATRA,\
        :MENGENATRABASIS,\
        :MENGENATRAGROSSH,\
        :MENGENATRAHERST,\
        :PREISEKAPO,\
        :PREISVKAPO,\
        :PREISEKAPONETTO,\
        :PREISEKGROSSO,\
        :PREISEKGROSSONA,\
        :RABATTFESTDM,\
        :PREISFEST,\
        :RABATTFEST,\
        :PREISPROZENT,\
        :KOBEHAELTNR,\
        :RABATTHILFE,\
        :RABATTFAEHIG,\
        :ARTBESTNACHUPD,\
        :UHRZEITBESTNACHUPD,\
        :DATUMVERFALL,\
        :MENGEGUTSCHRIFT,\
        :LAGERBEREICHNR,\
        :STATIONNR,\
        :LAGERFACHNR,\
        :ZUZAHLUNG,\
        :BEMERKUNGEN,\
        :ETARTKLASSE1,\
        :ETARTSCHALTER1,\
        :ETARTSCHALTER2,\
        :ETARTSCHALTER3,\
        :CONTSPLITMENGE,\
        :SENDESTATUS,\
        :HINWEIS,\
        :WANNENNR,\
        :MENGEVORAUSBEZUG,\
        :BATCHPOSNR,\
        :BEWEGUNGSART,\
        :SALESTAXRATE,\
        :KDAUFTRAGBESTELLNR,\
        :CODEBLOCAGE,\
        :PREISEKAPOFREE,\
        :LINKPOSNR,\
        :PREIS_TYP,\
        :ARTICLE_NO_PACK,\
        :PREISFAKTUR,\
        :MAXTARGETNO,\
        :CONTAINERLEVEL,\
        :REFUNDVALUE,\
        :PROMOTION_NO,\
        :PROMOTYP,\
        :CODE_TYPE,\
        :ARTICLE_CODE,\
        :PROBLEMSTATE,\
        :ETPOSSCHALTER7,\
        :ETPOSSCHALTER8,\
        :SUBGERAETTYP,\
        :KZPRISO,\
        :BUSINESSTYPENO,\
        :TOURIDIBT,\
        :IBTTOURWEEKDAY,\
        :IBTTYPE,\
        :ISDAYIBT,\
        :IBTTYPEID,\
        :PURCHASERELEVANTQTY,\
        :MENGEBESTELLT_ORG,\
        :MENGEBESTELLTNATRA,\
        :NATRACATEGORY,\
        :NATRAPHARMACYGROUP,\
        :PREISEKAGP
#define KDAUFTRAGPOS_UPDATE_390 \
        KDAUFTRAGNR=:KDAUFTRAGNR,\
        POSNR=:POSNR,\
        ARTIKEL_NR=:ARTIKEL_NR,\
        POSTYP=:POSTYP,\
        GERAETTYP=:GERAETTYP,\
        FEHLERMENGE=:FEHLERMENGE,\
        FEHLERARTIKEL=:FEHLERARTIKEL,\
        ETPOSSCHALTER1=:ETPOSSCHALTER1,\
        ETPOSSCHALTER2=:ETPOSSCHALTER2,\
        ETPOSSCHALTER3=:ETPOSSCHALTER3,\
        ETPOSSCHALTER4=:ETPOSSCHALTER4,\
        ETPOSSCHALTER5=:ETPOSSCHALTER5,\
        ETPOSSCHALTER6=:ETPOSSCHALTER6,\
        MENGEBESTELLT=:MENGEBESTELLT,\
        MENGEBESTAETIGT=:MENGEBESTAETIGT,\
        MENGEGELIEFERT=:MENGEGELIEFERT,\
        MENGEABGEBUCHT=:MENGEABGEBUCHT,\
        MENGENATRA=:MENGENATRA,\
        MENGENATRABASIS=:MENGENATRABASIS,\
        MENGENATRAGROSSH=:MENGENATRAGROSSH,\
        MENGENATRAHERST=:MENGENATRAHERST,\
        PREISEKAPO=:PREISEKAPO,\
        PREISVKAPO=:PREISVKAPO,\
        PREISEKAPONETTO=:PREISEKAPONETTO,\
        PREISEKGROSSO=:PREISEKGROSSO,\
        PREISEKGROSSONA=:PREISEKGROSSONA,\
        RABATTFESTDM=:RABATTFESTDM,\
        PREISFEST=:PREISFEST,\
        RABATTFEST=:RABATTFEST,\
        PREISPROZENT=:PREISPROZENT,\
        KOBEHAELTNR=:KOBEHAELTNR,\
        RABATTHILFE=:RABATTHILFE,\
        RABATTFAEHIG=:RABATTFAEHIG,\
        ARTBESTNACHUPD=:ARTBESTNACHUPD,\
        UHRZEITBESTNACHUPD=:UHRZEITBESTNACHUPD,\
        DATUMVERFALL=:DATUMVERFALL,\
        MENGEGUTSCHRIFT=:MENGEGUTSCHRIFT,\
        LAGERBEREICHNR=:LAGERBEREICHNR,\
        STATIONNR=:STATIONNR,\
        LAGERFACHNR=:LAGERFACHNR,\
        ZUZAHLUNG=:ZUZAHLUNG,\
        BEMERKUNGEN=:BEMERKUNGEN,\
        ETARTKLASSE1=:ETARTKLASSE1,\
        ETARTSCHALTER1=:ETARTSCHALTER1,\
        ETARTSCHALTER2=:ETARTSCHALTER2,\
        ETARTSCHALTER3=:ETARTSCHALTER3,\
        CONTSPLITMENGE=:CONTSPLITMENGE,\
        SENDESTATUS=:SENDESTATUS,\
        HINWEIS=:HINWEIS,\
        WANNENNR=:WANNENNR,\
        MENGEVORAUSBEZUG=:MENGEVORAUSBEZUG,\
        BATCHPOSNR=:BATCHPOSNR,\
        BEWEGUNGSART=:BEWEGUNGSART,\
        SALESTAXRATE=:SALESTAXRATE,\
        KDAUFTRAGBESTELLNR=:KDAUFTRAGBESTELLNR,\
        CODEBLOCAGE=:CODEBLOCAGE,\
        PREISEKAPOFREE=:PREISEKAPOFREE,\
        LINKPOSNR=:LINKPOSNR,\
        PREIS_TYP=:PREIS_TYP,\
        ARTICLE_NO_PACK=:ARTICLE_NO_PACK,\
        PREISFAKTUR=:PREISFAKTUR,\
        MAXTARGETNO=:MAXTARGETNO,\
        CONTAINERLEVEL=:CONTAINERLEVEL,\
        REFUNDVALUE=:REFUNDVALUE,\
        PROMOTION_NO=:PROMOTION_NO,\
        PROMOTYP=:PROMOTYP,\
        CODE_TYPE=:CODE_TYPE,\
        ARTICLE_CODE=:ARTICLE_CODE,\
        PROBLEMSTATE=:PROBLEMSTATE,\
        ETPOSSCHALTER7=:ETPOSSCHALTER7,\
        ETPOSSCHALTER8=:ETPOSSCHALTER8,\
        SUBGERAETTYP=:SUBGERAETTYP,\
        KZPRISO=:KZPRISO,\
        BUSINESSTYPENO=:BUSINESSTYPENO,\
        TOURIDIBT=:TOURIDIBT,\
        IBTTOURWEEKDAY=:IBTTOURWEEKDAY,\
        IBTTYPE=:IBTTYPE,\
        ISDAYIBT=:ISDAYIBT,\
        IBTTYPEID=:IBTTYPEID,\
        PURCHASERELEVANTQTY=:PURCHASERELEVANTQTY,\
        MENGEBESTELLT_ORG=:MENGEBESTELLT_ORG,\
        MENGEBESTELLTNATRA=:MENGEBESTELLTNATRA,\
        NATRACATEGORY=:NATRACATEGORY,\
        NATRAPHARMACYGROUP=:NATRAPHARMACYGROUP,\
        PREISEKAGP=:PREISEKAGP
#ifdef TRANSCLASS
#include <string.h>
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* original struct of KDAUFTRAGPOS ********************************************/

#ifndef TRANSCLASS
typedef struct N_KDAUFTRAGPOS {
    long KDAUFTRAGNR;
    long POSNR;
    long ARTIKEL_NR;
    short POSTYP;
    short GERAETTYP;
    short FEHLERMENGE;
    short FEHLERARTIKEL;
    long ETPOSSCHALTER1;
    long ETPOSSCHALTER2;
    long ETPOSSCHALTER3;
    long ETPOSSCHALTER4;
    long ETPOSSCHALTER5;
    long ETPOSSCHALTER6;
    long MENGEBESTELLT;
    long MENGEBESTAETIGT;
    long MENGEGELIEFERT;
    long MENGEABGEBUCHT;
    long MENGENATRA;
    long MENGENATRABASIS;
    long MENGENATRAGROSSH;
    long MENGENATRAHERST;
    double PREISEKAPO;
    double PREISVKAPO;
    double PREISEKAPONETTO;
    double PREISEKGROSSO;
    double PREISEKGROSSONA;
    double RABATTFESTDM;
    double PREISFEST;
    double RABATTFEST;
    double PREISPROZENT;
    long KOBEHAELTNR;
    char RABATTHILFE[2];
    char RABATTFAEHIG[3];
    long ARTBESTNACHUPD;
    long UHRZEITBESTNACHUPD;
    long DATUMVERFALL;
    long MENGEGUTSCHRIFT;
    short LAGERBEREICHNR;
    char STATIONNR[3];
    char LAGERFACHNR[11];
    char ZUZAHLUNG[2];
    char BEMERKUNGEN[241];
    long ETARTKLASSE1;
    long ETARTSCHALTER1;
    long ETARTSCHALTER2;
    long ETARTSCHALTER3;
    long CONTSPLITMENGE;
    short SENDESTATUS;
    char HINWEIS[3];
    long WANNENNR;
    long MENGEVORAUSBEZUG;
    long BATCHPOSNR;
    char BEWEGUNGSART[2];
    double SALESTAXRATE;
    char KDAUFTRAGBESTELLNR[10];
    char CODEBLOCAGE[2];
    double PREISEKAPOFREE;
    long LINKPOSNR;
    short PREIS_TYP;
    long ARTICLE_NO_PACK;
    double PREISFAKTUR;
    short MAXTARGETNO;
    short CONTAINERLEVEL;
    double REFUNDVALUE;
    short PROMOTION_NO;
    short PROMOTYP;
    short CODE_TYPE;
    char ARTICLE_CODE[26];
    short PROBLEMSTATE;
    long ETPOSSCHALTER7;
    long ETPOSSCHALTER8;
    short SUBGERAETTYP;
    char KZPRISO[2];
    short BUSINESSTYPENO;
    char TOURIDIBT[7];
    short IBTTOURWEEKDAY;
    short IBTTYPE;
    short ISDAYIBT;
    short IBTTYPEID;
    long PURCHASERELEVANTQTY;
    long MENGEBESTELLT_ORG;
    long MENGEBESTELLTNATRA;
    short NATRACATEGORY;
    char NATRAPHARMACYGROUP[4];
    double PREISEKAGP;
} kdauftragposS;
#else /* TRANSCLASS */
typedef struct N_KDAUFTRAGPOS {
    long KDAUFTRAGNR;
    long POSNR;
    long ARTIKEL_NR;
    short POSTYP;
    short GERAETTYP;
    short FEHLERMENGE;
    short FEHLERARTIKEL;
    long ETPOSSCHALTER1;
    long ETPOSSCHALTER2;
    long ETPOSSCHALTER3;
    long ETPOSSCHALTER4;
    long ETPOSSCHALTER5;
    long ETPOSSCHALTER6;
    long MENGEBESTELLT;
    long MENGEBESTAETIGT;
    long MENGEGELIEFERT;
    long MENGEABGEBUCHT;
    long MENGENATRA;
    long MENGENATRABASIS;
    long MENGENATRAGROSSH;
    long MENGENATRAHERST;
    double PREISEKAPO;
    double PREISVKAPO;
    double PREISEKAPONETTO;
    double PREISEKGROSSO;
    double PREISEKGROSSONA;
    double RABATTFESTDM;
    double PREISFEST;
    double RABATTFEST;
    double PREISPROZENT;
    long KOBEHAELTNR;
    char RABATTHILFE[2];
    char RABATTFAEHIG[3];
    long ARTBESTNACHUPD;
    long UHRZEITBESTNACHUPD;
    long DATUMVERFALL;
    long MENGEGUTSCHRIFT;
    short LAGERBEREICHNR;
    char STATIONNR[3];
    char LAGERFACHNR[11];
    char ZUZAHLUNG[2];
    char BEMERKUNGEN[241];
    long ETARTKLASSE1;
    long ETARTSCHALTER1;
    long ETARTSCHALTER2;
    long ETARTSCHALTER3;
    long CONTSPLITMENGE;
    short SENDESTATUS;
    char HINWEIS[3];
    long WANNENNR;
    long MENGEVORAUSBEZUG;
    long BATCHPOSNR;
    char BEWEGUNGSART[2];
    double SALESTAXRATE;
    char KDAUFTRAGBESTELLNR[10];
    char CODEBLOCAGE[2];
    double PREISEKAPOFREE;
    long LINKPOSNR;
    short PREIS_TYP;
    long ARTICLE_NO_PACK;
    double PREISFAKTUR;
    short MAXTARGETNO;
    short CONTAINERLEVEL;
    double REFUNDVALUE;
    short PROMOTION_NO;
    short PROMOTYP;
    short CODE_TYPE;
    char ARTICLE_CODE[26];
    short PROBLEMSTATE;
    long ETPOSSCHALTER7;
    long ETPOSSCHALTER8;
    short SUBGERAETTYP;
    char KZPRISO[2];
    short BUSINESSTYPENO;
    char TOURIDIBT[7];
    short IBTTOURWEEKDAY;
    short IBTTYPE;
    short ISDAYIBT;
    short IBTTYPEID;
    long PURCHASERELEVANTQTY;
    long MENGEBESTELLT_ORG;
    long MENGEBESTELLTNATRA;
    short NATRACATEGORY;
    char NATRAPHARMACYGROUP[4];
    double PREISEKAGP;

    bool operator == (const N_KDAUFTRAGPOS& right) const {
        return (
            KDAUFTRAGNR == right.KDAUFTRAGNR &&
            POSNR == right.POSNR &&
            ARTIKEL_NR == right.ARTIKEL_NR &&
            POSTYP == right.POSTYP &&
            GERAETTYP == right.GERAETTYP &&
            FEHLERMENGE == right.FEHLERMENGE &&
            FEHLERARTIKEL == right.FEHLERARTIKEL &&
            ETPOSSCHALTER1 == right.ETPOSSCHALTER1 &&
            ETPOSSCHALTER2 == right.ETPOSSCHALTER2 &&
            ETPOSSCHALTER3 == right.ETPOSSCHALTER3 &&
            ETPOSSCHALTER4 == right.ETPOSSCHALTER4 &&
            ETPOSSCHALTER5 == right.ETPOSSCHALTER5 &&
            ETPOSSCHALTER6 == right.ETPOSSCHALTER6 &&
            MENGEBESTELLT == right.MENGEBESTELLT &&
            MENGEBESTAETIGT == right.MENGEBESTAETIGT &&
            MENGEGELIEFERT == right.MENGEGELIEFERT &&
            MENGEABGEBUCHT == right.MENGEABGEBUCHT &&
            MENGENATRA == right.MENGENATRA &&
            MENGENATRABASIS == right.MENGENATRABASIS &&
            MENGENATRAGROSSH == right.MENGENATRAGROSSH &&
            MENGENATRAHERST == right.MENGENATRAHERST &&
            PREISEKAPO == right.PREISEKAPO &&
            PREISVKAPO == right.PREISVKAPO &&
            PREISEKAPONETTO == right.PREISEKAPONETTO &&
            PREISEKGROSSO == right.PREISEKGROSSO &&
            PREISEKGROSSONA == right.PREISEKGROSSONA &&
            RABATTFESTDM == right.RABATTFESTDM &&
            PREISFEST == right.PREISFEST &&
            RABATTFEST == right.RABATTFEST &&
            PREISPROZENT == right.PREISPROZENT &&
            KOBEHAELTNR == right.KOBEHAELTNR &&
            !strcmp(RABATTHILFE, right.RABATTHILFE) &&
            !strcmp(RABATTFAEHIG, right.RABATTFAEHIG) &&
            ARTBESTNACHUPD == right.ARTBESTNACHUPD &&
            UHRZEITBESTNACHUPD == right.UHRZEITBESTNACHUPD &&
            DATUMVERFALL == right.DATUMVERFALL &&
            MENGEGUTSCHRIFT == right.MENGEGUTSCHRIFT &&
            LAGERBEREICHNR == right.LAGERBEREICHNR &&
            !strcmp(STATIONNR, right.STATIONNR) &&
            !strcmp(LAGERFACHNR, right.LAGERFACHNR) &&
            !strcmp(ZUZAHLUNG, right.ZUZAHLUNG) &&
            !strcmp(BEMERKUNGEN, right.BEMERKUNGEN) &&
            ETARTKLASSE1 == right.ETARTKLASSE1 &&
            ETARTSCHALTER1 == right.ETARTSCHALTER1 &&
            ETARTSCHALTER2 == right.ETARTSCHALTER2 &&
            ETARTSCHALTER3 == right.ETARTSCHALTER3 &&
            CONTSPLITMENGE == right.CONTSPLITMENGE &&
            SENDESTATUS == right.SENDESTATUS &&
            !strcmp(HINWEIS, right.HINWEIS) &&
            WANNENNR == right.WANNENNR &&
            MENGEVORAUSBEZUG == right.MENGEVORAUSBEZUG &&
            BATCHPOSNR == right.BATCHPOSNR &&
            !strcmp(BEWEGUNGSART, right.BEWEGUNGSART) &&
            SALESTAXRATE == right.SALESTAXRATE &&
            !strcmp(KDAUFTRAGBESTELLNR, right.KDAUFTRAGBESTELLNR) &&
            !strcmp(CODEBLOCAGE, right.CODEBLOCAGE) &&
            PREISEKAPOFREE == right.PREISEKAPOFREE &&
            LINKPOSNR == right.LINKPOSNR &&
            PREIS_TYP == right.PREIS_TYP &&
            ARTICLE_NO_PACK == right.ARTICLE_NO_PACK &&
            PREISFAKTUR == right.PREISFAKTUR &&
            MAXTARGETNO == right.MAXTARGETNO &&
            CONTAINERLEVEL == right.CONTAINERLEVEL &&
            REFUNDVALUE == right.REFUNDVALUE &&
            PROMOTION_NO == right.PROMOTION_NO &&
            PROMOTYP == right.PROMOTYP &&
            CODE_TYPE == right.CODE_TYPE &&
            !strcmp(ARTICLE_CODE, right.ARTICLE_CODE) &&
            PROBLEMSTATE == right.PROBLEMSTATE &&
            ETPOSSCHALTER7 == right.ETPOSSCHALTER7 &&
            ETPOSSCHALTER8 == right.ETPOSSCHALTER8 &&
            SUBGERAETTYP == right.SUBGERAETTYP &&
            !strcmp(KZPRISO, right.KZPRISO) &&
            BUSINESSTYPENO == right.BUSINESSTYPENO &&
            !strcmp(TOURIDIBT, right.TOURIDIBT) &&
            IBTTOURWEEKDAY == right.IBTTOURWEEKDAY &&
            IBTTYPE == right.IBTTYPE &&
            ISDAYIBT == right.ISDAYIBT &&
            IBTTYPEID == right.IBTTYPEID &&
            PURCHASERELEVANTQTY == right.PURCHASERELEVANTQTY &&
            MENGEBESTELLT_ORG == right.MENGEBESTELLT_ORG &&
            MENGEBESTELLTNATRA == right.MENGEBESTELLTNATRA &&
            NATRACATEGORY == right.NATRACATEGORY &&
            !strcmp(NATRAPHARMACYGROUP, right.NATRAPHARMACYGROUP) &&
            PREISEKAGP == right.PREISEKAGP
        );
    }
    void clear() {
#ifdef WIN32
        memset((char*)this, 0, sizeof(*this));
#else
        KDAUFTRAGNR = 0;
        POSNR = 0;
        ARTIKEL_NR = 0;
        POSTYP = 0;
        GERAETTYP = 0;
        FEHLERMENGE = 0;
        FEHLERARTIKEL = 0;
        ETPOSSCHALTER1 = 0;
        ETPOSSCHALTER2 = 0;
        ETPOSSCHALTER3 = 0;
        ETPOSSCHALTER4 = 0;
        ETPOSSCHALTER5 = 0;
        ETPOSSCHALTER6 = 0;
        MENGEBESTELLT = 0;
        MENGEBESTAETIGT = 0;
        MENGEGELIEFERT = 0;
        MENGEABGEBUCHT = 0;
        MENGENATRA = 0;
        MENGENATRABASIS = 0;
        MENGENATRAGROSSH = 0;
        MENGENATRAHERST = 0;
        PREISEKAPO = 0;
        PREISVKAPO = 0;
        PREISEKAPONETTO = 0;
        PREISEKGROSSO = 0;
        PREISEKGROSSONA = 0;
        RABATTFESTDM = 0;
        PREISFEST = 0;
        RABATTFEST = 0;
        PREISPROZENT = 0;
        KOBEHAELTNR = 0;
        strcpy(RABATTHILFE, " " );
        strcpy(RABATTFAEHIG, " " );
        ARTBESTNACHUPD = 0;
        UHRZEITBESTNACHUPD = 0;
        DATUMVERFALL = 0;
        MENGEGUTSCHRIFT = 0;
        LAGERBEREICHNR = 0;
        strcpy(STATIONNR, " " );
        strcpy(LAGERFACHNR, " " );
        strcpy(ZUZAHLUNG, " " );
        strcpy(BEMERKUNGEN, " " );
        ETARTKLASSE1 = 0;
        ETARTSCHALTER1 = 0;
        ETARTSCHALTER2 = 0;
        ETARTSCHALTER3 = 0;
        CONTSPLITMENGE = 0;
        SENDESTATUS = 0;
        strcpy(HINWEIS, " " );
        WANNENNR = 0;
        MENGEVORAUSBEZUG = 0;
        BATCHPOSNR = 0;
        strcpy(BEWEGUNGSART, " " );
        SALESTAXRATE = 0;
        strcpy(KDAUFTRAGBESTELLNR, " " );
        strcpy(CODEBLOCAGE, " " );
        PREISEKAPOFREE = 0;
        LINKPOSNR = 0;
        PREIS_TYP = 0;
        ARTICLE_NO_PACK = 0;
        PREISFAKTUR = 0;
        MAXTARGETNO = 0;
        CONTAINERLEVEL = 0;
        REFUNDVALUE = 0;
        PROMOTION_NO = 0;
        PROMOTYP = 0;
        CODE_TYPE = 0;
        strcpy(ARTICLE_CODE, " " );
        PROBLEMSTATE = 0;
        ETPOSSCHALTER7 = 0;
        ETPOSSCHALTER8 = 0;
        SUBGERAETTYP = 0;
        strcpy(KZPRISO, " " );
        BUSINESSTYPENO = 0;
        strcpy(TOURIDIBT, " " );
        IBTTOURWEEKDAY = 0;
        IBTTYPE = 0;
        ISDAYIBT = 0;
        IBTTYPEID = 0;
        PURCHASERELEVANTQTY = 0;
        MENGEBESTELLT_ORG = 0;
        MENGEBESTELLTNATRA = 0;
        NATRACATEGORY = 0;
        strcpy(NATRAPHARMACYGROUP, " " );
        PREISEKAGP = 0;
#endif
    }
} kdauftragposS;
#endif /* TRANSCLASS */

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Stringbuffer Structur of KDAUFTRAGPOS **************************************/

struct S_KDAUFTRAGPOS {
    char KDAUFTRAGNR[11];
    char POSNR[11];
    char ARTIKEL_NR[11];
    char POSTYP[7];
    char GERAETTYP[7];
    char FEHLERMENGE[7];
    char FEHLERARTIKEL[7];
    char ETPOSSCHALTER1[5 + 1];
    char ETPOSSCHALTER2[5 + 1];
    char ETPOSSCHALTER3[5 + 1];
    char ETPOSSCHALTER4[5 + 1];
    char ETPOSSCHALTER5[5 + 1];
    char ETPOSSCHALTER6[5 + 1];
    char MENGEBESTELLT[11];
    char MENGEBESTAETIGT[11];
    char MENGEGELIEFERT[11];
    char MENGEABGEBUCHT[11];
    char MENGENATRA[11];
    char MENGENATRABASIS[11];
    char MENGENATRAGROSSH[11];
    char MENGENATRAHERST[11];
    char PREISEKAPO[9 + 2];
    char PREISVKAPO[9 + 2];
    char PREISEKAPONETTO[9 + 2];
    char PREISEKGROSSO[9 + 2];
    char PREISEKGROSSONA[9 + 2];
    char RABATTFESTDM[9 + 2];
    char PREISFEST[9 + 2];
    char RABATTFEST[7 + 2];
    char PREISPROZENT[5 + 2];
    char KOBEHAELTNR[11];
    char RABATTHILFE[1 + 1];
    char RABATTFAEHIG[2 + 1];
    char ARTBESTNACHUPD[11];
    char UHRZEITBESTNACHUPD[11];
    char DATUMVERFALL[11];
    char MENGEGUTSCHRIFT[11];
    char LAGERBEREICHNR[7];
    char STATIONNR[2 + 1];
    char LAGERFACHNR[10 + 1];
    char ZUZAHLUNG[1 + 1];
    char BEMERKUNGEN[240 + 1];
    char ETARTKLASSE1[5 + 1];
    char ETARTSCHALTER1[5 + 1];
    char ETARTSCHALTER2[5 + 1];
    char ETARTSCHALTER3[5 + 1];
    char CONTSPLITMENGE[11];
    char SENDESTATUS[7];
    char HINWEIS[2 + 1];
    char WANNENNR[11];
    char MENGEVORAUSBEZUG[11];
    char BATCHPOSNR[11];
    char BEWEGUNGSART[1 + 1];
    char SALESTAXRATE[5 + 2];
    char KDAUFTRAGBESTELLNR[9 + 1];
    char CODEBLOCAGE[1 + 1];
    char PREISEKAPOFREE[9 + 2];
    char LINKPOSNR[11];
    char PREIS_TYP[7];
    char ARTICLE_NO_PACK[11];
    char PREISFAKTUR[9 + 2];
    char MAXTARGETNO[7];
    char CONTAINERLEVEL[7];
    char REFUNDVALUE[9 + 2];
    char PROMOTION_NO[7];
    char PROMOTYP[7];
    char CODE_TYPE[7];
    char ARTICLE_CODE[25 + 1];
    char PROBLEMSTATE[7];
    char ETPOSSCHALTER7[5 + 1];
    char ETPOSSCHALTER8[5 + 1];
    char SUBGERAETTYP[7];
    char KZPRISO[1 + 1];
    char BUSINESSTYPENO[7];
    char TOURIDIBT[6 + 1];
    char IBTTOURWEEKDAY[7];
    char IBTTYPE[7];
    char ISDAYIBT[7];
    char IBTTYPEID[7];
    char PURCHASERELEVANTQTY[11];
    char MENGEBESTELLT_ORG[11];
    char MENGEBESTELLTNATRA[11];
    char NATRACATEGORY[7];
    char NATRAPHARMACYGROUP[3 + 1];
    char PREISEKAGP[9 + 2];
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Stringbuffer (without strend) Structur of KDAUFTRAGPOS *********************/

struct O_KDAUFTRAGPOS {
    char KDAUFTRAGNR[11];
    char POSNR[11];
    char ARTIKEL_NR[11];
    char POSTYP[7];
    char GERAETTYP[7];
    char FEHLERMENGE[7];
    char FEHLERARTIKEL[7];
    char ETPOSSCHALTER1[5];
    char ETPOSSCHALTER2[5];
    char ETPOSSCHALTER3[5];
    char ETPOSSCHALTER4[5];
    char ETPOSSCHALTER5[5];
    char ETPOSSCHALTER6[5];
    char MENGEBESTELLT[11];
    char MENGEBESTAETIGT[11];
    char MENGEGELIEFERT[11];
    char MENGEABGEBUCHT[11];
    char MENGENATRA[11];
    char MENGENATRABASIS[11];
    char MENGENATRAGROSSH[11];
    char MENGENATRAHERST[11];
    char PREISEKAPO[9];
    char PREISVKAPO[9];
    char PREISEKAPONETTO[9];
    char PREISEKGROSSO[9];
    char PREISEKGROSSONA[9];
    char RABATTFESTDM[9];
    char PREISFEST[9];
    char RABATTFEST[7];
    char PREISPROZENT[5];
    char KOBEHAELTNR[11];
    char RABATTHILFE[1];
    char RABATTFAEHIG[2];
    char ARTBESTNACHUPD[11];
    char UHRZEITBESTNACHUPD[11];
    char DATUMVERFALL[11];
    char MENGEGUTSCHRIFT[11];
    char LAGERBEREICHNR[7];
    char STATIONNR[2];
    char LAGERFACHNR[10];
    char ZUZAHLUNG[1];
    char BEMERKUNGEN[240];
    char ETARTKLASSE1[5];
    char ETARTSCHALTER1[5];
    char ETARTSCHALTER2[5];
    char ETARTSCHALTER3[5];
    char CONTSPLITMENGE[11];
    char SENDESTATUS[7];
    char HINWEIS[2];
    char WANNENNR[11];
    char MENGEVORAUSBEZUG[11];
    char BATCHPOSNR[11];
    char BEWEGUNGSART[1];
    char SALESTAXRATE[5];
    char KDAUFTRAGBESTELLNR[9];
    char CODEBLOCAGE[1];
    char PREISEKAPOFREE[9];
    char LINKPOSNR[11];
    char PREIS_TYP[7];
    char ARTICLE_NO_PACK[11];
    char PREISFAKTUR[9];
    char MAXTARGETNO[7];
    char CONTAINERLEVEL[7];
    char REFUNDVALUE[9];
    char PROMOTION_NO[7];
    char PROMOTYP[7];
    char CODE_TYPE[7];
    char ARTICLE_CODE[25];
    char PROBLEMSTATE[7];
    char ETPOSSCHALTER7[5];
    char ETPOSSCHALTER8[5];
    char SUBGERAETTYP[7];
    char KZPRISO[1];
    char BUSINESSTYPENO[7];
    char TOURIDIBT[6];
    char IBTTOURWEEKDAY[7];
    char IBTTYPE[7];
    char ISDAYIBT[7];
    char IBTTYPEID[7];
    char PURCHASERELEVANTQTY[11];
    char MENGEBESTELLT_ORG[11];
    char MENGEBESTELLTNATRA[11];
    char NATRACATEGORY[7];
    char NATRAPHARMACYGROUP[3];
    char PREISEKAGP[9];
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Structur with real chartype of KDAUFTRAGPOS ********************************/

struct C_KDAUFTRAGPOS {
    long KDAUFTRAGNR;
    long POSNR;
    long ARTIKEL_NR;
    short POSTYP;
    short GERAETTYP;
    short FEHLERMENGE;
    short FEHLERARTIKEL;
    long ETPOSSCHALTER1;
    long ETPOSSCHALTER2;
    long ETPOSSCHALTER3;
    long ETPOSSCHALTER4;
    long ETPOSSCHALTER5;
    long ETPOSSCHALTER6;
    long MENGEBESTELLT;
    long MENGEBESTAETIGT;
    long MENGEGELIEFERT;
    long MENGEABGEBUCHT;
    long MENGENATRA;
    long MENGENATRABASIS;
    long MENGENATRAGROSSH;
    long MENGENATRAHERST;
    double PREISEKAPO;
    double PREISVKAPO;
    double PREISEKAPONETTO;
    double PREISEKGROSSO;
    double PREISEKGROSSONA;
    double RABATTFESTDM;
    double PREISFEST;
    double RABATTFEST;
    double PREISPROZENT;
    long KOBEHAELTNR;
    char RABATTHILFE;
    char RABATTFAEHIG[3];
    long ARTBESTNACHUPD;
    long UHRZEITBESTNACHUPD;
    long DATUMVERFALL;
    long MENGEGUTSCHRIFT;
    short LAGERBEREICHNR;
    char STATIONNR[3];
    char LAGERFACHNR[11];
    char ZUZAHLUNG;
    char BEMERKUNGEN[241];
    long ETARTKLASSE1;
    long ETARTSCHALTER1;
    long ETARTSCHALTER2;
    long ETARTSCHALTER3;
    long CONTSPLITMENGE;
    short SENDESTATUS;
    char HINWEIS[3];
    long WANNENNR;
    long MENGEVORAUSBEZUG;
    long BATCHPOSNR;
    char BEWEGUNGSART;
    double SALESTAXRATE;
    char KDAUFTRAGBESTELLNR[10];
    char CODEBLOCAGE;
    double PREISEKAPOFREE;
    long LINKPOSNR;
    short PREIS_TYP;
    long ARTICLE_NO_PACK;
    double PREISFAKTUR;
    short MAXTARGETNO;
    short CONTAINERLEVEL;
    double REFUNDVALUE;
    short PROMOTION_NO;
    short PROMOTYP;
    short CODE_TYPE;
    char ARTICLE_CODE[26];
    short PROBLEMSTATE;
    long ETPOSSCHALTER7;
    long ETPOSSCHALTER8;
    short SUBGERAETTYP;
    char KZPRISO;
    short BUSINESSTYPENO;
    char TOURIDIBT[7];
    short IBTTOURWEEKDAY;
    short IBTTYPE;
    short ISDAYIBT;
    short IBTTYPEID;
    long PURCHASERELEVANTQTY;
    long MENGEBESTELLT_ORG;
    long MENGEBESTELLTNATRA;
    short NATRACATEGORY;
    char NATRAPHARMACYGROUP[4];
    double PREISEKAGP;
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Sizetype  Structur (buf_desc) of KDAUFTRAGPOS ******************************/

struct I_KDAUFTRAGPOS {
    short KDAUFTRAGNR;
    short POSNR;
    short ARTIKEL_NR;
    short POSTYP;
    short GERAETTYP;
    short FEHLERMENGE;
    short FEHLERARTIKEL;
    short ETPOSSCHALTER1;
    short ETPOSSCHALTER2;
    short ETPOSSCHALTER3;
    short ETPOSSCHALTER4;
    short ETPOSSCHALTER5;
    short ETPOSSCHALTER6;
    short MENGEBESTELLT;
    short MENGEBESTAETIGT;
    short MENGEGELIEFERT;
    short MENGEABGEBUCHT;
    short MENGENATRA;
    short MENGENATRABASIS;
    short MENGENATRAGROSSH;
    short MENGENATRAHERST;
    short PREISEKAPO;
    short PREISVKAPO;
    short PREISEKAPONETTO;
    short PREISEKGROSSO;
    short PREISEKGROSSONA;
    short RABATTFESTDM;
    short PREISFEST;
    short RABATTFEST;
    short PREISPROZENT;
    short KOBEHAELTNR;
    short RABATTHILFE;
    short RABATTFAEHIG;
    short ARTBESTNACHUPD;
    short UHRZEITBESTNACHUPD;
    short DATUMVERFALL;
    short MENGEGUTSCHRIFT;
    short LAGERBEREICHNR;
    short STATIONNR;
    short LAGERFACHNR;
    short ZUZAHLUNG;
    short BEMERKUNGEN;
    short ETARTKLASSE1;
    short ETARTSCHALTER1;
    short ETARTSCHALTER2;
    short ETARTSCHALTER3;
    short CONTSPLITMENGE;
    short SENDESTATUS;
    short HINWEIS;
    short WANNENNR;
    short MENGEVORAUSBEZUG;
    short BATCHPOSNR;
    short BEWEGUNGSART;
    short SALESTAXRATE;
    short KDAUFTRAGBESTELLNR;
    short CODEBLOCAGE;
    short PREISEKAPOFREE;
    short LINKPOSNR;
    short PREIS_TYP;
    short ARTICLE_NO_PACK;
    short PREISFAKTUR;
    short MAXTARGETNO;
    short CONTAINERLEVEL;
    short REFUNDVALUE;
    short PROMOTION_NO;
    short PROMOTYP;
    short CODE_TYPE;
    short ARTICLE_CODE;
    short PROBLEMSTATE;
    short ETPOSSCHALTER7;
    short ETPOSSCHALTER8;
    short SUBGERAETTYP;
    short KZPRISO;
    short BUSINESSTYPENO;
    short TOURIDIBT;
    short IBTTOURWEEKDAY;
    short IBTTYPE;
    short ISDAYIBT;
    short IBTTYPEID;
    short PURCHASERELEVANTQTY;
    short MENGEBESTELLT_ORG;
    short MENGEBESTELLTNATRA;
    short NATRACATEGORY;
    short NATRAPHARMACYGROUP;
    short PREISEKAGP;
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

/* structures of Buf_Desc *****************************************************/

/* Structur (buf_desc) of KDAUFTRAGPOS ****************************************/

#if defined (BUF_DESC)
static struct buf_desc KDAUFTRAGPOS_BES [] = {
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 7, 2 },
   { TYP_D, 5, 2 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 2, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 2, 0 },
   { TYP_C, 10, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 240, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 2, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_D, 5, 2 },
   { TYP_C, 9, 0 },
   { TYP_C, 1, 0 },
   { TYP_D, 9, 2 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_D, 9, 2 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_D, 9, 2 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 25, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 3, 0 },
   { TYP_D, 9, 2 },
};
#elif defined (C_BUF_DESC)
static struct buf_desc KDAUFTRAGPOS_BES [] = {
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 7, 2 },
   { TYP_D, 5, 2 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 2, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 2, 0 },
   { TYP_C, 10, 0 },
   { TYP_C, 1, 0 },
   { TYP_C, 240, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 2, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C, 1, 0 },
   { TYP_D, 5, 2 },
   { TYP_C, 9, 0 },
   { TYP_C, 1, 0 },
   { TYP_D, 9, 2 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_D, 9, 2 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_D, 9, 2 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 25, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L ,  11, 0 },
   { TYP_L ,  11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 1, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_C, 3, 0 },
   { TYP_D, 9, 2 },
};
#endif

/* description for datatypes of KDAUFTRAGPOS **********************************/

 #define KDAUFTRAGPOS_S390 \
         long KDAUFTRAGNR; \
         long POSNR; \
         long ARTIKEL_NR; \
         short POSTYP; \
         short GERAETTYP; \
         short FEHLERMENGE; \
         short FEHLERARTIKEL; \
         long ETPOSSCHALTER1; \
         long ETPOSSCHALTER2; \
         long ETPOSSCHALTER3; \
         long ETPOSSCHALTER4; \
         long ETPOSSCHALTER5; \
         long ETPOSSCHALTER6; \
         long MENGEBESTELLT; \
         long MENGEBESTAETIGT; \
         long MENGEGELIEFERT; \
         long MENGEABGEBUCHT; \
         long MENGENATRA; \
         long MENGENATRABASIS; \
         long MENGENATRAGROSSH; \
         long MENGENATRAHERST; \
         double PREISEKAPO; \
         double PREISVKAPO; \
         double PREISEKAPONETTO; \
         double PREISEKGROSSO; \
         double PREISEKGROSSONA; \
         double RABATTFESTDM; \
         double PREISFEST; \
         double RABATTFEST; \
         double PREISPROZENT; \
         long KOBEHAELTNR; \
         char RABATTHILFE; \
         char RABATTFAEHIG[3]; \
         long ARTBESTNACHUPD; \
         long UHRZEITBESTNACHUPD; \
         long DATUMVERFALL; \
         long MENGEGUTSCHRIFT; \
         short LAGERBEREICHNR; \
         char STATIONNR[3]; \
         char LAGERFACHNR[11]; \
         char ZUZAHLUNG; \
         char BEMERKUNGEN[241]; \
         long ETARTKLASSE1; \
         long ETARTSCHALTER1; \
         long ETARTSCHALTER2; \
         long ETARTSCHALTER3; \
         long CONTSPLITMENGE; \
         short SENDESTATUS; \
         char HINWEIS[3]; \
         long WANNENNR; \
         long MENGEVORAUSBEZUG; \
         long BATCHPOSNR; \
         char BEWEGUNGSART; \
         double SALESTAXRATE; \
         char KDAUFTRAGBESTELLNR[10]; \
         char CODEBLOCAGE; \
         double PREISEKAPOFREE; \
         long LINKPOSNR; \
         short PREIS_TYP; \
         long ARTICLE_NO_PACK; \
         double PREISFAKTUR; \
         short MAXTARGETNO; \
         short CONTAINERLEVEL; \
         double REFUNDVALUE; \
         short PROMOTION_NO; \
         short PROMOTYP; \
         short CODE_TYPE; \
         char ARTICLE_CODE[26]; \
         short PROBLEMSTATE; \
         long ETPOSSCHALTER7; \
         long ETPOSSCHALTER8; \
         short SUBGERAETTYP; \
         char KZPRISO; \
         short BUSINESSTYPENO; \
         char TOURIDIBT[7]; \
         short IBTTOURWEEKDAY; \
         short IBTTYPE; \
         short ISDAYIBT; \
         short IBTTYPEID; \
         long PURCHASERELEVANTQTY; \
         long MENGEBESTELLT_ORG; \
         long MENGEBESTELLTNATRA; \
         short NATRACATEGORY; \
         char NATRAPHARMACYGROUP[4]; \
         double PREISEKAGP; \



/* Copy-Function Struct to single Data KDAUFTRAGPOS ***************************/

 #define KDAUFTRAGPOS_S390_COPY_TO_SINGLE(_x_) \
         KDAUFTRAGNR=_x_->KDAUFTRAGNR;\
         POSNR=_x_->POSNR;\
         ARTIKEL_NR=_x_->ARTIKEL_NR;\
         POSTYP=_x_->POSTYP;\
         GERAETTYP=_x_->GERAETTYP;\
         FEHLERMENGE=_x_->FEHLERMENGE;\
         FEHLERARTIKEL=_x_->FEHLERARTIKEL;\
         ETPOSSCHALTER1=_x_->ETPOSSCHALTER1;\
         ETPOSSCHALTER2=_x_->ETPOSSCHALTER2;\
         ETPOSSCHALTER3=_x_->ETPOSSCHALTER3;\
         ETPOSSCHALTER4=_x_->ETPOSSCHALTER4;\
         ETPOSSCHALTER5=_x_->ETPOSSCHALTER5;\
         ETPOSSCHALTER6=_x_->ETPOSSCHALTER6;\
         MENGEBESTELLT=_x_->MENGEBESTELLT;\
         MENGEBESTAETIGT=_x_->MENGEBESTAETIGT;\
         MENGEGELIEFERT=_x_->MENGEGELIEFERT;\
         MENGEABGEBUCHT=_x_->MENGEABGEBUCHT;\
         MENGENATRA=_x_->MENGENATRA;\
         MENGENATRABASIS=_x_->MENGENATRABASIS;\
         MENGENATRAGROSSH=_x_->MENGENATRAGROSSH;\
         MENGENATRAHERST=_x_->MENGENATRAHERST;\
         PREISEKAPO=_x_->PREISEKAPO;\
         PREISVKAPO=_x_->PREISVKAPO;\
         PREISEKAPONETTO=_x_->PREISEKAPONETTO;\
         PREISEKGROSSO=_x_->PREISEKGROSSO;\
         PREISEKGROSSONA=_x_->PREISEKGROSSONA;\
         RABATTFESTDM=_x_->RABATTFESTDM;\
         PREISFEST=_x_->PREISFEST;\
         RABATTFEST=_x_->RABATTFEST;\
         PREISPROZENT=_x_->PREISPROZENT;\
         KOBEHAELTNR=_x_->KOBEHAELTNR;\
         RABATTHILFE=_x_->RABATTHILFE;\
          strcpy(RABATTFAEHIG,_x_->RABATTFAEHIG);\
         ARTBESTNACHUPD=_x_->ARTBESTNACHUPD;\
         UHRZEITBESTNACHUPD=_x_->UHRZEITBESTNACHUPD;\
         DATUMVERFALL=_x_->DATUMVERFALL;\
         MENGEGUTSCHRIFT=_x_->MENGEGUTSCHRIFT;\
         LAGERBEREICHNR=_x_->LAGERBEREICHNR;\
          strcpy(STATIONNR,_x_->STATIONNR);\
          strcpy(LAGERFACHNR,_x_->LAGERFACHNR);\
         ZUZAHLUNG=_x_->ZUZAHLUNG;\
          strcpy(BEMERKUNGEN,_x_->BEMERKUNGEN);\
         ETARTKLASSE1=_x_->ETARTKLASSE1;\
         ETARTSCHALTER1=_x_->ETARTSCHALTER1;\
         ETARTSCHALTER2=_x_->ETARTSCHALTER2;\
         ETARTSCHALTER3=_x_->ETARTSCHALTER3;\
         CONTSPLITMENGE=_x_->CONTSPLITMENGE;\
         SENDESTATUS=_x_->SENDESTATUS;\
          strcpy(HINWEIS,_x_->HINWEIS);\
         WANNENNR=_x_->WANNENNR;\
         MENGEVORAUSBEZUG=_x_->MENGEVORAUSBEZUG;\
         BATCHPOSNR=_x_->BATCHPOSNR;\
         BEWEGUNGSART=_x_->BEWEGUNGSART;\
         SALESTAXRATE=_x_->SALESTAXRATE;\
          strcpy(KDAUFTRAGBESTELLNR,_x_->KDAUFTRAGBESTELLNR);\
         CODEBLOCAGE=_x_->CODEBLOCAGE;\
         PREISEKAPOFREE=_x_->PREISEKAPOFREE;\
         LINKPOSNR=_x_->LINKPOSNR;\
         PREIS_TYP=_x_->PREIS_TYP;\
         ARTICLE_NO_PACK=_x_->ARTICLE_NO_PACK;\
         PREISFAKTUR=_x_->PREISFAKTUR;\
         MAXTARGETNO=_x_->MAXTARGETNO;\
         CONTAINERLEVEL=_x_->CONTAINERLEVEL;\
         REFUNDVALUE=_x_->REFUNDVALUE;\
         PROMOTION_NO=_x_->PROMOTION_NO;\
         PROMOTYP=_x_->PROMOTYP;\
         CODE_TYPE=_x_->CODE_TYPE;\
          strcpy(ARTICLE_CODE,_x_->ARTICLE_CODE);\
         PROBLEMSTATE=_x_->PROBLEMSTATE;\
         ETPOSSCHALTER7=_x_->ETPOSSCHALTER7;\
         ETPOSSCHALTER8=_x_->ETPOSSCHALTER8;\
         SUBGERAETTYP=_x_->SUBGERAETTYP;\
         KZPRISO=_x_->KZPRISO;\
         BUSINESSTYPENO=_x_->BUSINESSTYPENO;\
          strcpy(TOURIDIBT,_x_->TOURIDIBT);\
         IBTTOURWEEKDAY=_x_->IBTTOURWEEKDAY;\
         IBTTYPE=_x_->IBTTYPE;\
         ISDAYIBT=_x_->ISDAYIBT;\
         IBTTYPEID=_x_->IBTTYPEID;\
         PURCHASERELEVANTQTY=_x_->PURCHASERELEVANTQTY;\
         MENGEBESTELLT_ORG=_x_->MENGEBESTELLT_ORG;\
         MENGEBESTELLTNATRA=_x_->MENGEBESTELLTNATRA;\
         NATRACATEGORY=_x_->NATRACATEGORY;\
          strcpy(NATRAPHARMACYGROUP,_x_->NATRAPHARMACYGROUP);\
         PREISEKAGP=_x_->PREISEKAGP;\

 #define KDAUFTRAGPOS_S390_COPY_TO_STRUCT(_x_) \
          _x_->KDAUFTRAGNR=KDAUFTRAGNR;\
          _x_->POSNR=POSNR;\
          _x_->ARTIKEL_NR=ARTIKEL_NR;\
          _x_->POSTYP=POSTYP;\
          _x_->GERAETTYP=GERAETTYP;\
          _x_->FEHLERMENGE=FEHLERMENGE;\
          _x_->FEHLERARTIKEL=FEHLERARTIKEL;\
          _x_->ETPOSSCHALTER1=ETPOSSCHALTER1;\
          _x_->ETPOSSCHALTER2=ETPOSSCHALTER2;\
          _x_->ETPOSSCHALTER3=ETPOSSCHALTER3;\
          _x_->ETPOSSCHALTER4=ETPOSSCHALTER4;\
          _x_->ETPOSSCHALTER5=ETPOSSCHALTER5;\
          _x_->ETPOSSCHALTER6=ETPOSSCHALTER6;\
          _x_->MENGEBESTELLT=MENGEBESTELLT;\
          _x_->MENGEBESTAETIGT=MENGEBESTAETIGT;\
          _x_->MENGEGELIEFERT=MENGEGELIEFERT;\
          _x_->MENGEABGEBUCHT=MENGEABGEBUCHT;\
          _x_->MENGENATRA=MENGENATRA;\
          _x_->MENGENATRABASIS=MENGENATRABASIS;\
          _x_->MENGENATRAGROSSH=MENGENATRAGROSSH;\
          _x_->MENGENATRAHERST=MENGENATRAHERST;\
          _x_->PREISEKAPO=PREISEKAPO;\
          _x_->PREISVKAPO=PREISVKAPO;\
          _x_->PREISEKAPONETTO=PREISEKAPONETTO;\
          _x_->PREISEKGROSSO=PREISEKGROSSO;\
          _x_->PREISEKGROSSONA=PREISEKGROSSONA;\
          _x_->RABATTFESTDM=RABATTFESTDM;\
          _x_->PREISFEST=PREISFEST;\
          _x_->RABATTFEST=RABATTFEST;\
          _x_->PREISPROZENT=PREISPROZENT;\
          _x_->KOBEHAELTNR=KOBEHAELTNR;\
          _x_->RABATTHILFE=RABATTHILFE;\
          strcpy(_x_->RABATTFAEHIG,RABATTFAEHIG);\
          _x_->ARTBESTNACHUPD=ARTBESTNACHUPD;\
          _x_->UHRZEITBESTNACHUPD=UHRZEITBESTNACHUPD;\
          _x_->DATUMVERFALL=DATUMVERFALL;\
          _x_->MENGEGUTSCHRIFT=MENGEGUTSCHRIFT;\
          _x_->LAGERBEREICHNR=LAGERBEREICHNR;\
          strcpy(_x_->STATIONNR,STATIONNR);\
          strcpy(_x_->LAGERFACHNR,LAGERFACHNR);\
          _x_->ZUZAHLUNG=ZUZAHLUNG;\
          strcpy(_x_->BEMERKUNGEN,BEMERKUNGEN);\
          _x_->ETARTKLASSE1=ETARTKLASSE1;\
          _x_->ETARTSCHALTER1=ETARTSCHALTER1;\
          _x_->ETARTSCHALTER2=ETARTSCHALTER2;\
          _x_->ETARTSCHALTER3=ETARTSCHALTER3;\
          _x_->CONTSPLITMENGE=CONTSPLITMENGE;\
          _x_->SENDESTATUS=SENDESTATUS;\
          strcpy(_x_->HINWEIS,HINWEIS);\
          _x_->WANNENNR=WANNENNR;\
          _x_->MENGEVORAUSBEZUG=MENGEVORAUSBEZUG;\
          _x_->BATCHPOSNR=BATCHPOSNR;\
          _x_->BEWEGUNGSART=BEWEGUNGSART;\
          _x_->SALESTAXRATE=SALESTAXRATE;\
          strcpy(_x_->KDAUFTRAGBESTELLNR,KDAUFTRAGBESTELLNR);\
          _x_->CODEBLOCAGE=CODEBLOCAGE;\
          _x_->PREISEKAPOFREE=PREISEKAPOFREE;\
          _x_->LINKPOSNR=LINKPOSNR;\
          _x_->PREIS_TYP=PREIS_TYP;\
          _x_->ARTICLE_NO_PACK=ARTICLE_NO_PACK;\
          _x_->PREISFAKTUR=PREISFAKTUR;\
          _x_->MAXTARGETNO=MAXTARGETNO;\
          _x_->CONTAINERLEVEL=CONTAINERLEVEL;\
          _x_->REFUNDVALUE=REFUNDVALUE;\
          _x_->PROMOTION_NO=PROMOTION_NO;\
          _x_->PROMOTYP=PROMOTYP;\
          _x_->CODE_TYPE=CODE_TYPE;\
          strcpy(_x_->ARTICLE_CODE,ARTICLE_CODE);\
          _x_->PROBLEMSTATE=PROBLEMSTATE;\
          _x_->ETPOSSCHALTER7=ETPOSSCHALTER7;\
          _x_->ETPOSSCHALTER8=ETPOSSCHALTER8;\
          _x_->SUBGERAETTYP=SUBGERAETTYP;\
          _x_->KZPRISO=KZPRISO;\
          _x_->BUSINESSTYPENO=BUSINESSTYPENO;\
          strcpy(_x_->TOURIDIBT,TOURIDIBT);\
          _x_->IBTTOURWEEKDAY=IBTTOURWEEKDAY;\
          _x_->IBTTYPE=IBTTYPE;\
          _x_->ISDAYIBT=ISDAYIBT;\
          _x_->IBTTYPEID=IBTTYPEID;\
          _x_->PURCHASERELEVANTQTY=PURCHASERELEVANTQTY;\
          _x_->MENGEBESTELLT_ORG=MENGEBESTELLT_ORG;\
          _x_->MENGEBESTELLTNATRA=MENGEBESTELLTNATRA;\
          _x_->NATRACATEGORY=NATRACATEGORY;\
          strcpy(_x_->NATRAPHARMACYGROUP,NATRAPHARMACYGROUP);\
          _x_->PREISEKAGP=PREISEKAGP;\



/* FunctionNumber-Define of kdauftragpos **************************************/


#ifdef PRZ_OLD_FUNCTION
/* Old-FunctionNumber-Define of kdauftragpos **********************************/


#endif

/* C++ Class ******************************************************************/

#ifdef TRANSCLASS

#include<vector>
using namespace std;

/* ppunixc */
#include <sockclient.h>
#include <ppstring.h>
#include <ppgeneric.h>

/* must be implemented */
void FehlerBehandlung(int rc, const char * const error_msg);

#ifndef __VIRTUAL_DADE_CLASS__
#define __VIRTUAL_DADE_CLASS__

class ppDadeVirtual {
public:
    virtual    ~ppDadeVirtual() {};
    virtual int SelList      (int FetchRel = 1, int pos = 0) = 0;
    virtual int SelListHist  (int FetchRel = 1, int pos = 0) = 0;
    virtual int SelListFuture(int FetchRel = 1, int pos = 0) = 0;
    virtual int Load         (int pos = 0                  ) = 0;
    virtual int Delete       (int pos = 0                  ) = 0;
    virtual int Save         (int pos = 0                  ) = 0;
};
#endif

class CKDAUFTRAGPOS : public ppDadeVirtual {
public:
    kdauftragposS s;
    int  rc;
    char error_msg[81];
private:
    bool bOpenCursor;
    bool bEndOfSelect;
    int  FncNumber;
    int  CursorPos;
    int  AnzPos;
    vector<kdauftragposS> lst; // class list

public:
    unsigned int GetSize() const { return static_cast<unsigned int>(lst.size()); };
    void         ClearStruct() { s.clear(); }
    bool         SetData(unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     s = lst.at(i);
                     return true;
                 }
    bool         SetList(const unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     vector< kdauftragposS >::iterator it = lst.begin() + i;
                     *it = s;
                     return true;
                 }
    bool         InsList() {
                     Strip(s);
                     kdauftragposS c = s;
                     lst.insert(lst.end(), c);
                     AnzPos++;
                     return true;
                 }
    bool         DelList(const unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     vector< kdauftragposS >::iterator it = lst.begin() + i;
                     if (it != lst.end())
                         lst.erase(it);
                     if (--AnzPos < 0)
                         AnzPos = 0;
                     return true;
                 }

    vector<kdauftragposS>::iterator
                 beginList() { return lst.begin(); }
    vector<kdauftragposS>::iterator
                 endList  () { return lst.end  (); }

    long         GetKdauftragnr() const { return s.KDAUFTRAGNR; }
    long         GetPosnr() const { return s.POSNR; }
    long         GetArtikel_nr() const { return s.ARTIKEL_NR; }
    short        GetPostyp() const { return s.POSTYP; }
    short        GetGeraettyp() const { return s.GERAETTYP; }
    short        GetFehlermenge() const { return s.FEHLERMENGE; }
    short        GetFehlerartikel() const { return s.FEHLERARTIKEL; }
    long         GetEtposschalter1() const { return s.ETPOSSCHALTER1; }
    long         GetEtposschalter2() const { return s.ETPOSSCHALTER2; }
    long         GetEtposschalter3() const { return s.ETPOSSCHALTER3; }
    long         GetEtposschalter4() const { return s.ETPOSSCHALTER4; }
    long         GetEtposschalter5() const { return s.ETPOSSCHALTER5; }
    long         GetEtposschalter6() const { return s.ETPOSSCHALTER6; }
    long         GetMengebestellt() const { return s.MENGEBESTELLT; }
    long         GetMengebestaetigt() const { return s.MENGEBESTAETIGT; }
    long         GetMengegeliefert() const { return s.MENGEGELIEFERT; }
    long         GetMengeabgebucht() const { return s.MENGEABGEBUCHT; }
    long         GetMengenatra() const { return s.MENGENATRA; }
    long         GetMengenatrabasis() const { return s.MENGENATRABASIS; }
    long         GetMengenatragrossh() const { return s.MENGENATRAGROSSH; }
    long         GetMengenatraherst() const { return s.MENGENATRAHERST; }
    double       GetPreisekapo() const { return s.PREISEKAPO; }
    double       GetPreisvkapo() const { return s.PREISVKAPO; }
    double       GetPreisekaponetto() const { return s.PREISEKAPONETTO; }
    double       GetPreisekgrosso() const { return s.PREISEKGROSSO; }
    double       GetPreisekgrossona() const { return s.PREISEKGROSSONA; }
    double       GetRabattfestdm() const { return s.RABATTFESTDM; }
    double       GetPreisfest() const { return s.PREISFEST; }
    double       GetRabattfest() const { return s.RABATTFEST; }
    double       GetPreisprozent() const { return s.PREISPROZENT; }
    long         GetKobehaeltnr() const { return s.KOBEHAELTNR; }
    char         GetRabatthilfe() const { return s.RABATTHILFE[0]; }
    const char*  GetRabattfaehig(ppString & t) const { t = s.RABATTFAEHIG; t.erasespace(ppString::END); return t.c_str(); }
    long         GetArtbestnachupd() const { return s.ARTBESTNACHUPD; }
    long         GetUhrzeitbestnachupd() const { return s.UHRZEITBESTNACHUPD; }
    long         GetDatumverfall() const { return s.DATUMVERFALL; }
    long         GetMengegutschrift() const { return s.MENGEGUTSCHRIFT; }
    short        GetLagerbereichnr() const { return s.LAGERBEREICHNR; }
    const char*  GetStationnr(ppString & t) const { t = s.STATIONNR; t.erasespace(ppString::END); return t.c_str(); }
    const char*  GetLagerfachnr(ppString & t) const { t = s.LAGERFACHNR; t.erasespace(ppString::END); return t.c_str(); }
    char         GetZuzahlung() const { return s.ZUZAHLUNG[0]; }
    const char*  GetBemerkungen(ppString & t) const { t = s.BEMERKUNGEN; t.erasespace(ppString::END); return t.c_str(); }
    long         GetEtartklasse1() const { return s.ETARTKLASSE1; }
    long         GetEtartschalter1() const { return s.ETARTSCHALTER1; }
    long         GetEtartschalter2() const { return s.ETARTSCHALTER2; }
    long         GetEtartschalter3() const { return s.ETARTSCHALTER3; }
    long         GetContsplitmenge() const { return s.CONTSPLITMENGE; }
    short        GetSendestatus() const { return s.SENDESTATUS; }
    const char*  GetHinweis(ppString & t) const { t = s.HINWEIS; t.erasespace(ppString::END); return t.c_str(); }
    long         GetWannennr() const { return s.WANNENNR; }
    long         GetMengevorausbezug() const { return s.MENGEVORAUSBEZUG; }
    long         GetBatchposnr() const { return s.BATCHPOSNR; }
    char         GetBewegungsart() const { return s.BEWEGUNGSART[0]; }
    double       GetSalestaxrate() const { return s.SALESTAXRATE; }
    const char*  GetKdauftragbestellnr(ppString & t) const { t = s.KDAUFTRAGBESTELLNR; t.erasespace(ppString::END); return t.c_str(); }
    char         GetCodeblocage() const { return s.CODEBLOCAGE[0]; }
    double       GetPreisekapofree() const { return s.PREISEKAPOFREE; }
    long         GetLinkposnr() const { return s.LINKPOSNR; }
    short        GetPreis_typ() const { return s.PREIS_TYP; }
    long         GetArticle_no_pack() const { return s.ARTICLE_NO_PACK; }
    double       GetPreisfaktur() const { return s.PREISFAKTUR; }
    short        GetMaxtargetno() const { return s.MAXTARGETNO; }
    short        GetContainerlevel() const { return s.CONTAINERLEVEL; }
    double       GetRefundvalue() const { return s.REFUNDVALUE; }
    short        GetPromotion_no() const { return s.PROMOTION_NO; }
    short        GetPromotyp() const { return s.PROMOTYP; }
    short        GetCode_type() const { return s.CODE_TYPE; }
    const char*  GetArticle_code(ppString & t) const { t = s.ARTICLE_CODE; t.erasespace(ppString::END); return t.c_str(); }
    short        GetProblemstate() const { return s.PROBLEMSTATE; }
    long         GetEtposschalter7() const { return s.ETPOSSCHALTER7; }
    long         GetEtposschalter8() const { return s.ETPOSSCHALTER8; }
    short        GetSubgeraettyp() const { return s.SUBGERAETTYP; }
    char         GetKzpriso() const { return s.KZPRISO[0]; }
    short        GetBusinesstypeno() const { return s.BUSINESSTYPENO; }
    const char*  GetTouridibt(ppString & t) const { t = s.TOURIDIBT; t.erasespace(ppString::END); return t.c_str(); }
    short        GetIbttourweekday() const { return s.IBTTOURWEEKDAY; }
    short        GetIbttype() const { return s.IBTTYPE; }
    short        GetIsdayibt() const { return s.ISDAYIBT; }
    short        GetIbttypeid() const { return s.IBTTYPEID; }
    long         GetPurchaserelevantqty() const { return s.PURCHASERELEVANTQTY; }
    long         GetMengebestellt_org() const { return s.MENGEBESTELLT_ORG; }
    long         GetMengebestelltnatra() const { return s.MENGEBESTELLTNATRA; }
    short        GetNatracategory() const { return s.NATRACATEGORY; }
    const char*  GetNatrapharmacygroup(ppString & t) const { t = s.NATRAPHARMACYGROUP; t.erasespace(ppString::END); return t.c_str(); }
    double       GetPreisekagp() const { return s.PREISEKAGP; }

    const kdauftragposS &
                 GetStruct() const { return s; }
    void         SetKdauftragnr(long t) { s.KDAUFTRAGNR = t; }
    void         SetPosnr(long t) { s.POSNR = t; }
    void         SetArtikel_nr(long t) { s.ARTIKEL_NR = t; }
    void         SetPostyp(short t) { s.POSTYP = t; }
    void         SetGeraettyp(short t) { s.GERAETTYP = t; }
    void         SetFehlermenge(short t) { s.FEHLERMENGE = t; }
    void         SetFehlerartikel(short t) { s.FEHLERARTIKEL = t; }
    void         SetEtposschalter1(long t) { s.ETPOSSCHALTER1 = t; }
    void         SetEtposschalter2(long t) { s.ETPOSSCHALTER2 = t; }
    void         SetEtposschalter3(long t) { s.ETPOSSCHALTER3 = t; }
    void         SetEtposschalter4(long t) { s.ETPOSSCHALTER4 = t; }
    void         SetEtposschalter5(long t) { s.ETPOSSCHALTER5 = t; }
    void         SetEtposschalter6(long t) { s.ETPOSSCHALTER6 = t; }
    void         SetMengebestellt(long t) { s.MENGEBESTELLT = t; }
    void         SetMengebestaetigt(long t) { s.MENGEBESTAETIGT = t; }
    void         SetMengegeliefert(long t) { s.MENGEGELIEFERT = t; }
    void         SetMengeabgebucht(long t) { s.MENGEABGEBUCHT = t; }
    void         SetMengenatra(long t) { s.MENGENATRA = t; }
    void         SetMengenatrabasis(long t) { s.MENGENATRABASIS = t; }
    void         SetMengenatragrossh(long t) { s.MENGENATRAGROSSH = t; }
    void         SetMengenatraherst(long t) { s.MENGENATRAHERST = t; }
    void         SetPreisekapo(double t) { s.PREISEKAPO = t; }
    void         SetPreisvkapo(double t) { s.PREISVKAPO = t; }
    void         SetPreisekaponetto(double t) { s.PREISEKAPONETTO = t; }
    void         SetPreisekgrosso(double t) { s.PREISEKGROSSO = t; }
    void         SetPreisekgrossona(double t) { s.PREISEKGROSSONA = t; }
    void         SetRabattfestdm(double t) { s.RABATTFESTDM = t; }
    void         SetPreisfest(double t) { s.PREISFEST = t; }
    void         SetRabattfest(double t) { s.RABATTFEST = t; }
    void         SetPreisprozent(double t) { s.PREISPROZENT = t; }
    void         SetKobehaeltnr(long t) { s.KOBEHAELTNR = t; }
    void         SetRabatthilfe(char t) { s.RABATTHILFE[0] = t; s.RABATTHILFE[1] = '\0';}
    void         SetRabattfaehig(const ppString & t) { ppGStrCopy(s.RABATTFAEHIG, t.c_str(), L_KDAUFTRAGPOS_RABATTFAEHIG); }
    void         SetArtbestnachupd(long t) { s.ARTBESTNACHUPD = t; }
    void         SetUhrzeitbestnachupd(long t) { s.UHRZEITBESTNACHUPD = t; }
    void         SetDatumverfall(long t) { s.DATUMVERFALL = t; }
    void         SetMengegutschrift(long t) { s.MENGEGUTSCHRIFT = t; }
    void         SetLagerbereichnr(short t) { s.LAGERBEREICHNR = t; }
    void         SetStationnr(const ppString & t) { ppGStrCopy(s.STATIONNR, t.c_str(), L_KDAUFTRAGPOS_STATIONNR); }
    void         SetLagerfachnr(const ppString & t) { ppGStrCopy(s.LAGERFACHNR, t.c_str(), L_KDAUFTRAGPOS_LAGERFACHNR); }
    void         SetZuzahlung(char t) { s.ZUZAHLUNG[0] = t; s.ZUZAHLUNG[1] = '\0';}
    void         SetBemerkungen(const ppString & t) { ppGStrCopy(s.BEMERKUNGEN, t.c_str(), L_KDAUFTRAGPOS_BEMERKUNGEN); }
    void         SetEtartklasse1(long t) { s.ETARTKLASSE1 = t; }
    void         SetEtartschalter1(long t) { s.ETARTSCHALTER1 = t; }
    void         SetEtartschalter2(long t) { s.ETARTSCHALTER2 = t; }
    void         SetEtartschalter3(long t) { s.ETARTSCHALTER3 = t; }
    void         SetContsplitmenge(long t) { s.CONTSPLITMENGE = t; }
    void         SetSendestatus(short t) { s.SENDESTATUS = t; }
    void         SetHinweis(const ppString & t) { ppGStrCopy(s.HINWEIS, t.c_str(), L_KDAUFTRAGPOS_HINWEIS); }
    void         SetWannennr(long t) { s.WANNENNR = t; }
    void         SetMengevorausbezug(long t) { s.MENGEVORAUSBEZUG = t; }
    void         SetBatchposnr(long t) { s.BATCHPOSNR = t; }
    void         SetBewegungsart(char t) { s.BEWEGUNGSART[0] = t; s.BEWEGUNGSART[1] = '\0';}
    void         SetSalestaxrate(double t) { s.SALESTAXRATE = t; }
    void         SetKdauftragbestellnr(const ppString & t) { ppGStrCopy(s.KDAUFTRAGBESTELLNR, t.c_str(), L_KDAUFTRAGPOS_KDAUFTRAGBESTELLNR); }
    void         SetCodeblocage(char t) { s.CODEBLOCAGE[0] = t; s.CODEBLOCAGE[1] = '\0';}
    void         SetPreisekapofree(double t) { s.PREISEKAPOFREE = t; }
    void         SetLinkposnr(long t) { s.LINKPOSNR = t; }
    void         SetPreis_typ(short t) { s.PREIS_TYP = t; }
    void         SetArticle_no_pack(long t) { s.ARTICLE_NO_PACK = t; }
    void         SetPreisfaktur(double t) { s.PREISFAKTUR = t; }
    void         SetMaxtargetno(short t) { s.MAXTARGETNO = t; }
    void         SetContainerlevel(short t) { s.CONTAINERLEVEL = t; }
    void         SetRefundvalue(double t) { s.REFUNDVALUE = t; }
    void         SetPromotion_no(short t) { s.PROMOTION_NO = t; }
    void         SetPromotyp(short t) { s.PROMOTYP = t; }
    void         SetCode_type(short t) { s.CODE_TYPE = t; }
    void         SetArticle_code(const ppString & t) { ppGStrCopy(s.ARTICLE_CODE, t.c_str(), L_KDAUFTRAGPOS_ARTICLE_CODE); }
    void         SetProblemstate(short t) { s.PROBLEMSTATE = t; }
    void         SetEtposschalter7(long t) { s.ETPOSSCHALTER7 = t; }
    void         SetEtposschalter8(long t) { s.ETPOSSCHALTER8 = t; }
    void         SetSubgeraettyp(short t) { s.SUBGERAETTYP = t; }
    void         SetKzpriso(char t) { s.KZPRISO[0] = t; s.KZPRISO[1] = '\0';}
    void         SetBusinesstypeno(short t) { s.BUSINESSTYPENO = t; }
    void         SetTouridibt(const ppString & t) { ppGStrCopy(s.TOURIDIBT, t.c_str(), L_KDAUFTRAGPOS_TOURIDIBT); }
    void         SetIbttourweekday(short t) { s.IBTTOURWEEKDAY = t; }
    void         SetIbttype(short t) { s.IBTTYPE = t; }
    void         SetIsdayibt(short t) { s.ISDAYIBT = t; }
    void         SetIbttypeid(short t) { s.IBTTYPEID = t; }
    void         SetPurchaserelevantqty(long t) { s.PURCHASERELEVANTQTY = t; }
    void         SetMengebestellt_org(long t) { s.MENGEBESTELLT_ORG = t; }
    void         SetMengebestelltnatra(long t) { s.MENGEBESTELLTNATRA = t; }
    void         SetNatracategory(short t) { s.NATRACATEGORY = t; }
    void         SetNatrapharmacygroup(const ppString & t) { ppGStrCopy(s.NATRAPHARMACYGROUP, t.c_str(), L_KDAUFTRAGPOS_NATRAPHARMACYGROUP); }
    void         SetPreisekagp(double t) { s.PREISEKAGP = t; }

    void         SetStruct(const kdauftragposS & t) { s = t; }


    // virtual functions
public:
    int          Load(int pos = 0) { pos = pos; return 1; }
    int          Save(int pos = 0) { pos = pos; return 1; }
    int          Delete(int pos = 0) { pos = pos; return 1; }
    int          SelList(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }
    int          SelListHist(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }
    int          SelListFuture(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }

    // constructor
    CKDAUFTRAGPOS() {
        ::buf_default((void *)&s, KDAUFTRAGPOS_BES, KDAUFTRAGPOS_ANZ);
        bOpenCursor   = false;
        bEndOfSelect  = false;
        FncNumber     = 0;
        CursorPos     = 0;
        AnzPos        = 0;
        rc            = 0;
        s.clear();
    }

    // destructor
    virtual ~CKDAUFTRAGPOS() {
    }

    // buffer init
    void buf_default() {
        ::buf_default((void *)&s, KDAUFTRAGPOS_BES, KDAUFTRAGPOS_ANZ);
    }

    // socket server call
    int Server(int fkt_nr, int pos = 0) {
    #ifdef WIN32
        rc = ::ServerNr(pos, fkt_nr, (void *)&s, KDAUFTRAGPOS_BES, (int)KDAUFTRAGPOS_ANZ, error_msg);
    #else
        rc = ::Server(fkt_nr, (void *)&s, KDAUFTRAGPOS_BES, (int)KDAUFTRAGPOS_ANZ, error_msg);
    #endif
        if (rc < 0)
            FehlerBehandlung( rc, error_msg );
        return rc;
    }

private:
    void Strip(N_KDAUFTRAGPOS & d) {
        d = d;
    #ifdef WIN32
        ppGStripLast(d.RABATTFAEHIG);
        ppGStripLast(d.STATIONNR);
        ppGStripLast(d.LAGERFACHNR);
        ppGStripLast(d.BEMERKUNGEN);
        ppGStripLast(d.HINWEIS);
        ppGStripLast(d.KDAUFTRAGBESTELLNR);
        ppGStripLast(d.ARTICLE_CODE);
        ppGStripLast(d.TOURIDIBT);
        ppGStripLast(d.NATRAPHARMACYGROUP);
    #endif
    }

    int UniqueServerCall(int FncNr, int pos = 0) {
    #ifndef __DADE_LOAD__
       rc = ::ServerNr(pos, FncNr, (void *)&s, KDAUFTRAGPOS_BES, (int)KDAUFTRAGPOS_ANZ, error_msg);
    #else
       pos = pos;
       rc = DistributorFunSelect(FncNr, (void *)&s, error_msg, &rc);
    #endif
       if (rc < 0)
           FehlerBehandlung( rc, error_msg );
       return rc;
    }
};
#endif    // TRANSCLASS
/* CreateSqlStatement of KDAUFTRAGPOS *****************************************/

 #define KDAUFTRAGPOS_CREATE(x) EXEC SQL create table x (\
         KDAUFTRAGNR integer default 0 not null,\
         POSNR integer default 0 not null,\
         ARTIKEL_NR integer default 0 not null,\
         POSTYP smallint default 0 not null,\
         GERAETTYP smallint default 0 not null,\
         FEHLERMENGE smallint default 0 not null,\
         FEHLERARTIKEL smallint default 0 not null,\
         ETPOSSCHALTER1 integer default 0 not null,\
         ETPOSSCHALTER2 integer default 0 not null,\
         ETPOSSCHALTER3 integer default 0 not null,\
         ETPOSSCHALTER4 integer default 0 not null,\
         ETPOSSCHALTER5 integer default 0 not null,\
         ETPOSSCHALTER6 integer default 0 not null,\
         MENGEBESTELLT integer default 0 not null,\
         MENGEBESTAETIGT integer default 0 not null,\
         MENGEGELIEFERT integer default 0 not null,\
         MENGEABGEBUCHT integer default 0 not null,\
         MENGENATRA integer default 0 not null,\
         MENGENATRABASIS integer default 0 not null,\
         MENGENATRAGROSSH integer default 0 not null,\
         MENGENATRAHERST integer default 0 not null,\
         PREISEKAPO decimal(9,2) default 0 not null,\
         PREISVKAPO decimal(9,2) default 0 not null,\
         PREISEKAPONETTO decimal(9,2) default 0 not null,\
         PREISEKGROSSO decimal(9,2) default 0 not null,\
         PREISEKGROSSONA decimal(9,2) default 0 not null,\
         RABATTFESTDM decimal(9,2) default 0 not null,\
         PREISFEST decimal(9,2) default 0 not null,\
         RABATTFEST decimal(7,2) default 0 not null,\
         PREISPROZENT decimal(5,2) default 0 not null,\
         KOBEHAELTNR integer default 0 not null,\
         RABATTHILFE char(1) default " " not null,\
         RABATTFAEHIG char(2) default " " not null,\
         ARTBESTNACHUPD integer default 0 not null,\
         UHRZEITBESTNACHUPD integer default 0 not null,\
         DATUMVERFALL integer default 0 not null,\
         MENGEGUTSCHRIFT integer default 0 not null,\
         LAGERBEREICHNR smallint default 0 not null,\
         STATIONNR char(2) default " " not null,\
         LAGERFACHNR char(10) default " " not null,\
         ZUZAHLUNG char(1) default " " not null,\
         BEMERKUNGEN varchar(240,0) default " " not null,\
         ETARTKLASSE1 integer default 0 not null,\
         ETARTSCHALTER1 integer default 0 not null,\
         ETARTSCHALTER2 integer default 0 not null,\
         ETARTSCHALTER3 integer default 0 not null,\
         CONTSPLITMENGE integer default 0 not null,\
         SENDESTATUS smallint default 0 not null,\
         HINWEIS char(2) default " " not null,\
         WANNENNR integer default 0 not null,\
         MENGEVORAUSBEZUG integer default 0 not null,\
         BATCHPOSNR integer default 0 not null,\
         BEWEGUNGSART char(1) default " " not null,\
         SALESTAXRATE decimal(5,2) default 0 not null,\
         KDAUFTRAGBESTELLNR char(9) default " " not null,\
         CODEBLOCAGE char(1) default " " not null,\
         PREISEKAPOFREE decimal(9,2) default 0 not null,\
         LINKPOSNR integer default 0 not null,\
         PREIS_TYP smallint default 0 not null,\
         ARTICLE_NO_PACK integer default 0 not null,\
         PREISFAKTUR decimal(9,2) default 0 not null,\
         MAXTARGETNO smallint default 0 not null,\
         CONTAINERLEVEL smallint default 0 not null,\
         REFUNDVALUE decimal(9,2) default 0 not null,\
         PROMOTION_NO smallint default 0 not null,\
         PROMOTYP smallint default 0 not null,\
         CODE_TYPE smallint default 0 not null,\
         ARTICLE_CODE char(25) default " " not null,\
         PROBLEMSTATE smallint default 0 not null,\
         ETPOSSCHALTER7 integer default 0 not null,\
         ETPOSSCHALTER8 integer default 0 not null,\
         SUBGERAETTYP smallint default 0 not null,\
         KZPRISO char(1) default " " not null,\
         BUSINESSTYPENO smallint default 0 not null,\
         TOURIDIBT char(6) default " " not null,\
         IBTTOURWEEKDAY smallint default 0 not null,\
         IBTTYPE smallint default 0 not null,\
         ISDAYIBT smallint default 0 not null,\
         IBTTYPEID smallint default 0 not null,\
         PURCHASERELEVANTQTY integer default 0 not null,\
         MENGEBESTELLT_ORG integer default 0 not null,\
         MENGEBESTELLTNATRA integer default 0 not null,\
         NATRACATEGORY smallint default 0 not null,\
         NATRAPHARMACYGROUP char(3) default " " not null,\
         PREISEKAGP decimal(9,2) default 0 not null) in ksc extent size 10980 next size 1100 lock mode row;



/* CreateIndexStatement of KDAUFTRAGPOS ***************************************/

 #define KDAUFTRAGPOS_CREATE_INDEX(_X_,_Y_)\
              _Y_ = 0;\
         EXEC SQL create   index i_kdauftragpos_2 on _X_(\
              artikel_nr ) in ksc;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\
         EXEC SQL create unique index kdauftragposx on _X_(\
              kdauftragnr,\
              posnr ) in ksc;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\


/* DeleteIndexStatement of KDAUFTRAGPOS ***************************************/

 #define KDAUFTRAGPOS_DELETE_INDEX(_X_)\
              _X_ = 0;\
         EXEC SQL drop index i_kdauftragpos_2;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\
         EXEC SQL drop index kdauftragposx;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\




#endif   // GUARD
