#ifndef __PP_KDAUFTRAGWERTE_H_
#define __PP_KDAUFTRAGWERTE_H_

/******************************************************************************/
/* c:\prri\Headerfiles\kdauftragwerte *****************************************/
/* produced by DADE 6.22.2 ****************************************************/
/******************************************************************************/

/* ppunixc */
#if defined (BUF_DESC) || defined (C_BUF_DESC)
#include <bufkon.h>
#endif

/* Length-Define of KDAUFTRAGWERTE ********************************************/

#define L_KDAUFTRAGWERTE_KDAUFTRAGNR 11
#define L_KDAUFTRAGWERTE_ORDVALFTAXFSDISC 11
#define N_KDAUFTRAGWERTE_ORDVALFTAXFSDISC 2
#define L_KDAUFTRAGWERTE_ORDVALFTAXFS 11
#define N_KDAUFTRAGWERTE_ORDVALFTAXFS 2
#define L_KDAUFTRAGWERTE_ORDVALLTAXFSDISC 11
#define N_KDAUFTRAGWERTE_ORDVALLTAXFSDISC 2
#define L_KDAUFTRAGWERTE_ORDVALLTAXFS 11
#define N_KDAUFTRAGWERTE_ORDVALLTAXFS 2
#define L_KDAUFTRAGWERTE_ORDVALFTAXHFDISC 11
#define N_KDAUFTRAGWERTE_ORDVALFTAXHFDISC 2
#define L_KDAUFTRAGWERTE_ORDVALFTAXHF 11
#define N_KDAUFTRAGWERTE_ORDVALFTAXHF 2
#define L_KDAUFTRAGWERTE_ORDVALLTAXHFDISC 11
#define N_KDAUFTRAGWERTE_ORDVALLTAXHFDISC 2
#define L_KDAUFTRAGWERTE_ORDVALLTAXHF 11
#define N_KDAUFTRAGWERTE_ORDVALLTAXHF 2
#define L_KDAUFTRAGWERTE_TAXVALFTAXFSDISC 9
#define N_KDAUFTRAGWERTE_TAXVALFTAXFSDISC 2
#define L_KDAUFTRAGWERTE_TAXVALFTAXFS 9
#define N_KDAUFTRAGWERTE_TAXVALFTAXFS 2
#define L_KDAUFTRAGWERTE_TAXVALLTAXFSDISC 9
#define N_KDAUFTRAGWERTE_TAXVALLTAXFSDISC 2
#define L_KDAUFTRAGWERTE_TAXVALLTAXFS 9
#define N_KDAUFTRAGWERTE_TAXVALLTAXFS 2
#define L_KDAUFTRAGWERTE_TAXVALFTAXHFDISC 9
#define N_KDAUFTRAGWERTE_TAXVALFTAXHFDISC 2
#define L_KDAUFTRAGWERTE_TAXVALFTAXHF 9
#define N_KDAUFTRAGWERTE_TAXVALFTAXHF 2
#define L_KDAUFTRAGWERTE_TAXVALLTAXHFDISC 9
#define N_KDAUFTRAGWERTE_TAXVALLTAXHFDISC 2
#define L_KDAUFTRAGWERTE_TAXVALLTAXHF 9
#define N_KDAUFTRAGWERTE_TAXVALLTAXHF 2
#define L_KDAUFTRAGWERTE_ORDVALFTAXRSDISC 11
#define N_KDAUFTRAGWERTE_ORDVALFTAXRSDISC 2
#define L_KDAUFTRAGWERTE_ORDVALFTAXRS 11
#define N_KDAUFTRAGWERTE_ORDVALFTAXRS 2
#define L_KDAUFTRAGWERTE_ORDVALLTAXRSDISC 11
#define N_KDAUFTRAGWERTE_ORDVALLTAXRSDISC 2
#define L_KDAUFTRAGWERTE_ORDVALLTAXRS 11
#define N_KDAUFTRAGWERTE_ORDVALLTAXRS 2
#define L_KDAUFTRAGWERTE_TAXVALFTAXRSDISC 9
#define N_KDAUFTRAGWERTE_TAXVALFTAXRSDISC 2
#define L_KDAUFTRAGWERTE_TAXVALFTAXRS 9
#define N_KDAUFTRAGWERTE_TAXVALFTAXRS 2
#define L_KDAUFTRAGWERTE_TAXVALLTAXRSDISC 9
#define N_KDAUFTRAGWERTE_TAXVALLTAXRSDISC 2
#define L_KDAUFTRAGWERTE_TAXVALLTAXRS 9
#define N_KDAUFTRAGWERTE_TAXVALLTAXRS 2
#define L_KDAUFTRAGWERTE_ORDVALNTAXFSDISC 11
#define N_KDAUFTRAGWERTE_ORDVALNTAXFSDISC 2
#define L_KDAUFTRAGWERTE_ORDVALNTAXFS 11
#define N_KDAUFTRAGWERTE_ORDVALNTAXFS 2
#define L_KDAUFTRAGWERTE_ORDVALNTAXHFDISC 11
#define N_KDAUFTRAGWERTE_ORDVALNTAXHFDISC 2
#define L_KDAUFTRAGWERTE_ORDVALNTAXHF 11
#define N_KDAUFTRAGWERTE_ORDVALNTAXHF 2
#define L_KDAUFTRAGWERTE_ORDVALNTAXRSDISC 11
#define N_KDAUFTRAGWERTE_ORDVALNTAXRSDISC 2
#define L_KDAUFTRAGWERTE_ORDVALNTAXRS 11
#define N_KDAUFTRAGWERTE_ORDVALNTAXRS 2
#define L_KDAUFTRAGWERTE_TAXVALNTAXFSDISC 9
#define N_KDAUFTRAGWERTE_TAXVALNTAXFSDISC 2
#define L_KDAUFTRAGWERTE_TAXVALNTAXFS 9
#define N_KDAUFTRAGWERTE_TAXVALNTAXFS 2
#define L_KDAUFTRAGWERTE_TAXVALNTAXHFDISC 9
#define N_KDAUFTRAGWERTE_TAXVALNTAXHFDISC 2
#define L_KDAUFTRAGWERTE_TAXVALNTAXHF 9
#define N_KDAUFTRAGWERTE_TAXVALNTAXHF 2
#define L_KDAUFTRAGWERTE_TAXVALNTAXRSDISC 9
#define N_KDAUFTRAGWERTE_TAXVALNTAXRSDISC 2
#define L_KDAUFTRAGWERTE_TAXVALNTAXRS 9
#define N_KDAUFTRAGWERTE_TAXVALNTAXRS 2

/* Length/Count-Define of KDAUFTRAGWERTE **************************************/

#define LS_KDAUFTRAGWERTE_KDAUFTRAGNR 10 + 1
#define LS_KDAUFTRAGWERTE_ORDVALFTAXFSDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALFTAXFS 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALLTAXFSDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALLTAXFS 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALFTAXHFDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALFTAXHF 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALLTAXHFDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALLTAXHF 11 + 2
#define LS_KDAUFTRAGWERTE_TAXVALFTAXFSDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALFTAXFS 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALLTAXFSDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALLTAXFS 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALFTAXHFDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALFTAXHF 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALLTAXHFDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALLTAXHF 9 + 2
#define LS_KDAUFTRAGWERTE_ORDVALFTAXRSDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALFTAXRS 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALLTAXRSDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALLTAXRS 11 + 2
#define LS_KDAUFTRAGWERTE_TAXVALFTAXRSDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALFTAXRS 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALLTAXRSDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALLTAXRS 9 + 2
#define LS_KDAUFTRAGWERTE_ORDVALNTAXFSDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALNTAXFS 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALNTAXHFDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALNTAXHF 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALNTAXRSDISC 11 + 2
#define LS_KDAUFTRAGWERTE_ORDVALNTAXRS 11 + 2
#define LS_KDAUFTRAGWERTE_TAXVALNTAXFSDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALNTAXFS 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALNTAXHFDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALNTAXHF 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALNTAXRSDISC 9 + 2
#define LS_KDAUFTRAGWERTE_TAXVALNTAXRS 9 + 2

#define KDAUFTRAGWERTEKDAUFTRAGNR 0
#define KDAUFTRAGWERTEORDVALFTAXFSDISC 1
#define KDAUFTRAGWERTEORDVALFTAXFS 2
#define KDAUFTRAGWERTEORDVALLTAXFSDISC 3
#define KDAUFTRAGWERTEORDVALLTAXFS 4
#define KDAUFTRAGWERTEORDVALFTAXHFDISC 5
#define KDAUFTRAGWERTEORDVALFTAXHF 6
#define KDAUFTRAGWERTEORDVALLTAXHFDISC 7
#define KDAUFTRAGWERTEORDVALLTAXHF 8
#define KDAUFTRAGWERTETAXVALFTAXFSDISC 9
#define KDAUFTRAGWERTETAXVALFTAXFS 10
#define KDAUFTRAGWERTETAXVALLTAXFSDISC 11
#define KDAUFTRAGWERTETAXVALLTAXFS 12
#define KDAUFTRAGWERTETAXVALFTAXHFDISC 13
#define KDAUFTRAGWERTETAXVALFTAXHF 14
#define KDAUFTRAGWERTETAXVALLTAXHFDISC 15
#define KDAUFTRAGWERTETAXVALLTAXHF 16
#define KDAUFTRAGWERTEORDVALFTAXRSDISC 17
#define KDAUFTRAGWERTEORDVALFTAXRS 18
#define KDAUFTRAGWERTEORDVALLTAXRSDISC 19
#define KDAUFTRAGWERTEORDVALLTAXRS 20
#define KDAUFTRAGWERTETAXVALFTAXRSDISC 21
#define KDAUFTRAGWERTETAXVALFTAXRS 22
#define KDAUFTRAGWERTETAXVALLTAXRSDISC 23
#define KDAUFTRAGWERTETAXVALLTAXRS 24
#define KDAUFTRAGWERTEORDVALNTAXFSDISC 25
#define KDAUFTRAGWERTEORDVALNTAXFS 26
#define KDAUFTRAGWERTEORDVALNTAXHFDISC 27
#define KDAUFTRAGWERTEORDVALNTAXHF 28
#define KDAUFTRAGWERTEORDVALNTAXRSDISC 29
#define KDAUFTRAGWERTEORDVALNTAXRS 30
#define KDAUFTRAGWERTETAXVALNTAXFSDISC 31
#define KDAUFTRAGWERTETAXVALNTAXFS 32
#define KDAUFTRAGWERTETAXVALNTAXHFDISC 33
#define KDAUFTRAGWERTETAXVALNTAXHF 34
#define KDAUFTRAGWERTETAXVALNTAXRSDISC 35
#define KDAUFTRAGWERTETAXVALNTAXRS 36

/* define of Buf_Desc *********************************************************/

#if defined (BUF_DESC) || defined (C_BUF_DESC)
#define KDAUFTRAGWERTE_H
#define KDAUFTRAGWERTE_ANZ ( sizeof(KDAUFTRAGWERTE_BES) / sizeof(struct buf_desc) )
#endif

/* SqlDefine of KDAUFTRAGWERTE ************************************************/

#define KDAUFTRAGWERTE_LISTE \
        KDAUFTRAGWERTE.KDAUFTRAGNR,\
        KDAUFTRAGWERTE.ORDVALFTAXFSDISC,\
        KDAUFTRAGWERTE.ORDVALFTAXFS,\
        KDAUFTRAGWERTE.ORDVALLTAXFSDISC,\
        KDAUFTRAGWERTE.ORDVALLTAXFS,\
        KDAUFTRAGWERTE.ORDVALFTAXHFDISC,\
        KDAUFTRAGWERTE.ORDVALFTAXHF,\
        KDAUFTRAGWERTE.ORDVALLTAXHFDISC,\
        KDAUFTRAGWERTE.ORDVALLTAXHF,\
        KDAUFTRAGWERTE.TAXVALFTAXFSDISC,\
        KDAUFTRAGWERTE.TAXVALFTAXFS,\
        KDAUFTRAGWERTE.TAXVALLTAXFSDISC,\
        KDAUFTRAGWERTE.TAXVALLTAXFS,\
        KDAUFTRAGWERTE.TAXVALFTAXHFDISC,\
        KDAUFTRAGWERTE.TAXVALFTAXHF,\
        KDAUFTRAGWERTE.TAXVALLTAXHFDISC,\
        KDAUFTRAGWERTE.TAXVALLTAXHF,\
        KDAUFTRAGWERTE.ORDVALFTAXRSDISC,\
        KDAUFTRAGWERTE.ORDVALFTAXRS,\
        KDAUFTRAGWERTE.ORDVALLTAXRSDISC,\
        KDAUFTRAGWERTE.ORDVALLTAXRS,\
        KDAUFTRAGWERTE.TAXVALFTAXRSDISC,\
        KDAUFTRAGWERTE.TAXVALFTAXRS,\
        KDAUFTRAGWERTE.TAXVALLTAXRSDISC,\
        KDAUFTRAGWERTE.TAXVALLTAXRS,\
        KDAUFTRAGWERTE.ORDVALNTAXFSDISC,\
        KDAUFTRAGWERTE.ORDVALNTAXFS,\
        KDAUFTRAGWERTE.ORDVALNTAXHFDISC,\
        KDAUFTRAGWERTE.ORDVALNTAXHF,\
        KDAUFTRAGWERTE.ORDVALNTAXRSDISC,\
        KDAUFTRAGWERTE.ORDVALNTAXRS,\
        KDAUFTRAGWERTE.TAXVALNTAXFSDISC,\
        KDAUFTRAGWERTE.TAXVALNTAXFS,\
        KDAUFTRAGWERTE.TAXVALNTAXHFDISC,\
        KDAUFTRAGWERTE.TAXVALNTAXHF,\
        KDAUFTRAGWERTE.TAXVALNTAXRSDISC,\
        KDAUFTRAGWERTE.TAXVALNTAXRS
#define KDAUFTRAGWERTE_LISTE_390 \
        KDAUFTRAGNR,\
        ORDVALFTAXFSDISC,\
        ORDVALFTAXFS,\
        ORDVALLTAXFSDISC,\
        ORDVALLTAXFS,\
        ORDVALFTAXHFDISC,\
        ORDVALFTAXHF,\
        ORDVALLTAXHFDISC,\
        ORDVALLTAXHF,\
        TAXVALFTAXFSDISC,\
        TAXVALFTAXFS,\
        TAXVALLTAXFSDISC,\
        TAXVALLTAXFS,\
        TAXVALFTAXHFDISC,\
        TAXVALFTAXHF,\
        TAXVALLTAXHFDISC,\
        TAXVALLTAXHF,\
        ORDVALFTAXRSDISC,\
        ORDVALFTAXRS,\
        ORDVALLTAXRSDISC,\
        ORDVALLTAXRS,\
        TAXVALFTAXRSDISC,\
        TAXVALFTAXRS,\
        TAXVALLTAXRSDISC,\
        TAXVALLTAXRS,\
        ORDVALNTAXFSDISC,\
        ORDVALNTAXFS,\
        ORDVALNTAXHFDISC,\
        ORDVALNTAXHF,\
        ORDVALNTAXRSDISC,\
        ORDVALNTAXRS,\
        TAXVALNTAXFSDISC,\
        TAXVALNTAXFS,\
        TAXVALNTAXHFDISC,\
        TAXVALNTAXHF,\
        TAXVALNTAXRSDISC,\
        TAXVALNTAXRS
#define KDAUFTRAGWERTE_PLISTE \
        "KDAUFTRAGWERTE.KDAUFTRAGNR,"\
        "KDAUFTRAGWERTE.ORDVALFTAXFSDISC,"\
        "KDAUFTRAGWERTE.ORDVALFTAXFS,"\
        "KDAUFTRAGWERTE.ORDVALLTAXFSDISC,"\
        "KDAUFTRAGWERTE.ORDVALLTAXFS,"\
        "KDAUFTRAGWERTE.ORDVALFTAXHFDISC,"\
        "KDAUFTRAGWERTE.ORDVALFTAXHF,"\
        "KDAUFTRAGWERTE.ORDVALLTAXHFDISC,"\
        "KDAUFTRAGWERTE.ORDVALLTAXHF,"\
        "KDAUFTRAGWERTE.TAXVALFTAXFSDISC,"\
        "KDAUFTRAGWERTE.TAXVALFTAXFS,"\
        "KDAUFTRAGWERTE.TAXVALLTAXFSDISC,"\
        "KDAUFTRAGWERTE.TAXVALLTAXFS,"\
        "KDAUFTRAGWERTE.TAXVALFTAXHFDISC,"\
        "KDAUFTRAGWERTE.TAXVALFTAXHF,"\
        "KDAUFTRAGWERTE.TAXVALLTAXHFDISC,"\
        "KDAUFTRAGWERTE.TAXVALLTAXHF,"\
        "KDAUFTRAGWERTE.ORDVALFTAXRSDISC,"\
        "KDAUFTRAGWERTE.ORDVALFTAXRS,"\
        "KDAUFTRAGWERTE.ORDVALLTAXRSDISC,"\
        "KDAUFTRAGWERTE.ORDVALLTAXRS,"\
        "KDAUFTRAGWERTE.TAXVALFTAXRSDISC,"\
        "KDAUFTRAGWERTE.TAXVALFTAXRS,"\
        "KDAUFTRAGWERTE.TAXVALLTAXRSDISC,"\
        "KDAUFTRAGWERTE.TAXVALLTAXRS,"\
        "KDAUFTRAGWERTE.ORDVALNTAXFSDISC,"\
        "KDAUFTRAGWERTE.ORDVALNTAXFS,"\
        "KDAUFTRAGWERTE.ORDVALNTAXHFDISC,"\
        "KDAUFTRAGWERTE.ORDVALNTAXHF,"\
        "KDAUFTRAGWERTE.ORDVALNTAXRSDISC,"\
        "KDAUFTRAGWERTE.ORDVALNTAXRS,"\
        "KDAUFTRAGWERTE.TAXVALNTAXFSDISC,"\
        "KDAUFTRAGWERTE.TAXVALNTAXFS,"\
        "KDAUFTRAGWERTE.TAXVALNTAXHFDISC,"\
        "KDAUFTRAGWERTE.TAXVALNTAXHF,"\
        "KDAUFTRAGWERTE.TAXVALNTAXRSDISC,"\
        "KDAUFTRAGWERTE.TAXVALNTAXRS"
#define KDAUFTRAGWERTE_PELISTE \
        "KDAUFTRAGNR,"\
        "ORDVALFTAXFSDISC,"\
        "ORDVALFTAXFS,"\
        "ORDVALLTAXFSDISC,"\
        "ORDVALLTAXFS,"\
        "ORDVALFTAXHFDISC,"\
        "ORDVALFTAXHF,"\
        "ORDVALLTAXHFDISC,"\
        "ORDVALLTAXHF,"\
        "TAXVALFTAXFSDISC,"\
        "TAXVALFTAXFS,"\
        "TAXVALLTAXFSDISC,"\
        "TAXVALLTAXFS,"\
        "TAXVALFTAXHFDISC,"\
        "TAXVALFTAXHF,"\
        "TAXVALLTAXHFDISC,"\
        "TAXVALLTAXHF,"\
        "ORDVALFTAXRSDISC,"\
        "ORDVALFTAXRS,"\
        "ORDVALLTAXRSDISC,"\
        "ORDVALLTAXRS,"\
        "TAXVALFTAXRSDISC,"\
        "TAXVALFTAXRS,"\
        "TAXVALLTAXRSDISC,"\
        "TAXVALLTAXRS,"\
        "ORDVALNTAXFSDISC,"\
        "ORDVALNTAXFS,"\
        "ORDVALNTAXHFDISC,"\
        "ORDVALNTAXHF,"\
        "ORDVALNTAXRSDISC,"\
        "ORDVALNTAXRS,"\
        "TAXVALNTAXFSDISC,"\
        "TAXVALNTAXFS,"\
        "TAXVALNTAXHFDISC,"\
        "TAXVALNTAXHF,"\
        "TAXVALNTAXRSDISC,"\
        "TAXVALNTAXRS"
#define KDAUFTRAGWERTE_UPDLISTE \
        "KDAUFTRAGNR=?,"\
        "ORDVALFTAXFSDISC=?,"\
        "ORDVALFTAXFS=?,"\
        "ORDVALLTAXFSDISC=?,"\
        "ORDVALLTAXFS=?,"\
        "ORDVALFTAXHFDISC=?,"\
        "ORDVALFTAXHF=?,"\
        "ORDVALLTAXHFDISC=?,"\
        "ORDVALLTAXHF=?,"\
        "TAXVALFTAXFSDISC=?,"\
        "TAXVALFTAXFS=?,"\
        "TAXVALLTAXFSDISC=?,"\
        "TAXVALLTAXFS=?,"\
        "TAXVALFTAXHFDISC=?,"\
        "TAXVALFTAXHF=?,"\
        "TAXVALLTAXHFDISC=?,"\
        "TAXVALLTAXHF=?,"\
        "ORDVALFTAXRSDISC=?,"\
        "ORDVALFTAXRS=?,"\
        "ORDVALLTAXRSDISC=?,"\
        "ORDVALLTAXRS=?,"\
        "TAXVALFTAXRSDISC=?,"\
        "TAXVALFTAXRS=?,"\
        "TAXVALLTAXRSDISC=?,"\
        "TAXVALLTAXRS=?,"\
        "ORDVALNTAXFSDISC=?,"\
        "ORDVALNTAXFS=?,"\
        "ORDVALNTAXHFDISC=?,"\
        "ORDVALNTAXHF=?,"\
        "ORDVALNTAXRSDISC=?,"\
        "ORDVALNTAXRS=?,"\
        "TAXVALNTAXFSDISC=?,"\
        "TAXVALNTAXFS=?,"\
        "TAXVALNTAXHFDISC=?,"\
        "TAXVALNTAXHF=?,"\
        "TAXVALNTAXRSDISC=?,"\
        "TAXVALNTAXRS=?"
/* SqlMacros-Define of KDAUFTRAGWERTE *****************************************/

#define KDAUFTRAGWERTE_ZEIGER(x) \
        :x->KDAUFTRAGNR,\
        :x->ORDVALFTAXFSDISC,\
        :x->ORDVALFTAXFS,\
        :x->ORDVALLTAXFSDISC,\
        :x->ORDVALLTAXFS,\
        :x->ORDVALFTAXHFDISC,\
        :x->ORDVALFTAXHF,\
        :x->ORDVALLTAXHFDISC,\
        :x->ORDVALLTAXHF,\
        :x->TAXVALFTAXFSDISC,\
        :x->TAXVALFTAXFS,\
        :x->TAXVALLTAXFSDISC,\
        :x->TAXVALLTAXFS,\
        :x->TAXVALFTAXHFDISC,\
        :x->TAXVALFTAXHF,\
        :x->TAXVALLTAXHFDISC,\
        :x->TAXVALLTAXHF,\
        :x->ORDVALFTAXRSDISC,\
        :x->ORDVALFTAXRS,\
        :x->ORDVALLTAXRSDISC,\
        :x->ORDVALLTAXRS,\
        :x->TAXVALFTAXRSDISC,\
        :x->TAXVALFTAXRS,\
        :x->TAXVALLTAXRSDISC,\
        :x->TAXVALLTAXRS,\
        :x->ORDVALNTAXFSDISC,\
        :x->ORDVALNTAXFS,\
        :x->ORDVALNTAXHFDISC,\
        :x->ORDVALNTAXHF,\
        :x->ORDVALNTAXRSDISC,\
        :x->ORDVALNTAXRS,\
        :x->TAXVALNTAXFSDISC,\
        :x->TAXVALNTAXFS,\
        :x->TAXVALNTAXHFDISC,\
        :x->TAXVALNTAXHF,\
        :x->TAXVALNTAXRSDISC,\
        :x->TAXVALNTAXRS
#define KDAUFTRAGWERTE_ZEIGERSEL(x) \
        :x->KDAUFTRAGNR,\
        :x->ORDVALFTAXFSDISC,\
        :x->ORDVALFTAXFS,\
        :x->ORDVALLTAXFSDISC,\
        :x->ORDVALLTAXFS,\
        :x->ORDVALFTAXHFDISC,\
        :x->ORDVALFTAXHF,\
        :x->ORDVALLTAXHFDISC,\
        :x->ORDVALLTAXHF,\
        :x->TAXVALFTAXFSDISC,\
        :x->TAXVALFTAXFS,\
        :x->TAXVALLTAXFSDISC,\
        :x->TAXVALLTAXFS,\
        :x->TAXVALFTAXHFDISC,\
        :x->TAXVALFTAXHF,\
        :x->TAXVALLTAXHFDISC,\
        :x->TAXVALLTAXHF,\
        :x->ORDVALFTAXRSDISC,\
        :x->ORDVALFTAXRS,\
        :x->ORDVALLTAXRSDISC,\
        :x->ORDVALLTAXRS,\
        :x->TAXVALFTAXRSDISC,\
        :x->TAXVALFTAXRS,\
        :x->TAXVALLTAXRSDISC,\
        :x->TAXVALLTAXRS,\
        :x->ORDVALNTAXFSDISC,\
        :x->ORDVALNTAXFS,\
        :x->ORDVALNTAXHFDISC,\
        :x->ORDVALNTAXHF,\
        :x->ORDVALNTAXRSDISC,\
        :x->ORDVALNTAXRS,\
        :x->TAXVALNTAXFSDISC,\
        :x->TAXVALNTAXFS,\
        :x->TAXVALNTAXHFDISC,\
        :x->TAXVALNTAXHF,\
        :x->TAXVALNTAXRSDISC,\
        :x->TAXVALNTAXRS
#define KDAUFTRAGWERTE_UPDATE(x) \
        KDAUFTRAGWERTE.KDAUFTRAGNR=:x->KDAUFTRAGNR,\
        KDAUFTRAGWERTE.ORDVALFTAXFSDISC=:x->ORDVALFTAXFSDISC,\
        KDAUFTRAGWERTE.ORDVALFTAXFS=:x->ORDVALFTAXFS,\
        KDAUFTRAGWERTE.ORDVALLTAXFSDISC=:x->ORDVALLTAXFSDISC,\
        KDAUFTRAGWERTE.ORDVALLTAXFS=:x->ORDVALLTAXFS,\
        KDAUFTRAGWERTE.ORDVALFTAXHFDISC=:x->ORDVALFTAXHFDISC,\
        KDAUFTRAGWERTE.ORDVALFTAXHF=:x->ORDVALFTAXHF,\
        KDAUFTRAGWERTE.ORDVALLTAXHFDISC=:x->ORDVALLTAXHFDISC,\
        KDAUFTRAGWERTE.ORDVALLTAXHF=:x->ORDVALLTAXHF,\
        KDAUFTRAGWERTE.TAXVALFTAXFSDISC=:x->TAXVALFTAXFSDISC,\
        KDAUFTRAGWERTE.TAXVALFTAXFS=:x->TAXVALFTAXFS,\
        KDAUFTRAGWERTE.TAXVALLTAXFSDISC=:x->TAXVALLTAXFSDISC,\
        KDAUFTRAGWERTE.TAXVALLTAXFS=:x->TAXVALLTAXFS,\
        KDAUFTRAGWERTE.TAXVALFTAXHFDISC=:x->TAXVALFTAXHFDISC,\
        KDAUFTRAGWERTE.TAXVALFTAXHF=:x->TAXVALFTAXHF,\
        KDAUFTRAGWERTE.TAXVALLTAXHFDISC=:x->TAXVALLTAXHFDISC,\
        KDAUFTRAGWERTE.TAXVALLTAXHF=:x->TAXVALLTAXHF,\
        KDAUFTRAGWERTE.ORDVALFTAXRSDISC=:x->ORDVALFTAXRSDISC,\
        KDAUFTRAGWERTE.ORDVALFTAXRS=:x->ORDVALFTAXRS,\
        KDAUFTRAGWERTE.ORDVALLTAXRSDISC=:x->ORDVALLTAXRSDISC,\
        KDAUFTRAGWERTE.ORDVALLTAXRS=:x->ORDVALLTAXRS,\
        KDAUFTRAGWERTE.TAXVALFTAXRSDISC=:x->TAXVALFTAXRSDISC,\
        KDAUFTRAGWERTE.TAXVALFTAXRS=:x->TAXVALFTAXRS,\
        KDAUFTRAGWERTE.TAXVALLTAXRSDISC=:x->TAXVALLTAXRSDISC,\
        KDAUFTRAGWERTE.TAXVALLTAXRS=:x->TAXVALLTAXRS,\
        KDAUFTRAGWERTE.ORDVALNTAXFSDISC=:x->ORDVALNTAXFSDISC,\
        KDAUFTRAGWERTE.ORDVALNTAXFS=:x->ORDVALNTAXFS,\
        KDAUFTRAGWERTE.ORDVALNTAXHFDISC=:x->ORDVALNTAXHFDISC,\
        KDAUFTRAGWERTE.ORDVALNTAXHF=:x->ORDVALNTAXHF,\
        KDAUFTRAGWERTE.ORDVALNTAXRSDISC=:x->ORDVALNTAXRSDISC,\
        KDAUFTRAGWERTE.ORDVALNTAXRS=:x->ORDVALNTAXRS,\
        KDAUFTRAGWERTE.TAXVALNTAXFSDISC=:x->TAXVALNTAXFSDISC,\
        KDAUFTRAGWERTE.TAXVALNTAXFS=:x->TAXVALNTAXFS,\
        KDAUFTRAGWERTE.TAXVALNTAXHFDISC=:x->TAXVALNTAXHFDISC,\
        KDAUFTRAGWERTE.TAXVALNTAXHF=:x->TAXVALNTAXHF,\
        KDAUFTRAGWERTE.TAXVALNTAXRSDISC=:x->TAXVALNTAXRSDISC,\
        KDAUFTRAGWERTE.TAXVALNTAXRS=:x->TAXVALNTAXRS
/* SqlMacros390-Define of KDAUFTRAGWERTE **************************************/

#define KDAUFTRAGWERTE_ZEIGER_390 \
        :KDAUFTRAGNR,\
        :ORDVALFTAXFSDISC,\
        :ORDVALFTAXFS,\
        :ORDVALLTAXFSDISC,\
        :ORDVALLTAXFS,\
        :ORDVALFTAXHFDISC,\
        :ORDVALFTAXHF,\
        :ORDVALLTAXHFDISC,\
        :ORDVALLTAXHF,\
        :TAXVALFTAXFSDISC,\
        :TAXVALFTAXFS,\
        :TAXVALLTAXFSDISC,\
        :TAXVALLTAXFS,\
        :TAXVALFTAXHFDISC,\
        :TAXVALFTAXHF,\
        :TAXVALLTAXHFDISC,\
        :TAXVALLTAXHF,\
        :ORDVALFTAXRSDISC,\
        :ORDVALFTAXRS,\
        :ORDVALLTAXRSDISC,\
        :ORDVALLTAXRS,\
        :TAXVALFTAXRSDISC,\
        :TAXVALFTAXRS,\
        :TAXVALLTAXRSDISC,\
        :TAXVALLTAXRS,\
        :ORDVALNTAXFSDISC,\
        :ORDVALNTAXFS,\
        :ORDVALNTAXHFDISC,\
        :ORDVALNTAXHF,\
        :ORDVALNTAXRSDISC,\
        :ORDVALNTAXRS,\
        :TAXVALNTAXFSDISC,\
        :TAXVALNTAXFS,\
        :TAXVALNTAXHFDISC,\
        :TAXVALNTAXHF,\
        :TAXVALNTAXRSDISC,\
        :TAXVALNTAXRS
#define KDAUFTRAGWERTE_UPDATE_390 \
        KDAUFTRAGNR=:KDAUFTRAGNR,\
        ORDVALFTAXFSDISC=:ORDVALFTAXFSDISC,\
        ORDVALFTAXFS=:ORDVALFTAXFS,\
        ORDVALLTAXFSDISC=:ORDVALLTAXFSDISC,\
        ORDVALLTAXFS=:ORDVALLTAXFS,\
        ORDVALFTAXHFDISC=:ORDVALFTAXHFDISC,\
        ORDVALFTAXHF=:ORDVALFTAXHF,\
        ORDVALLTAXHFDISC=:ORDVALLTAXHFDISC,\
        ORDVALLTAXHF=:ORDVALLTAXHF,\
        TAXVALFTAXFSDISC=:TAXVALFTAXFSDISC,\
        TAXVALFTAXFS=:TAXVALFTAXFS,\
        TAXVALLTAXFSDISC=:TAXVALLTAXFSDISC,\
        TAXVALLTAXFS=:TAXVALLTAXFS,\
        TAXVALFTAXHFDISC=:TAXVALFTAXHFDISC,\
        TAXVALFTAXHF=:TAXVALFTAXHF,\
        TAXVALLTAXHFDISC=:TAXVALLTAXHFDISC,\
        TAXVALLTAXHF=:TAXVALLTAXHF,\
        ORDVALFTAXRSDISC=:ORDVALFTAXRSDISC,\
        ORDVALFTAXRS=:ORDVALFTAXRS,\
        ORDVALLTAXRSDISC=:ORDVALLTAXRSDISC,\
        ORDVALLTAXRS=:ORDVALLTAXRS,\
        TAXVALFTAXRSDISC=:TAXVALFTAXRSDISC,\
        TAXVALFTAXRS=:TAXVALFTAXRS,\
        TAXVALLTAXRSDISC=:TAXVALLTAXRSDISC,\
        TAXVALLTAXRS=:TAXVALLTAXRS,\
        ORDVALNTAXFSDISC=:ORDVALNTAXFSDISC,\
        ORDVALNTAXFS=:ORDVALNTAXFS,\
        ORDVALNTAXHFDISC=:ORDVALNTAXHFDISC,\
        ORDVALNTAXHF=:ORDVALNTAXHF,\
        ORDVALNTAXRSDISC=:ORDVALNTAXRSDISC,\
        ORDVALNTAXRS=:ORDVALNTAXRS,\
        TAXVALNTAXFSDISC=:TAXVALNTAXFSDISC,\
        TAXVALNTAXFS=:TAXVALNTAXFS,\
        TAXVALNTAXHFDISC=:TAXVALNTAXHFDISC,\
        TAXVALNTAXHF=:TAXVALNTAXHF,\
        TAXVALNTAXRSDISC=:TAXVALNTAXRSDISC,\
        TAXVALNTAXRS=:TAXVALNTAXRS
#ifdef TRANSCLASS
#include <string.h>
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* original struct of KDAUFTRAGWERTE ******************************************/

#ifndef TRANSCLASS
typedef struct N_KDAUFTRAGWERTE {
    long KDAUFTRAGNR;
    double ORDVALFTAXFSDISC;
    double ORDVALFTAXFS;
    double ORDVALLTAXFSDISC;
    double ORDVALLTAXFS;
    double ORDVALFTAXHFDISC;
    double ORDVALFTAXHF;
    double ORDVALLTAXHFDISC;
    double ORDVALLTAXHF;
    double TAXVALFTAXFSDISC;
    double TAXVALFTAXFS;
    double TAXVALLTAXFSDISC;
    double TAXVALLTAXFS;
    double TAXVALFTAXHFDISC;
    double TAXVALFTAXHF;
    double TAXVALLTAXHFDISC;
    double TAXVALLTAXHF;
    double ORDVALFTAXRSDISC;
    double ORDVALFTAXRS;
    double ORDVALLTAXRSDISC;
    double ORDVALLTAXRS;
    double TAXVALFTAXRSDISC;
    double TAXVALFTAXRS;
    double TAXVALLTAXRSDISC;
    double TAXVALLTAXRS;
    double ORDVALNTAXFSDISC;
    double ORDVALNTAXFS;
    double ORDVALNTAXHFDISC;
    double ORDVALNTAXHF;
    double ORDVALNTAXRSDISC;
    double ORDVALNTAXRS;
    double TAXVALNTAXFSDISC;
    double TAXVALNTAXFS;
    double TAXVALNTAXHFDISC;
    double TAXVALNTAXHF;
    double TAXVALNTAXRSDISC;
    double TAXVALNTAXRS;
} kdauftragwerteS;
#else /* TRANSCLASS */
typedef struct N_KDAUFTRAGWERTE {
    long KDAUFTRAGNR;
    double ORDVALFTAXFSDISC;
    double ORDVALFTAXFS;
    double ORDVALLTAXFSDISC;
    double ORDVALLTAXFS;
    double ORDVALFTAXHFDISC;
    double ORDVALFTAXHF;
    double ORDVALLTAXHFDISC;
    double ORDVALLTAXHF;
    double TAXVALFTAXFSDISC;
    double TAXVALFTAXFS;
    double TAXVALLTAXFSDISC;
    double TAXVALLTAXFS;
    double TAXVALFTAXHFDISC;
    double TAXVALFTAXHF;
    double TAXVALLTAXHFDISC;
    double TAXVALLTAXHF;
    double ORDVALFTAXRSDISC;
    double ORDVALFTAXRS;
    double ORDVALLTAXRSDISC;
    double ORDVALLTAXRS;
    double TAXVALFTAXRSDISC;
    double TAXVALFTAXRS;
    double TAXVALLTAXRSDISC;
    double TAXVALLTAXRS;
    double ORDVALNTAXFSDISC;
    double ORDVALNTAXFS;
    double ORDVALNTAXHFDISC;
    double ORDVALNTAXHF;
    double ORDVALNTAXRSDISC;
    double ORDVALNTAXRS;
    double TAXVALNTAXFSDISC;
    double TAXVALNTAXFS;
    double TAXVALNTAXHFDISC;
    double TAXVALNTAXHF;
    double TAXVALNTAXRSDISC;
    double TAXVALNTAXRS;

    bool operator == (const N_KDAUFTRAGWERTE& right) const {
        return (
            KDAUFTRAGNR == right.KDAUFTRAGNR &&
            ORDVALFTAXFSDISC == right.ORDVALFTAXFSDISC &&
            ORDVALFTAXFS == right.ORDVALFTAXFS &&
            ORDVALLTAXFSDISC == right.ORDVALLTAXFSDISC &&
            ORDVALLTAXFS == right.ORDVALLTAXFS &&
            ORDVALFTAXHFDISC == right.ORDVALFTAXHFDISC &&
            ORDVALFTAXHF == right.ORDVALFTAXHF &&
            ORDVALLTAXHFDISC == right.ORDVALLTAXHFDISC &&
            ORDVALLTAXHF == right.ORDVALLTAXHF &&
            TAXVALFTAXFSDISC == right.TAXVALFTAXFSDISC &&
            TAXVALFTAXFS == right.TAXVALFTAXFS &&
            TAXVALLTAXFSDISC == right.TAXVALLTAXFSDISC &&
            TAXVALLTAXFS == right.TAXVALLTAXFS &&
            TAXVALFTAXHFDISC == right.TAXVALFTAXHFDISC &&
            TAXVALFTAXHF == right.TAXVALFTAXHF &&
            TAXVALLTAXHFDISC == right.TAXVALLTAXHFDISC &&
            TAXVALLTAXHF == right.TAXVALLTAXHF &&
            ORDVALFTAXRSDISC == right.ORDVALFTAXRSDISC &&
            ORDVALFTAXRS == right.ORDVALFTAXRS &&
            ORDVALLTAXRSDISC == right.ORDVALLTAXRSDISC &&
            ORDVALLTAXRS == right.ORDVALLTAXRS &&
            TAXVALFTAXRSDISC == right.TAXVALFTAXRSDISC &&
            TAXVALFTAXRS == right.TAXVALFTAXRS &&
            TAXVALLTAXRSDISC == right.TAXVALLTAXRSDISC &&
            TAXVALLTAXRS == right.TAXVALLTAXRS &&
            ORDVALNTAXFSDISC == right.ORDVALNTAXFSDISC &&
            ORDVALNTAXFS == right.ORDVALNTAXFS &&
            ORDVALNTAXHFDISC == right.ORDVALNTAXHFDISC &&
            ORDVALNTAXHF == right.ORDVALNTAXHF &&
            ORDVALNTAXRSDISC == right.ORDVALNTAXRSDISC &&
            ORDVALNTAXRS == right.ORDVALNTAXRS &&
            TAXVALNTAXFSDISC == right.TAXVALNTAXFSDISC &&
            TAXVALNTAXFS == right.TAXVALNTAXFS &&
            TAXVALNTAXHFDISC == right.TAXVALNTAXHFDISC &&
            TAXVALNTAXHF == right.TAXVALNTAXHF &&
            TAXVALNTAXRSDISC == right.TAXVALNTAXRSDISC &&
            TAXVALNTAXRS == right.TAXVALNTAXRS
        );
    }
    void clear() {
#ifdef WIN32
        memset((char*)this, 0, sizeof(*this));
#else
        KDAUFTRAGNR = 0;
        ORDVALFTAXFSDISC = 0;
        ORDVALFTAXFS = 0;
        ORDVALLTAXFSDISC = 0;
        ORDVALLTAXFS = 0;
        ORDVALFTAXHFDISC = 0;
        ORDVALFTAXHF = 0;
        ORDVALLTAXHFDISC = 0;
        ORDVALLTAXHF = 0;
        TAXVALFTAXFSDISC = 0;
        TAXVALFTAXFS = 0;
        TAXVALLTAXFSDISC = 0;
        TAXVALLTAXFS = 0;
        TAXVALFTAXHFDISC = 0;
        TAXVALFTAXHF = 0;
        TAXVALLTAXHFDISC = 0;
        TAXVALLTAXHF = 0;
        ORDVALFTAXRSDISC = 0;
        ORDVALFTAXRS = 0;
        ORDVALLTAXRSDISC = 0;
        ORDVALLTAXRS = 0;
        TAXVALFTAXRSDISC = 0;
        TAXVALFTAXRS = 0;
        TAXVALLTAXRSDISC = 0;
        TAXVALLTAXRS = 0;
        ORDVALNTAXFSDISC = 0;
        ORDVALNTAXFS = 0;
        ORDVALNTAXHFDISC = 0;
        ORDVALNTAXHF = 0;
        ORDVALNTAXRSDISC = 0;
        ORDVALNTAXRS = 0;
        TAXVALNTAXFSDISC = 0;
        TAXVALNTAXFS = 0;
        TAXVALNTAXHFDISC = 0;
        TAXVALNTAXHF = 0;
        TAXVALNTAXRSDISC = 0;
        TAXVALNTAXRS = 0;
#endif
    }
} kdauftragwerteS;
#endif /* TRANSCLASS */

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Stringbuffer Structur of KDAUFTRAGWERTE ************************************/

struct S_KDAUFTRAGWERTE {
    char KDAUFTRAGNR[11];
    char ORDVALFTAXFSDISC[11 + 2];
    char ORDVALFTAXFS[11 + 2];
    char ORDVALLTAXFSDISC[11 + 2];
    char ORDVALLTAXFS[11 + 2];
    char ORDVALFTAXHFDISC[11 + 2];
    char ORDVALFTAXHF[11 + 2];
    char ORDVALLTAXHFDISC[11 + 2];
    char ORDVALLTAXHF[11 + 2];
    char TAXVALFTAXFSDISC[9 + 2];
    char TAXVALFTAXFS[9 + 2];
    char TAXVALLTAXFSDISC[9 + 2];
    char TAXVALLTAXFS[9 + 2];
    char TAXVALFTAXHFDISC[9 + 2];
    char TAXVALFTAXHF[9 + 2];
    char TAXVALLTAXHFDISC[9 + 2];
    char TAXVALLTAXHF[9 + 2];
    char ORDVALFTAXRSDISC[11 + 2];
    char ORDVALFTAXRS[11 + 2];
    char ORDVALLTAXRSDISC[11 + 2];
    char ORDVALLTAXRS[11 + 2];
    char TAXVALFTAXRSDISC[9 + 2];
    char TAXVALFTAXRS[9 + 2];
    char TAXVALLTAXRSDISC[9 + 2];
    char TAXVALLTAXRS[9 + 2];
    char ORDVALNTAXFSDISC[11 + 2];
    char ORDVALNTAXFS[11 + 2];
    char ORDVALNTAXHFDISC[11 + 2];
    char ORDVALNTAXHF[11 + 2];
    char ORDVALNTAXRSDISC[11 + 2];
    char ORDVALNTAXRS[11 + 2];
    char TAXVALNTAXFSDISC[9 + 2];
    char TAXVALNTAXFS[9 + 2];
    char TAXVALNTAXHFDISC[9 + 2];
    char TAXVALNTAXHF[9 + 2];
    char TAXVALNTAXRSDISC[9 + 2];
    char TAXVALNTAXRS[9 + 2];
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Stringbuffer (without strend) Structur of KDAUFTRAGWERTE *******************/

struct O_KDAUFTRAGWERTE {
    char KDAUFTRAGNR[11];
    char ORDVALFTAXFSDISC[11];
    char ORDVALFTAXFS[11];
    char ORDVALLTAXFSDISC[11];
    char ORDVALLTAXFS[11];
    char ORDVALFTAXHFDISC[11];
    char ORDVALFTAXHF[11];
    char ORDVALLTAXHFDISC[11];
    char ORDVALLTAXHF[11];
    char TAXVALFTAXFSDISC[9];
    char TAXVALFTAXFS[9];
    char TAXVALLTAXFSDISC[9];
    char TAXVALLTAXFS[9];
    char TAXVALFTAXHFDISC[9];
    char TAXVALFTAXHF[9];
    char TAXVALLTAXHFDISC[9];
    char TAXVALLTAXHF[9];
    char ORDVALFTAXRSDISC[11];
    char ORDVALFTAXRS[11];
    char ORDVALLTAXRSDISC[11];
    char ORDVALLTAXRS[11];
    char TAXVALFTAXRSDISC[9];
    char TAXVALFTAXRS[9];
    char TAXVALLTAXRSDISC[9];
    char TAXVALLTAXRS[9];
    char ORDVALNTAXFSDISC[11];
    char ORDVALNTAXFS[11];
    char ORDVALNTAXHFDISC[11];
    char ORDVALNTAXHF[11];
    char ORDVALNTAXRSDISC[11];
    char ORDVALNTAXRS[11];
    char TAXVALNTAXFSDISC[9];
    char TAXVALNTAXFS[9];
    char TAXVALNTAXHFDISC[9];
    char TAXVALNTAXHF[9];
    char TAXVALNTAXRSDISC[9];
    char TAXVALNTAXRS[9];
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Structur with real chartype of KDAUFTRAGWERTE ******************************/

struct C_KDAUFTRAGWERTE {
    long KDAUFTRAGNR;
    double ORDVALFTAXFSDISC;
    double ORDVALFTAXFS;
    double ORDVALLTAXFSDISC;
    double ORDVALLTAXFS;
    double ORDVALFTAXHFDISC;
    double ORDVALFTAXHF;
    double ORDVALLTAXHFDISC;
    double ORDVALLTAXHF;
    double TAXVALFTAXFSDISC;
    double TAXVALFTAXFS;
    double TAXVALLTAXFSDISC;
    double TAXVALLTAXFS;
    double TAXVALFTAXHFDISC;
    double TAXVALFTAXHF;
    double TAXVALLTAXHFDISC;
    double TAXVALLTAXHF;
    double ORDVALFTAXRSDISC;
    double ORDVALFTAXRS;
    double ORDVALLTAXRSDISC;
    double ORDVALLTAXRS;
    double TAXVALFTAXRSDISC;
    double TAXVALFTAXRS;
    double TAXVALLTAXRSDISC;
    double TAXVALLTAXRS;
    double ORDVALNTAXFSDISC;
    double ORDVALNTAXFS;
    double ORDVALNTAXHFDISC;
    double ORDVALNTAXHF;
    double ORDVALNTAXRSDISC;
    double ORDVALNTAXRS;
    double TAXVALNTAXFSDISC;
    double TAXVALNTAXFS;
    double TAXVALNTAXHFDISC;
    double TAXVALNTAXHF;
    double TAXVALNTAXRSDISC;
    double TAXVALNTAXRS;
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Sizetype  Structur (buf_desc) of KDAUFTRAGWERTE ****************************/

struct I_KDAUFTRAGWERTE {
    short KDAUFTRAGNR;
    short ORDVALFTAXFSDISC;
    short ORDVALFTAXFS;
    short ORDVALLTAXFSDISC;
    short ORDVALLTAXFS;
    short ORDVALFTAXHFDISC;
    short ORDVALFTAXHF;
    short ORDVALLTAXHFDISC;
    short ORDVALLTAXHF;
    short TAXVALFTAXFSDISC;
    short TAXVALFTAXFS;
    short TAXVALLTAXFSDISC;
    short TAXVALLTAXFS;
    short TAXVALFTAXHFDISC;
    short TAXVALFTAXHF;
    short TAXVALLTAXHFDISC;
    short TAXVALLTAXHF;
    short ORDVALFTAXRSDISC;
    short ORDVALFTAXRS;
    short ORDVALLTAXRSDISC;
    short ORDVALLTAXRS;
    short TAXVALFTAXRSDISC;
    short TAXVALFTAXRS;
    short TAXVALLTAXRSDISC;
    short TAXVALLTAXRS;
    short ORDVALNTAXFSDISC;
    short ORDVALNTAXFS;
    short ORDVALNTAXHFDISC;
    short ORDVALNTAXHF;
    short ORDVALNTAXRSDISC;
    short ORDVALNTAXRS;
    short TAXVALNTAXFSDISC;
    short TAXVALNTAXFS;
    short TAXVALNTAXHFDISC;
    short TAXVALNTAXHF;
    short TAXVALNTAXRSDISC;
    short TAXVALNTAXRS;
};
#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif

/* structures of Buf_Desc *****************************************************/

/* Structur (buf_desc) of KDAUFTRAGWERTE **************************************/

#if defined (BUF_DESC)
static struct buf_desc KDAUFTRAGWERTE_BES [] = {
   { TYP_L , 11, 0 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
};
#elif defined (C_BUF_DESC)
static struct buf_desc KDAUFTRAGWERTE_BES [] = {
   { TYP_L , 11, 0 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 11, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
   { TYP_D, 9, 2 },
};
#endif

/* description for datatypes of KDAUFTRAGWERTE ********************************/

 #define KDAUFTRAGWERTE_S390 \
         long KDAUFTRAGNR; \
         double ORDVALFTAXFSDISC; \
         double ORDVALFTAXFS; \
         double ORDVALLTAXFSDISC; \
         double ORDVALLTAXFS; \
         double ORDVALFTAXHFDISC; \
         double ORDVALFTAXHF; \
         double ORDVALLTAXHFDISC; \
         double ORDVALLTAXHF; \
         double TAXVALFTAXFSDISC; \
         double TAXVALFTAXFS; \
         double TAXVALLTAXFSDISC; \
         double TAXVALLTAXFS; \
         double TAXVALFTAXHFDISC; \
         double TAXVALFTAXHF; \
         double TAXVALLTAXHFDISC; \
         double TAXVALLTAXHF; \
         double ORDVALFTAXRSDISC; \
         double ORDVALFTAXRS; \
         double ORDVALLTAXRSDISC; \
         double ORDVALLTAXRS; \
         double TAXVALFTAXRSDISC; \
         double TAXVALFTAXRS; \
         double TAXVALLTAXRSDISC; \
         double TAXVALLTAXRS; \
         double ORDVALNTAXFSDISC; \
         double ORDVALNTAXFS; \
         double ORDVALNTAXHFDISC; \
         double ORDVALNTAXHF; \
         double ORDVALNTAXRSDISC; \
         double ORDVALNTAXRS; \
         double TAXVALNTAXFSDISC; \
         double TAXVALNTAXFS; \
         double TAXVALNTAXHFDISC; \
         double TAXVALNTAXHF; \
         double TAXVALNTAXRSDISC; \
         double TAXVALNTAXRS; \



/* Copy-Function Struct to single Data KDAUFTRAGWERTE *************************/

 #define KDAUFTRAGWERTE_S390_COPY_TO_SINGLE(_x_) \
         KDAUFTRAGNR=_x_->KDAUFTRAGNR;\
         ORDVALFTAXFSDISC=_x_->ORDVALFTAXFSDISC;\
         ORDVALFTAXFS=_x_->ORDVALFTAXFS;\
         ORDVALLTAXFSDISC=_x_->ORDVALLTAXFSDISC;\
         ORDVALLTAXFS=_x_->ORDVALLTAXFS;\
         ORDVALFTAXHFDISC=_x_->ORDVALFTAXHFDISC;\
         ORDVALFTAXHF=_x_->ORDVALFTAXHF;\
         ORDVALLTAXHFDISC=_x_->ORDVALLTAXHFDISC;\
         ORDVALLTAXHF=_x_->ORDVALLTAXHF;\
         TAXVALFTAXFSDISC=_x_->TAXVALFTAXFSDISC;\
         TAXVALFTAXFS=_x_->TAXVALFTAXFS;\
         TAXVALLTAXFSDISC=_x_->TAXVALLTAXFSDISC;\
         TAXVALLTAXFS=_x_->TAXVALLTAXFS;\
         TAXVALFTAXHFDISC=_x_->TAXVALFTAXHFDISC;\
         TAXVALFTAXHF=_x_->TAXVALFTAXHF;\
         TAXVALLTAXHFDISC=_x_->TAXVALLTAXHFDISC;\
         TAXVALLTAXHF=_x_->TAXVALLTAXHF;\
         ORDVALFTAXRSDISC=_x_->ORDVALFTAXRSDISC;\
         ORDVALFTAXRS=_x_->ORDVALFTAXRS;\
         ORDVALLTAXRSDISC=_x_->ORDVALLTAXRSDISC;\
         ORDVALLTAXRS=_x_->ORDVALLTAXRS;\
         TAXVALFTAXRSDISC=_x_->TAXVALFTAXRSDISC;\
         TAXVALFTAXRS=_x_->TAXVALFTAXRS;\
         TAXVALLTAXRSDISC=_x_->TAXVALLTAXRSDISC;\
         TAXVALLTAXRS=_x_->TAXVALLTAXRS;\
         ORDVALNTAXFSDISC=_x_->ORDVALNTAXFSDISC;\
         ORDVALNTAXFS=_x_->ORDVALNTAXFS;\
         ORDVALNTAXHFDISC=_x_->ORDVALNTAXHFDISC;\
         ORDVALNTAXHF=_x_->ORDVALNTAXHF;\
         ORDVALNTAXRSDISC=_x_->ORDVALNTAXRSDISC;\
         ORDVALNTAXRS=_x_->ORDVALNTAXRS;\
         TAXVALNTAXFSDISC=_x_->TAXVALNTAXFSDISC;\
         TAXVALNTAXFS=_x_->TAXVALNTAXFS;\
         TAXVALNTAXHFDISC=_x_->TAXVALNTAXHFDISC;\
         TAXVALNTAXHF=_x_->TAXVALNTAXHF;\
         TAXVALNTAXRSDISC=_x_->TAXVALNTAXRSDISC;\
         TAXVALNTAXRS=_x_->TAXVALNTAXRS;\

 #define KDAUFTRAGWERTE_S390_COPY_TO_STRUCT(_x_) \
          _x_->KDAUFTRAGNR=KDAUFTRAGNR;\
          _x_->ORDVALFTAXFSDISC=ORDVALFTAXFSDISC;\
          _x_->ORDVALFTAXFS=ORDVALFTAXFS;\
          _x_->ORDVALLTAXFSDISC=ORDVALLTAXFSDISC;\
          _x_->ORDVALLTAXFS=ORDVALLTAXFS;\
          _x_->ORDVALFTAXHFDISC=ORDVALFTAXHFDISC;\
          _x_->ORDVALFTAXHF=ORDVALFTAXHF;\
          _x_->ORDVALLTAXHFDISC=ORDVALLTAXHFDISC;\
          _x_->ORDVALLTAXHF=ORDVALLTAXHF;\
          _x_->TAXVALFTAXFSDISC=TAXVALFTAXFSDISC;\
          _x_->TAXVALFTAXFS=TAXVALFTAXFS;\
          _x_->TAXVALLTAXFSDISC=TAXVALLTAXFSDISC;\
          _x_->TAXVALLTAXFS=TAXVALLTAXFS;\
          _x_->TAXVALFTAXHFDISC=TAXVALFTAXHFDISC;\
          _x_->TAXVALFTAXHF=TAXVALFTAXHF;\
          _x_->TAXVALLTAXHFDISC=TAXVALLTAXHFDISC;\
          _x_->TAXVALLTAXHF=TAXVALLTAXHF;\
          _x_->ORDVALFTAXRSDISC=ORDVALFTAXRSDISC;\
          _x_->ORDVALFTAXRS=ORDVALFTAXRS;\
          _x_->ORDVALLTAXRSDISC=ORDVALLTAXRSDISC;\
          _x_->ORDVALLTAXRS=ORDVALLTAXRS;\
          _x_->TAXVALFTAXRSDISC=TAXVALFTAXRSDISC;\
          _x_->TAXVALFTAXRS=TAXVALFTAXRS;\
          _x_->TAXVALLTAXRSDISC=TAXVALLTAXRSDISC;\
          _x_->TAXVALLTAXRS=TAXVALLTAXRS;\
          _x_->ORDVALNTAXFSDISC=ORDVALNTAXFSDISC;\
          _x_->ORDVALNTAXFS=ORDVALNTAXFS;\
          _x_->ORDVALNTAXHFDISC=ORDVALNTAXHFDISC;\
          _x_->ORDVALNTAXHF=ORDVALNTAXHF;\
          _x_->ORDVALNTAXRSDISC=ORDVALNTAXRSDISC;\
          _x_->ORDVALNTAXRS=ORDVALNTAXRS;\
          _x_->TAXVALNTAXFSDISC=TAXVALNTAXFSDISC;\
          _x_->TAXVALNTAXFS=TAXVALNTAXFS;\
          _x_->TAXVALNTAXHFDISC=TAXVALNTAXHFDISC;\
          _x_->TAXVALNTAXHF=TAXVALNTAXHF;\
          _x_->TAXVALNTAXRSDISC=TAXVALNTAXRSDISC;\
          _x_->TAXVALNTAXRS=TAXVALNTAXRS;\



/* FunctionNumber-Define of kdauftragwerte ************************************/


#ifdef PRZ_OLD_FUNCTION
/* Old-FunctionNumber-Define of kdauftragwerte ********************************/


#endif

/* C++ Class ******************************************************************/

#ifdef TRANSCLASS

#include<vector>
using namespace std;

/* ppunixc */
#include <sockclient.h>
#include <ppstring.h>
#include <ppgeneric.h>

/* must be implemented */
void FehlerBehandlung(int rc, const char * const error_msg);

#ifndef __VIRTUAL_DADE_CLASS__
#define __VIRTUAL_DADE_CLASS__

class ppDadeVirtual {
public:
    virtual    ~ppDadeVirtual() {};
    virtual int SelList      (int FetchRel = 1, int pos = 0) = 0;
    virtual int SelListHist  (int FetchRel = 1, int pos = 0) = 0;
    virtual int SelListFuture(int FetchRel = 1, int pos = 0) = 0;
    virtual int Load         (int pos = 0                  ) = 0;
    virtual int Delete       (int pos = 0                  ) = 0;
    virtual int Save         (int pos = 0                  ) = 0;
};
#endif

class CKDAUFTRAGWERTE : public ppDadeVirtual {
public:
    kdauftragwerteS s;
    int  rc;
    char error_msg[81];
private:
    bool bOpenCursor;
    bool bEndOfSelect;
    int  FncNumber;
    int  CursorPos;
    int  AnzPos;
    vector<kdauftragwerteS> lst; // class list

public:
    unsigned int GetSize() const { return static_cast<unsigned int>(lst.size()); };
    void         ClearStruct() { s.clear(); }
    bool         SetData(unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     s = lst.at(i);
                     return true;
                 }
    bool         SetList(const unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     vector< kdauftragwerteS >::iterator it = lst.begin() + i;
                     *it = s;
                     return true;
                 }
    bool         InsList() {
                     Strip(s);
                     kdauftragwerteS c = s;
                     lst.insert(lst.end(), c);
                     AnzPos++;
                     return true;
                 }
    bool         DelList(const unsigned int i) {
                     if (GetSize() <= i)
                         return false;
                     vector< kdauftragwerteS >::iterator it = lst.begin() + i;
                     if (it != lst.end())
                         lst.erase(it);
                     if (--AnzPos < 0)
                         AnzPos = 0;
                     return true;
                 }

    vector<kdauftragwerteS>::iterator
                 beginList() { return lst.begin(); }
    vector<kdauftragwerteS>::iterator
                 endList  () { return lst.end  (); }

    long         GetKdauftragnr() const { return s.KDAUFTRAGNR; }
    double       GetOrdvalftaxfsdisc() const { return s.ORDVALFTAXFSDISC; }
    double       GetOrdvalftaxfs() const { return s.ORDVALFTAXFS; }
    double       GetOrdvalltaxfsdisc() const { return s.ORDVALLTAXFSDISC; }
    double       GetOrdvalltaxfs() const { return s.ORDVALLTAXFS; }
    double       GetOrdvalftaxhfdisc() const { return s.ORDVALFTAXHFDISC; }
    double       GetOrdvalftaxhf() const { return s.ORDVALFTAXHF; }
    double       GetOrdvalltaxhfdisc() const { return s.ORDVALLTAXHFDISC; }
    double       GetOrdvalltaxhf() const { return s.ORDVALLTAXHF; }
    double       GetTaxvalftaxfsdisc() const { return s.TAXVALFTAXFSDISC; }
    double       GetTaxvalftaxfs() const { return s.TAXVALFTAXFS; }
    double       GetTaxvalltaxfsdisc() const { return s.TAXVALLTAXFSDISC; }
    double       GetTaxvalltaxfs() const { return s.TAXVALLTAXFS; }
    double       GetTaxvalftaxhfdisc() const { return s.TAXVALFTAXHFDISC; }
    double       GetTaxvalftaxhf() const { return s.TAXVALFTAXHF; }
    double       GetTaxvalltaxhfdisc() const { return s.TAXVALLTAXHFDISC; }
    double       GetTaxvalltaxhf() const { return s.TAXVALLTAXHF; }
    double       GetOrdvalftaxrsdisc() const { return s.ORDVALFTAXRSDISC; }
    double       GetOrdvalftaxrs() const { return s.ORDVALFTAXRS; }
    double       GetOrdvalltaxrsdisc() const { return s.ORDVALLTAXRSDISC; }
    double       GetOrdvalltaxrs() const { return s.ORDVALLTAXRS; }
    double       GetTaxvalftaxrsdisc() const { return s.TAXVALFTAXRSDISC; }
    double       GetTaxvalftaxrs() const { return s.TAXVALFTAXRS; }
    double       GetTaxvalltaxrsdisc() const { return s.TAXVALLTAXRSDISC; }
    double       GetTaxvalltaxrs() const { return s.TAXVALLTAXRS; }
    double       GetOrdvalntaxfsdisc() const { return s.ORDVALNTAXFSDISC; }
    double       GetOrdvalntaxfs() const { return s.ORDVALNTAXFS; }
    double       GetOrdvalntaxhfdisc() const { return s.ORDVALNTAXHFDISC; }
    double       GetOrdvalntaxhf() const { return s.ORDVALNTAXHF; }
    double       GetOrdvalntaxrsdisc() const { return s.ORDVALNTAXRSDISC; }
    double       GetOrdvalntaxrs() const { return s.ORDVALNTAXRS; }
    double       GetTaxvalntaxfsdisc() const { return s.TAXVALNTAXFSDISC; }
    double       GetTaxvalntaxfs() const { return s.TAXVALNTAXFS; }
    double       GetTaxvalntaxhfdisc() const { return s.TAXVALNTAXHFDISC; }
    double       GetTaxvalntaxhf() const { return s.TAXVALNTAXHF; }
    double       GetTaxvalntaxrsdisc() const { return s.TAXVALNTAXRSDISC; }
    double       GetTaxvalntaxrs() const { return s.TAXVALNTAXRS; }

    const kdauftragwerteS &
                 GetStruct() const { return s; }
    void         SetKdauftragnr(long t) { s.KDAUFTRAGNR = t; }
    void         SetOrdvalftaxfsdisc(double t) { s.ORDVALFTAXFSDISC = t; }
    void         SetOrdvalftaxfs(double t) { s.ORDVALFTAXFS = t; }
    void         SetOrdvalltaxfsdisc(double t) { s.ORDVALLTAXFSDISC = t; }
    void         SetOrdvalltaxfs(double t) { s.ORDVALLTAXFS = t; }
    void         SetOrdvalftaxhfdisc(double t) { s.ORDVALFTAXHFDISC = t; }
    void         SetOrdvalftaxhf(double t) { s.ORDVALFTAXHF = t; }
    void         SetOrdvalltaxhfdisc(double t) { s.ORDVALLTAXHFDISC = t; }
    void         SetOrdvalltaxhf(double t) { s.ORDVALLTAXHF = t; }
    void         SetTaxvalftaxfsdisc(double t) { s.TAXVALFTAXFSDISC = t; }
    void         SetTaxvalftaxfs(double t) { s.TAXVALFTAXFS = t; }
    void         SetTaxvalltaxfsdisc(double t) { s.TAXVALLTAXFSDISC = t; }
    void         SetTaxvalltaxfs(double t) { s.TAXVALLTAXFS = t; }
    void         SetTaxvalftaxhfdisc(double t) { s.TAXVALFTAXHFDISC = t; }
    void         SetTaxvalftaxhf(double t) { s.TAXVALFTAXHF = t; }
    void         SetTaxvalltaxhfdisc(double t) { s.TAXVALLTAXHFDISC = t; }
    void         SetTaxvalltaxhf(double t) { s.TAXVALLTAXHF = t; }
    void         SetOrdvalftaxrsdisc(double t) { s.ORDVALFTAXRSDISC = t; }
    void         SetOrdvalftaxrs(double t) { s.ORDVALFTAXRS = t; }
    void         SetOrdvalltaxrsdisc(double t) { s.ORDVALLTAXRSDISC = t; }
    void         SetOrdvalltaxrs(double t) { s.ORDVALLTAXRS = t; }
    void         SetTaxvalftaxrsdisc(double t) { s.TAXVALFTAXRSDISC = t; }
    void         SetTaxvalftaxrs(double t) { s.TAXVALFTAXRS = t; }
    void         SetTaxvalltaxrsdisc(double t) { s.TAXVALLTAXRSDISC = t; }
    void         SetTaxvalltaxrs(double t) { s.TAXVALLTAXRS = t; }
    void         SetOrdvalntaxfsdisc(double t) { s.ORDVALNTAXFSDISC = t; }
    void         SetOrdvalntaxfs(double t) { s.ORDVALNTAXFS = t; }
    void         SetOrdvalntaxhfdisc(double t) { s.ORDVALNTAXHFDISC = t; }
    void         SetOrdvalntaxhf(double t) { s.ORDVALNTAXHF = t; }
    void         SetOrdvalntaxrsdisc(double t) { s.ORDVALNTAXRSDISC = t; }
    void         SetOrdvalntaxrs(double t) { s.ORDVALNTAXRS = t; }
    void         SetTaxvalntaxfsdisc(double t) { s.TAXVALNTAXFSDISC = t; }
    void         SetTaxvalntaxfs(double t) { s.TAXVALNTAXFS = t; }
    void         SetTaxvalntaxhfdisc(double t) { s.TAXVALNTAXHFDISC = t; }
    void         SetTaxvalntaxhf(double t) { s.TAXVALNTAXHF = t; }
    void         SetTaxvalntaxrsdisc(double t) { s.TAXVALNTAXRSDISC = t; }
    void         SetTaxvalntaxrs(double t) { s.TAXVALNTAXRS = t; }

    void         SetStruct(const kdauftragwerteS & t) { s = t; }


    // virtual functions
public:
    int          Load(int pos = 0) { pos = pos; return 1; }
    int          Save(int pos = 0) { pos = pos; return 1; }
    int          Delete(int pos = 0) { pos = pos; return 1; }
    int          SelList(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }
    int          SelListHist(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }
    int          SelListFuture(int FetchRel = 1, int pos = 0) { FetchRel = FetchRel; pos = pos; return 1; }

    // constructor
    CKDAUFTRAGWERTE() {
        ::buf_default((void *)&s, KDAUFTRAGWERTE_BES, KDAUFTRAGWERTE_ANZ);
        bOpenCursor   = false;
        bEndOfSelect  = false;
        FncNumber     = 0;
        CursorPos     = 0;
        AnzPos        = 0;
        rc            = 0;
        s.clear();
    }

    // destructor
    virtual ~CKDAUFTRAGWERTE() {
    }

    // buffer init
    void buf_default() {
        ::buf_default((void *)&s, KDAUFTRAGWERTE_BES, KDAUFTRAGWERTE_ANZ);
    }

    // socket server call
    int Server(int fkt_nr, int pos = 0) {
    #ifdef WIN32
        rc = ::ServerNr(pos, fkt_nr, (void *)&s, KDAUFTRAGWERTE_BES, (int)KDAUFTRAGWERTE_ANZ, error_msg);
    #else
        rc = ::Server(fkt_nr, (void *)&s, KDAUFTRAGWERTE_BES, (int)KDAUFTRAGWERTE_ANZ, error_msg);
    #endif
        if (rc < 0)
            FehlerBehandlung( rc, error_msg );
        return rc;
    }

private:
    void Strip(N_KDAUFTRAGWERTE & d) {
        d = d;
    #ifdef WIN32
    #endif
    }

    int UniqueServerCall(int FncNr, int pos = 0) {
    #ifndef __DADE_LOAD__
       rc = ::ServerNr(pos, FncNr, (void *)&s, KDAUFTRAGWERTE_BES, (int)KDAUFTRAGWERTE_ANZ, error_msg);
    #else
       pos = pos;
       rc = DistributorFunSelect(FncNr, (void *)&s, error_msg, &rc);
    #endif
       if (rc < 0)
           FehlerBehandlung( rc, error_msg );
       return rc;
    }
};
#endif    // TRANSCLASS
/* CreateSqlStatement of KDAUFTRAGWERTE ***************************************/

 #define KDAUFTRAGWERTE_CREATE(x) EXEC SQL create table x (\
         KDAUFTRAGNR integer default 0 not null,\
         ORDVALFTAXFSDISC decimal(11,2) default 0 not null,\
         ORDVALFTAXFS decimal(11,2) default 0 not null,\
         ORDVALLTAXFSDISC decimal(11,2) default 0 not null,\
         ORDVALLTAXFS decimal(11,2) default 0 not null,\
         ORDVALFTAXHFDISC decimal(11,2) default 0 not null,\
         ORDVALFTAXHF decimal(11,2) default 0 not null,\
         ORDVALLTAXHFDISC decimal(11,2) default 0 not null,\
         ORDVALLTAXHF decimal(11,2) default 0 not null,\
         TAXVALFTAXFSDISC decimal(9,2) default 0 not null,\
         TAXVALFTAXFS decimal(9,2) default 0 not null,\
         TAXVALLTAXFSDISC decimal(9,2) default 0 not null,\
         TAXVALLTAXFS decimal(9,2) default 0 not null,\
         TAXVALFTAXHFDISC decimal(9,2) default 0 not null,\
         TAXVALFTAXHF decimal(9,2) default 0 not null,\
         TAXVALLTAXHFDISC decimal(9,2) default 0 not null,\
         TAXVALLTAXHF decimal(9,2) default 0 not null,\
         ORDVALFTAXRSDISC decimal(11,2) default 0 not null,\
         ORDVALFTAXRS decimal(11,2) default 0 not null,\
         ORDVALLTAXRSDISC decimal(11,2) default 0 not null,\
         ORDVALLTAXRS decimal(11,2) default 0 not null,\
         TAXVALFTAXRSDISC decimal(9,2) default 0 not null,\
         TAXVALFTAXRS decimal(9,2) default 0 not null,\
         TAXVALLTAXRSDISC decimal(9,2) default 0 not null,\
         TAXVALLTAXRS decimal(9,2) default 0 not null,\
         ORDVALNTAXFSDISC decimal(11,2) default 0 not null,\
         ORDVALNTAXFS decimal(11,2) default 0 not null,\
         ORDVALNTAXHFDISC decimal(11,2) default 0 not null,\
         ORDVALNTAXHF decimal(11,2) default 0 not null,\
         ORDVALNTAXRSDISC decimal(11,2) default 0 not null,\
         ORDVALNTAXRS decimal(11,2) default 0 not null,\
         TAXVALNTAXFSDISC decimal(9,2) default 0 not null,\
         TAXVALNTAXFS decimal(9,2) default 0 not null,\
         TAXVALNTAXHFDISC decimal(9,2) default 0 not null,\
         TAXVALNTAXHF decimal(9,2) default 0 not null,\
         TAXVALNTAXRSDISC decimal(9,2) default 0 not null,\
         TAXVALNTAXRS decimal(9,2) default 0 not null) in ksc extent size 940 next size 96 lock mode row;



/* CreateIndexStatement of KDAUFTRAGWERTE *************************************/

 #define KDAUFTRAGWERTE_CREATE_INDEX(_X_,_Y_)\
              _Y_ = 0;\
         EXEC SQL create unique index i_kdauftragwerte_1 on _X_(\
              kdauftragnr ) in kscidx;\
         if ( sqlca.sqlcode != 0 ) _Y_ = sqlca.sqlcode;\


/* DeleteIndexStatement of KDAUFTRAGWERTE *************************************/

 #define KDAUFTRAGWERTE_DELETE_INDEX(_X_)\
              _X_ = 0;\
         EXEC SQL drop index i_kdauftragwerte_1;\
         if ( sqlca.sqlcode != 0 ) _X_ = sqlca.sqlcode;\




#endif   // GUARD
