#ifndef __PP_NARCTRACTTRFER_H_
#define __PP_NARCTRACTTRFER_H_

/******************************************************************************/
/* C:\prj\ek\exeink\dbmod\artkonto\artkonto ***********************************/
/******************************************************************************/

/* Length-Define of NARCTRANSACTIONTRANSFER **********************************************/

  #define L_NARCTRANSACTIONTRANSFER_TRANSFERID 11
  #define L_NARCTRANSACTIONTRANSFER_BRANCHNO 6
  #define L_NARCTRANSACTIONTRANSFER_ARTICLENO 11
  #define L_NARCTRANSACTIONTRANSFER_TRANSACTIONDATE 11
  #define L_NARCTRANSACTIONTRANSFER_TRANSACTIONTIME 11
  #define L_NARCTRANSACTIONTRANSFER_CUSTOMERSUPPLIERNO 11
  #define L_NARCTRANSACTIONTRANSFER_TRANSACTIONTYPE 2
  #define L_NARCTRANSACTIONTRANSFER_PURCHASEORDERNO 11
  #define L_NARCTRANSACTIONTRANSFER_ORDERNO 11
  #define L_NARCTRANSACTIONTRANSFER_QTYTRANSACTION 11
  #define L_NARCTRANSACTIONTRANSFER_QTYINSTOCK 11
  #define L_NARCTRANSACTIONTRANSFER_COMPLETEDFLAG 1
  #define L_NARCTRANSACTIONTRANSFER_POSNO 11
  #define L_NARCTRANSACTIONTRANSFER_TOURID 6

/* Length/Count-Define of NARCTRANSACTIONTRANSFER ****************************************/

  #define LS_NARCTRANSACTIONTRANSFER_TRANSFERID 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_BRANCHNO 5 + 1
  #define LS_NARCTRANSACTIONTRANSFER_ARTICLENO 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_TRANSACTIONDATE 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_TRANSACTIONTIME 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_CUSTOMERSUPPLIERNO 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_TRANSACTIONTYPE 2 + 1
  #define LS_NARCTRANSACTIONTRANSFER_PURCHASEORDERNO 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_ORDERNO 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_QTYTRANSACTION 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_QTYINSTOCK 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_COMPLETEDFLAG 1 + 1
  #define LS_NARCTRANSACTIONTRANSFER_POSNO 10 + 1
  #define LS_NARCTRANSACTIONTRANSFER_TOURID 6 + 1

  #define NARCTRANSACTIONTRANSFERTRANSFERID 0
  #define NARCTRANSACTIONTRANSFERBRANCHNO 1
  #define NARCTRANSACTIONTRANSFERARTICLENO 2
  #define NARCTRANSACTIONTRANSFERTRANSACTIONDATE 3
  #define NARCTRANSACTIONTRANSFERTRANSACTIONTIME 4
  #define NARCTRANSACTIONTRANSFERCUSTOMERSUPPLIERNO 5
  #define NARCTRANSACTIONTRANSFERTRANSACTIONTYPE 6
  #define NARCTRANSACTIONTRANSFERPURCHASEORDERNO 7
  #define NARCTRANSACTIONTRANSFERORDERNO 8
  #define NARCTRANSACTIONTRANSFERQTYTRANSACTION 9
  #define NARCTRANSACTIONTRANSFERQTYINSTOCK 10
  #define NARCTRANSACTIONTRANSFERCOMPLETEDFLAG 11
  #define NARCTRANSACTIONTRANSFERPOSNO 12
  #define NARCTRANSACTIONTRANSFERTOURID 13

/* define of Buf_Desc *********************************************************/

#if defined (BUF_DESC) || defined (C_BUF_DESC)
 #define NARCTRANSACTIONTRANSFER_H
 #define NARCTRANSACTIONTRANSFER_ANZ ( sizeof(NARCTRANSACTIONTRANSFER_BES) / sizeof(struct buf_desc) )
#endif

/* SqlDefine of NARCTRANSACTIONTRANSFER **************************************************/

 #define NARCTRANSACTIONTRANSFER_LISTE \
         NARCTRANSACTIONTRANSFER.TRANSFERID, \
         NARCTRANSACTIONTRANSFER.BRANCHNO, \
         NARCTRANSACTIONTRANSFER.ARTICLENO, \
         NARCTRANSACTIONTRANSFER.TRANSACTIONDATE, \
         NARCTRANSACTIONTRANSFER.TRANSACTIONTIME, \
         NARCTRANSACTIONTRANSFER.CUSTOMERSUPPLIERNO, \
         NARCTRANSACTIONTRANSFER.TRANSACTIONTYPE, \
         NARCTRANSACTIONTRANSFER.PURCHASEORDERNO, \
         NARCTRANSACTIONTRANSFER.ORDERNO, \
         NARCTRANSACTIONTRANSFER.QTYTRANSACTION, \
         NARCTRANSACTIONTRANSFER.QTYINSTOCK, \
         NARCTRANSACTIONTRANSFER.COMPLETEDFLAG, \
         NARCTRANSACTIONTRANSFER.POSNO, \
         NARCTRANSACTIONTRANSFER.TOURID

/* SqlMacros-Define of NARCTRANSACTIONTRANSFER *******************************************/

 #define NARCTRANSACTIONTRANSFER_ZEIGER(x) \
         :x->TRANSFERID, \
         :x->BRANCHNO, \
         :x->ARTICLENO, \
         :x->TRANSACTIONDATE, \
         :x->TRANSACTIONTIME, \
         :x->CUSTOMERSUPPLIERNO, \
         :x->TRANSACTIONTYPE, \
         :x->PURCHASEORDERNO, \
         :x->ORDERNO, \
         :x->QTYTRANSACTION, \
         :x->QTYINSTOCK, \
         :x->COMPLETEDFLAG, \
         :x->POSNO, \
         :x->TOURID

 #define NARCTRANSACTIONTRANSFER_UPDATE(x) \
         NARCTRANSACTIONTRANSFER.BRANCHNO=:x->BRANCHNO,\
         NARCTRANSACTIONTRANSFER.ARTICLENO=:x->ARTICLENO,\
         NARCTRANSACTIONTRANSFER.TRANSACTIONDATE=:x->TRANSACTIONDATE,\
         NARCTRANSACTIONTRANSFER.TRANSACTIONTIME=:x->TRANSACTIONTIME,\
         NARCTRANSACTIONTRANSFER.CUSTOMERSUPPLIERNO=:x->CUSTOMERSUPPLIERNO,\
         NARCTRANSACTIONTRANSFER.TRANSACTIONTYPE=:x->TRANSACTIONTYPE,\
         NARCTRANSACTIONTRANSFER.PURCHASEORDERNO=:x->PURCHASEORDERNO,\
         NARCTRANSACTIONTRANSFER.ORDERNO=:x->ORDERNO,\
         NARCTRANSACTIONTRANSFER.QTYTRANSACTION=:x->QTYTRANSACTION,\
         NARCTRANSACTIONTRANSFER.QTYINSTOCK=:x->QTYINSTOCK, \
         NARCTRANSACTIONTRANSFER.COMPLETEDFLAG=:x->COMPLETEDFLAG, \
         NARCTRANSACTIONTRANSFER.POSNO=:x->POSNO, \
         NARCTRANSACTIONTRANSFER.TOURID=:x->TOURID


#ifdef ESQL_C
 EXEC SQL BEGIN DECLARE SECTION;
#endif

/* Strucur with real chartype of NARCTRANSACTIONTRANSFER *********************************/

 struct C_NARCTRANSACTIONTRANSFER {
         long TRANSFERID;
         short BRANCHNO;
         long ARTICLENO;
         long TRANSACTIONDATE;
         long TRANSACTIONTIME;
         long CUSTOMERSUPPLIERNO;
         char TRANSACTIONTYPE[3];
         long PURCHASEORDERNO;
         long ORDERNO;
         long QTYTRANSACTION;
         long QTYINSTOCK;
         char COMPLETEDFLAG;
         long POSNO;
         char TOURID[7];
         };

#ifdef ESQL_C
 EXEC SQL END DECLARE SECTION;
#endif


/* structures of Buf_Desc *****************************************************/

/* Structur (buf_desc) of NARCTRANSACTIONTRANSFER ****************************************/

#if defined (BUF_DESC)
 static struct buf_desc NARCTRANSACTIONTRANSFER_BES [] =
 {
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_L,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C , 2, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C ,  1, 0 },
   { TYP_L , 11, 0 },
   { TYP_C ,  6, 0 },
 };
#elif defined (C_BUF_DESC)
 static struct buf_desc NARCTRANSACTIONTRANSFER_BES [] =
 {
   { TYP_L , 11, 0 },
   { TYP_S ,  6, 0 },
   { TYP_L , 11, 0 },
   { TYP_L,  11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C , 2, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_L , 11, 0 },
   { TYP_C , 1,  0 },
   { TYP_L , 11, 0 },
   { TYP_C ,  6, 0 },
 };
#endif

#endif
