//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ArtikelMapping {
    
    private ArtikelMappingXMLArtikel[] xMLArtikelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XMLArtikel")]
    public ArtikelMappingXMLArtikel[] XMLArtikel {
        get {
            return this.xMLArtikelField;
        }
        set {
            this.xMLArtikelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ArtikelMappingXMLArtikel {
    
    private int[] artikelNrField;
    
    private string articleIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ArtikelNr")]
    public int[] ArtikelNr {
        get {
            return this.artikelNrField;
        }
        set {
            this.artikelNrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ArticleID {
        get {
            return this.articleIDField;
        }
        set {
            this.articleIDField = value;
        }
    }
}
