//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_IREASON_H
#define GUARD_LIBCSC_CREMA_IREASON_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class IReason
{
public:
    virtual ~IReason() {}

    virtual basar::VarString getReason() const = 0;
    virtual basar::Int32 getId() const = 0;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_IREASON_H
