//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/reason/reason.h>

namespace libcsc {
namespace crema {

Reason::Reason()
{
}

Reason::~Reason()
{
}

basar::VarString Reason::getReason() const
{
    return m_Reason;
}

basar::Int32 Reason::getId() const
{
    return m_Id;
}

} // end namespace crema
} // end namespace libcsc
