//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_REASON_H
#define GUARD_LIBCSC_CREMA_REASON_H

#include <crema/reason/ireason.h>
#include <datatypes/varstring.h>
#include <datatypes/int32.h>

namespace libcsc {
namespace crema {

class Reason : public IReason
{
    // because of OR mapping
    friend class ReasonMapperBase;

public:
    Reason();
    virtual ~Reason();

    virtual basar::VarString getReason() const;
    virtual basar::Int32 getId() const;

private:
    libcsc::VarString m_Reason;
    libcsc::Int32 m_Id;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_REASON_H
