//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/reason/reasonsqlmapper.h>

namespace libcsc {
namespace crema {

ReasonSqlMapper::ReasonSqlMapper(ReasonPtr reason, const basar::db::sql::ResultsetRef resultSet)
: ReasonMapperBase(reason), m_ResultSet(resultSet)
{
}

ReasonSqlMapper::~ReasonSqlMapper()
{
}

void ReasonSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setReason(m_ResultSet.getString("reason"));
    setId(m_ResultSet.getInt32("id"));
}

} // end namespace crema
} // end namespace libcsc
