    

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_REASONCOLLECTION_H
#define GUARD_LIBCSC_CREMA_REASONCOLLECTION_H

#include <vector>
#include <crema/reason/reasonptr.h>

namespace libcsc {
namespace crema {

typedef std::vector<ReasonPtr> ReasonCollection;

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_REASONCOLLECTION_H
