//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/reason/reasonmapperbase.h>
#include <crema/reason/reason.h>

namespace libcsc {
namespace crema {

ReasonMapperBase::ReasonMapperBase(ReasonPtr reason)
: m_Reason(reason)
{
}

ReasonMapperBase::~ReasonMapperBase()
{
}

void ReasonMapperBase::map()
{
    doMap();
}

void ReasonMapperBase::setReason(const basar::VarString& reason)
{
    m_Reason->m_Reason = reason;
    m_Reason->m_Reason.setClean();
}

void ReasonMapperBase::setId(const basar::Int32& id)
{
    m_Reason->m_Id = id;
    m_Reason->m_Id.setClean();
}

} // end namespace crema
} // end namespace libcsc
