//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_REASONSQLMAPPER_H
#define GUARD_LIBCSC_CREMA_REASONSQLMAPPER_H

#include <crema/reason/reasonmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class ReasonSqlMapper : public ReasonMapperBase
{
public:
    ReasonSqlMapper(ReasonPtr reason, const basar::db::sql::ResultsetRef resultSet);
    virtual ~ReasonSqlMapper();

protected:
    virtual void doMap();

private:
    ReasonSqlMapper(const ReasonSqlMapper&);
    ReasonSqlMapper& operator=(const ReasonSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_REASONSQLMAPPER_H
