//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_REASONMAPPERBASE_H
#define GUARD_LIBCSC_CREMA_REASONMAPPERBASE_H

#include <crema/reason/reasonptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class ReasonMapperBase
{
public:
    ReasonMapperBase(ReasonPtr reason);

    void map();

protected:
    virtual ~ReasonMapperBase();

    virtual void doMap() = 0;

    void setReason(const basar::VarString& reason);
    void setId(const basar::Int32& id);

private:
    ReasonPtr m_Reason;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_REASONMAPPERBASE_H
