#define ANZ_FKTN         0

#define KscsrvChangePaymentToCashOrder 750
#define KscsrvChangeDeliveryTour       749
#define KscsrvIsExportPermitted        748
#define KscsrvWriteDispoItem           747
#define KscsrvGetApprovalData          746
#define KscsrvGetArticleManufacturer   745
#define KscsrvSetRelationNo			   744
#define KscsrvSetTurnOverOrigin		   743
#define KscsrvGetArticleStockBulk      742
#define KscsrvGetArticleAvailabilityBulk 741
//#define KscsrvSetTenderContractId	   740
#define KscsrvSetOrderInfoDetails      739
#define KscsrvSetValueDate			   738
#define KscsrvNeworderMSV3			   737
#define KscsrvCancelorderDebtLimit     736
#define KscsrvCloseorderDebtLimit      735
#define KscsrvGetArticleStock	       734
#define KscsrvGetArticleInfoCode       733
#define KscsrvWriteProLink             732
#define KscsrvChangeReference          731
#define KscsrvSetROParam               730
#define KscsrvGetProforma              729
#define KscsrvProformaorder            728
#define KscsrvSetBTMLicense            727
#define KscsrvSetTourId                726
#define KscsrvSetTenderNo              725
#define KscsrvSetBatchOrderTyp	       724
#define KscsrvSetdelayeddate	       723
#define KscsrvGetArticleInquiry        722
#define KscsrvGetArticleInfo           721
#define KscsrvOpenInfoOrder            720
#define KscsrvNeworderVz               719
#define KscsrvCheckDoubleOrder         718
#define KscsrvAddCallback              717
#define KscsrvChangeorder              716
#define KscsrvCancelorder              715
#define KscsrvPostponeorder            714
#define KscsrvWritetextpos             713
#define KscsrvCloseorderInternet       712
#define KscsrvPostponeorderinternet    711
#define KscsrvOpenorderInternetOrderno 710
#define KscsrvInsertReference	       709
#define KscsrvCheckReference           708
#define KscsrvInsKopfZlnAuf            707
#define KscsrvWritepos                 706
#define KscsrvChangeOrdBem             705
#define KscsrvCloseorder               704
#define KscsrvNeworder                 703
#define KscsrvOpenorder                702
#define KscsrvClosesession             701
#define KscsrvOpensession              700
