#####################################################################
#                                                                   #
#   kscserverinf makefile for informix esqlc sources (Windows)      #
#   Frank Naumann                                                   #
#   18.11.2014                                                      #
#                                                                   #
#####################################################################

#-------------------------------------------------------------
#   target
#-------------------------------------------------------------
TARGET_NAME = $(OUT_DIR)\kscserverinf.lib

#-------------------------------------------------------------
#   flags
#-------------------------------------------------------------
CFLAGS_CMN = /D_LIB /D_CRT_SECURE_NO_WARNINGS /DWIN32 /W4 /wd"4115"
CFLAGS_DBG = /Od /D_DEBUG /MD /Zi /Fd..\Debug\kscserverinf.pdb
CFLAGS_REL = /O2 /DNDEBUG /MD /Zi /Fd..\Release\kscserverinf.pdb
CFLAGS     = $(CFLAGS_CMN) $(CFLAGS_DBG)
LFLAGS     = /subsystem:console
ESQL_DEFINES = /DESQL_C

#-------------------------------------------------------------
#   libraries, lib path, include path
#-------------------------------------------------------------
LIBS        = isqlt09a.lib
LIBS_DIR    = /LIBPATH:"$(INFORMIXDIR)\lib"

INT_DIR     = Debug
INT_DIR_REL = Release

OUT_DIR     = ..\Debug
OUT_DIR_REL = ..\Release

INCS        = -I..\..\ext\pplib\include \
              -I..\..\ext\pplib\include\pplib \
              -I..\..\cxxtools\include \
              -I..\..\ext\libtpld\include \
              -I..\..\pxverbund\include
#-------------------------------------------------------------
#   object files
#-------------------------------------------------------------
PROJ_OBJS=\
        $(INT_DIR)\auftraginfo.obj \
        $(INT_DIR)\kscartselect.obj \
        $(INT_DIR)\ksccheckcallplan.obj \
        $(INT_DIR)\kscpromo.obj

#-------------------------------------------------------------
#   tools (Microsoft)
#-------------------------------------------------------------
MAKE     = nmake /f makefile.win
LINK     = lib
ESQL     = "$(INFORMIXDIR)\bin\esql.exe"
EPROTECT = "$(INFORMIXDIR)\lib\eprotect.exe"

#-------------------------------------------------------------
#   target rules
#-------------------------------------------------------------

$(TARGET_NAME): $(INT_DIR) $(PROJ_OBJS) $(OUT_DIR)
    $(LINK) /OUT:$(TARGET_NAME) $(LIBS_DIR) $(LFLAGS) $(PROJ_OBJS) $(LIBS)

$(OUT_DIR):
    mkdir $(OUT_DIR)

$(INT_DIR):
    mkdir $(INT_DIR)

rel:
    $(MAKE) CFLAGS="$(CFLAGS_CMN) $(CFLAGS_REL)" INT_DIR="$(INT_DIR_REL)" OUT_DIR="$(OUT_DIR_REL)"

rel_all:
    $(MAKE) rel_clean
    $(MAKE) rel

dbg_all:
    $(MAKE) clean
    $(MAKE)

rel_clean:
    $(MAKE) INT_DIR="$(INT_DIR_REL)" OUT_DIR="$(OUT_DIR_REL)" clean

clean:
    del /q $(INT_DIR)\*.obj $(INT_DIR)\*.ec $(OUT_DIR)\kscserverinf.lib  $(OUT_DIR)\kscserverinf.pdb

#-------------------------------------------------------------
#   suffix rules
#-------------------------------------------------------------

.cxx.obj:
    set PATH=%PATH%;$(INFORMIXDIR)\bin
    @if not exist $(INT_DIR) mkdir $(INT_DIR)
    $(CPP) $(CFLAGS) $(ESQL_DEFINES) $(INCS) /E /TC $*.cxx >$(INT_DIR)\$*.ec
    $(ESQL) -dcmdl $(CFLAGS) /Fo$(INT_DIR)\ /TC -c $(INT_DIR)\$*.ec
    del $(*)*.c $(*)*.c_
#   del $(INT_DIR)\$*.ec

#-------------------------------------------------------------
#   suffix
#-------------------------------------------------------------
.SUFFIXES:
.SUFFIXES: .cxx

#-------------------------------------------------------------
#   dependencies between object and header files
#-------------------------------------------------------------
# DEP_START

$(INT_DIR)\auftraginfo.obj: auftraginfo.cxx
                $(MAKE) CFLAGS="$(CFLAGS)" INT_DIR="$(INT_DIR)" auftraginfo.obj

$(INT_DIR)\kscartselect.obj: kscartselect.cxx
                $(MAKE) CFLAGS="$(CFLAGS)" INT_DIR="$(INT_DIR)" kscartselect.obj

$(INT_DIR)\ksccheckcallplan.obj: ksccheckcallplan.cxx
                $(MAKE) CFLAGS="$(CFLAGS)" INT_DIR="$(INT_DIR)" ksccheckcallplan.obj

$(INT_DIR)\kscpromo.obj: kscpromo.cxx
                $(MAKE) CFLAGS="$(CFLAGS)" INT_DIR="$(INT_DIR)" kscpromo.obj

# DEP_END
