//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
namespace msv3v1
{
    namespace Phoenix.Types.Config
    {
        using System.Xml.Serialization;

        //
        // This source code was auto-generated by xsd, Version=4.0.30319.1.
        //


        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class SalesWebConfig
        {

            private SalesWebConfigGeneral generalField;

            private SalesWebConfigXmlValidation xmlValidationField;

            private SalesWebConfigSmtp smtpField;

            private SalesWebConfigFrontend frontendField;

            private SalesWebConfigBackend backendField;

            /// <remarks/>
            public SalesWebConfigGeneral General
            {
                get
                {
                    return this.generalField;
                }
                set
                {
                    this.generalField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigXmlValidation XmlValidation
            {
                get
                {
                    return this.xmlValidationField;
                }
                set
                {
                    this.xmlValidationField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigSmtp Smtp
            {
                get
                {
                    return this.smtpField;
                }
                set
                {
                    this.smtpField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigFrontend Frontend
            {
                get
                {
                    return this.frontendField;
                }
                set
                {
                    this.frontendField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigBackend Backend
            {
                get
                {
                    return this.backendField;
                }
                set
                {
                    this.backendField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigGeneral
        {

            private SalesWebConfigGeneralCountry countryField;

            private SalesWebConfigGeneralLanguage languageField;

            private string domainField;

            private bool pzn8AktiveField;

            public SalesWebConfigGeneral()
            {
                this.domainField = "PHOENIXEXT";
                this.pzn8AktiveField = false;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public SalesWebConfigGeneralCountry Country
            {
                get
                {
                    return this.countryField;
                }
                set
                {
                    this.countryField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public SalesWebConfigGeneralLanguage Language
            {
                get
                {
                    return this.languageField;
                }
                set
                {
                    this.languageField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("PHOENIXEXT")]
            public string Domain
            {
                get
                {
                    return this.domainField;
                }
                set
                {
                    this.domainField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(false)]
            public bool Pzn8Aktive
            {
                get
                {
                    return this.pzn8AktiveField;
                }
                set
                {
                    this.pzn8AktiveField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public enum SalesWebConfigGeneralCountry
        {

            /// <remarks/>
            Empty,

            /// <remarks/>
            Austria,

            /// <remarks/>
            Bulgaria,

            /// <remarks/>
            Croatia,

            /// <remarks/>
            France,

            /// <remarks/>
            Germany,

            /// <remarks/>
            Serbia,

            /// <remarks/>
            Switzerland,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public enum SalesWebConfigGeneralLanguage
        {

            /// <remarks/>
            Empty,

            /// <remarks/>
            Bulgarian,

            /// <remarks/>
            Croatian,

            /// <remarks/>
            English,

            /// <remarks/>
            French,

            /// <remarks/>
            German,

            /// <remarks/>
            Serbian,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class Customer
        {

            private int numberField;

            private int branchField;

            private bool branchFieldSpecified;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Number
            {
                get
                {
                    return this.numberField;
                }
                set
                {
                    this.numberField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Branch
            {
                get
                {
                    return this.branchField;
                }
                set
                {
                    this.branchField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool BranchSpecified
            {
                get
                {
                    return this.branchFieldSpecified;
                }
                set
                {
                    this.branchFieldSpecified = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigXmlValidation
        {

            private bool validateXMLField;

            private string xsdPathField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public bool ValidateXML
            {
                get
                {
                    return this.validateXMLField;
                }
                set
                {
                    this.validateXMLField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string XsdPath
            {
                get
                {
                    return this.xsdPathField;
                }
                set
                {
                    this.xsdPathField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigSmtp
        {

            private string serverField;

            private int portField;

            private string mailAddressToField;

            private string mailAddressFromField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Server
            {
                get
                {
                    return this.serverField;
                }
                set
                {
                    this.serverField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Port
            {
                get
                {
                    return this.portField;
                }
                set
                {
                    this.portField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string MailAddressTo
            {
                get
                {
                    return this.mailAddressToField;
                }
                set
                {
                    this.mailAddressToField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string MailAddressFrom
            {
                get
                {
                    return this.mailAddressFromField;
                }
                set
                {
                    this.mailAddressFromField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigFrontend
        {

            private SalesWebConfigFrontendBackendEndpoint backendEndpointField;

            private SalesWebConfigFrontendSubmitDurations submitDurationsField;

            /// <remarks/>
            public SalesWebConfigFrontendBackendEndpoint BackendEndpoint
            {
                get
                {
                    return this.backendEndpointField;
                }
                set
                {
                    this.backendEndpointField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigFrontendSubmitDurations SubmitDurations
            {
                get
                {
                    return this.submitDurationsField;
                }
                set
                {
                    this.submitDurationsField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigFrontendBackendEndpoint
        {

            private int[] branchesField;

            private string nameField;

            private string addressField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Branch", IsNullable = false)]
            public int[] Branches
            {
                get
                {
                    return this.branchesField;
                }
                set
                {
                    this.branchesField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Address
            {
                get
                {
                    return this.addressField;
                }
                set
                {
                    this.addressField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigFrontendSubmitDurations
        {

            private SalesWebConfigFrontendSubmitDurationsUser[] userField;

            private bool submitField;

            private SalesWebConfigFrontendSubmitDurationsSubmitDurationType submitDurationTypeField;

            public SalesWebConfigFrontendSubmitDurations()
            {
                this.submitField = false;
                this.submitDurationTypeField = SalesWebConfigFrontendSubmitDurationsSubmitDurationType.Mail;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("User")]
            public SalesWebConfigFrontendSubmitDurationsUser[] User
            {
                get
                {
                    return this.userField;
                }
                set
                {
                    this.userField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(false)]
            public bool Submit
            {
                get
                {
                    return this.submitField;
                }
                set
                {
                    this.submitField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(SalesWebConfigFrontendSubmitDurationsSubmitDurationType.Mail)]
            public SalesWebConfigFrontendSubmitDurationsSubmitDurationType SubmitDurationType
            {
                get
                {
                    return this.submitDurationTypeField;
                }
                set
                {
                    this.submitDurationTypeField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigFrontendSubmitDurationsUser
        {

            private int branchNoField;

            private int idfField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int BranchNo
            {
                get
                {
                    return this.branchNoField;
                }
                set
                {
                    this.branchNoField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Idf
            {
                get
                {
                    return this.idfField;
                }
                set
                {
                    this.idfField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public enum SalesWebConfigFrontendSubmitDurationsSubmitDurationType
        {

            /// <remarks/>
            Mail,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackend
        {

            private SalesWebConfigBackendLog logField;

            private SalesWebConfigBackendBlacklisting blacklistingField;

            private SalesWebConfigBackendCSCService[] cSCServicesField;

            private SalesWebConfigBackendRequestQueue requestQueueField;

            private SalesWebConfigBackendSpecialUser[] specialUsersField;

            private Customer[] testCustomersField;

            private Customer[] blackListedCustomersField;

            private SalesWebConfigBackendBranch[] allowedBranchesField;

            /// <remarks/>
            public SalesWebConfigBackendLog Log
            {
                get
                {
                    return this.logField;
                }
                set
                {
                    this.logField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigBackendBlacklisting Blacklisting
            {
                get
                {
                    return this.blacklistingField;
                }
                set
                {
                    this.blacklistingField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("CSCService", IsNullable = false)]
            public SalesWebConfigBackendCSCService[] CSCServices
            {
                get
                {
                    return this.cSCServicesField;
                }
                set
                {
                    this.cSCServicesField = value;
                }
            }

            /// <remarks/>
            public SalesWebConfigBackendRequestQueue RequestQueue
            {
                get
                {
                    return this.requestQueueField;
                }
                set
                {
                    this.requestQueueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("SpecialUser", IsNullable = false)]
            public SalesWebConfigBackendSpecialUser[] SpecialUsers
            {
                get
                {
                    return this.specialUsersField;
                }
                set
                {
                    this.specialUsersField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Customer", IsNullable = false)]
            public Customer[] TestCustomers
            {
                get
                {
                    return this.testCustomersField;
                }
                set
                {
                    this.testCustomersField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Customer", IsNullable = false)]
            public Customer[] BlackListedCustomers
            {
                get
                {
                    return this.blackListedCustomersField;
                }
                set
                {
                    this.blackListedCustomersField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Branch", IsNullable = false)]
            public SalesWebConfigBackendBranch[] AllowedBranches
            {
                get
                {
                    return this.allowedBranchesField;
                }
                set
                {
                    this.allowedBranchesField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendLog
        {

            private string connectionStringField;

            private string queuePathField;

            private string logTableNameField;

            private SalesWebConfigBackendLogSeverity severityField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string ConnectionString
            {
                get
                {
                    return this.connectionStringField;
                }
                set
                {
                    this.connectionStringField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string QueuePath
            {
                get
                {
                    return this.queuePathField;
                }
                set
                {
                    this.queuePathField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string LogTableName
            {
                get
                {
                    return this.logTableNameField;
                }
                set
                {
                    this.logTableNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public SalesWebConfigBackendLogSeverity Severity
            {
                get
                {
                    return this.severityField;
                }
                set
                {
                    this.severityField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public enum SalesWebConfigBackendLogSeverity
        {

            /// <remarks/>
            None,

            /// <remarks/>
            Debug,

            /// <remarks/>
            Info,

            /// <remarks/>
            Warn,

            /// <remarks/>
            Error,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendBlacklisting
        {

            private SalesWebConfigBackendBlacklistingDuration[] durationField;

            private int maxPosCountField;

            public SalesWebConfigBackendBlacklisting()
            {
                this.maxPosCountField = 65568;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Duration")]
            public SalesWebConfigBackendBlacklistingDuration[] Duration
            {
                get
                {
                    return this.durationField;
                }
                set
                {
                    this.durationField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute(65568)]
            public int MaxPosCount
            {
                get
                {
                    return this.maxPosCountField;
                }
                set
                {
                    this.maxPosCountField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendBlacklistingDuration
        {

            private string fromField;

            private string toField;

            public SalesWebConfigBackendBlacklistingDuration()
            {
                this.fromField = "12:00:00";
                this.toField = "12:00:00";
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("12:00:00")]
            public string From
            {
                get
                {
                    return this.fromField;
                }
                set
                {
                    this.fromField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            [System.ComponentModel.DefaultValueAttribute("12:00:00")]
            public string To
            {
                get
                {
                    return this.toField;
                }
                set
                {
                    this.toField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendCSCService
        {

            private int[] branchesField;

            private string regionField;

            private int encodingField;

            private string deviceNameField;

            private int uidField;

            private int portField;

            private string serverField;

            private int timeoutField;

            private bool timeoutFieldSpecified;

            private string infoLevelField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Branch", IsNullable = false)]
            public int[] Branches
            {
                get
                {
                    return this.branchesField;
                }
                set
                {
                    this.branchesField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Region
            {
                get
                {
                    return this.regionField;
                }
                set
                {
                    this.regionField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Encoding
            {
                get
                {
                    return this.encodingField;
                }
                set
                {
                    this.encodingField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string DeviceName
            {
                get
                {
                    return this.deviceNameField;
                }
                set
                {
                    this.deviceNameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Uid
            {
                get
                {
                    return this.uidField;
                }
                set
                {
                    this.uidField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Port
            {
                get
                {
                    return this.portField;
                }
                set
                {
                    this.portField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Server
            {
                get
                {
                    return this.serverField;
                }
                set
                {
                    this.serverField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Timeout
            {
                get
                {
                    return this.timeoutField;
                }
                set
                {
                    this.timeoutField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool TimeoutSpecified
            {
                get
                {
                    return this.timeoutFieldSpecified;
                }
                set
                {
                    this.timeoutFieldSpecified = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string InfoLevel
            {
                get
                {
                    return this.infoLevelField;
                }
                set
                {
                    this.infoLevelField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendRequestQueue
        {

            private string queuePathField;

            private int requeueTimeSpanMinutesField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string QueuePath
            {
                get
                {
                    return this.queuePathField;
                }
                set
                {
                    this.queuePathField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int RequeueTimeSpanMinutes
            {
                get
                {
                    return this.requeueTimeSpanMinutesField;
                }
                set
                {
                    this.requeueTimeSpanMinutesField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendSpecialUser
        {

            private bool specialUserTreatmentField;

            private bool specialUserTreatmentFieldSpecified;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public bool SpecialUserTreatment
            {
                get
                {
                    return this.specialUserTreatmentField;
                }
                set
                {
                    this.specialUserTreatmentField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool SpecialUserTreatmentSpecified
            {
                get
                {
                    return this.specialUserTreatmentFieldSpecified;
                }
                set
                {
                    this.specialUserTreatmentFieldSpecified = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class SalesWebConfigBackendBranch
        {

            private int numberField;

            private SalesWebConfigGeneralLanguage languageField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public int Number
            {
                get
                {
                    return this.numberField;
                }
                set
                {
                    this.numberField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public SalesWebConfigGeneralLanguage Language
            {
                get
                {
                    return this.languageField;
                }
                set
                {
                    this.languageField = value;
                }
            }
        }
    }
}