//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/discountaccount/discountaccount.h>

namespace libcsc {
namespace customer {

DiscountAccount::DiscountAccount()
{
}

DiscountAccount::~DiscountAccount()
{
}

basar::Decimal DiscountAccount::getValue() const
{
    return m_Value;
}

} // end namespace customer
} // end namespace libcsc
