//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNTSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNTSQLMAPPER_H

#include <customer/discountaccount/discountaccountmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class DiscountAccountSqlMapper : public DiscountAccountMapperBase
{
public:
    DiscountAccountSqlMapper(DiscountAccountPtr discountAccount, const basar::db::sql::ResultsetRef resultSet);
    virtual ~DiscountAccountSqlMapper();

protected:
    virtual void doMap();

private:
    DiscountAccountSqlMapper(const DiscountAccountSqlMapper&);
    DiscountAccountSqlMapper& operator=(const DiscountAccountSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNTSQLMAPPER_H
