//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNT_H
#define GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNT_H

#include <customer/discountaccount/idiscountaccount.h>
#include <datatypes/decimal.h>

namespace libcsc {
namespace customer {

class DiscountAccount : public IDiscountAccount
{
    // because of OR mapping
    friend class DiscountAccountMapperBase;

public:
    DiscountAccount();
    virtual ~DiscountAccount();

    virtual basar::Decimal getValue() const;

private:
    libcsc::Decimal m_Value;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNT_H
