//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNTMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNTMAPPERBASE_H

#include <customer/discountaccount/discountaccountptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class DiscountAccountMapperBase
{
public:
    DiscountAccountMapperBase(DiscountAccountPtr discountAccount);

    void map();

protected:
    virtual ~DiscountAccountMapperBase();

    virtual void doMap() = 0;

    void setValue(const basar::Decimal& value);

private:
    DiscountAccountPtr m_DiscountAccount;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_DISCOUNTACCOUNTMAPPERBASE_H
