//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/discountaccount/discountaccountmapperbase.h>
#include <customer/discountaccount/discountaccount.h>

namespace libcsc {
namespace customer {

DiscountAccountMapperBase::DiscountAccountMapperBase(DiscountAccountPtr discountAccount)
: m_DiscountAccount(discountAccount)
{
}

DiscountAccountMapperBase::~DiscountAccountMapperBase()
{
}

void DiscountAccountMapperBase::map()
{
    doMap();
}

void DiscountAccountMapperBase::setValue(const basar::Decimal& value)
{
    m_DiscountAccount->m_Value = value;
    m_DiscountAccount->m_Value.setClean();
}

} // end namespace customer
} // end namespace libcsc
