//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/discountaccount/discountaccountsqlmapper.h>

namespace libcsc {
namespace customer {

DiscountAccountSqlMapper::DiscountAccountSqlMapper(DiscountAccountPtr discountAccount, const basar::db::sql::ResultsetRef resultSet)
: DiscountAccountMapperBase(discountAccount), m_ResultSet(resultSet)
{
}

DiscountAccountSqlMapper::~DiscountAccountSqlMapper()
{
}

void DiscountAccountSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setValue(m_ResultSet.getDecimal("value"));
}

} // end namespace customer
} // end namespace libcsc
