//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_IDISCOUNTACCOUNT_H
#define GUARD_LIBCSC_CUSTOMER_IDISCOUNTACCOUNT_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class IDiscountAccount
{
public:
    virtual ~IDiscountAccount() {}

    virtual basar::Decimal getValue() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_IDISCOUNTACCOUNT_H
