#include "discountcalculatortypemapper.h"

namespace libcsc
{
namespace discount
{
std::ostream & DiscountCalculatorTypeMapper::toStream( std::ostream & str, const DiscountCalculatorTypeEnum type )
{
	switch( type )
	{
		case CT_UNSET: str << "CT_UNSET"; break;
		case CT_ROOT: str << "CT_ROOT"; break;

		// Common 
		case CT_FIXED_PRICE_TYPE: str << "CT_FIXED_PRICE_TYPE"; break;
		case CT_FIRST_WINS_TYPE: str << "CT_FIRST_WINS_TYPE"; break;
		case CT_BEST_OF_FOR_CUSTOMER_TYPE: str << "CT_BEST_OF_FOR_CUSTOMER_TYPE"; break;
		case CT_SUM_TYPE: str << "CT_SUM_TYPE"; break;
		case CT_RETAIL_TYPE: str << "CT_RETAIL_TYPE"; break;
		case CT_WH_CUSTOMER_ARTICLE_TYPE: str << "CT_WH_CUSTOMER_ARTICLE_TYPE"; break;
		case CT_WH_CUSTOMER_ARTICLE_GROUP_TYPE: str << "CT_WH_CUSTOMER_ARTICLE_GROUP_TYPE"; break;
		case CT_WH_CUSTOMER_MANUFACTURER_TYPE: str << "CT_WH_CUSTOMER_MANUFACTURER_TYPE"; break;
		case CT_WH_CUSTOMER_MANUFACTURER_GROUP_TYPE: str << "CT_WH_CUSTOMER_MANUFACTURER_GROUP_TYPE"; break;
		case CT_WH_CUSTOMER_GROUP_ARTICLE_TYPE: str << "CT_WH_CUSTOMER_GROUP_ARTICLE_TYPE"; break;
		case CT_WH_CUSTOMER_GROUP_ARTICLE_GROUP_TYPE: str << "CT_WH_CUSTOMER_GROUP_ARTICLE_GROUP_TYPE"; break;
		case CT_WH_CUSTOMER_GROUP_MANUFACTURER_TYPE: str << "CT_WH_CUSTOMER_GROUP_MANUFACTURER_TYPE"; break;
		case CT_WH_CUSTOMER_GROUP_MANUFACTURER_GROUP_TYPE: str << "CT_WH_CUSTOMER_GROUP_MANUFACTURER_GROUP_TYPE"; break;
		case CT_WH_ALL_CUSTOMER_ARTICLE_TYPE: str << "CT_WH_ALL_CUSTOMER_ARTICLE_TYPE"; break;
		case CT_WH_ALL_CUSTOMER_ARTICLE_GROUP_TYPE: str << "CT_WH_ALL_CUSTOMER_ARTICLE_GROUP_TYPE"; break;
		case CT_WH_ALL_CUSTOMER_MANUFACTURER_TYPE: str << "CT_WH_ALL_CUSTOMER_MANUFACTURER_TYPE"; break;
		case CT_WH_ALL_CUSTOMER_MANUFACTURER_GROUP_TYPE: str << "CT_WH_ALL_CUSTOMER_MANUFACTURER_GROUP_TYPE"; break;
		case CT_WH_INDUSTRY_CUSTOMER_ARTICLE_TYPE: str << "CT_WH_INDUSTRY_CUSTOMER_ARTICLE_TYPE"; break;
		case CT_WH_INDUSTRY_CUSTOMER_ARTICLE_GROUP_TYPE: str << "CT_WH_INDUSTRY_CUSTOMER_ARTICLE_GROUP_TYPE"; break;
		case CT_WH_INDUSTRY_CUSTOMER_MANUFACTURER_TYPE: str << "CT_WH_INDUSTRY_CUSTOMER_MANUFACTURER_TYPE"; break;
		case CT_WH_INDUSTRY_CUSTOMER_MANUFACTURER_GROUP_TYPE: str << "CT_WH_INDUSTRY_CUSTOMER_MANUFACTURER_GROUP_TYPE"; break;
		case CT_WH_INDUSTRY_CUSTOMER_GROUP_ARTICLE_TYPE: str << "CT_WH_INDUSTRY_CUSTOMER_GROUP_ARTICLE_TYPE"; break;
		case CT_WH_INDUSTRY_CUSTOMER_GROUP_ARTICLE_GROUP_TYPE: str << "CT_WH_INDUSTRY_CUSTOMER_GROUP_ARTICLE_GROUP_TYPE"; break;
		case CT_WH_INDUSTRY_CUSTOMER_GROUP_MANUFACTURER_TYPE: str << "CT_WH_INDUSTRY_CUSTOMER_GROUP_MANUFACTURER_TYPE"; break;
		case CT_WH_INDUSTRY_CUSTOMER_GROUP_MANUFACTURER_GROUP_TYPE: str << "CT_WH_INDUSTRY_CUSTOMER_GROUP_MANUFACTURER_GROUP_TYPE"; break;
		case CT_WH_INDUSTRY_ALL_CUSTOMER_ARTICLE_TYPE: str << "CT_WH_INDUSTRY_ALL_CUSTOMER_ARTICLE_TYPE"; break;
		case CT_WH_INDUSTRY_ALL_CUSTOMER_ARTICLE_GROUP_TYPE: str << "CT_WH_INDUSTRY_ALL_CUSTOMER_ARTICLE_GROUP_TYPE"; break;
		case CT_WH_INDUSTRY_ALL_CUSTOMER_MANUFACTURER_TYPE: str << "CT_WH_INDUSTRY_ALL_CUSTOMER_MANUFACTURER_TYPE"; break;
		case CT_WH_INDUSTRY_ALL_CUSTOMER_MANUFACTURER_GROUP_TYPE: str << "CT_WH_INDUSTRY_ALL_CUSTOMER_MANUFACTURER_GROUP_TYPE"; break;
	
		// Croatia
		case CT_HR_FIXED_PRICE_BEATS_ALL_TYPE: str << "CT_HR_FIXED_PRICE_BEATS_ALL_TYPE"; break;
		case CT_HR_SUM_RE_WH_WI_TYPE: str << "CT_HR_SUM_RE_WH_WI_TYPE"; break;
		case CT_HR_FIRST_WINS_WH_TYPE: str << "CT_HR_FIRST_WINS_WH_TYPE"; break;
		case CT_HR_FIRST_WINS_WI_TYPE: str << "CT_HR_FIRST_WINS_WI_TYPE"; break;
		case CT_HR_BEST_OF_WH_CUSTOMER_TYPE: str << "CT_HR_BEST_OF_WH_CUSTOMER_TYPE"; break;
		case CT_HR_BEST_OF_WH_CUSTOMER_GROUP_TYPE: str << "CT_HR_BEST_OF_WH_CUSTOMER_GROUP_TYPE"; break;
		case CT_HR_BEST_OF_WH_ALL_CUSTOMER_TYPE: str << "CT_HR_BEST_OF_WH_ALL_CUSTOMER_TYPE"; break;
		case CT_HR_BEST_OF_WH_INDUSTRY_CUSTOMER_TYPE: str << "CT_HR_BEST_OF_WH_INDUSTRY_CUSTOMER_TYPE"; break;
		case CT_HR_BEST_OF_WH_INDUSTRY_CUSTOMER_GROUP_TYPE: str << "CT_HR_BEST_OF_WH_INDUSTRY_CUSTOMER_GROUP_TYPE"; break;
		case CT_HR_BEST_OF_WH_INDUSTRY_ALL_CUSTOMER_TYPE: str << "CT_HR_BEST_OF_WH_INDUSTRY_ALL_CUSTOMER_TYPE"; break;
		case CT_HR_SUM_WH_WI_TYPE: str << "CT_HR_SUM_WH_WI_TYPE"; break;
		case CT_HR_SUM_ALL_TYPE: str << "CT_HR_SUM_ALL_TYPE"; break;

		// DEPricing
		case CT_FIXED_PRICE_CONCEPT_DEAP_MODE: str << "CT_FIXED_PRICE_CONCEPT_DEAP_MODE"; break;
		case CT_FIXED_PRICE_CONCEPT_MVDA_MODE: str << "CT_FIXED_PRICE_CONCEPT_MVDA_MODE"; break;
		case CT_SURCHARGE_EXF_MODE: str << "CT_SURCHARGE_EXF_MODE"; break;

		default: str << "-UNKNOWN-"; break;
	}

	return str;
}

} // end namespace discount
} // end namespace libcsc

