#ifndef GUARD_LIBCSC_DISCOUNT_CALCULATOR_TYPE_ENUM_H
#define GUARD_LIBCSC_DISCOUNT_CALCULATOR_TYPE_ENUM_H

#include <datatypes/property.hpp>

namespace libcsc
{
namespace discount
{
enum DiscountCalculatorTypeEnum
{
	CT_UNSET = -1,
	CT_ROOT = 0,

	// Common 
	CT_FIXED_PRICE_TYPE = 1,
	CT_FIRST_WINS_TYPE,
	CT_BEST_OF_FOR_CUSTOMER_TYPE,
	CT_SUM_TYPE,
	CT_RETAIL_TYPE,
	CT_WH_CUSTOMER_ARTICLE_TYPE,
	CT_WH_CUSTOMER_ARTICLE_GROUP_TYPE,
	CT_WH_CUSTOMER_MANUFACTURER_TYPE,
	CT_WH_CUSTOMER_MANUFACTURER_GROUP_TYPE,
	CT_WH_CUSTOMER_GROUP_ARTICLE_TYPE,
	CT_WH_CUSTOMER_GROUP_ARTICLE_GROUP_TYPE,
	CT_WH_CUSTOMER_GROUP_MANUFACTURER_TYPE,
	CT_WH_CUSTOMER_GROUP_MANUFACTURER_GROUP_TYPE,
	CT_WH_ALL_CUSTOMER_ARTICLE_TYPE,
	CT_WH_ALL_CUSTOMER_ARTICLE_GROUP_TYPE,
	CT_WH_ALL_CUSTOMER_MANUFACTURER_TYPE,
	CT_WH_ALL_CUSTOMER_MANUFACTURER_GROUP_TYPE,
	CT_WH_INDUSTRY_CUSTOMER_ARTICLE_TYPE,
	CT_WH_INDUSTRY_CUSTOMER_ARTICLE_GROUP_TYPE,
	CT_WH_INDUSTRY_CUSTOMER_MANUFACTURER_TYPE,
	CT_WH_INDUSTRY_CUSTOMER_MANUFACTURER_GROUP_TYPE,
	CT_WH_INDUSTRY_CUSTOMER_GROUP_ARTICLE_TYPE,
	CT_WH_INDUSTRY_CUSTOMER_GROUP_ARTICLE_GROUP_TYPE,
	CT_WH_INDUSTRY_CUSTOMER_GROUP_MANUFACTURER_TYPE,
	CT_WH_INDUSTRY_CUSTOMER_GROUP_MANUFACTURER_GROUP_TYPE,
	CT_WH_INDUSTRY_ALL_CUSTOMER_ARTICLE_TYPE,
	CT_WH_INDUSTRY_ALL_CUSTOMER_ARTICLE_GROUP_TYPE,
	CT_WH_INDUSTRY_ALL_CUSTOMER_MANUFACTURER_TYPE,
	CT_WH_INDUSTRY_ALL_CUSTOMER_MANUFACTURER_GROUP_TYPE,

	// Croatia
	CT_HR_FIXED_PRICE_BEATS_ALL_TYPE = 100,
	CT_HR_SUM_RE_WH_WI_TYPE,
	CT_HR_FIRST_WINS_WH_TYPE,
	CT_HR_FIRST_WINS_WI_TYPE,
	CT_HR_BEST_OF_WH_CUSTOMER_TYPE,
	CT_HR_BEST_OF_WH_CUSTOMER_GROUP_TYPE,
	CT_HR_BEST_OF_WH_ALL_CUSTOMER_TYPE,
	CT_HR_BEST_OF_WH_INDUSTRY_CUSTOMER_TYPE,
	CT_HR_BEST_OF_WH_INDUSTRY_CUSTOMER_GROUP_TYPE,
	CT_HR_BEST_OF_WH_INDUSTRY_ALL_CUSTOMER_TYPE,
	CT_HR_SUM_WH_WI_TYPE,
	CT_HR_SUM_ALL_TYPE,

	// DEPricing
	CT_FIXED_PRICE_CONCEPT_DEAP_MODE = 200,
	CT_FIXED_PRICE_CONCEPT_MVDA_MODE,
	CT_SURCHARGE_EXF_MODE
};

enum DiscountCalculatorUseCaseEnum
{
	CE_POSITIONDISCOUNTCALCUC = 0,
	CE_ORDERDISCOUNTCALCUC
};

typedef libcsc::Property<DiscountCalculatorTypeEnum> DiscountCalculatorType; 

} // end namespace discount
} // end namespace libcsc

#endif // GUARD_LIBCSC_DISCOUNT_CALCULATOR_TYPE_ENUM_H
