#ifndef GUARD_LIBCSC_RETURNS_RETURNACCEPTANCECHECKENUM_H
#define GUARD_LIBCSC_RETURNS_RETURNACCEPTANCECHECKENUM_H

#include <datatypes/property.hpp>

namespace libcsc {
namespace returns {

enum ReturnAcceptanceCheckEnum
{
	CHECK_UNKNOWN                       = -1,
	CHECK_01_INVOICE_UNKNOWN			= 1,
	CHECK_02_INVOICE_CANCELLED			= 2,
	CHECK_03_ARTICLE_NOT_IN_INVOICE		= 3,

	CHECK_23_BATCH_NOT_IN_INVOICE		= 23,
	CHECK_24_EXPIRYDATE_NOT_IN_INVOICE	= 24,

	CHECK_04_QUANTITY_EXCEEDED			= 4,
	CHECK_05_OUT_OF_TRADE				= 5,
	CHECK_06_BLOCKED_FOR_RETURNS		= 6,
	CHECK_07_BLOCKED_BY_SALES			= 7,
	CHECK_08_MANUFACTURER_RECALL		= 8,
	CHECK_09_BATCH_RECALL				= 9,
	CHECK_10_DEADLINE_GUG				= 10,
	CHECK_11_DEADLINE_NARC				= 11,
	CHECK_12_DEADLINE_COLDCHAIN			= 12,
	CHECK_13_DEADLINE_COLD08			= 13,
	CHECK_14_DEADLINE_COLD20			= 14,
	CHECK_15_DEADLINE_RETURNS			= 15,
	CHECK_16_GUG_ARTICLE				= 16,
	CHECK_17_NARC_ARTICLE				= 17,
	CHECK_18_COLDCHAIN_ARTICLE			= 18,
	CHECK_19_COLD08_ARTICLE				= 19,
	CHECK_20_COLD20_ARTICLE				= 20,
	CHECK_21_HIGH_PRICE_ARTICLE			= 21,
	CHECK_22_CALLBACK_ORDERTYPE			= 22
};


} // namespace returns
} // namespace libcsc

namespace libcsc
{
	typedef libcsc::Property <libcsc::returns::ReturnAcceptanceCheckEnum> ReturnAcceptanceCheckEnum;
} // end namespace libcsc


#endif // GUARD_LIBCSC_RETURNS_RETURNACCEPTANCECHECKENUM_H
