// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#ifndef GUARD_CSCSERVICE_BASE_HANDLER_HPP
#define GUARD_CSCSERVICE_BASE_HANDLER_HPP

#include "CscServiceBase.h"
#include "cscserviceimplpxverbund.h"

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CscServiceBaseHandler : virtual public csc::service::CscServiceBaseIf
{
public:
	CscServiceBaseHandler()
	{
		m_Impl = boost::make_shared<csc::service::CscServiceImplPxVerbund>();
	}

	void openSession(
		::csc::base::SessionResponse& _return,
		const  ::csc::base::SessionRequest& request)
	{
		m_Impl->processOpenSession(_return, request);
	}

	void closeSession( ::csc::base::SessionResponse& _return)
	{
		m_Impl->processCloseSession(_return);
	}

	void setExplainOn()
	{
		m_Impl->setExplainOn();
	}

	void setExplainOff()
	{
		m_Impl->setExplainOff();
	}

	void setParentPort(const int32_t port) // rein informativ, wird nicht benötigt!
	{
		m_Impl->setParentPort(port);
	}

protected:
	boost::shared_ptr<csc::service::CscServiceImplPxVerbund> m_Impl;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif


#endif // GUARD_CSCSERVICE_BASE_HANDLER_HPP
