// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#ifndef GUARD_CSCSERVICE_ONLINE_HANDLER_HPP
#define GUARD_CSCSERVICE_ONLINE_HANDLER_HPP

#include "CscServiceOnline.h"
#include "cscservicebasehandler.hpp"

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CscServiceOnlineHandler : virtual public csc::service::CscServiceOnlineIf, public CscServiceBaseHandler
{
public:
	CscServiceOnlineHandler() : csc::service::CscServiceOnlineIf(), CscServiceBaseHandler()
	{
	}


	void openOrder(
		csc::order::OpenOrderResponse& _return,
		const csc::order::OpenOrderRequest& request)
	{
		std::stringstream in;
		in << "IN: " << request;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

		m_Impl->processOrderOpen(_return, request);

		std::stringstream out;
		out << "OUT: " << _return;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
	}

	void addPosition(
		csc::order::OrderPositionResponse& _return,
		const csc::order::OrderPositionRequest& request)
	{
		std::stringstream in;
		in << "IN: " << request;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

		m_Impl->processOrderPosition(_return, request);

		std::stringstream out;
		out << "OUT: " << _return;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
	}

	void closeOrder(
		csc::order::PlaceOrderResponse& _return,
		const csc::order::CloseOrderRequest& request)
	{
		std::stringstream in;
		in << "IN: " << request;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

		m_Impl->processOrderClose(_return, request);

		std::stringstream out;
		out << "OUT: " << _return;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
	}

};

#ifdef _WIN32
  #pragma warning( pop )
#endif

#endif // GUARD_CSCSERVICE_ONLINE_HANDLER_HPP
