// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#ifndef GUARD_CSCSERVICE_BATCH_HANDLER_HPP
#define GUARD_CSCSERVICE_BATCH_HANDLER_HPP

#include "CscServiceBatch.h"
#include "cscservicebasehandler.hpp"
#include <logger/loggerpool.h>

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance
#endif

class CscServiceBatchHandler : virtual public csc::service::CscServiceBatchIf, public CscServiceBaseHandler
{
public:
    CscServiceBatchHandler() : csc::service::CscServiceBatchIf(), CscServiceBaseHandler()
    {
    }

    void placeNewOrder(
        ::csc::order::PlaceOrderResponse& _return,
        const  ::csc::order::PlaceOrderRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processPlaceNewOrder(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void isArticleExportPermitted(
        csc::order::ArticleExportPermittedResponse& _return,
        const  csc::order::ArticleExportPermittedRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->isArticleExportPermitted(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void findSubsequentDeliveryArticleQtyAggregation( ::csc::customer::SubsequentDeliveryArticleQtyAggregationResponse& _return, const ::csc::customer::SubsequentDeliveryRequest& request )
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->findSubsequentDeliveryArticleQtyAggregation(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void findSubsequentDeliveries( ::csc::customer::SubsequentDeliveryResponse& _return, const ::csc::customer::SubsequentDeliveryRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->findSubsequentDeliveries(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }


    void findCustomerArticlePrices(::csc::customer::CustomerArticlePricesResponse& _return, const ::csc::customer::CustomerArticlePricesRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->findCustomerArticlePrices( _return, request );

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }


    void adjustSubsequentDeliveries(::csc::customer::SubsequentDeliveryAdjustmentResponse& _return, const ::csc::customer::SubsequentDeliveryAdjustmentRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->adjustSubsequentDeliveries(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getArticleInquiry(
        ::csc::inquiry::ArticleInquiryResponse& _return,
        const  ::csc::inquiry::ArticleInquiryRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processArticleInquiry(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getArticleAvaliabilityBulk(
        ::csc::inquiry::ArticleAvailabilityBulkResponse& _return,
        const  ::csc::inquiry::ArticleAvailabilityBulkRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processArticleAvailabilityBulk(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getArticleAvaliabilityBulkRange(
        ::csc::inquiry::ArticleAvailabilityBulkRangeResponse& _return,
        const  ::csc::inquiry::ArticleAvailabilityBulkRangeRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processArticleAvailabilityBulkRange(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getArticleStockBulk(
        ::csc::inquiry::ArticleStockBulkResponse& _return,
        const  ::csc::inquiry::ArticleStockBulkRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processArticleStockBulk(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getArticleStockDetails(
        ::csc::inquiry::ArticleStockDetailsResponse& _return,
        const  ::csc::inquiry::ArticleStockDetailsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processArticleStockDetails(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getXmlInfoLevel(
        ::csc::msv3::XmlInfoLevelResponse& _return,
        const ::csc::msv3::XmlInfoLevelRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->getXmlInfoLevel(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getDeliveryAdvices(
        ::documents::DeliveryAdvicesResponse& _return,
        const ::documents::DeliveryAdvicesRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->getDeliveryAdvices(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getSpecificDeliveryAdvices(
        ::documents::DeliveryAdvicesResponse& _return,
        const ::documents::DeliveryAdviceSpecificRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->getSpecificDeliveryAdvices(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getDataForBatchAdviceCreation(
        ::documents::BatchAdviceResponse& _return,
        const ::documents::BatchAdviceRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->getDataForBatchAdviceCreation(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void updateDeliveryAdvices(
        ::documents::UpdateDeliveryAdvicesResponse& _return,
        const ::documents::UpdateDeliveryAdvicesRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->updateDeliveryAdvices(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void confirmDeliveryAdviceReceipt(
        ::documents::DeliveryAdviceReceiveConfirmationResponse& _return,
        const ::documents::DeliveryAdviceReceiveConfirmationRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->confirmDeliveryAdviceReceipt(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void setDocumentInformation(
        ::documents::SetDocumentInformationResponse& _return,
        const ::documents::SetDocumentInformationRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->setDocumentInformation(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getDocumentInformation(
        ::documents::GetDocumentInformationResponse& _return,
        const ::documents::GetDocumentInformationRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->getDocumentInformation(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }


    void setNarcoticTransactionStatus(
        ::narcotics::SetNarcoticTransactionStatusResponse& _return,
        const ::narcotics::SetNarcoticTransactionStatusRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->setNarcoticTransactionStatus(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getNarcoticTransaction(
        ::narcotics::GetNarcoticTransactionResponse& _return,
        const ::narcotics::GetNarcoticTransactionRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->getNarcoticTransaction(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }


    void processReturnsRequest(
        ::csc::returns::ReturnsResponse& _return,
        const ::csc::returns::ReturnsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processReturnsRequest(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }


    void getMsv3ContractData(::csc::msv3::Msv3ContractDataResponse& _return, const csc::msv3::Msv3ContractDataRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->getMsv3ContractData(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void prepareMSV3Transmission(
        ::csc::msv3::Msv3TransmissionPreparationResponse& _return,
        const csc::msv3::Msv3TransmissionPreparationRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processPrepareMSV3Transmission(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getMSV3OrderStatus(
        ::csc::msv3::Msv3OrderStatusResponse& _return,
        const  ::csc::msv3::Msv3OrderStatusRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processMSV3OrderStatus(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void postProcessMSV3Transmission(
        const ::csc::msv3::Msv3TransmissionPostProcessingRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processPostProcessMSV3Transmission(request);
    }

    void getCustomerDetails(csc::customer::CustomerDetailsResponse& _return, const csc::customer::CustomerDetailsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processCustomerDetails(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getCustomerConditionsSerbia(::csc::customer::CustomerConditionsResponse& _return, const  ::csc::customer::CustomerConditionsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processCustomerConditionsSerbia(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getTenderInfoSerbia(::csc::customer::TenderInfoResponse& _return, const  ::csc::customer::TenderInfoRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processTenderInfoSerbia(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getArticleInfoSerbia(::csc::customer::ArticleInfoResponse& _return, const  ::csc::customer::ArticleInfoRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processArticleInfoSerbia(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getOrderInfoSerbia(::csc::customer::OrderInfoResponse& _return, const  ::csc::customer::OrderInfoRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processOrderInfoSerbia(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void changeCreditLimit(::csc::customer::ChangeCreditLimitResponse& _return, const ::csc::customer::ChangeCreditLimitRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processChangeCreditLimit(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getCallback(csc::callback::GetCallbackResponse& _return, const csc::callback::GetCallbackRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processGetCallback(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getCallbackDivisions(csc::callback::CallbackDivisionInquiryResponse& _return, const csc::callback::CallbackDivisionInquiryRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processGetCallbackDivisions(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getCallbackReasons(csc::callback::CallbackReasonInquiryResponse& _return, const csc::callback::CallbackReasonInquiryRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processGetCallbackReasons(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getCallbackStatuses(csc::callback::CallbackStatusInquiryResponse& _return, const csc::callback::CallbackStatusInquiryRequest& request)
	{
		std::stringstream in;
		in << "IN: " << request;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());
		m_Impl->porcessGetCallbackStatuses(_return, request);
		std::stringstream out;
		out << "OUT: " << _return;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
	}
    
	void getCallbackStatusVisibility(csc::callback::CallbackStatusVisibilityInquiryResponse& _return, const csc::callback::CallbackStatusVisibilityInquiryRequest& request)
	{
		std::stringstream in;
		in << "IN: " << request;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());
		m_Impl->processGetCallbackStatusVisibility(_return, request);
		std::stringstream out;
		out << "OUT: " << _return;
		LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
	}

    void findCustomers(csc::callback::FindCustomersResponse& _return, const csc::callback::FindCustomersRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processFindCallbackCustomers(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void writeNewCallbackCritPos(csc::callback::NewCallbackCritPosResponse& _return, const csc::callback::NewCallbackCritPosRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processWriteNewCallbackCritPos(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void writeNewCallback(csc::callback::NewCallbackResponse& _return, const csc::callback::NewCallbackRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processWriteNewCallback(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void findCallbacks(csc::callback::FindCallbacksResponse& _return, const csc::callback::FindCallbacksRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processFindCallbacks(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void GetCallbackDivisionAndReasonName(csc::callback::GetCallbackDivisionAndReasonNameResponse& _return, const csc::callback::GetCallbackDivisionAndReasonNameRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processGetCallbackDivisionAndReasonName(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getShipmentTracking(warehouse::shipmenttracking::ShipmentTrackingResponse& _return, const warehouse::shipmenttracking::ShipmentTrackingRequest & request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->getShipmentTracking(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getOrderStatusBulgaria(::csc::customer::OrderStatusResponse& _return, const ::csc::customer::OrderStatusRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processOrderStatusBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getPricesAndDiscountsBulgaria(::csc::customer::PricesAndDiscountsResponse& _return, const ::csc::customer::PricesAndDiscountsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processPricesAndDiscountsBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getPaymentsBulgaria(::csc::customer::PaymentsResponse& _return, const ::csc::customer::PaymentsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processPaymentsBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getPaymentConditionsBulgaria(::csc::customer::PaymentConditionsResponse& _return, const ::csc::customer::PaymentConditionsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processPaymentConditionsBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getTurnoverBulgaria(::csc::customer::TurnoverResponse& _return, const ::csc::customer::TurnoverRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processTurnoverBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getChangedQuantitiesBulgaria(::csc::customer::ChangedQuantitiesResponse& _return, const ::csc::customer::ChangedQuantitiesRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processChangedQuantitiesBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getDiscountAccountBulgaria(::csc::customer::DiscountAccountResponse& _return, const ::csc::customer::DiscountAccountRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processDiscountAccountBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getPromotionsBulgaria(::csc::customer::PromotionsResponse& _return, const ::csc::customer::PromotionsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processPromotionsBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getRoutesBulgaria(::csc::customer::RoutesResponse& _return, const ::csc::customer::RoutesRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processRoutesBulgaria(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getDeliveryAdvicesCroatia(::documents::DeliveryAdvicesHRResponse& _return, const ::documents::DeliveryAdvicesHRRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processDeliveryAdvicesCroatia(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getArticleInquiryCroatia(::csc::inquiry::ArticleInquiryResponse& _return, const ::csc::inquiry::ArticleInquiryHRRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processArticleInquiryCroatia(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getOpenCremaOrder(::csc::crema::OpenCremaOrderResponse& _return, const ::csc::crema::OpenCremaOrderRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processOpenCremaOrder(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getCremaUserSuggestion(::csc::crema::UserSuggestionResponse& _return, const ::csc::crema::UserSuggestionRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processCremaUserSuggestion(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getOpenCremaOrders(::csc::crema::OpenCremaOrdersResponse& _return, const ::csc::crema::OpenCremaOrdersRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processOpenCremaOrders(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void getFinishedTodayCremaOrders(::csc::crema::FinishedTodayCremaOrdersResponse& _return, const ::csc::crema::FinishedTodayCremaOrdersRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processFinishedTodayCremaOrders(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void saveCremaLastDecision(::csc::crema::LastDecisionResponse& _return, const ::csc::crema::LastDecisionRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processCremaLastDecision(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void finishCremaOrder(::csc::crema::FinishOrderResponse& _return, const ::csc::crema::FinishOrderRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processFinishCremaOrder(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void processGetTourIDs(::csc::customer::CustomerTourIDsResponse& _return, const ::csc::customer::CustomerTourIDsRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processGetTourIDs(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void processGetCustomerIDFsByTourId(::csc::customer::CustomerIDFsByTourIdResponse& _return, const ::csc::customer::CustomerIDFsByTourIdRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processGetCustomerIDFsByTourId(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }

    void processGetCustomerToursForWeek(::csc::customer::CustomerToursForWeekResponse& _return, const ::csc::customer::CustomerToursForWeekRequest& request)
    {
        std::stringstream in;
        in << "IN: " << request;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), in.str());

        m_Impl->processGetCustomerToursForWeek(_return, request);

        std::stringstream out;
        out << "OUT: " << _return;
        LOG4CPLUS_DEBUG(libcsc::LoggerPool::getLoggerSession(), out.str());
    }
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

#endif // GUARD_CSCSERVICE_BATCH_HANDLER_HPP
