//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_CREMAORDERSQLMAPPER_H
#define GUARD_LIBCSC_CREMA_CREMAORDERSQLMAPPER_H

#include <crema/cremaorder/cremaordermapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class CremaOrderSqlMapper : public CremaOrderMapperBase
{
public:
    CremaOrderSqlMapper(CremaOrderPtr cremaOrder, const basar::db::sql::ResultsetRef resultSet);
    virtual ~CremaOrderSqlMapper();

protected:
    virtual void doMap();

private:
    CremaOrderSqlMapper(const CremaOrderSqlMapper&);
    CremaOrderSqlMapper& operator=(const CremaOrderSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_CREMAORDERSQLMAPPER_H
