//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_CREMAORDERMAPPERBASE_H
#define GUARD_LIBCSC_CREMA_CREMAORDERMAPPERBASE_H

#include <crema/cremaorder/cremaorderptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class CremaOrderMapperBase
{
public:
    CremaOrderMapperBase(CremaOrderPtr cremaOrder);

    void map();

protected:
    virtual ~CremaOrderMapperBase();

    virtual void doMap() = 0;

    void setOrderNo(const basar::Int32& orderNo);
    void setGuid(const basar::VarString& guid);
    void setSendDate(const basar::Int32& sendDate);
    void setBranchNo(const basar::Int16& branchNo);
    void setOrderValue(const basar::Decimal& orderValue);
    void setCustomerNo(const basar::Int32& customerNo);
    void setUrl(const basar::VarString& url);
    void setReleaseUser(const basar::VarString& releaseUser);
    void setReleaseReason(const basar::VarString& releaseReason);
    void setReleaseComment(const basar::VarString& releaseComment);
    void setPharmacy(const basar::VarString& pharmacy);
    void setPlace(const basar::VarString& place);
    void setChainNo(const basar::Int32& chainNo);

private:
    CremaOrderPtr m_CremaOrder;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_CREMAORDERMAPPERBASE_H
