//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/cremaorder/cremaordermapperbase.h>
#include <crema/cremaorder/cremaorder.h>

namespace libcsc {
namespace crema {

CremaOrderMapperBase::CremaOrderMapperBase(CremaOrderPtr cremaOrder)
: m_CremaOrder(cremaOrder)
{
}

CremaOrderMapperBase::~CremaOrderMapperBase()
{
}

void CremaOrderMapperBase::map()
{
    doMap();
}

void CremaOrderMapperBase::setOrderNo(const basar::Int32& orderNo)
{
    m_CremaOrder->m_OrderNo = orderNo;
    m_CremaOrder->m_OrderNo.setClean();
}

void CremaOrderMapperBase::setGuid(const basar::VarString& guid)
{
    m_CremaOrder->m_Guid = guid;
    m_CremaOrder->m_Guid.setClean();
}

void CremaOrderMapperBase::setSendDate(const basar::Int32& sendDate)
{
    m_CremaOrder->m_SendDate = sendDate;
    m_CremaOrder->m_SendDate.setClean();
}

void CremaOrderMapperBase::setBranchNo(const basar::Int16& branchNo)
{
    m_CremaOrder->m_BranchNo = branchNo;
    m_CremaOrder->m_BranchNo.setClean();
}

void CremaOrderMapperBase::setOrderValue(const basar::Decimal& orderValue)
{
    m_CremaOrder->m_OrderValue = orderValue;
    m_CremaOrder->m_OrderValue.setClean();
}

void CremaOrderMapperBase::setCustomerNo(const basar::Int32& customerNo)
{
    m_CremaOrder->m_CustomerNo = customerNo;
    m_CremaOrder->m_CustomerNo.setClean();
}

void CremaOrderMapperBase::setUrl(const basar::VarString& url)
{
    m_CremaOrder->m_Url = url;
    m_CremaOrder->m_Url.setClean();
}

void CremaOrderMapperBase::setReleaseUser(const basar::VarString& releaseUser)
{
    m_CremaOrder->m_ReleaseUser = releaseUser;
    m_CremaOrder->m_ReleaseUser.setClean();
}

void CremaOrderMapperBase::setReleaseReason(const basar::VarString& releaseReason)
{
    m_CremaOrder->m_ReleaseReason = releaseReason;
    m_CremaOrder->m_ReleaseReason.setClean();
}

void CremaOrderMapperBase::setReleaseComment(const basar::VarString& releaseComment)
{
    m_CremaOrder->m_ReleaseComment = releaseComment;
    m_CremaOrder->m_ReleaseComment.setClean();
}

void CremaOrderMapperBase::setPharmacy(const basar::VarString& pharmacy)
{
    m_CremaOrder->m_Pharmacy = pharmacy;
    m_CremaOrder->m_Pharmacy.setClean();
}

void CremaOrderMapperBase::setPlace(const basar::VarString& place)
{
    m_CremaOrder->m_Place = place;
    m_CremaOrder->m_Place.setClean();
}

void CremaOrderMapperBase::setChainNo(const basar::Int32& chainNo)
{
    m_CremaOrder->m_ChainNo = chainNo;
    m_CremaOrder->m_ChainNo.setClean();
}
} // end namespace crema
} // end namespace libcsc
