//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_CREMAORDER_H
#define GUARD_LIBCSC_CREMA_CREMAORDER_H

#include <crema/cremaorder/icremaorder.h>
#include <datatypes/int32.h>
#include <datatypes/varstring.h>
#include <datatypes/datetime.h>
#include <datatypes/int16.h>
#include <datatypes/decimal.h>

namespace libcsc {
namespace crema {

class CremaOrder : public ICremaOrder
{
    // because of OR mapping
    friend class CremaOrderMapperBase;

public:
    CremaOrder();
    virtual ~CremaOrder();

    virtual basar::Int32 getOrderNo() const;
    virtual basar::VarString getGuid() const;
    virtual basar::Int32 getSendDate() const;
    virtual basar::Int16 getBranchNo() const;
    virtual basar::Decimal getOrderValue() const;
    virtual basar::Int32 getCustomerNo() const;
    virtual basar::VarString getUrl() const;
    virtual basar::VarString getReleaseUser() const;
    virtual basar::VarString getReleaseReason() const;
    virtual basar::VarString getReleaseComment() const;
    virtual basar::VarString getPharmacy() const;
    virtual basar::VarString getPlace() const;
    virtual basar::Int32 getChainNo() const;

private:
    libcsc::Int32 m_OrderNo;
    libcsc::VarString m_Guid;
    libcsc::Int32 m_SendDate;
    libcsc::Int16 m_BranchNo;
    libcsc::Decimal m_OrderValue;
    libcsc::Int32 m_CustomerNo;
    libcsc::VarString m_Url;
    libcsc::VarString m_ReleaseUser;
    libcsc::VarString m_ReleaseReason;
    libcsc::VarString m_ReleaseComment;
    libcsc::VarString m_Pharmacy;
    libcsc::VarString m_Place;
    libcsc::Int32 m_ChainNo;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_CREMAORDER_H
