//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/cremaorder/cremaorder.h>

namespace libcsc {
namespace crema {

CremaOrder::CremaOrder()
{
}

CremaOrder::~CremaOrder()
{
}

basar::Int32 CremaOrder::getOrderNo() const
{
    return m_OrderNo;
}

basar::VarString CremaOrder::getGuid() const
{
    return m_Guid;
}

basar::Int32 CremaOrder::getSendDate() const
{
    return m_SendDate;
}

basar::Int16 CremaOrder::getBranchNo() const
{
    return m_BranchNo;
}

basar::Decimal CremaOrder::getOrderValue() const
{
    return m_OrderValue;
}

basar::Int32 CremaOrder::getCustomerNo() const
{
    return m_CustomerNo;
}

basar::VarString CremaOrder::getUrl() const
{
    return m_Url;
}

basar::VarString CremaOrder::getReleaseUser() const
{
    return m_ReleaseUser;
}

basar::VarString CremaOrder::getReleaseReason() const
{
    return m_ReleaseReason;
}

basar::VarString CremaOrder::getReleaseComment() const
{
    return m_ReleaseComment;
}

basar::VarString CremaOrder::getPharmacy() const
{
    return m_Pharmacy;
}

basar::VarString CremaOrder::getPlace() const
{
    return m_Place;
}

basar::Int32 CremaOrder::getChainNo() const
{
    return m_ChainNo;
}

} // end namespace crema
} // end namespace libcsc
