//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/cremaorder/cremaordersqlmapper.h>

namespace libcsc {
namespace crema {

CremaOrderSqlMapper::CremaOrderSqlMapper(CremaOrderPtr cremaOrder, const basar::db::sql::ResultsetRef resultSet)
: CremaOrderMapperBase(cremaOrder), m_ResultSet(resultSet)
{
}

CremaOrderSqlMapper::~CremaOrderSqlMapper()
{
}

void CremaOrderSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setOrderNo(m_ResultSet.getInt32("kdauftragnr"));
    setBranchNo(m_ResultSet.getInt16("branchno"));
    setOrderValue(m_ResultSet.getDecimal("ordervalue"));
    setCustomerNo(m_ResultSet.getInt32("idfnr"));
    setPharmacy(m_ResultSet.getString("nameapo"));
    setChainNo(m_ResultSet.getInt32("maincstno"));

    basar::VarString place = m_ResultSet.getString("postleitzahl") + basar::VarString(" ") + m_ResultSet.getString("ort");
    setPlace(place);

    if (m_ResultSet.isExist("guid"))
    {
        setGuid(m_ResultSet.getString("guid"));
        setSendDate(m_ResultSet.getInt32("senddate"));
        setUrl(m_ResultSet.getString("url"));
    }
    else
    {
        setReleaseUser(m_ResultSet.getString("reluser"));
        setReleaseReason(m_ResultSet.getString("relreason"));
        setReleaseComment(m_ResultSet.getString("relcomment"));
    }
}

} // end namespace crema
} // end namespace libcsc
