//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_ICREMAORDER_H
#define GUARD_LIBCSC_CREMA_ICREMAORDER_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class ICremaOrder
{
public:
    virtual ~ICremaOrder() {}

    virtual basar::Int32 getOrderNo() const = 0;
    virtual basar::VarString getGuid() const = 0;
    virtual basar::Int32 getSendDate() const = 0;
    virtual basar::Int16 getBranchNo() const = 0;
    virtual basar::Decimal getOrderValue() const = 0;
    virtual basar::Int32 getCustomerNo() const = 0;
    virtual basar::VarString getUrl() const = 0;
    virtual basar::VarString getReleaseUser() const = 0;
    virtual basar::VarString getReleaseReason() const = 0;
    virtual basar::VarString getReleaseComment() const = 0;
    virtual basar::VarString getPharmacy() const = 0;
    virtual basar::VarString getPlace() const = 0;
    virtual basar::Int32 getChainNo() const = 0;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_ICREMAORDER_H
