//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/orderstatus/orderstatusmapperbase.h>
#include <customer/orderstatus/orderstatus.h>

namespace libcsc {
namespace customer {

OrderStatusMapperBase::OrderStatusMapperBase(OrderStatusPtr orderStatus)
: m_OrderStatus(orderStatus)
{
}

OrderStatusMapperBase::~OrderStatusMapperBase()
{
}

void OrderStatusMapperBase::map()
{
    doMap();
}

void OrderStatusMapperBase::setInprocess(const basar::VarString& inprocess)
{
    m_OrderStatus->m_Inprocess = inprocess;
    m_OrderStatus->m_Inprocess.setClean();
}

void OrderStatusMapperBase::setOnhold(const basar::VarString& onhold)
{
    m_OrderStatus->m_Onhold = onhold;
    m_OrderStatus->m_Onhold.setClean();
}

void OrderStatusMapperBase::setOrdercreated(const basar::VarString& ordercreated)
{
    m_OrderStatus->m_Ordercreated = ordercreated;
    m_OrderStatus->m_Ordercreated.setClean();
}

void OrderStatusMapperBase::setReadyforinvoicing(const basar::VarString& readyforinvoicing)
{
    m_OrderStatus->m_Readyforinvoicing = readyforinvoicing;
    m_OrderStatus->m_Readyforinvoicing.setClean();
}

void OrderStatusMapperBase::setInvoicecreated(const basar::VarString& invoicecreated)
{
    m_OrderStatus->m_Invoicecreated = invoicecreated;
    m_OrderStatus->m_Invoicecreated.setClean();
}

void OrderStatusMapperBase::setOrdercanceled(const basar::VarString& ordercanceled)
{
    m_OrderStatus->m_Ordercanceled = ordercanceled;
    m_OrderStatus->m_Ordercanceled.setClean();
}

void OrderStatusMapperBase::setOnhold2(const basar::VarString& onhold2)
{
    m_OrderStatus->m_Onhold2 = onhold2;
    m_OrderStatus->m_Onhold2.setClean();
}

void OrderStatusMapperBase::setDriverId(const basar::Int32& driverId)
{
    m_OrderStatus->m_DriverId = driverId;
    m_OrderStatus->m_DriverId.setClean();
}

void OrderStatusMapperBase::setInvoiceNo(const basar::Int32& invoiceNo)
{
    m_OrderStatus->m_InvoiceNo = invoiceNo;
    m_OrderStatus->m_InvoiceNo.setClean();
}

void OrderStatusMapperBase::setPharmosOrderNo(const basar::Int32& pharmosOrderNo)
{
    m_OrderStatus->m_PharmosOrderNo = pharmosOrderNo;
    m_OrderStatus->m_PharmosOrderNo.setClean();
}

} // end namespace customer
} // end namespace libcsc
