//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ORDERSTATUSSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_ORDERSTATUSSQLMAPPER_H

#include <customer/orderstatus/orderstatusmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class OrderStatusSqlMapper : public OrderStatusMapperBase
{
public:
    OrderStatusSqlMapper(OrderStatusPtr orderStatus, const basar::db::sql::ResultsetRef resultSet);
    virtual ~OrderStatusSqlMapper();

protected:
    virtual void doMap();

private:
    OrderStatusSqlMapper(const OrderStatusSqlMapper&);
    OrderStatusSqlMapper& operator=(const OrderStatusSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ORDERSTATUSSQLMAPPER_H
