//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/orderstatus/orderstatussqlmapper.h>

namespace libcsc {
namespace customer {

OrderStatusSqlMapper::OrderStatusSqlMapper(OrderStatusPtr orderStatus, const basar::db::sql::ResultsetRef resultSet)
: OrderStatusMapperBase(orderStatus), m_ResultSet(resultSet)
{
}

OrderStatusSqlMapper::~OrderStatusSqlMapper()
{
}

void OrderStatusSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setInprocess(m_ResultSet.getString("inprocess"));
    setOnhold(m_ResultSet.getString("onhold"));
    setOrdercreated(m_ResultSet.getString("ordercreated"));
    setReadyforinvoicing(m_ResultSet.getString("readyforinvoicing"));
    setInvoicecreated(m_ResultSet.getString("invoicecreated"));
    setOrdercanceled(m_ResultSet.getString("ordercanceled"));
    setOnhold2(m_ResultSet.getString("onhold2"));
    setDriverId(m_ResultSet.getInt32("driverid"));
    setInvoiceNo(m_ResultSet.getInt32("invoiceno"));
    setPharmosOrderNo(m_ResultSet.getInt32("pharmosorderno"));
}

} // end namespace customer
} // end namespace libcsc
