//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/orderstatus/orderstatus.h>

namespace libcsc {
namespace customer {

OrderStatus::OrderStatus()
{
}

OrderStatus::~OrderStatus()
{
}

basar::VarString OrderStatus::getInprocess() const
{
    return m_Inprocess;
}

basar::VarString OrderStatus::getOnhold() const
{
    return m_Onhold;
}

basar::VarString OrderStatus::getOrdercreated() const
{
    return m_Ordercreated;
}

basar::VarString OrderStatus::getReadyforinvoicing() const
{
    return m_Readyforinvoicing;
}

basar::VarString OrderStatus::getInvoicecreated() const
{
    return m_Invoicecreated;
}

basar::VarString OrderStatus::getOrdercanceled() const
{
    return m_Ordercanceled;
}

basar::VarString OrderStatus::getOnhold2() const
{
    return m_Onhold2;
}

basar::Int32 OrderStatus::getDriverId() const
{
    return m_DriverId;
}

basar::Int32 OrderStatus::getInvoiceNo() const
{
    return m_InvoiceNo;
}

basar::Int32 OrderStatus::getPharmosOrderNo() const
{
    return m_PharmosOrderNo;
}

} // end namespace customer
} // end namespace libcsc
