//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ORDERSTATUSMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_ORDERSTATUSMAPPERBASE_H

#include <customer/orderstatus/orderstatusptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class OrderStatusMapperBase
{
public:
    OrderStatusMapperBase(OrderStatusPtr orderStatus);

    void map();

protected:
    virtual ~OrderStatusMapperBase();

    virtual void doMap() = 0;

    void setInprocess(const basar::VarString& inprocess);
    void setOnhold(const basar::VarString& onhold);
    void setOrdercreated(const basar::VarString& ordercreated);
    void setReadyforinvoicing(const basar::VarString& readyforinvoicing);
    void setInvoicecreated(const basar::VarString& invoicecreated);
    void setOrdercanceled(const basar::VarString& ordercanceled);
    void setOnhold2(const basar::VarString& onhold2);
    void setDriverId(const basar::Int32& driverId);
    void setInvoiceNo(const basar::Int32& invoiceNo);
    void setPharmosOrderNo(const basar::Int32& pharmosOrderNo);

private:
    OrderStatusPtr m_OrderStatus;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ORDERSTATUSMAPPERBASE_H
