//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_ORDERSTATUS_H
#define GUARD_LIBCSC_CUSTOMER_ORDERSTATUS_H

#include <customer/orderstatus/iorderstatus.h>
#include <datatypes/varstring.h>
#include <datatypes/int32.h>

namespace libcsc {
namespace customer {

class OrderStatus : public IOrderStatus
{
    // because of OR mapping
    friend class OrderStatusMapperBase;

public:
    OrderStatus();
    virtual ~OrderStatus();

    virtual basar::VarString getInprocess() const;
    virtual basar::VarString getOnhold() const;
    virtual basar::VarString getOrdercreated() const;
    virtual basar::VarString getReadyforinvoicing() const;
    virtual basar::VarString getInvoicecreated() const;
    virtual basar::VarString getOrdercanceled() const;
    virtual basar::VarString getOnhold2() const;
    virtual basar::Int32 getDriverId() const;
    virtual basar::Int32 getInvoiceNo() const;
    virtual basar::Int32 getPharmosOrderNo() const;

private:
    libcsc::VarString m_Inprocess;
    libcsc::VarString m_Onhold;
    libcsc::VarString m_Ordercreated;
    libcsc::VarString m_Readyforinvoicing;
    libcsc::VarString m_Invoicecreated;
    libcsc::VarString m_Ordercanceled;
    libcsc::VarString m_Onhold2;
    libcsc::Int32 m_DriverId;
    libcsc::Int32 m_InvoiceNo;
    libcsc::Int32 m_PharmosOrderNo;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_ORDERSTATUS_H
