//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_IPAYMENTCONDITIONS_H
#define GUARD_LIBCSC_CUSTOMER_IPAYMENTCONDITIONS_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class IPaymentConditions
{
public:
    virtual ~IPaymentConditions() {}

    virtual basar::Int16 getNZOKDiscountMethod() const = 0;
    virtual basar::Int16 getDiscountMethod() const = 0;
    virtual basar::Int16 getNZOKDaysOfPayment() const = 0;
    virtual basar::Int16 getDaysOfPayment() const = 0;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_IPAYMENTCONDITIONS_H
