//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/paymentconditions/paymentconditionsmapperbase.h>
#include <customer/paymentconditions/paymentconditions.h>

namespace libcsc {
namespace customer {

PaymentConditionsMapperBase::PaymentConditionsMapperBase(PaymentConditionsPtr paymentConditions)
: m_PaymentConditions(paymentConditions)
{
}

PaymentConditionsMapperBase::~PaymentConditionsMapperBase()
{
}

void PaymentConditionsMapperBase::map()
{
    doMap();
}

void PaymentConditionsMapperBase::setNZOKDiscountMethod(const basar::Int16& nZOKDiscountMethod)
{
    m_PaymentConditions->m_NZOKDiscountMethod = nZOKDiscountMethod;
    m_PaymentConditions->m_NZOKDiscountMethod.setClean();
}

void PaymentConditionsMapperBase::setDiscountMethod(const basar::Int16& discountMethod)
{
    m_PaymentConditions->m_DiscountMethod = discountMethod;
    m_PaymentConditions->m_DiscountMethod.setClean();
}

void PaymentConditionsMapperBase::setNZOKDaysOfPayment(const basar::Int16& nZOKDaysOfPayment)
{
    m_PaymentConditions->m_NZOKDaysOfPayment = nZOKDaysOfPayment;
    m_PaymentConditions->m_NZOKDaysOfPayment.setClean();
}

void PaymentConditionsMapperBase::setDaysOfPayment(const basar::Int16& daysOfPayment)
{
    m_PaymentConditions->m_DaysOfPayment = daysOfPayment;
    m_PaymentConditions->m_DaysOfPayment.setClean();
}

} // end namespace customer
} // end namespace libcsc
