//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONSMAPPERBASE_H
#define GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONSMAPPERBASE_H

#include <customer/paymentconditions/paymentconditionsptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class PaymentConditionsMapperBase
{
public:
    PaymentConditionsMapperBase(PaymentConditionsPtr paymentConditions);

    void map();

protected:
    virtual ~PaymentConditionsMapperBase();

    virtual void doMap() = 0;

    void setNZOKDiscountMethod(const basar::Int16& nZOKDiscountMethod);
    void setDiscountMethod(const basar::Int16& discountMethod);
    void setNZOKDaysOfPayment(const basar::Int16& nZOKDaysOfPayment);
    void setDaysOfPayment(const basar::Int16& daysOfPayment);

private:
    PaymentConditionsPtr m_PaymentConditions;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONSMAPPERBASE_H
