//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/paymentconditions/paymentconditions.h>

namespace libcsc {
namespace customer {

PaymentConditions::PaymentConditions()
{
}

PaymentConditions::~PaymentConditions()
{
}

basar::Int16 PaymentConditions::getNZOKDiscountMethod() const
{
    return m_NZOKDiscountMethod;
}

basar::Int16 PaymentConditions::getDiscountMethod() const
{
    return m_DiscountMethod;
}

basar::Int16 PaymentConditions::getNZOKDaysOfPayment() const
{
    return m_NZOKDaysOfPayment;
}

basar::Int16 PaymentConditions::getDaysOfPayment() const
{
    return m_DaysOfPayment;
}

} // end namespace customer
} // end namespace libcsc
