//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <customer/paymentconditions/paymentconditionssqlmapper.h>

namespace libcsc {
namespace customer {

PaymentConditionsSqlMapper::PaymentConditionsSqlMapper(PaymentConditionsPtr paymentConditions, const basar::db::sql::ResultsetRef resultSet)
: PaymentConditionsMapperBase(paymentConditions), m_ResultSet(resultSet)
{
}

PaymentConditionsSqlMapper::~PaymentConditionsSqlMapper()
{
}

void PaymentConditionsSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setNZOKDiscountMethod(m_ResultSet.getInt16("nzokdiscountmethod"));
    setDiscountMethod(m_ResultSet.getInt16("discountmethod"));
    setNZOKDaysOfPayment(m_ResultSet.getInt16("nzokdaysofpayment"));
    setDaysOfPayment(m_ResultSet.getInt16("daysofpayment"));
}

} // end namespace customer
} // end namespace libcsc
