//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONSSQLMAPPER_H
#define GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONSSQLMAPPER_H

#include <customer/paymentconditions/paymentconditionsmapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace customer {

class PaymentConditionsSqlMapper : public PaymentConditionsMapperBase
{
public:
    PaymentConditionsSqlMapper(PaymentConditionsPtr paymentConditions, const basar::db::sql::ResultsetRef resultSet);
    virtual ~PaymentConditionsSqlMapper();

protected:
    virtual void doMap();

private:
    PaymentConditionsSqlMapper(const PaymentConditionsSqlMapper&);
    PaymentConditionsSqlMapper& operator=(const PaymentConditionsSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONSSQLMAPPER_H
