//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONS_H
#define GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONS_H

#include <customer/paymentconditions/ipaymentconditions.h>
#include <datatypes/int16.h>

namespace libcsc {
namespace customer {

class PaymentConditions : public IPaymentConditions
{
    // because of OR mapping
    friend class PaymentConditionsMapperBase;

public:
    PaymentConditions();
    virtual ~PaymentConditions();

    virtual basar::Int16 getNZOKDiscountMethod() const;
    virtual basar::Int16 getDiscountMethod() const;
    virtual basar::Int16 getNZOKDaysOfPayment() const;
    virtual basar::Int16 getDaysOfPayment() const;

private:
    libcsc::Int16 m_NZOKDiscountMethod;
    libcsc::Int16 m_DiscountMethod;
    libcsc::Int16 m_NZOKDaysOfPayment;
    libcsc::Int16 m_DaysOfPayment;
};

} // end namespace customer
} // end namespace libcsc

#endif // GUARD_LIBCSC_CUSTOMER_PAYMENTCONDITIONS_H
