//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_CREDITLIMITDATAMAPPERBASE_H
#define GUARD_LIBCSC_CREMA_CREDITLIMITDATAMAPPERBASE_H

#include <crema/creditlimitdata/creditlimitdataptr.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class CreditLimitDataMapperBase
{
public:
    CreditLimitDataMapperBase(CreditLimitDataPtr creditLimitData);

    void map();

protected:
    virtual ~CreditLimitDataMapperBase();

    virtual void doMap() = 0;

    void setCreditLimit(const basar::Decimal& creditLimit);
    void setSumDebitside(const basar::Decimal& sumDebitside);
    void setSumCreditside(const basar::Decimal& sumCreditside);
    void setSumMonTurnover(const basar::Decimal& sumMonTurnover);
    void setSumDayTurnover(const basar::Decimal& sumDayTurnover);
    void setSumReturns(const basar::Decimal& sumReturns);
    void setSumGoodsReceipt(const basar::Decimal& sumGoodsReceipt);
    void setLimitType(const basar::Int16& limitType);
    void setIsChain(const bool& isChain);

private:
    CreditLimitDataPtr m_CreditLimitData;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_CREDITLIMITDATAMAPPERBASE_H
