//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/creditlimitdata/creditlimitdatamapperbase.h>
#include <crema/creditlimitdata/creditlimitdata.h>

namespace libcsc {
namespace crema {

CreditLimitDataMapperBase::CreditLimitDataMapperBase(CreditLimitDataPtr creditLimitData)
: m_CreditLimitData(creditLimitData)
{
}

CreditLimitDataMapperBase::~CreditLimitDataMapperBase()
{
}

void CreditLimitDataMapperBase::map()
{
    doMap();
}

void CreditLimitDataMapperBase::setCreditLimit(const basar::Decimal& creditLimit)
{
    m_CreditLimitData->m_CreditLimit = creditLimit;
    m_CreditLimitData->m_CreditLimit.setClean();
}

void CreditLimitDataMapperBase::setSumDebitside(const basar::Decimal& sumDebitside)
{
    m_CreditLimitData->m_SumDebitside = sumDebitside;
    m_CreditLimitData->m_SumDebitside.setClean();
}

void CreditLimitDataMapperBase::setSumCreditside(const basar::Decimal& sumCreditside)
{
    m_CreditLimitData->m_SumCreditside = sumCreditside;
    m_CreditLimitData->m_SumCreditside.setClean();
}

void CreditLimitDataMapperBase::setSumMonTurnover(const basar::Decimal& sumMonTurnover)
{
    m_CreditLimitData->m_SumMonTurnover = sumMonTurnover;
    m_CreditLimitData->m_SumMonTurnover.setClean();
}

void CreditLimitDataMapperBase::setSumDayTurnover(const basar::Decimal& sumDayTurnover)
{
    m_CreditLimitData->m_SumDayTurnover = sumDayTurnover;
    m_CreditLimitData->m_SumDayTurnover.setClean();
}

void CreditLimitDataMapperBase::setSumReturns(const basar::Decimal& sumReturns)
{
    m_CreditLimitData->m_SumReturns = sumReturns;
    m_CreditLimitData->m_SumReturns.setClean();
}

void CreditLimitDataMapperBase::setSumGoodsReceipt(const basar::Decimal& sumGoodsReceipt)
{
    m_CreditLimitData->m_SumGoodsReceipt = sumGoodsReceipt;
    m_CreditLimitData->m_SumGoodsReceipt.setClean();
}

void CreditLimitDataMapperBase::setLimitType(const basar::Int16& limitType)
{
    m_CreditLimitData->m_LimitType = limitType;
    m_CreditLimitData->m_LimitType.setClean();
}

void CreditLimitDataMapperBase::setIsChain(const bool& isChain)
{
    m_CreditLimitData->m_IsChain = isChain;
    m_CreditLimitData->m_IsChain.setClean();
}

} // end namespace crema
} // end namespace libcsc
