//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/creditlimitdata/creditlimitdata.h>

namespace libcsc {
namespace crema {

CreditLimitData::CreditLimitData()
{
}

CreditLimitData::~CreditLimitData()
{
}

basar::Decimal CreditLimitData::getCreditLimit() const
{
    return m_CreditLimit;
}

basar::Decimal CreditLimitData::getSumDebitside() const
{
    return m_SumDebitside;
}

basar::Decimal CreditLimitData::getSumCreditside() const
{
    return m_SumCreditside;
}

basar::Decimal CreditLimitData::getSumMonTurnover() const
{
    return m_SumMonTurnover;
}

basar::Decimal CreditLimitData::getSumDayTurnover() const
{
    return m_SumDayTurnover;
}

basar::Decimal CreditLimitData::getSumReturns() const
{
    return m_SumReturns;
}

basar::Decimal CreditLimitData::getSumGoodsReceipt() const
{
    return m_SumGoodsReceipt;
}

basar::Int16 CreditLimitData::getLimitType() const
{
    return m_LimitType;
}

bool CreditLimitData::getIsChain() const
{
    return m_IsChain;
}

} // end namespace crema
} // end namespace libcsc
