//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_CREDITLIMITDATASQLMAPPER_H
#define GUARD_LIBCSC_CREMA_CREDITLIMITDATASQLMAPPER_H

#include <crema/creditlimitdata/creditlimitdatamapperbase.h>

#include <libbasardbsql_resultsetref.h>
#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class CreditLimitDataSqlMapper : public CreditLimitDataMapperBase
{
public:
    CreditLimitDataSqlMapper(CreditLimitDataPtr creditLimitData, const basar::db::sql::ResultsetRef resultSet);
    virtual ~CreditLimitDataSqlMapper();

protected:
    virtual void doMap();

private:
    CreditLimitDataSqlMapper(const CreditLimitDataSqlMapper&);
    CreditLimitDataSqlMapper& operator=(const CreditLimitDataSqlMapper&);

    const basar::db::sql::ResultsetRef m_ResultSet;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_CREDITLIMITDATASQLMAPPER_H
