//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_CREDITLIMITDATA_H
#define GUARD_LIBCSC_CREMA_CREDITLIMITDATA_H

#include <crema/creditlimitdata/icreditlimitdata.h>
#include <datatypes/decimal.h>
#include <datatypes/int16.h>

namespace libcsc {
namespace crema {

class CreditLimitData : public ICreditLimitData
{
    // because of OR mapping
    friend class CreditLimitDataMapperBase;

public:
    CreditLimitData();
    virtual ~CreditLimitData();

    virtual basar::Decimal getCreditLimit() const;
    virtual basar::Decimal getSumDebitside() const;
    virtual basar::Decimal getSumCreditside() const;
    virtual basar::Decimal getSumMonTurnover() const;
    virtual basar::Decimal getSumDayTurnover() const;
    virtual basar::Decimal getSumReturns() const;
    virtual basar::Decimal getSumGoodsReceipt() const;
    virtual basar::Int16 getLimitType() const;
    virtual bool getIsChain() const;

private:
    libcsc::Decimal m_CreditLimit;
    libcsc::Decimal m_SumDebitside;
    libcsc::Decimal m_SumCreditside;
    libcsc::Decimal m_SumMonTurnover;
    libcsc::Decimal m_SumDayTurnover;
    libcsc::Decimal m_SumReturns;
    libcsc::Decimal m_SumGoodsReceipt;
    libcsc::Int16 m_LimitType;
    libcsc::Int16 m_IsChain;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_CREDITLIMITDATA_H
