//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <crema/creditlimitdata/creditlimitdatasqlmapper.h>

namespace libcsc {
namespace crema {

CreditLimitDataSqlMapper::CreditLimitDataSqlMapper(CreditLimitDataPtr creditLimitData, const basar::db::sql::ResultsetRef resultSet)
: CreditLimitDataMapperBase(creditLimitData), m_ResultSet(resultSet)
{
}

CreditLimitDataSqlMapper::~CreditLimitDataSqlMapper()
{
}

void CreditLimitDataSqlMapper::doMap()
{
    if (m_ResultSet.isNull())
    {
        throw;
    }

    setCreditLimit(m_ResultSet.getDecimal("creditlimit"));
    setSumDebitside(m_ResultSet.getDecimal("sumdebitside"));
    setSumCreditside(m_ResultSet.getDecimal("sumcreditside"));
    setSumMonTurnover(m_ResultSet.getDecimal("summonturnover"));
    setSumDayTurnover(m_ResultSet.getDecimal("sumdayturnover"));
    setSumReturns(m_ResultSet.getDecimal("sumreturns"));
    setSumGoodsReceipt(m_ResultSet.getDecimal("sumgoodsreceipt"));
    setLimitType(m_ResultSet.getInt16("limittype"));
    setIsChain(m_ResultSet.getInt16("ischain"));
}

} // end namespace crema
} // end namespace libcsc
