//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ormapper.tt template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef GUARD_LIBCSC_CREMA_ICREDITLIMITDATA_H
#define GUARD_LIBCSC_CREMA_ICREDITLIMITDATA_H

#include <libbasar_definitions.h>

namespace libcsc {
namespace crema {

class ICreditLimitData
{
public:
    virtual ~ICreditLimitData() {}

    virtual basar::Decimal getCreditLimit() const = 0;
    virtual basar::Decimal getSumDebitside() const = 0;
    virtual basar::Decimal getSumCreditside() const = 0;
    virtual basar::Decimal getSumMonTurnover() const = 0;
    virtual basar::Decimal getSumDayTurnover() const = 0;
    virtual basar::Decimal getSumReturns() const = 0;
    virtual basar::Decimal getSumGoodsReceipt() const = 0;
    virtual basar::Int16 getLimitType() const = 0;
    virtual bool getIsChain() const = 0;
};

} // end namespace crema
} // end namespace libcsc

#endif // GUARD_LIBCSC_CREMA_ICREDITLIMITDATA_H
