//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

namespace SWIMP.FR
{
    public partial class Util
    {
        public static ctPML_ENV_ATTRIBUTE createPML_ENV_ATTRIBUTE_forOrderRequest()
        {
            var retval = new SWIMP.FR.ctPML_ENV_ATTRIBUTE();
            retval.Version_Protocole = "1.0.0.0";
            retval.Nature_Action = ctPML_ENV_ATTRIBUTENature_Action.REP_RECEPTION;
            retval.Usage = "P";
            return retval;
        }

        public static ctPML_ENV_ENTETE createPML_ENV_ENTETE_forOrderRequest()
        {
            var retval = new SWIMP.FR.ctPML_ENV_ENTETE();

            retval.EMETTEUR = new ctPML_ENV_ENTETEEMETTEUR();
            retval.EMETTEUR.Nature = ctPML_ENV_ENTETEEMETTEURNature.RE;
            retval.EMETTEUR.Code = "23";
            retval.EMETTEUR.Id_Repartiteur = "PHOENIX";
            retval.EMETTEUR.Adresse = "PHOENIX";

            retval.RECEPTEUR = new ctPML_ENV_ENTETERECEPTEUR();
            retval.RECEPTEUR.Nature = ctPML_ENV_ENTETEEMETTEURNature.OF;
            retval.RECEPTEUR.Code = "00";
            retval.RECEPTEUR.Id_Officine = "044100";
            retval.RECEPTEUR.Adresse = "Adresse";

            retval.REF_MESSAGE = "C0441000515000300001";
            retval.EN_REPONSE_A = "W0441000515000342179";

            retval.DATE = DateTime.Now;
            retval.DATESpecified = true;

            return retval;
        }

        public static ctPML_MESS_ENTETE createPML_MESS_ENTETE_forOrderRequest()
        {
            var retval = new ctPML_MESS_ENTETE();

            retval.EMETTEUR = new ctPML_MESS_Repartiteur();
            retval.EMETTEUR.Nature_Partenaire = stPML_MESS_CodePartenaire.RE;
            retval.EMETTEUR.Code_Societe = "23";
            retval.EMETTEUR.Id_Repartiteur = "PHOENIX";

            retval.DESTINATAIRE = new ctPML_MESS_Officine();
            retval.DESTINATAIRE.Nature_Partenaire = stPML_MESS_CodePartenaire.OF;
            retval.DESTINATAIRE.Id_Client = "044100";

            retval.DATE = DateTime.Now;
            retval.DATESpecified = true;

            return retval;
        }

        public static ctPML_MESS_CORPS createPML_MESS_CORPS_forOrderRequest()
        {
            var retval = new ctPML_MESS_CORPS();

            retval.Ref_Doc_Client = "W0441000515000342179"; 
            retval.Ref_Rep_Repartiteur = "C0441000515000300001";
            retval.Devise = "EUR";
            retval.Code_Speciale = "NO";

            retval.INFOS_LIVRAISON = new ctPML_MESS_InformationsLivraison();

            retval.INFOS_LIVRAISON.LIVREUR = new ctPML_MESS_InformationsLivraisonLIVREUR();
            retval.INFOS_LIVRAISON.LIVREUR.Societe = "soc";
            retval.INFOS_LIVRAISON.LIVREUR.Etablissement = "etb";

            retval.INFOS_LIVRAISON.TOURNEE = new ctPML_MESS_InformationsLivraisonTOURNEE();
            retval.INFOS_LIVRAISON.TOURNEE.Reference = "Tournee";

            return retval;
        }
    }

}